"""Project bundles: a whole fit in one zip file (dashboard Stage 1).

The ALIS dashboard keeps each project in one file, ``project.model`` (D8). It is
an ordinary zip file, and ``run_alis project.model`` runs it without the
dashboard, with nothing unpacked to disk (D9)::

    manifest.json       format version, ALIS version, dates, the model's path,
                        the atomic table, the unblinding log, and a SHA-256
                        for every other member
    files/...           the model and its snips, at their relative paths on disk
    atomic/<name>       the atomic table the model uses (Q1.10)
    hidden.bin          hidden lines and files, compressed JSON (not readable)
    sources.json        the source spectra: path, SHA-256, size, dataset
    sources/...         source spectra embedded for archiving (optional)
    ui/...              the dashboard's own state (kept unchanged)
    runs/latest/...     the most recent run: run.json, input.mod, files/...
    runs/last_error.json  the last run that stopped with an error
    runs/0001/...       runs committed to the history (dashboard Stage 6)

**The files tree.** The root of ``files/`` is the lowest directory that holds the
model and all of its data, so the model text never needs to change (D7): a data
line is resolved exactly as on disk, relative to the model.

**Hidden values.** A model line with ``blind=True`` is stored as a placeholder
line, ``<hidden:n>``, with its real text kept in ``hidden.bin`` (D24, Q1.2). A
bundle run restores the lines in memory only. Of its outputs, the lines that
reveal blinded values are hidden the same way, and under ``run blind True`` the
whole ``.mod.out`` is. Hiding prevents accidental viewing, not a determined user
(QF.19(d)).

Generated by RJC and Claude.
"""

import copy
import datetime
import hashlib
import json
import logging
import os
import platform
import posixpath
import re
import sys
import tempfile
import time
import zipfile
import zlib

import alis
from alis import load, logger, outputs
from alis.config import ArgFlag

msgs = logger.msgs()

FORMAT = "alis-project"
FORMAT_VERSION = 1
SUFFIX = ".model"
MANIFEST = "manifest.json"
HIDDEN = "hidden.bin"
SOURCES = "sources.json"
TREE = "files/"
ATOMIC = "atomic/"
EMBEDDED = "sources/"
RUNS = "runs/"
LATEST = "runs/latest/"
LAST_ERROR = "runs/last_error.json"
# What a plain run writes in place of a blinded component's values
BLIND_LINE = "       ------ BLIND MODEL ------"

_PLACEHOLDER = re.compile(r"^(\s*)<hidden:(\d+)>\s*$")
_NUMBER = re.compile(r"[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?")
# How long to wait for another program to finish writing the bundle, and when
# a lock left behind by a program that died is ignored, in seconds
LOCK_WAIT = 60.0
LOCK_STALE = 600.0


class BundleError(Exception):
    """A project bundle cannot be made, read, written or run as asked."""


def sha256(data):
    """
    The SHA-256 of ``data`` (bytes), as a hexadecimal string.

    Generated by RJC and Claude.
    """
    return hashlib.sha256(data).hexdigest()


def now():
    """
    The current time, in ISO 8601 form, to the second.

    Generated by RJC and Claude.
    """
    return datetime.datetime.now().astimezone().isoformat(timespec="seconds")


# -- Hidden lines ---------------------------------------------------------------


def placeholder(indent, num):
    """
    The placeholder line that stands for hidden line ``num``.

    Generated by RJC and Claude.
    """
    return "{0:s}<hidden:{1:d}>".format(indent, num)


def blind_line_numbers(text):
    """
    The lines of a model that carry ``blind=True``, commented out or not.

    Parameters
    ----------
    text : str
        The model text.

    Returns
    -------
    list of int
        Line numbers, from 0.

    Generated by RJC and Claude.
    """
    found = []
    for num, line in enumerate(text.splitlines()):
        words = line.replace("#", " ").split()
        if any(word.lower() == "blind=true" for word in words):
            found.append(num)
    return found


def hide_lines(text, numbers, store):
    """
    Replace some lines of ``text`` by placeholders.

    Parameters
    ----------
    text : str
        The text, such as a model or a ``.mod.out``.
    numbers : iterable of int
        The lines to hide, from 0.
    store : dict
        The hidden lines of this text, by number (as a string); it is updated.

    Returns
    -------
    str
        The text with each hidden line replaced by ``<hidden:n>``, keeping its
        indentation and line ending.

    Generated by RJC and Claude.
    """
    numbers = set(numbers)
    if not numbers:
        return text
    nextnum = max([int(k) for k in store] + [0]) + 1
    lines = text.splitlines(keepends=True)
    for num in sorted(numbers):
        if num >= len(lines):
            continue
        line = lines[num]
        body = line.rstrip("\r\n")
        ending = line[len(body):]
        if _PLACEHOLDER.match(body):
            continue
        indent = body[:len(body) - len(body.lstrip())]
        store[str(nextnum)] = body
        lines[num] = placeholder(indent, nextnum) + ending
        nextnum += 1
    return "".join(lines)


def restore_lines(text, store, replace=None):
    """
    Put the hidden lines of ``text`` back.

    Parameters
    ----------
    text : str
        Text with ``<hidden:n>`` placeholders.
    store : dict
        The hidden lines of this text, by number (as a string).
    replace : callable, optional
        Given a hidden line, returns what to write instead of it (used when
        extracting best-fit values). By default the line itself is restored.

    Returns
    -------
    str
        The text with every placeholder replaced.

    Generated by RJC and Claude.
    """
    out = []
    for line in text.splitlines(keepends=True):
        body = line.rstrip("\r\n")
        match = _PLACEHOLDER.match(body)
        if match is None:
            out.append(line)
            continue
        real = store.get(match.group(2))
        if real is None:
            raise BundleError("The bundle is damaged: hidden line {0:s} is missing"
                              .format(match.group(2)))
        out.append((real if replace is None else replace(real))
                   + line[len(body):])
    return "".join(out)


class _MaskHidden(logging.Filter):
    """
    Keep hidden lines out of every message while a bundle runs (Task 1.6).

    A message that quotes a hidden line shows its placeholder instead, and every
    number in that message is masked, since such messages also quote values.

    Generated by RJC and Claude.
    """

    def __init__(self, store):
        super().__init__()
        self._pairs = [(line.strip(), "<hidden:{0:s}>".format(num))
                       for num, line in store.items() if line.strip()]

    def filter(self, record):
        message = record.getMessage()
        masked = False
        for real, mark in self._pairs:
            if real in message:
                message = message.replace(real, mark)
                masked = True
        if masked:
            parts = re.split(r"(<hidden:\d+>)", message)
            message = "".join(part if part.startswith("<hidden:")
                              else _NUMBER.sub("▒▒▒", part) for part in parts)
            record.msg, record.args = message, ()
        return True


# -- The bundle in memory ---------------------------------------------------------


class Bundle:
    """
    A project bundle, held in memory.

    Attributes
    ----------
    members : dict
        Zip member name to bytes, for every member except the manifest, the
        sources list and ``hidden.bin``, which are held below.
    manifest : dict
        The manifest's fields other than the member checksums.
    hidden : dict
        ``{"lines": {member: {num: line}}, "files": {member: text}}``: the hidden
        lines of each member, and the members hidden whole.
    sources : list of dict
        The source spectra (``id``, ``dataset``, ``path``, ``relpath``,
        ``sha256``, ``size``, ``embedded``).

    Generated by RJC and Claude.
    """

    def __init__(self, members=None, manifest=None, hidden=None, sources=None):
        self.members = dict(members or {})
        self.manifest = dict(manifest or {})
        self.hidden = hidden or {"lines": {}, "files": {}}
        self.hidden.setdefault("lines", {})
        self.hidden.setdefault("files", {})
        self.sources = list(sources or [])

    # -- the model ---------------------------------------------------------------

    @property
    def model_member(self):
        """The member holding the model, e.g. ``files/model/fit.mod``."""
        return self.manifest["model"]

    @property
    def model_dir(self):
        """The model's directory within the files tree (may be '')."""
        return posixpath.dirname(self.model_member[len(TREE):])

    @property
    def model_name(self):
        """The model's file name."""
        return posixpath.basename(self.model_member)

    def text(self, member, restore=False):
        """
        The text of ``member``, with its hidden lines restored if asked.

        Generated by RJC and Claude.
        """
        text = self.members[member].decode("utf-8")
        if restore:
            text = restore_lines(text, self.hidden["lines"].get(member, {}))
        return text

    def model_text(self, restore=False):
        """The model text, with placeholders unless ``restore`` is set."""
        return self.text(self.model_member, restore=restore)

    def hidden_model_lines(self):
        """The real text of the model's hidden lines, by number."""
        return dict(self.hidden["lines"].get(self.model_member, {}))

    def data_for_run(self):
        """
        Every file of the tree except the model, by its path from the model.

        These are the keys ``load_data`` looks up, e.g. ``../data/x.dat``.

        Generated by RJC and Claude.
        """
        data = {}
        for member, content in self.members.items():
            if not member.startswith(TREE) or member == self.model_member:
                continue
            rel = posixpath.relpath(member[len(TREE):], self.model_dir or ".")
            data[os.path.normpath(rel)] = content
        return data

    def atomic_table(self):
        """The packed atomic table, as ``(name, bytes)``."""
        member = self.manifest["atomic"]
        return posixpath.basename(member), self.members[member]

    def is_blinded(self):
        """Whether anything in the bundle is hidden."""
        return any(self.hidden["lines"].values()) or bool(self.hidden["files"])

    # -- source spectra (Q0.5, F13) ----------------------------------------------

    def source(self, ident):
        """The source spectrum with this id."""
        for entry in self.sources:
            if entry["id"] == ident:
                return entry
        raise BundleError("There is no source spectrum with id " + str(ident))


# -- Packing ----------------------------------------------------------------------


def _split_model(text):
    """
    Read the settings and the data lines of a model, as ALIS reads them.

    Returns
    -------
    tuple
        ``(argflag, parlines, datlines, modlines, lnklines)``.

    Generated by RJC and Claude.
    """

    class _Reader:
        pass

    reader = _Reader()
    reader._argflag = ArgFlag()
    reader._argflag["out"]["verbose"] = -1
    parlines, datlines, modlines, lnklines = load.load_input(
        reader, textstr=text.splitlines(keepends=True))
    return reader._argflag, parlines, datlines, modlines, lnklines


def _commented_data_paths(text, datadirc):
    """
    The files named on commented-out lines of the data block (Q1.11).

    Generated by RJC and Claude.
    """
    paths, inblock = [], False
    for line in text.splitlines():
        words = line.split("#")[0].split()
        if words[:2] == ["data", "read"]:
            inblock = True
            continue
        if words[:2] == ["data", "end"]:
            break
        stripped = line.strip()
        if inblock and stripped.startswith("#"):
            body = stripped.lstrip("#").split()
            if body and "=" not in body[0] and not body[0].startswith(("-", "<")):
                paths.append(datadirc + body[0])
    return paths


def unsupported(argflag, datlines):
    """
    What in a model a bundle cannot run (Q1.5, Q1.6).

    Parameters
    ----------
    argflag : ArgFlag
        The settings, after the model's own and the command line's.
    datlines : list of str
        The data lines.

    Returns
    -------
    list of str
        One reason per problem; empty when the bundle can be run.

    Generated by RJC and Claude.
    """
    reasons = []
    if argflag["sim"]["random"] is not None:
        reasons.append("'sim random' runs simulations")
    if argflag["sim"]["perturb"] is not None:
        reasons.append("'sim perturb' runs simulations")
    if argflag["sim"]["beginfrom"] not in ("", '""'):
        reasons.append("'sim beginfrom' reads a fit from disk")
    if argflag["iterate"]["model"] is not None:
        reasons.append("'iterate model' reads a module from disk")
    if argflag["generate"]["data"]:
        reasons.append("'generate data' writes data files")
    for line in datlines:
        for word in line.split("#")[0].split()[1:]:
            key, _, value = word.partition("=")
            if key == "resolution" and value.startswith("lsffile("):
                reasons.append("'lsffile' reads a file from disk: " + word)
            elif key == "systematics" and value.lower() not in ("columns", "none"):
                reasons.append("'systematics' reads a file from disk: " + word)
            elif key == "systmodule" and value.lower() != "none":
                reasons.append("'systmodule' reads a module from disk: " + word)
    return reasons


def _output_names(modname, argflag, datapaths):
    """
    The files a plain run of the model may have left beside it.

    Generated by RJC and Claude.
    """
    names = []
    modelname = argflag["out"]["modelname"]
    if modelname in ("", '""'):
        modelname = modname + ".out"
    names.append(modelname)
    names.append(modelname[:-4] + ".report" if modelname.endswith(".out")
                 else modelname + ".report")
    covar = argflag["out"]["covar"]
    if covar:
        names += [covar, os.path.splitext(covar)[0] + ".png"]
    plots = argflag["out"]["plots"]
    if plots.lower() == "true":
        names.append(modelname + ".pdf")
    elif plots not in ("", "false", "False"):
        names.append(plots if plots.endswith(".pdf") else plots + ".pdf")
    names.append(modname + ".plot.py")
    for path in datapaths:
        stem, ext = os.path.splitext(path)
        names.append(stem + "_fit" + (".fits" if ext in (".fits", ".fit") else ".dat"))
    return names


def pack(modfile, sources=(), embed=False, with_outputs=True):
    """
    Make a bundle from a plain model and its snips (Task 1.5, Q1.4(b)).

    Parameters
    ----------
    modfile : str
        The ``.mod`` file. Its data lines are resolved relative to its directory,
        as ``run_alis`` resolves them when run there.
    sources : iterable of str or (str, str)
        Source spectra to record, each a path or ``(path, dataset)``.
    embed : bool
        Embed the source spectra in the bundle, for archiving.
    with_outputs : bool
        Add the outputs of an earlier plain run, if they are beside the model,
        as the latest run.

    Returns
    -------
    Bundle
        The bundle, not yet written.

    Generated by RJC and Claude.
    """
    modfile = os.path.abspath(modfile)
    moddir = os.path.dirname(modfile)
    with open(modfile, "rb") as fil:
        raw = fil.read()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        raise BundleError("The model file is not a text file: " + modfile)
    argflag, _, datlines, _, _ = _split_model(text)
    reasons = unsupported(argflag, datlines)
    if reasons:
        raise BundleError("This model cannot be packed in a bundle, because:\n"
                          + "\n".join("  - " + r for r in reasons))
    datadirc = argflag["run"]["datadirc"]
    live = load.data_file_paths(datlines, datadirc)
    commented = [p for p in _commented_data_paths(text, datadirc)
                 if p not in live and not os.path.isabs(p)
                 and os.path.isfile(os.path.join(moddir, p))]
    for path in live:
        if os.path.isabs(path):
            raise BundleError("Data files must be given by relative paths to be"
                              " packed (Q1.1). This one is absolute:\n  " + path)
        if not os.path.isfile(os.path.join(moddir, path)):
            raise BundleError("A data file does not exist:\n  " + path)
    datapaths = list(dict.fromkeys(live + commented))
    absdata = [os.path.normpath(os.path.join(moddir, p)) for p in datapaths]
    root = os.path.commonpath([moddir] + [os.path.dirname(a) for a in absdata])

    def tree(path):
        return TREE + os.path.relpath(path, root).replace(os.sep, "/")

    bundle = Bundle()
    model_member = tree(modfile)
    hidden = {}
    stored = hide_lines(text, blind_line_numbers(text), hidden)
    bundle.members[model_member] = raw if not hidden else stored.encode("utf-8")
    if hidden:
        bundle.hidden["lines"][model_member] = hidden
    for path in absdata:
        with open(path, "rb") as fil:
            bundle.members[tree(path)] = fil.read()
    # The atomic table, looked up as run_alis would from the model's directory
    cwd = os.getcwd()
    try:
        os.chdir(moddir)
        atomic_path = os.path.abspath(load.atomic_table_path(
            argflag["run"]["atomic"], verbose=-1))
    finally:
        os.chdir(cwd)
    with open(atomic_path, "rb") as fil:
        atomic_member = ATOMIC + os.path.basename(atomic_path)
        bundle.members[atomic_member] = fil.read()
    created = now()
    bundle.manifest.update({
        "format": FORMAT, "version": FORMAT_VERSION,
        "alis_version": alis.__version__, "created": created, "modified": created,
        "model": model_member, "atomic": atomic_member, "unblinding": [],
    })
    for item in sources:
        path, dataset = (item, "") if isinstance(item, str) else item
        add_source(bundle, path, dataset=dataset, embed=embed)
    if with_outputs:
        _pack_outputs(bundle, moddir, os.path.basename(modfile), argflag, live)
    return bundle


def _pack_outputs(bundle, moddir, modname, argflag, datapaths):
    """
    Add the outputs of an earlier plain run as the latest run.

    Generated by RJC and Claude.
    """
    found = {}
    for name in _output_names(modname, argflag, datapaths):
        path = os.path.join(moddir, name)
        if os.path.isfile(path):
            with open(path, "rb") as fil:
                found[os.path.normpath(name)] = fil.read()
    if not found:
        return
    _set_latest(bundle, found, {}, {
        "status": "imported", "imported": now(),
        "note": "outputs found beside the model when it was packed",
    }, bundle.members[bundle.model_member], bundle.hidden_model_lines())


# -- Reading and writing ----------------------------------------------------------


def read(path):
    """
    Read a bundle, checking every member against the manifest (Task 1.5).

    Parameters
    ----------
    path : str
        The ``.model`` file.

    Returns
    -------
    Bundle
        The bundle.

    Raises
    ------
    BundleError
        If the file is not a bundle, was written by a newer ALIS, or is damaged.

    Generated by RJC and Claude.
    """
    if not zipfile.is_zipfile(path):
        raise BundleError("This is not a project bundle (a zip file): " + path)
    with zipfile.ZipFile(path) as zfil:
        names = zfil.namelist()
        if MANIFEST not in names:
            raise BundleError("This zip file is not a project bundle: " + path)
        manifest = json.loads(zfil.read(MANIFEST).decode("utf-8"))
        if manifest.get("format") != FORMAT:
            raise BundleError("This zip file is not a project bundle: " + path)
        if int(manifest.get("version", 0)) > FORMAT_VERSION:
            raise BundleError("This bundle was written by a newer version of ALIS"
                              " (format {0}). Please update ALIS.".format(
                                  manifest.get("version")))
        checksums = manifest.pop("members", {})
        listed = set(checksums)
        present = set(names) - {MANIFEST}
        if listed != present:
            raise BundleError("The bundle is damaged: its members do not match its"
                              " manifest: " + path)
        content = {}
        for name in present:
            data = zfil.read(name)
            if sha256(data) != checksums[name]:
                raise BundleError("The bundle is damaged: {0:s} does not match its"
                                  " checksum".format(name))
            content[name] = data
    hidden = {"lines": {}, "files": {}}
    if HIDDEN in content:
        hidden = json.loads(zlib.decompress(content.pop(HIDDEN)).decode("utf-8"))
    sources = []
    if SOURCES in content:
        sources = json.loads(content.pop(SOURCES).decode("utf-8"))
    return Bundle(members=content, manifest=manifest, hidden=hidden, sources=sources)


def _serialise(bundle):
    """
    Every member of the bundle as bytes, with the manifest last.

    Generated by RJC and Claude.
    """
    content = dict(bundle.members)
    content[SOURCES] = json.dumps(bundle.sources, indent=1).encode("utf-8")
    hidden = {"lines": {k: v for k, v in bundle.hidden["lines"].items() if v},
              "files": dict(bundle.hidden["files"])}
    if hidden["lines"] or hidden["files"]:
        content[HIDDEN] = zlib.compress(json.dumps(hidden).encode("utf-8"), 9)
    manifest = dict(bundle.manifest)
    manifest["modified"] = now()
    manifest["members"] = {name: sha256(data) for name, data in sorted(content.items())}
    content[MANIFEST] = json.dumps(manifest, indent=1).encode("utf-8")
    return content


class _Lock:
    """
    A lock file beside a bundle, so that two programs never write it at once.

    Generated by RJC and Claude.
    """

    def __init__(self, path):
        self.path = path + ".lock"

    def __enter__(self):
        start = time.time()
        while True:
            try:
                fd = os.open(self.path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(fd, str(os.getpid()).encode())
                os.close(fd)
                return self
            except FileExistsError:
                try:
                    if time.time() - os.path.getmtime(self.path) > LOCK_STALE:
                        os.remove(self.path)
                        continue
                except OSError:
                    continue
                if time.time() - start > LOCK_WAIT:
                    raise BundleError("The bundle is being written by another"
                                      " program (lock file {0:s})".format(self.path))
                time.sleep(0.1)

    def __exit__(self, *exc):
        try:
            os.remove(self.path)
        except OSError:
            pass


def _write_unlocked(bundle, path):
    """
    Write the bundle to a temporary file beside ``path``, then rename it.

    Generated by RJC and Claude.
    """
    content = _serialise(bundle)
    folder = os.path.dirname(os.path.abspath(path))
    fd, tmp = tempfile.mkstemp(dir=folder, prefix=".", suffix=".model.tmp")
    try:
        with os.fdopen(fd, "wb") as raw, zipfile.ZipFile(
                raw, "w", compression=zipfile.ZIP_DEFLATED) as zfil:
            for name in sorted(content):
                if name != MANIFEST:
                    zfil.writestr(name, content[name])
            zfil.writestr(MANIFEST, content[MANIFEST])
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.remove(tmp)
        raise


def write(bundle, path):
    """
    Write a bundle: atomically, and under a lock file (Task 1.5, F1).

    Generated by RJC and Claude.
    """
    with _Lock(path):
        _write_unlocked(bundle, path)


def update(path, change):
    """
    Re-read the bundle at ``path``, apply ``change(bundle)``, and write it back.

    Done under the lock, so that changes saved by another program meanwhile
    are kept (Q1.7).

    Generated by RJC and Claude.
    """
    with _Lock(path):
        bundle = read(path)
        change(bundle)
        _write_unlocked(bundle, path)
        return bundle


# -- Unblinding (D24) -------------------------------------------------------------


def unblind(bundle, note=""):
    """
    Put every hidden line and file back in plain form, and log it (Task 1.6).

    The dashboard asks the user to confirm before calling this (D24, Q1.3).

    Generated by RJC and Claude.
    """
    for member, store in list(bundle.hidden["lines"].items()):
        if member in bundle.members and store:
            bundle.members[member] = bundle.text(member, restore=True).encode("utf-8")
    for member, text in bundle.hidden["files"].items():
        bundle.members[member] = text.encode("utf-8")
    bundle.hidden = {"lines": {}, "files": {}}
    bundle.manifest.setdefault("unblinding", []).append({"time": now(), "note": note})


# -- Source spectra (Q0.5, F13) ----------------------------------------------------


def _source_location(entry, bundle_path=None):
    """The path where a source spectrum is expected now."""
    if bundle_path is not None and entry.get("relpath"):
        candidate = os.path.join(os.path.dirname(os.path.abspath(bundle_path)),
                                 entry["relpath"])
        if os.path.isfile(candidate):
            return candidate
    return entry["path"]


def add_source(bundle, path, dataset="", embed=False, bundle_path=None):
    """
    Record a source spectrum by path and checksum, optionally embedding it.

    Returns
    -------
    dict
        The new entry.

    Generated by RJC and Claude.
    """
    with open(path, "rb") as fil:
        data = fil.read()
    num = 1 + max([int(e["id"][1:]) for e in bundle.sources] + [0])
    entry = {"id": "s{0:d}".format(num), "dataset": dataset,
             "path": os.path.abspath(path), "relpath": None,
             "sha256": sha256(data), "size": len(data), "embedded": None}
    if bundle_path is not None:
        entry["relpath"] = os.path.relpath(
            os.path.abspath(path), os.path.dirname(os.path.abspath(bundle_path)))
    bundle.sources.append(entry)
    if embed:
        _embed(bundle, entry, data)
    return entry


def _embed(bundle, entry, data):
    member = EMBEDDED + entry["id"] + "_" + os.path.basename(entry["path"])
    bundle.members[member] = data
    entry["embedded"] = member


def check_sources(bundle, bundle_path=None):
    """
    The state of every source spectrum: ``present``, ``missing`` or ``changed``.

    Returns
    -------
    list of tuple
        ``(entry, state)`` for each source.

    Generated by RJC and Claude.
    """
    states = []
    for entry in bundle.sources:
        where = _source_location(entry, bundle_path)
        if not os.path.isfile(where):
            states.append((entry, "missing"))
            continue
        with open(where, "rb") as fil:
            same = sha256(fil.read()) == entry["sha256"]
        states.append((entry, "present" if same else "changed"))
    return states


def relink_source(bundle, ident, newpath, bundle_path=None):
    """
    Point a moved source spectrum to its new path, if its checksum matches (F13).

    Generated by RJC and Claude.
    """
    entry = bundle.source(ident)
    with open(newpath, "rb") as fil:
        if sha256(fil.read()) != entry["sha256"]:
            raise BundleError("This file is not the same spectrum (its checksum"
                              " differs):\n  " + newpath)
    entry["path"] = os.path.abspath(newpath)
    if bundle_path is not None:
        entry["relpath"] = os.path.relpath(
            os.path.abspath(newpath), os.path.dirname(os.path.abspath(bundle_path)))


def embed_source(bundle, ident, bundle_path=None):
    """
    Embed a copy of a source spectrum, which must be present and unchanged.

    Generated by RJC and Claude.
    """
    entry = bundle.source(ident)
    where = _source_location(entry, bundle_path)
    with open(where, "rb") as fil:
        data = fil.read()
    if sha256(data) != entry["sha256"]:
        raise BundleError("The source spectrum has changed since it was added:\n  "
                          + where)
    _embed(bundle, entry, data)


def unembed_source(bundle, ident):
    """
    Remove the embedded copy of a source spectrum (its path is kept).

    Generated by RJC and Claude.
    """
    entry = bundle.source(ident)
    if entry["embedded"]:
        bundle.members.pop(entry["embedded"], None)
        entry["embedded"] = None


# -- Extracting (D9, D10) --------------------------------------------------------


def _installed_atomic(name):
    """The bytes of the table the installed ALIS reads for ``name``, if any."""
    for path in (os.path.join(load.atomic_datadir(), name),
                 os.path.join(load.atomic_datadir(), load.DEFAULT_ATOMIC)):
        if os.path.isfile(path):
            with open(path, "rb") as fil:
                return fil.read()
    return None


def extract(bundle, outdir, overwrite=False):
    """
    Write a bundle out as plain files (Task 1.8, D9, D10, Q1.3).

    Writes the files tree (the model, with hidden starting values in plain text,
    after a warning), and the latest run's outputs. Hidden best-fit values are
    written only as a plain blind run would write them: a hidden ``.mod.out`` is
    left out, and hidden model lines read "BLIND MODEL". The packed atomic table
    is written beside the model when the installed ALIS would read a different
    one, so that the plain model runs as the bundle does.

    Parameters
    ----------
    bundle : Bundle
        The bundle.
    outdir : str
        The directory to write to.
    overwrite : bool
        Write over existing files.

    Returns
    -------
    tuple
        ``(written, notes)``: the paths written, and notes for the user.

    Generated by RJC and Claude.
    """
    planned, notes = {}, []
    for member in bundle.members:
        if not member.startswith(TREE):
            continue
        if bundle.hidden["lines"].get(member):
            planned[member[len(TREE):]] = bundle.text(
                member, restore=True).encode("utf-8")
        else:
            planned[member[len(TREE):]] = bundle.members[member]
    if bundle.hidden_model_lines():
        notes.append("The model's hidden starting values are written in plain text"
                     " (D10).")
    name, table = bundle.atomic_table()
    if table != _installed_atomic(name):
        target = posixpath.join(bundle.model_dir, name)
        planned[target] = table
        notes.append("The atomic table packed in the bundle differs from the one"
                     " installed with ALIS, so it is written beside the model: "
                     + target)
    prefix = LATEST + "files/"
    for member in bundle.members:
        if member.startswith(prefix):
            store = bundle.hidden["lines"].get(member, {})
            if store:
                text = restore_lines(
                    bundle.members[member].decode("utf-8"), store,
                    replace=lambda real: real if real.lstrip().startswith("#")
                    else BLIND_LINE)
                planned[member[len(prefix):]] = text.encode("utf-8")
            else:
                planned[member[len(prefix):]] = bundle.members[member]
    for member in bundle.hidden["files"]:
        if member.startswith(prefix):
            notes.append("Not written, because it holds blinded values: "
                         + member[len(prefix):])
    targets = {rel: os.path.join(outdir, *rel.split("/")) for rel in planned}
    existing = [t for t in targets.values() if os.path.exists(t)]
    if existing and not overwrite:
        raise BundleError("These files exist already (use -w to overwrite them):\n"
                          + "\n".join("  " + t for t in existing[:10]))
    written = []
    for rel, target in sorted(targets.items()):
        os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
        with open(target, "wb") as fil:
            fil.write(planned[rel])
        written.append(target)
    return written, notes


# -- Running (D9, S31) ------------------------------------------------------------


def _tree_path(model_dir, key):
    """The path in the files tree of an output written at ``key``."""
    path = posixpath.normpath(posixpath.join(model_dir or ".",
                                             key.replace(os.sep, "/")))
    if path.startswith("../") or path == ".." or posixpath.isabs(path):
        return None
    return path


def _set_latest(bundle, files, hidden_marks, info, model_bytes, model_hidden):
    """
    Replace the latest run with ``files`` (output path -> bytes).

    Parameters
    ----------
    bundle : Bundle
        The bundle to change.
    files : dict
        Each output, by its path relative to the model's directory.
    hidden_marks : dict
        Output path to ``None`` (hidden whole) or a set of hidden line numbers.
    info : dict
        The fields of ``run.json`` known so far.
    model_bytes : bytes
        The model as it was run, with placeholders.
    model_hidden : dict
        The model's hidden lines.

    Generated by RJC and Claude.
    """
    for member in [m for m in bundle.members if m.startswith(LATEST)]:
        del bundle.members[member]
    for member in [m for m in bundle.hidden["lines"] if m.startswith(LATEST)]:
        del bundle.hidden["lines"][member]
    for member in [m for m in bundle.hidden["files"] if m.startswith(LATEST)]:
        del bundle.hidden["files"][member]
    listing = {}
    for key, data in sorted(files.items()):
        tree = _tree_path(bundle.model_dir, key)
        if tree is None:
            tree = "outside/" + posixpath.basename(key.replace(os.sep, "/"))
            msgs.warn("An output was written outside the bundle's files tree; it"
                      " is kept as " + tree)
        member = LATEST + "files/" + tree
        mark = hidden_marks.get(os.path.normpath(key), False)
        if mark is None:
            bundle.hidden["files"][member] = data.decode("utf-8")
            listing[member] = "hidden"
            continue
        if mark:
            store = {}
            data = hide_lines(data.decode("utf-8"), mark, store).encode("utf-8")
            bundle.hidden["lines"][member] = store
        bundle.members[member] = data
        listing[member] = sha256(data)
    bundle.members[LATEST + "input.mod"] = model_bytes
    if model_hidden:
        bundle.hidden["lines"][LATEST + "input.mod"] = dict(model_hidden)
    info = dict(info)
    info["outputs"] = listing
    bundle.members[LATEST + "run.json"] = json.dumps(info, indent=1).encode("utf-8")


def _run_info(inst, started, command, overrides, model_bytes, atomic):
    """
    What ``run.json`` records about a run (Task 1.7, S31).

    Generated by RJC and Claude.
    """
    name, table = atomic
    installed = _installed_atomic(name)
    info = {
        "started": started, "finished": now(), "host": platform.node(),
        "alis_version": alis.__version__, "command": command,
        "settings": ["{0} {1} {2}".format(o[0], o[1], o[3]) for o in overrides],
        "model_sha256": sha256(model_bytes),
        "atomic": {"name": name, "sha256": sha256(table),
                   "installed_differs": installed is not None and installed != table},
        "status": "completed",
    }
    if inst is None:
        return info
    if getattr(inst, "_chisq_init", None) is not None:
        info["chi2_initial"] = float(inst._chisq_init)
    fit = getattr(inst, "_fitresults", None)
    if fit is not None:
        info.update({"chi2_final": float(fit.fnorm), "dof": int(fit.dof),
                     "iterations": int(fit.niter), "status_code": int(fit.status)})
        if fit.status == -20:
            info["status"] = "interrupted"
        else:
            from alis.utils import getreason

            info["reason"] = getreason(fit.status, verbose=-1)
    elif inst._argflag["plot"]["only"]:
        info["status"] = "plotted"
    return info


class _LastError(logging.Handler):
    """Keep the last error message emitted while a bundle runs."""

    def __init__(self):
        super().__init__(level=logging.CRITICAL)
        self.message = ""

    def emit(self, record):
        self.message = record.getMessage()


def run(path, argflag, overrides=(), command=None):
    """
    Run a project bundle: ``run_alis project.model`` (Task 1.7, D9).

    The bundle is read into memory; its hidden lines are restored in memory
    only; the fit runs with its data, its atomic table and its outputs all in
    memory; and the outputs are merged into the bundle as it is on disk at the
    end, as ``runs/latest/`` (Q1.7). A run that stops with an error leaves the
    latest run as it was and records the error in ``runs/last_error.json``.

    Parameters
    ----------
    path : str
        The ``.model`` file.
    argflag : ArgFlag
        The settings from the defaults and the command line.
    overrides : list
        The settings the command line changed (``load.optarg``).
    command : str, optional
        The command line, for ``run.json``.

    Returns
    -------
    alis.main.ClassMain
        The finished fit.

    Generated by RJC and Claude.
    """
    from alis.main import ClassMain

    started = now()
    command = command or " ".join(sys.argv)
    try:
        bundle = read(path)
    except BundleError as err:
        msgs.error(str(err))
    text = bundle.model_text(restore=True)
    model_bytes = bundle.members[bundle.model_member]
    store = bundle.hidden_model_lines()
    mask = _MaskHidden(store)
    msgs.addFilter(mask)
    errors = _LastError()
    msgs.addHandler(errors)
    writer = outputs.MemoryOutputs(secret_lines=store.values())
    inst = None
    try:
        reader = copy.deepcopy(argflag)
        reader["out"]["verbose"] = -1

        class _Reader:
            pass

        rd = _Reader()
        rd._argflag = reader
        parlines, datlines, modlines, lnklines = load.load_input(
            rd, textstr=text.splitlines(keepends=True), updateself=False)
        settings = load.set_params(parlines, copy.deepcopy(argflag), verbose=-1)
        load.reapply_cli_overrides(settings, list(overrides), verbose=-1)
        reasons = unsupported(settings, datlines)
        if reasons:
            msgs.error("This bundle cannot be run as it is, because:" + msgs.newline()
                       + msgs.newline().join(reasons) + msgs.newline()
                       + "Extract it first (run_alis --extract) and run the plain"
                       " model.")
        argflag["run"]["modname"] = bundle.model_name
        inst = ClassMain(argflag, parlines=parlines, datlines=datlines,
                         modlines=modlines, lnklines=lnklines,
                         data=bundle.data_for_run(), cli_overrides=list(overrides),
                         writer=writer, atomic=bundle.atomic_table())
    except SystemExit as stop:
        if stop.code not in (0, None):
            error = {"time": now(), "message": errors.message, "command": command,
                     "model_sha256": sha256(model_bytes)}
            update(path, lambda b: b.members.__setitem__(
                LAST_ERROR, json.dumps(error, indent=1).encode("utf-8")))
            raise
        info = _run_info(inst, started, command, overrides, model_bytes,
                         bundle.atomic_table())
        info["status"] = "stopped"
        if writer.files:
            update(path, lambda b: _set_latest(b, writer.files, writer.hidden, info,
                                               model_bytes, store))
        raise
    finally:
        msgs.removeFilter(mask)
        msgs.removeHandler(errors)
    info = _run_info(inst, started, command, overrides, model_bytes,
                     bundle.atomic_table())
    update(path, lambda b: _set_latest(b, writer.files, writer.hidden, info,
                                       model_bytes, store))
    msgs.info("The outputs were stored in the bundle:" + msgs.newline() + path)
    return inst


def pack_to(modfile, path, overwrite=False, **kwargs):
    """
    Pack ``modfile`` and write the bundle to ``path`` (``run_alis --pack``).

    Generated by RJC and Claude.
    """
    if os.path.exists(path) and not overwrite:
        raise BundleError("The bundle exists already (use -w to overwrite it): "
                          + path)
    bundle = pack(modfile, **kwargs)
    write(bundle, path)
    return bundle


def default_bundle_name(modfile):
    """The bundle ``--pack`` writes by default: the model's name, ``.model``."""
    stem = os.path.splitext(modfile)[0]
    return stem + SUFFIX


def default_extract_dir(path):
    """The directory ``--extract`` writes to by default, beside the bundle."""
    return os.path.splitext(path)[0]


__all__ = [
    "Bundle", "BundleError", "pack", "pack_to", "read", "write", "update", "run",
    "extract", "unblind", "add_source", "check_sources", "relink_source",
    "embed_source", "unembed_source", "hide_lines", "restore_lines",
    "blind_line_numbers", "unsupported",
]
