"""Typed configuration dataclasses for ALIS (Stage 2.1).

The ``argflag`` settings structure -- historically a nested string-keyed
dict of dicts built in ``load.load_settings`` -- is represented here as
typed dataclasses. To keep the Stage 0 regression suite green while the
rest of the code base still uses ``argflag['section']['key']`` syntax, the
dataclasses expose dict-like access through :class:`_DictLike` (Q2.3:
incremental migration with dict-style access during the transition).

Field names, default values and default types mirror the original
``initialise()`` defaults exactly, so settings-file parsing
(``load.set_params``), which introspects value types, is unchanged.

Generated by RJC and Claude.
"""

from dataclasses import dataclass, field, fields
from typing import Any, Optional


class _DictLike:
    """Mixin giving a dataclass ``d['key']`` access during the migration.

    Only the operations the code base actually performs on ``argflag`` are
    implemented: subscripted get/set, ``keys()`` and ``in`` membership.
    Iteration and ``.items()``/``.values()`` are intentionally omitted --
    nothing uses them (checked in Stage 2.1).

    Generated by RJC and Claude.
    """

    def __getitem__(self, key: str) -> Any:
        if key in self.__dataclass_fields__:
            return getattr(self, key)
        raise KeyError(key)

    def __setitem__(self, key: str, value: Any) -> None:
        if key not in self.__dataclass_fields__:
            raise KeyError(key)
        setattr(self, key, value)

    def keys(self):
        return list(self.__dataclass_fields__)

    def __contains__(self, key: str) -> bool:
        return key in self.__dataclass_fields__


@dataclass
class RunConfig(_DictLike):
    """The ``run`` settings section."""

    prognm: str = "alis.py"
    last_update: str = "Last updated 27th May 2024"
    atomic: str = "atomic.xml"
    datadirc: str = ""
    modname: str = "model.mod"
    convergence: bool = False
    convnostop: bool = False
    convcriteria: float = 0.2
    datatype: str = "default"
    limpar: bool = False
    ncpus: int = -1
    ngpus: Optional[int] = None
    nsubpix: int = 5
    nsubmin: int = 5
    nsubmax: int = 21
    warn_subpix: int = 100
    renew_subpix: bool = False
    blind: bool = True
    bintype: str = "km/s"
    logn: bool = True
    capvalue: Optional[float] = None


@dataclass
class ChisqConfig(_DictLike):
    """The ``chisq`` settings section."""

    miniter: int = 0
    maxiter: int = 20000
    atol: float = 1.0e-10
    xtol: float = 1.0e-10
    ftol: float = 1.0e-10
    gtol: float = 1.0e-10
    fstep: float = 1.0


@dataclass
class PlotConfig(_DictLike):
    """The ``plot`` settings section."""

    dims: str = "3x3"
    fits: bool = True
    residuals: bool = False
    xaxis: str = "observed"
    labels: bool = False
    only: bool = False
    pages: str = "all"
    ticks: bool = True
    ticklabels: bool = False
    fitregions: bool = False


@dataclass
class OutConfig(_DictLike):
    """The ``out`` settings section."""

    wavecorr: bool = False
    model: bool = True
    modelname: str = ""
    plots: str = ""
    fits: bool = False
    onefits: bool = False
    overwrite: bool = False
    sm: bool = False
    verbose: int = 2
    reletter: bool = False
    covar: str = ""
    convtest: str = ""


@dataclass
class SimConfig(_DictLike):
    """The ``sim`` settings section."""

    repeat: Optional[int] = None
    random: Optional[int] = None
    perturb: Optional[Any] = None
    systematics: bool = False
    beginfrom: str = ""
    startid: int = 0
    maxperturb: float = 0.1
    systmodule: Optional[str] = None
    newstart: bool = True
    dirname: str = "sims"
    edgecut: float = 4.0


@dataclass
class GenerateConfig(_DictLike):
    """The ``generate`` settings section."""

    pixelsize: float = 2.5
    data: bool = False
    overwrite: bool = False
    peaksnr: float = 0.0
    skyfrac: float = 0.0


@dataclass
class IterateConfig(_DictLike):
    """The ``iterate`` settings section."""

    model: Optional[Any] = None
    data: Optional[Any] = None


@dataclass
class ModelPass(_DictLike):
    """The parsed model structure (formerly the ``modpass`` dict).

    Each field is a parallel list populated by ``load.load_model``; entry
    ``i`` of every list describes the same model component. Field names,
    order and list semantics mirror the original dict exactly, and
    ``modpass['mtyp']`` access is preserved via :class:`_DictLike`.

    Generated by RJC and Claude.
    """

    mtyp: list = field(default_factory=list)  # Type of model
    mpar: list = field(default_factory=list)  # Parameters for the model
    mtie: list = field(default_factory=list)  # Tied parameters + target
    mlim: list = field(default_factory=list)  # Limited parameters + value
    mlnk: list = field(default_factory=list)  # Linked parameter strings
    mfix: list = field(default_factory=list)  # Whether a parameter is fixed
    tpar: list = field(default_factory=list)  # Letters used to tie/fix params
    mkey: list = field(default_factory=list)  # Keyword parameters
    psto: list = field(default_factory=list)
    p0: list = field(default_factory=list)    # Variables/parameters
    emab: list = field(default_factory=list)  # Emission or Absorption?
    line: list = field(default_factory=list)  # Index of the modlines row


@dataclass
class DataOpt(_DictLike):
    """Per-snip data options (formerly the ``datopt`` dict).

    Each field is a parallel list populated by ``load.load_data`` -- entry
    ``i`` of every list describes the same loaded data snip. Field names,
    order and list semantics mirror the original dict exactly, and
    ``datopt['specid']`` access is preserved via :class:`_DictLike`.

    Generated by RJC and Claude.
    """

    specid: list = field(default_factory=list)
    fitrange: list = field(default_factory=list)
    loadrange: list = field(default_factory=list)
    plotone: list = field(default_factory=list)
    nsubpix: list = field(default_factory=list)
    bintype: list = field(default_factory=list)
    columns: list = field(default_factory=list)
    systematics: list = field(default_factory=list)
    systmodule: list = field(default_factory=list)
    label: list = field(default_factory=list)
    yrange: list = field(default_factory=list)


@dataclass
class AtomicData(_DictLike):
    """Atomic line data (formerly the ``atmdata`` / ``self._atomic`` dict).

    Built empty in ``load.load_atomic`` and then populated with parallel
    numpy arrays read from the atomic data file (each field is ``None``
    until assigned). Field names mirror the original dict keys, and
    ``atomic['Ion']`` access is preserved via :class:`_DictLike`.

    Generated by RJC and Claude.
    """

    Ion: Optional[Any] = None
    Wavelength: Optional[Any] = None
    fvalue: Optional[Any] = None
    Gamma: Optional[Any] = None
    Qvalue: Optional[Any] = None
    Kvalue: Optional[Any] = None
    Element: Optional[Any] = None
    AtomicMass: Optional[Any] = None


@dataclass
class ColumnMap(_DictLike):
    """Column indices for a loaded data file (formerly the ``wfe`` dict).

    Maps each data quantity to its column index in the input file; ``-1``
    means "not present". Built per data line in ``load.load_data`` (and
    overridden by the ``columns`` keyword, whose allowed names are exactly
    these fields), then stored in ``datopt['columns']``. ``wfe['flux']``
    access and ``.keys()`` (used by ``save``) are preserved via
    :class:`_DictLike`; field order matches the original dict literal.

    Generated by RJC and Claude.
    """

    wave: int = 0
    flux: int = 1
    error: int = 2
    continuum: int = -1
    zerolevel: int = -1
    systematics: int = -1
    fitrange: int = -1
    loadrange: int = -1
    resolution: int = -1


@dataclass
class ArgFlag(_DictLike):
    """The full ALIS settings structure (formerly the ``argflag`` dict).

    Sections are accessible either as attributes (``cfg.run.ncpus``) or,
    for backward compatibility during the migration, dict-style
    (``cfg['run']['ncpus']``).
    """

    run: RunConfig = field(default_factory=RunConfig)
    chisq: ChisqConfig = field(default_factory=ChisqConfig)
    plot: PlotConfig = field(default_factory=PlotConfig)
    out: OutConfig = field(default_factory=OutConfig)
    sim: SimConfig = field(default_factory=SimConfig)
    generate: GenerateConfig = field(default_factory=GenerateConfig)
    iterate: IterateConfig = field(default_factory=IterateConfig)
