import os
import datetime
import numpy as np
from alis import logger
from alis.utils import getreason
msgs = logger.msgs()


def assess_restarts(slf, restarts, refparams, perror):
    """Assess multi-start / random-restart convergence (Stage 3.3).

    Given the best-fit parameters from a set of randomised restarts (each row of
    ``restarts``), decide whether the fit "remembers" its starting values by
    testing, for every free parameter, that the restarts agree with the
    reference best-fit ``refparams`` within ``sim convergesig`` sigma. Two
    selectable tests (``sim convergetest``):

    - ``maxdev`` (default): max over restarts of |restart - refparams| / sigma
      must be <= X. Strict -- flags any single restart that stuck.
    - ``scatter``: the restart-to-restart std / sigma must be <= X. Statistical
      -- the restart spread is consistent with the fit error, robust to one
      outlier restart.

    Prints a report and writes ``<modelname>.converge``, and returns
    ``(converged, n_failed, n_free)`` (or ``None`` if it could not assess).
    Defensive: never raises (a report failure must not abort the simulations).

    NOTE: the ``sim random`` restarts each fit a fresh noise realisation, so the
    spread reflects noise as well as start-dependence; the report states this.

    Generated by RJC and Claude.
    """
    try:
        restarts = np.atleast_2d(np.asarray(restarts, dtype=float))
        refparams = np.asarray(refparams, dtype=float)
        perror = np.asarray(perror, dtype=float)
        nrun = restarts.shape[0]
        test = str(slf._argflag['sim']['convergetest']).lower()
        xsig = float(slf._argflag['sim']['convergesig'])
        newstart = bool(slf._argflag['sim']['newstart'])
        verbose = slf._argflag['out']['verbose']
        if nrun < 2:
            msgs.warn("Not enough restarts ({0:d}) to assess convergence".format(
                nrun), verbose=verbose)
            return None
        free = np.where(perror > 0.0)[0]
        rows, nfail, worst = [], 0, (None, 0.0)
        for j in free:
            col = restarts[:, j]
            if test == "scatter":
                metric = np.std(col) / perror[j]
            else:  # maxdev (default)
                metric = np.max(np.abs(col - refparams[j])) / perror[j]
            passed = metric <= xsig
            if not passed:
                nfail += 1
            if metric > worst[1]:
                worst = (j, metric)
            rows.append((j, refparams[j], perror[j], metric, passed))
        converged = nfail == 0

        metric_name = {"scatter": "std/sigma"}.get(test, "maxdev/sigma")
        lines = []
        lines.append("# ALIS multi-start convergence assessment")
        lines.append("# Model: {0:s}".format(slf._argflag['run']['modname']))
        lines.append("# Restarts: {0:d}   newstart={1}   test={2}   "
                     "tolerance={3:.1f} sigma".format(nrun, newstart, test, xsig))
        if newstart:
            lines.append("# Starts drawn from the fit covariance; each restart "
                         "also fits a fresh noise realisation, so the spread "
                         "includes noise as well as start-dependence.")
        lines.append("#")
        lines.append("# {0:>5s} {1:>16s} {2:>14s} {3:>12s}  {4}".format(
            "par", "best-fit", "1sigma", metric_name, "flag"))
        for j, val, err, metric, passed in rows:
            lines.append("  {0:>5d} {1:>16.8g} {2:>14.6g} {3:>12.3f}  {4}".format(
                j, val, err, metric, "" if passed else "<== > tol"))
        lines.append("#")
        if converged:
            lines.append("# Result: CONVERGED -- all {0:d} free parameters agree "
                         "within {1:.1f} sigma across restarts.".format(
                             len(free), xsig))
        else:
            lines.append("# Result: NOT CONVERGED -- {0:d}/{1:d} free parameters "
                         "exceed {2:.1f} sigma (worst: par {3} at {4:.2f} "
                         "sigma).".format(nfail, len(free), xsig, worst[0],
                                          worst[1]))
        text = "\n".join(lines)
        msgs.info("Multi-start convergence assessment:", verbose=verbose)
        print(text)
        fname = slf._argflag['out']['modelname'] + ".converge"
        try:
            with open(fname, "w") as fh:
                fh.write(text + "\n")
            msgs.info("Saved convergence assessment: {0:s}".format(fname),
                      verbose=verbose)
        except OSError as err:
            msgs.warn("Could not write {0:s}: {1}".format(fname, err),
                      verbose=verbose)
        return converged, nfail, len(free)
    except Exception as err:
        msgs.warn("Could not assess multi-start convergence: {0}".format(err),
                  verbose=slf._argflag['out']['verbose'])
        return None

def print_model(diff, mp, thresh, verbose=2, funcarray=[None, None, None]):
    function=funcarray[0]
    funccall=funcarray[1]
    funcinst=funcarray[2]
    level=0
    convstring = ""
    donecv, donesh, donezl = [], [], []
    lastemab=""
    for i in range(len(mp['mtyp'])):
        #if errs is not None and mp['emab'][i] == "cv": continue
        mtyp = mp['mtyp'][i]
        if mp['emab'][i] != lastemab:
            if   mp['emab'][i]=="em": aetag = "emission"
            elif mp['emab'][i]=="ab": aetag = "absorption"
            elif mp['emab'][i]=="cv": aetag = "Convolution"
            elif mp['emab'][i]=="sh": aetag = "Shift"
            elif mp['emab'][i]=="zl": aetag = "zerolevel"
            convstring += "#"+aetag+"\n"
            lastemab = mp['emab'][i]
        funcinst[mtyp]._keywd = mp['mkey'][i]
        outstr, cnvstr, level = funccall[mtyp].parout(funcinst[mtyp], diff, mp, i, level, conv=thresh)
        if outstr in donecv or outstr in donesh or outstr in donezl: continue
        if mp['emab'][i] == "cv": donecv.append(outstr) # Make sure we don't print convolution more than once.
        if mp['emab'][i] == "sh": donesh.append(outstr) # Make sure we don't print shifts more than once.
        if mp['emab'][i] == "zl": donezl.append(outstr) # Make sure we don't print zerolevel more than once.
        convstring += cnvstr
    return convstring

def save_convtest(slf,diff,thresh,info,printout=True,extratxt=["",""]):
    """
    Save the details of what parameters have converged.
    """
    msgs.info("Saving the best-fitting model parameters", verbose=slf._argflag['out']['verbose'])
    filename = extratxt[0]+slf._argflag['out']['modelname']+'.conv'+extratxt[1]
    prestring = "#\n#  Generated by ALIS on {0:s}\n#\n".format(datetime.datetime.now().strftime("%d/%m/%y at %H:%M:%S"))
    prestring += "#   Running Time (hrs)  = {0:f}\n".format(info[0])
    prestring += "#   Initial Chi-Squared = {0:f}\n".format(slf._chisq_init)
    prestring += "#   Bestfit Chi-Squared = {0:f}\n".format(info[1])
    prestring += "#   Degrees-of-Freedom  = {0:d}\n".format(info[2])
    prestring += "#   Num. of Iterations  = {0:d}\n".format(info[3])
    prestring += "#   Convergence Reason  = {0:s}\n".format(getreason(info[4],verbose=slf._argflag['out']['verbose']))
    prestring += "\n"
    inputmodl = "#\n"
    for i in range(len(slf._parlines)):
        prestring += slf._parlines[i]
        inputmodl += "#   "+slf._parlines[i]
    prestring +="\ndata read\n"
    inputmodl += "#   data read\n"
    msgs.bug("INCLUDE THE BEST-FIT FWHM HERE --- PLACE THE ERROR BELOW", verbose=slf._argflag['out']['verbose'])
    for i in range(len(slf._datlines)):
        prestring += slf._datlines[i]
        inputmodl += "#   "+slf._datlines[i]
    prestring +="data end\n"
    inputmodl += "#   data end\n"
    prestring +="\nmodel read\n"
    inputmodl += "#   model read\n"
    modcomlin=[]
    modcomind=[]
    tconvstring=''
    for i in range(len(slf._modlines)):
        if slf._modlines[i].split()[0] in ["fix", "lim"]: tconvstring += slf._modlines[i].replace('\t',' ')
        if slf._modlines[i].lstrip()[0] == '#':
            modcomlin.append(slf._modlines[i].rstrip('\n'))
            modcomind.append(i)
        inputmodl += "#   "+slf._modlines[i]
    convstring = print_model(diff,slf._modpass,thresh,verbose=slf._argflag['out']['verbose'],funcarray=slf._funcarray)
#	if printout and slf._argflag['out']['verbose'] != -1:
#		print "\n####################################################"
#		print convstring
#		print "####################################################\n"
    # Reinsert the comments at the original locations
    cnvstrspl = (tconvstring+convstring).split('\n')
    for i in range(len(modcomlin)): cnvstrspl.insert(modcomind[i],modcomlin[i])
    convstring = '\n'.join(cnvstrspl)
    # Include an end tag for the model
    convstring += "model end\n"
    inputmodl += "#   model end\n#\n\n"
    if slf._argflag['out']['overwrite']: ans='y'
    else: ans=''
    if os.path.exists(filename):
        while ans != 'y' and ans != 'n' and ans !='r':
            msgs.warn("File %s exists!" % (filename), verbose=slf._argflag['out']['verbose'])
            ans = nput(msgs.input()+"Overwrite? (y/n) or rename? (r) - ")
            if ans == 'r':
                fileend=input(msgs.input()+"Enter new filename - ")
                filename = fileend
                if os.path.exists(filename): ans = ''
    if ans != 'n':
        infile = open(filename,"w")
        infile.write(prestring)
        infile.write(convstring+"\n")
        infile.write("\n###################################################")
        infile.write("\n#                                                 #")
        infile.write("\n#          HERE IS A COPY OF THE INPUT MODEL      #")
        infile.write("\n#                                                 #")
        infile.write("\n###################################################\n")
        infile.write(inputmodl)
        infile.close()
        msgs.info("Saved output file successfully:"+msgs.newline()+filename, verbose=slf._argflag['out']['verbose'])

