"""Batched GPU dispatch for the model evaluation (Stage 4.3).

Task 4.1 fixed the *per-component* shape of the CPU/GPU contract: a model
function's ``call_GPU`` takes device arrays and a batch of profiles, launches
one kernel, and returns a device array -- it never transfers. Everything the
speed actually depends on therefore lives here, in the dispatcher (Q4.7):

* **Batching.** ``model_eval.model_func`` evaluates one *row* at a time on the
  CPU (Stage 3.1 made the profile cache per-row). This module instead sends a
  whole ``(sp, sn, ea, md)`` group -- every transition of every component of one
  model type in one snip -- to the device in a single launch. The Stage 4.2
  benchmark put the crossover at roughly 1e4 pixel-components, so batching is
  what moves a snip from the losing side of that line to the winning side.

* **Device residency.** The (shifted) sub-pixel wavelength grid is uploaded
  once and kept on the device, keyed by the snip and the shift parameters that
  produced it, so a fit whose shift model is fixed -- the usual case -- pays for
  the upload once per iteration rather than once per evaluation. When
  ``run renew_subpix`` rebuilds the sub-pixel grid the cache is dropped, which
  is why the upload is per-iteration and not per-fit.

* **The small-array fallback.** Below ``run gputhresh`` pixel-components the
  launch plus transfer costs more than the kernel saves, so the group falls
  through to the unchanged CPU path. The same happens for any function that has
  not opted in to GPU support.

**No numba import at module scope.** As in :mod:`alis.gpu`, every ``numba``
import happens inside a function, and only once a GPU backend is actually
active, so a CPU-only install never imports it (Task 4.1).

There is one dispatcher per *process*: the parent (which evaluates the base
model) and each GPU worker (which owns one device) enable their own. It is
module state rather than something carried on ``FitState`` because device
arrays cannot be pickled to the workers.

Generated by RJC and Claude.
"""

import numpy as np

from alis import logger

msgs = logger.msgs()

# Minimum number of pixel-components (sub-pixels x profile rows) for a group to
# be worth a kernel launch. From the Stage 4.2 kernel benchmark on an RTX
# 2080 Ti: 1000x1 ran at 0.9x the CPU (a loss), 10000x1 at 5.2x and 10000x20 at
# 25x. Exposed as ``run gputhresh`` so it can be tuned per model -- and so the
# GPU regression tests can force the device path on small examples.
DEFAULT_THRESHOLD = 10000

# Cap on the number of cached device wavelength grids. One entry per (snip,
# shift-parameter) combination; DH_orders, the largest model in hand, has 351.
_WAVE_CACHE_MAX = 4096

_ACTIVE = None


class Dispatcher:
    """Owns this process's device buffers and issues the batched launches.

    Generated by RJC and Claude.
    """

    def __init__(self, threshold=DEFAULT_THRESHOLD, verbose=2):
        self.threshold = int(threshold)
        self.verbose = verbose
        # The sub-pixel grid the cached wave buffers were derived from. Held as
        # a strong reference and compared by identity: ``load.load_subpixels``
        # returns a fresh list whenever ``renew_subpix`` rebuilds the grid, so a
        # changed identity is exactly the signal that the cache is stale.
        self._grid_ref = None
        self._wave_cache = {}
        # Counters, so a test can assert the device path was actually taken
        # rather than silently falling back to the CPU (Task 4.6).
        self.nlaunch = 0
        self.ngroups_gpu = 0
        self.ngroups_cpu = 0
        self.nrows_gpu = 0
        self.nwave_upload = 0
        self.nwave_reuse = 0

    # -- per-iteration state -------------------------------------------------

    def begin_iteration(self):
        """Start a new fit iteration (called from ``alfit.prepare_iteration``).

        Stage 3.5.2's ``prepare_iteration`` is the per-iteration seam, and the
        stage doc puts the read-only device upload here: the sub-pixel grid can
        change between iterations (``renew_subpix``), so the buffers are
        refreshed once per iteration rather than once per fit. Dropping them
        here rather than lazily also bounds the parent's device memory to one
        iteration's worth of shifted grids, which matters when the shift model
        is free and every evaluation produces a different grid.

        Within an iteration the buffers survive, so the base call and every
        line-search evaluation after it share one upload; the workers, which
        never reach this hook, keep theirs for the whole chunk.

        Generated by RJC and Claude.
        """
        self.note_grid(None)

    def note_grid(self, wavespx):
        """Register the sub-pixel grid this evaluation is using.

        Invalidates every cached device wavelength buffer when the grid object
        changes (``renew_subpix``), since those buffers were derived from it.

        Generated by RJC and Claude.
        """
        if wavespx is self._grid_ref:
            return
        self._grid_ref = wavespx
        self._wave_cache.clear()

    # -- routing -------------------------------------------------------------

    def should_dispatch(self, inst, nwave, nrow):
        """Return True if this component group is worth sending to the device.

        Parameters
        ----------
        inst : Base
            The model-function instance (``funcarray[2][mtyp]``).
        nwave : int
            Number of sub-pixels in this snip.
        nrow : int
            Number of profile rows in this group.

        Generated by RJC and Claude.
        """
        if not inst.supports_gpu():
            self.ngroups_cpu += 1
            return False
        if nwave * nrow < self.threshold:
            self.ngroups_cpu += 1
            return False
        return True

    # -- device buffers ------------------------------------------------------

    def wave_device(self, key, wave):
        """Return ``wave`` as a device array, uploading it only when it changes.

        ``key`` identifies the snip and the shift parameters that produced this
        (shifted) grid, so an unchanged shift model -- the usual case -- reuses
        the resident buffer with no transfer at all.

        Generated by RJC and Claude.
        """
        buf = self._wave_cache.get(key)
        if buf is not None:
            self.nwave_reuse += 1
            return buf
        from numba import cuda

        if len(self._wave_cache) >= _WAVE_CACHE_MAX:
            self._wave_cache.clear()
        buf = cuda.to_device(np.ascontiguousarray(wave, dtype=np.float64))
        self._wave_cache[key] = buf
        self.nwave_upload += 1
        return buf

    def _launch(self, cls, inst, wave_dev, params, ae, mkey):
        """Upload one batch of parameters, launch, and bring the result back.

        Generated by RJC and Claude.
        """
        from numba import cuda

        pin = cuda.to_device(np.ascontiguousarray(params, dtype=np.float64))
        out = cls.call_GPU(inst, wave_dev, pin, ae=ae, mkey=mkey)
        self.nlaunch += 1
        self.nrows_gpu += params.shape[0]
        return out.copy_to_host()

    def batch(self, cls, inst, wave_dev, params, mkey, ae):
        """Evaluate one component group on the device.

        Returns ``(combined, continuum)``: the whole group reduced exactly as
        ``model_func``'s per-row loop reduces it (summed for ``ae='em'``,
        multiplied otherwise, in row order), and the same reduction over just
        the rows whose ``continuum`` keyword is set -- or ``None`` when no row
        sets it. Splitting the continuum out needs a second launch only when
        the group is *mixed*; an all-continuum group reuses the first result.

        Generated by RJC and Claude.
        """
        combined = self._launch(cls, inst, wave_dev, params, ae, mkey)
        self.ngroups_gpu += 1
        cont = [i for i in range(len(mkey)) if mkey[i]["continuum"]]
        if not cont:
            return combined, None
        if len(cont) == params.shape[0]:
            return combined, combined
        sub = np.ascontiguousarray(params[cont, :])
        subkey = [mkey[i] for i in cont]
        return combined, self._launch(cls, inst, wave_dev, sub, ae, subkey)


def warm_up(verbose=2):
    """Pay the GPU's one-off start-up costs before anything is timed (4.3a).

    A cold GPU launch costs a CUDA context (~0.6 s) plus the ``@cuda.jit``
    compile of the kernel (~0.9 s, measured on the Voigt), which is why the
    stage doc insists the ``auto`` probe warms both backends first: a cold
    probe would mostly time the compiler and mis-pick the CPU. Called once per
    process -- in the parent and, via the Pool warm task, in every GPU worker.

    Only the Voigt kernel is warmed, because it is the only one that exists.
    When a second function is ported (Task 4.4) this should become a per-
    function hook rather than a hard-coded import.

    Returns True if a kernel was actually compiled and launched.

    Generated by RJC and Claude.
    """
    try:
        import numpy as _np
        from numba import cuda

        from alis.functions import voigt_gpu

        wave = cuda.to_device(_np.linspace(1215.0, 1216.0, 64))
        pin = cuda.to_device(_np.array([[14.0, 0.0, 10.0, 1215.6701, 0.4164, 6.265e8]]))
        voigt_gpu.evaluate(wave, pin, ae="ab", mkey=None).copy_to_host()
        return True
    except Exception as err:
        # Warming is an optimisation, not a requirement: a failure here would
        # reappear (loudly) at the first real launch, so do not abort the fit.
        msgs.warn(f"Could not warm up the GPU backend ({err})", verbose=verbose)
        return False


def enable(threshold=None, verbose=2):
    """Activate the GPU dispatcher for this process. Idempotent.

    Called by the parent once the backend has resolved to ``gpu``, and by each
    GPU worker after it binds its device.

    Generated by RJC and Claude.
    """
    global _ACTIVE
    if threshold is None:
        threshold = DEFAULT_THRESHOLD
    if _ACTIVE is None or _ACTIVE.threshold != int(threshold):
        _ACTIVE = Dispatcher(threshold=threshold, verbose=verbose)
    return _ACTIVE


def disable():
    """Deactivate the GPU dispatcher, releasing its device buffers.

    Generated by RJC and Claude.
    """
    global _ACTIVE
    _ACTIVE = None


def active():
    """Return this process's dispatcher, or ``None`` on the CPU backend.

    ``model_eval.model_func`` calls this once per evaluation; on the CPU
    backend it is a single module-global read and the evaluation proceeds down
    the unchanged CPU path.

    Generated by RJC and Claude.
    """
    return _ACTIVE
