""" Absorption LIne Software
"""

# Import standard libraries
import os
import pdb
import sys
import time
import copy
import signal
import warnings
import traceback
import numpy as np
# Import a Chi-Squared minimisation package
from alis.minimise import alfit
# Import useful ALIS definitions:
from alis import convergence
from alis import load
from alis import model_eval
from alis import plot
from alis import save
from alis import utils
from alis.functions import base
from alis import logger
msgs = logger.msgs()


def build_funcarray(argflag, atomic):
    """Load the model-function registry once (Stage 2.2).

    Each model-function class is instantiated exactly once, into
    ``[names, classes, instances]``:

    - ``[0]`` list of function keywords (``mtyp in funcarray[0]``);
    - ``[1]`` keyword -> class, used as ``funcarray[1][k].method(inst, ...)``;
    - ``[2]`` keyword -> the single reusable instance.

    ``[1]`` and ``[0]`` are derived from the instances (the class is
    ``type(instance)``), so ``base.call`` runs only once rather than three
    times. The same registry is reused for the whole fit -- including the
    ``sim repeat`` loop -- since the function instances hold no per-fit
    state beyond ``_keywd``, which is reset before every use.

    Generated by RJC and Claude.
    """
    verbose = argflag['out']['verbose']
    instances = base.call(prgname=argflag['run']['prognm'], getinst=True,
                          verbose=verbose, atomic=atomic)
    for key in instances.keys():
        instances[key]._verbose = verbose
    names = list(instances.keys())
    classes = {key: type(inst) for key, inst in instances.items()}
    return [names, classes, instances]

#from multiprocessing import Pool as mpPool
#import pycuda.driver as cuda
#import pycuda.autoinit
#from pycuda.compiler import SourceModule

### TO BE IMPLEMENTED ###
# Supermongo
# Make sure there is some data in the fitted region (when you load a model)
# Make sure each snip contains an absorption feature (or give a warning).
# generate starting parameter files


class ClassMain:

    def __init__(self, argflag, getinst=False, modelfile=None, parlines=[], datlines=[], modlines=[], lnklines=[], data=None, fitonly=False, verbose=None):
        if getinst: return # Just get an instance

        # Set parameters
        self._argflag = argflag
        if verbose is not None: self._argflag['out']['verbose'] = verbose
        # Apply the console verbosity to the logger (Stage 2.5)
        logger.set_verbosity(self._argflag['out']['verbose'])
        self._retself = False
        self._fitonly = fitonly
        self._isonefits = False

        # First send all signals to messages to be dealt
        # with (i.e. someone hits ctrl+c)
        signal.signal(signal.SIGINT, msgs.signal_handler)

        # Ignore all warnings given by python
        warnings.resetwarnings()
        warnings.simplefilter("ignore")

        # Record the starting time
        self._tstart=time.time()

        # Load the Input file
        if modelfile is not None:
            self._argflag['run']['modname'] = modelfile
            self._parlines, self._datlines, self._modlines, self._lnklines = load.load_input(self)
            self._retself = True
        elif parlines != [] or modlines != [] or datlines != [] or lnklines != []:
            self._parlines, self._datlines, self._modlines, self._lnklines = parlines, datlines, modlines, lnklines
            self._argflag = load.set_params(self._parlines, copy.deepcopy(self._argflag), setstr="Model ")
            load.check_argflag(self._argflag)
            self._retself = True
        else:
            self._parlines, self._datlines, self._modlines, self._lnklines = load.load_input(self)
        # Load the atomic data
        self._atomic = load.load_atomic(self)

        # Build the model-function registry once (Stage 2.2)
        self._funcarray = build_funcarray(self._argflag, self._atomic)

        # Load the Data
        load.load_data(self, self._datlines, data=data)

        # Load the Model
        self._modpass = load.load_model(self, self._modlines)

        # Load the Links
        self._links = load.load_links(self, self._lnklines)

        if self._argflag['out']['modelname'] in ['', "\"\""]:
            self._argflag['out']['modelname'] = self._argflag['run']['modname'] + '.out'

        #		print self._modpass
#		print self._snipid
#		print self._specid
#		sys.exit()

        # Fit the data!
        if isinstance(self._argflag['sim']['repeat'], int):
            base_outname = self._argflag['out']['modelname']
            for sim in range(self._argflag['sim']['repeat']):
                msgs.simulate("Realisation {0:s}/{1:s} began {2:s}".format(str(sim + 1), str(
                    self._argflag['sim']['repeat']), time.ctime()), verbose=self._argflag['out']['verbose'])

                # Reuse the registry built at start-up (Stage 2.2): the
                # function instances hold no per-fit state, so they are not
                # re-instantiated each realisation.
                # Reload the model
                self._modpass = load.load_model(self, self._modlines)
                # Reload the Links
                self._links = load.load_links(self, self._lnklines)
                # self._argflag['out']['modelname'] = self._argflag['out']['modelname'].replace('.out', '_{0:03d}.out'.format(ii))
                self._argflag['out']['modelname'] = base_outname + '.REPEAT{0:03d}'.format(sim)
                self.main()
        else:
            self.main()

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# The fitting code


    def model_func(self, x, p, pos, ddpid=None, getemab=False, output=0):
        return model_eval.model_func(self, x, p, pos, ddpid=ddpid,
                                getemab=getemab, output=output)

    def model_func_ddp(self, x, p, pp, pos, ddpid=None, emab=None, output=0):
        return model_eval.model_func_ddp(self, x, p, pp, pos, ddpid=ddpid,
                                    emab=emab, output=output)

    def myfunct(self, p, fjac=None, x=None, y=None, err=None, output=0,
                ddpid=None, pp=None, getemab=False, emab=None):
        return model_eval.myfunct(p, fjac=fjac, x=x, y=y, err=err, state=self,
                             output=output, ddpid=ddpid, pp=pp,
                             getemab=getemab, emab=emab)

    # Now for the fitting code
    def main(self):
        m = None
        msgs.info("Preparing model parameters",verbose=self._argflag['out']['verbose'])
        # Prepare the parameters and their limits
        wavf, fluf, errf = np.array([]), np.array([]), np.array([])
        for sp in range(len(self._posnfull)):
            wavf = np.append(wavf, self._wavefit[sp])
            fluf = np.append(fluf, self._fluxfit[sp])
            errf = np.append(errf, self._fluefit[sp])
        # Load the parameter information array
        parinfo, self._levadd = load.load_parinfo(self)
        # Load parameter influence
        self._pinfl = load.load_par_influence(self, self._modpass['p0'])
        # Sub-pixellate the spectrum
        self._wavespx, self._contspx, self._zerospx, self._posnspx, self._nexbins = load.load_subpixels(self, self._modpass['p0'])
        # If there are some linked parameters, apply the links here
        npar = len(self._modpass['p0'])
        self._ptied = []
        lnkcnt=0
        for i in range(npar):
            if 'tied' in parinfo[i].keys():
                self._ptied.append(parinfo[i]['tied'].replace("numpy","np"))
                self._modpass['mlnk'].append([-2-lnkcnt,parinfo[i]['tied'].replace("numpy","np")])
                lnkcnt += 1
            else: self._ptied.append('')
        self._qanytied = 0
        for i in range(npar):
            self._ptied[i] = self._ptied[i].strip()
            if self._ptied[i] != '':
                self._qanytied = 1
        if self._qanytied: self._modpass['p0'] = load.load_tied(self._modpass['p0'], self._ptied)
        # NOW PREPARE TO FIT THE DATA!
        # Explicit, picklable fit state for the minimiser (Stage 2.4),
        # replacing the former fdict = self.__dict__ copy.
        fa = {'x':wavf, 'y':fluf, 'err':errf,
              'state':model_eval.FitState.from_orchestrator(self)}
        # Calculate the initial Chi-Squared
        msgs.info("Calculating the starting chi-squared",verbose=self._argflag['out']['verbose'])
        # Calculate the starting function
        start_func = self.myfunct(self._modpass['p0'],output=2)
        if not self._argflag['generate']['data'] and self._argflag['sim']['beginfrom'] == "":
            self._chisq_init = np.sum(((fluf-start_func)/errf)**2)
            numfreepars = len(parinfo) - [parinfo[i]['fixed'] for i in range(len(parinfo))].count(1)
            if np.isnan(self._chisq_init): msgs.error("Initial chi-squared is not a number")
            if self._chisq_init == np.inf: msgs.error("Input chi-squared is Infinite"+msgs.newline()+"Perhaps the error spectrum is zero?")
            msgs.info("Chi-squared for input parameters = " + str(self._chisq_init),verbose=self._argflag['out']['verbose'])
            msgs.info("Number of free parameters: {0:d}".format(numfreepars),verbose=self._argflag['out']['verbose'])
        if self._argflag['plot']['only']:
            # Go straight to plotting
            self._fitparams = self._modpass['p0']
            plot.make_plots_all(self)
            plotCasePDF = ((self._argflag['out']['plots'].lower() == 'true') or ((self._argflag['out']['plots'].lower() != 'false') and (self._argflag['out']['plots'] != '')))
            if plotCasePDF:
                plot.plot_pdf(self)
            #fileend=input(msgs.input()+"Press enter to view the fits -")
            plot.plot_showall()
        elif self._argflag['sim']['random'] is not None and self._argflag['sim']['beginfrom'] != "":
            from alis import simulate
            # If doing systematics you can skip the initial fit
            # Get the covariance matrix from the best-fitting model
            covar = np.loadtxt(self._argflag['sim']['beginfrom']+".covar")
            # Load the best-fitting parameters
            parlines, datlines, modlines, lnklines = load.load_input(self, filename=self._argflag['sim']['beginfrom'], updateself=False)
            modpass = load.load_model(self, modlines, updateself=False)
            # Calculate the best-fitting model
            model = self.myfunct(modpass['p0'], output=1)
            msgs.info("Starting simulations",verbose=self._argflag['out']['verbose'])
            simulate.sim_random(self, covar, modpass['p0'], parinfo)
        elif self._argflag['sim']['perturb'] is not None and self._argflag['sim']['beginfrom'] != "":
            from alis import simulate
            # If doing systematics you can skip the initial fit
            # Get the covariance matrix from the best-fitting model
            covar = np.loadtxt(self._argflag['sim']['beginfrom']+".covar")
            # Load the best-fitting parameters
            parlines, datlines, modlines, lnklines = load.load_input(self, filename=self._argflag['sim']['beginfrom'], updateself=False)
            modpass = load.load_model(self, modlines, updateself=False)
            # Calculate the best-fitting model
            model = self.myfunct(modpass['p0'], output=1)
            msgs.info("Starting simulations",verbose=self._argflag['out']['verbose'])
            simulate.perturb(self, covar, modpass['p0'], parinfo)
        elif self._argflag['iterate']['model'] is not None:
            # The user wants to iterate over the model
            # Get the identifier text
            if len(self._argflag['iterate']['model'])==2:
                filename, idtxt = self._argflag['iterate']['model']
            elif len(self._argflag['iterate']['model'])==1:
                filename, idtxt = self._argflag['iterate']['model'][0], 'itermodule'
            else:
                msgs.error("You can only pass two arguments (separated by a comma) to iterate+model"+msgs.newline()+"The first argument is a python module, the second is a text string")
            path, file = os.path.split(filename)
            name, ext = os.path.splitext(file)
            # Set the import loader
            try:
                from ihooks import BasicModuleLoader as srcloader
            except ImportError:
                msgs.error("Cannot iterate model without 'ihooks' module installed." + msgs.newline() +
                           "Install ihooks to continue (note: ihooks is currently only supported in python 2.*)")
            impload = srcloader()
            modu = impload.find_module_in_dir(name, path)
            if not modu: msgs.error("Could not import {0:s}".format(name))
            itermod = impload.load_module(name, modu)
            # Now iterate
            complete = False
            iternum = 1
            while not complete:
                msgs.info("Iterating the model, Iteration {0:d}".format(iternum),verbose=self._argflag['out']['verbose'])
                # Fit this iteration
                m = alfit(model_eval._minimiser_eval, self._modpass['p0'], parinfo=parinfo, functkw=fa, funcarray=self._funcarray,
                        verbose=self._argflag['out']['verbose'], modpass=self._modpass, miniter=self._argflag['chisq']['miniter'], maxiter=self._argflag['chisq']['maxiter'],
                        atol=self._argflag['chisq']['atol'], ftol=self._argflag['chisq']['ftol'], gtol=self._argflag['chisq']['gtol'], xtol=self._argflag['chisq']['xtol'],
                        ncpus=self._argflag['run']['ncpus'], fstep=self._argflag['chisq']['fstep'],limpar=self._argflag['run']['limpar'])
                model = self.myfunct(m.params, output=2)
                # Pass the fitted information to the user module and obtain and updated model and completion status
                newmodln = save.modlines(self, m.params, self._modpass, verbose=self._argflag['out']['verbose'])
                newmerln = save.modlines(self, m.perror, self._modpass, verbose=self._argflag['out']['verbose'])
                modlines, complete = itermod.loader(self, idtxt, newmodln, newmerln, m, model=model)
                if not complete: # then update the appropriate variables
                    self._modlines = modlines
                    # Reload the new model
                    self._modpass = load.load_model(self, self._modlines)
                    # Reload the parameter information array
                    parinfo, self._levadd = load.load_parinfo(self)
                    # Reload parameter influence
                    self._pinfl = load.load_par_influence(self, self._modpass['p0'])
                    # Re-sub-pixellate the spectrum
                    self._wavespx, self._contspx, self._zerospx, self._posnspx, self._nexbins = load.load_subpixels(self, self._modpass['p0'])
                    # Update the parameter dictionary
                    fa['state'] = model_eval.FitState.from_orchestrator(self)
                    iternum += 1
            self._fitresults = m
            self._fitparams = m.params
            self._tend=time.time()
        elif self._argflag['generate']['data']:
            # Save the generated data
            #if self._argflag['out']['fits'] or self._argflag['out']['onefits']:
            # Go to modelfits to generate the fake data. It won't be written out unless self._argflag['out']['fits'] is True
            self, fnames = save.save_modelfits(self)
            self._fitparams = self._modpass['p0']
            # Plot the results
            plotCasePDF = ((self._argflag['out']['plots'].lower() == 'true') or ((self._argflag['out']['plots'].lower() != 'false') and (self._argflag['out']['plots'] != '')))
            if self._argflag['plot']['fits'] or self._argflag['plot']['residuals'] or (plotCasePDF):
                plot.make_plots_all(self)
                if plotCasePDF:
                    plot.plot_pdf(self)
                if self._argflag['plot']['fits'] or self._argflag['plot']['residuals']:
                    #null=input(msgs.input()+"Press enter to view the fits -")
                    plot.plot_showall()
        else:
            msgs.info("Commencing chi-squared minimisation",verbose=self._argflag['out']['verbose'])
            m = alfit(model_eval._minimiser_eval, self._modpass['p0'], parinfo=parinfo, functkw=fa, funcarray=self._funcarray,
                        verbose=self._argflag['out']['verbose'], modpass=self._modpass, miniter=self._argflag['chisq']['miniter'], maxiter=self._argflag['chisq']['maxiter'],
                        atol=self._argflag['chisq']['atol'], ftol=self._argflag['chisq']['ftol'], gtol=self._argflag['chisq']['gtol'], xtol=self._argflag['chisq']['xtol'],
                        ncpus=self._argflag['run']['ncpus'], fstep=self._argflag['chisq']['fstep'],limpar=self._argflag['run']['limpar'])
            self._tend=time.time()
            niter=m.niter
            if (m.status <= 0):
                if m.status == -20: # Interrupted fit
                    msgs.info("Fitting routine was interrupted",verbose=self._argflag['out']['verbose'])
                    msgs.warn("Setting ERRORS = PARAMETERS",verbose=self._argflag['out']['verbose'])
                    m.perror = m.params
                elif m.status == -21: # Parameters are not within the specified limits
                    if type(self._modpass['line'][m.errmsg[0][0]]) is int: msgs.error("A parameter that = {0:s} is not within the specified limits on line -".format(m.errmsg[1])+msgs.newline()+self._modlines[self._modpass['line'][m.errmsg[0][0]]])
                    else: msgs.error("A parameter that = {0:s} is not within specified limits on line -".format(m.errmsg[1])+msgs.newline()+self._modpass['line'][m.errmsg[0][0]])

                elif m.status == -16:
                    msgs.error("There was an error in the chi-squared minimization - "+msgs.newline()+"A parameter or function value has become infinite or an undefined"+msgs.newline()+"number. This is usually a consequence of numerical overflow in the"+msgs.newline()+"user's model function, which must be avoided.")
                else:
                    if m.errmsg == "": msgs.error("There was an error in the chi-squared minimization - "+msgs.newline()+"please contact the author")
                    msgs.error(m.errmsg)
            else:
                msgs.info("Reason for convergence:"+msgs.newline()+utils.getreason(m.status,verbose=self._argflag['out']['verbose']),verbose=self._argflag['out']['verbose'])
            # Create the best-fitting model, this generates some arrays that are now required
            msgs.info("Best-fitting model parameters found",verbose=self._argflag['out']['verbose'])
            # If the user just wants to fit the data and return, do so.
            if self._fitonly:
                self._fitresults = m
                self._fitparams = m.params
                model = self.myfunct(m.params, output=1)
                return self
            # Otherwise, do everything else
            if self._argflag['run']['convergence']:
                if m.status == -20:
                    msgs.warn("Cannot check convergence for an interrupted fit",verbose=self._argflag['out']['verbose'])
                else:
                    msgs.info("Beginning test for convergence",verbose=self._argflag['out']['verbose'])
                    mpars = copy.deepcopy(m)
                    lowby = 0
                    mt = copy.deepcopy(m) # The testing set of parameters
                    while True:
                        if mpars.status != 5: # If the maximum number of iterations was reached, don't lower the tolerance
                            self._argflag['chisq']['atol'] /= 10.0
                            self._argflag['chisq']['ftol'] /= 10.0
                            self._argflag['chisq']['gtol'] /= 10.0
                            self._argflag['chisq']['xtol'] /= 10.0
                            lowby -= 1
                        mc = alfit(model_eval._minimiser_eval, mpars.params, parinfo=parinfo, functkw=fa, funcarray=self._funcarray,
                                verbose=self._argflag['out']['verbose'], modpass=self._modpass, miniter=self._argflag['chisq']['miniter'], maxiter=self._argflag['chisq']['maxiter'],
                                atol=self._argflag['chisq']['atol'], ftol=self._argflag['chisq']['ftol'], gtol=self._argflag['chisq']['gtol'], xtol=self._argflag['chisq']['xtol'],
                                ncpus=self._argflag['run']['ncpus'], fstep=self._argflag['chisq']['fstep'],limpar=self._argflag['run']['limpar'], convtest=True)
                        # Update parameters
                        mpars = copy.deepcopy(mc)
                        # Keep going until this run has reached the tolerances
                        if mpars.status == 5 and self._argflag['run']['convnostop']:
                            continue
                        # Check that the chi-squared didn't fail
                        if mpars.status <= 0:
                            if mpars.status == -20:
                                msgs.info("Convergence check was interrupted",verbose=self._argflag['out']['verbose'])
                                # Force non-convergence
                                mpars.perror = 10.0*(mpars.params-mt.params)/self._argflag['run']['convcriteria']
                            else: msgs.error(mpars.errmsg)
                        # Keep going if the tolerances haven't been lowered
                        if lowby == 0: continue
                        # Check the solution
                        # Find out which parameters have converged
                        whrconv = np.where( (np.abs(mpars.params-mt.params)/mt.perror) >= self._argflag['run']['convcriteria'])[0]
                        outputconvfile = True
                        if np.size(whrconv) == 0 and mpars.niter > 1 and mpars.status != 5:
                            msgs.info("Solution has converged",verbose=self._argflag['out']['verbose'])
                            if outputconvfile:
                                fwrite = open(self._argflag['run']['modname'].rstrip("mod")+"convY", "w")
                                fwrite.close()
                            # Use the best-fit results from the convergence test
                            m = mpars
                            msgs.info("Reason for convergence:"+msgs.newline()+utils.getreason(mpars.status,verbose=self._argflag['out']['verbose']),verbose=self._argflag['out']['verbose'])
                            break
                        elif mc.niter == 1:
                            if outputconvfile:
                                fwrite = open(self._argflag['run']['modname'].rstrip("mod")+"convN", "w")
                                fwrite.close()
                            msgs.warn("Solution has probably not converged yet (after 1 iteration)",verbose=self._argflag['out']['verbose'])
                            if self._argflag['run']['convnostop']:
                                msgs.info("User has forced to continue convergence with 'noconvstop'",verbose=self._argflag['out']['verbose'])
                                continue
                            else: break
                        elif mc.status == 5:
                            if outputconvfile:
                                fwrite = open(self._argflag['run']['modname'].rstrip("mod")+"convN", "w")
                                fwrite.close()
                            msgs.warn("Solution has probably not converged yet."+msgs.newline()+"Maximum number of iterations reached",verbose=self._argflag['out']['verbose'])
                            if self._argflag['run']['convnostop']:
                                msgs.info("User has forced to continue convergence with 'noconvstop'",verbose=self._argflag['out']['verbose'])
                                continue
                            else: break
                        else:
                            if outputconvfile:
                                fwrite = open(self._argflag['run']['modname'].rstrip("mod")+"convN", "w")
                                fwrite.close()
                            msgs.warn("Solution has not converged for {0:d}/{1:d} free parameters".format(np.size(whrconv), numfreepars),verbose=self._argflag['out']['verbose'])
                            msgs.info("Maximum parameter difference was {0:f} sigma".format( np.max((np.abs(mpars.params-mt.params)/mt.perror)[whrconv]) ),verbose=self._argflag['out']['verbose'])
                            if not self._argflag['run']['convnostop']: break # Stop if convergence isn't forced
                            mt = copy.deepcopy(mpars)
                            continue
                    msgs.info("Convergence test complete",verbose=self._argflag['out']['verbose'])
            msgs.info("Generating best-fit model",verbose=self._argflag['out']['verbose'])
            model = self.myfunct(m.params, output=1)
            # Prepare some arrays for eventual plotting
#			if self._posnLya != 0:
#				elnames, elwaves, rdshft, comparr = plot.prep_arrs(self._snip_ions, self._snip_detl, self._posnfit)
            # Write out the results of the convergence test:
            if self._argflag['run']['convergence']:
                if m.status != -20 and mc.status != -20 and mpars.status != -20:
                    if self._argflag['out']['convtest'] != "":
                        fit_info=[(self._tend - self._tstart)/3600.0, m.fnorm, m.dof, m.niter, m.status]
                        diff = np.abs(mpars.params-mt.params)/mt.perror
                        diff[np.where((mpars.params==mt.params) & (mt.perror==0.0))[0]] = 0.0
                        convergence.save_convtest(self, diff, self._argflag['run']['convcriteria'],fit_info)
            # Store the fitting results
            self._fitresults = m
            self._fitparams = m.params
            # Write out the data and model fits
            if self._argflag['out']['fits'] or self._argflag['out']['onefits']:
                fnames = save.save_modelfits(self)
            # Write a supermongo file for the plots.
            if self._argflag['out']['sm']:
                msgs.error("Sorry, supermongo generated files are not implemented yet")
                msgs.info("Generating Supermongo files to plot the output",verbose=self._argflag['out']['verbose'])
                #save.save_smfiles(self._modname_dla, fnames, elnames, elwaves, comparr, rdshft)
            # Write an output of the parameters for the best-fitting model
            if self._argflag['run']['blind'] and m.status != -20:
                if self._argflag['run']['convergence']:
                    if mc.status != -20 and mpars.status != -20:
                        msgs.info("Printing out the parameter errors:",verbose=self._argflag['out']['verbose'])
                        print(save.print_model(m.perror, self._modpass, blind=True, verbose=self._argflag['out']['verbose'],funcarray=self._funcarray))
                else:
                    msgs.info("Printing out the parameter errors:",verbose=self._argflag['out']['verbose'])
                    print(save.print_model(m.perror, self._modpass, blind=True, verbose=self._argflag['out']['verbose'],funcarray=self._funcarray))
            if self._argflag['out']['model']:
                fit_info=[(self._tend - self._tstart)/3600.0, m.fnorm, m.dof, m.niter, m.status]
                save.save_model(self, m.params, m.perror, fit_info)
            if self._argflag['out']['covar'] != "":
                save.save_covar(self, m.covar)
            # Plot the results
            plotCasePDF = ((self._argflag['out']['plots'].lower() == 'true') or ((self._argflag['out']['plots'].lower() != 'false') and (self._argflag['out']['plots'] != '')))
            if self._argflag['plot']['fits'] or self._argflag['plot']['residuals'] or plotCasePDF:
                plot.make_plots_all(self)
                if plotCasePDF:
                    plot.plot_pdf(self)
                if self._argflag['plot']['fits'] or self._argflag['plot']['residuals']:
                    #null=input(msgs.input()+"Press enter to view the fits -")
                    plot.plot_showall()
#			if self._argflag['plot']['fits']:
#				plot.make_plots_all(self)
#				fileend=input(msgs.input()+"Press enter to view the fits -")
#				plot.plot_showall()
            msgs.info("Total fitting time in hours: %s" % ((self._tend - self._tstart)/3600.0),verbose=self._argflag['out']['verbose'])
            # If simulations were requested, do them now
            if self._argflag['sim']['random'] != None:
                from alis import simulate
                if m.perror is None or m.perror is m.params: msgs.warn("Fitting routine interrupted. Cannot perform simulations",verbose=self._argflag['out']['verbose'])
                else:
                    msgs.info("Starting simulations",verbose=self._argflag['out']['verbose'])
                    simulate.sim_random(self, m.covar, m.params, parinfo)
            elif self._argflag['sim']['perturb'] != None:
                from alis import simulate
                if m.perror is None or m.perror is m.params: msgs.warn("Fitting routine interrupted. Cannot perform simulations",verbose=self._argflag['out']['verbose'])
                else:
                    msgs.info("Starting simulations",verbose=self._argflag['out']['verbose'])
                    simulate.perturb(self, m.covar, m.params, parinfo)
        if self._retself == True:
            return self

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def alis(modelfile=None, parlines=[], datlines=[], modlines=[], lnklines=[], data=None, fitonly=False, verbose=-1):
    """
    modelfile : This is the name of a model file
    lines : This is a three element list of the form [parlines, datlines, modlines]

    lines is ignored if modelfile is given
    """
    msgs.info("calling ALIS...", verbose=verbose)
    debug = False  # There are two instances of this (one is in main just below)
    if debug:
        argflag = load.optarg(os.path.realpath(__file__), verbose=verbose)
        return ClassMain(argflag, parlines=parlines, datlines=datlines, modlines=modlines, lnklines=lnklines, modelfile=modelfile, data=data, fitonly=fitonly, verbose=verbose)
    else:
        try:
            argflag = load.optarg(os.path.realpath(__file__), verbose=verbose)
            return ClassMain(argflag, parlines=parlines, datlines=datlines, modlines=modlines, lnklines=lnklines, modelfile=modelfile, data=data, fitonly=fitonly, verbose=verbose)
        except Exception:
            # There is a bug in the code, print the file and line number of the error.
            et, ev, tb = sys.exc_info()
            while tb:
                co = tb.tb_frame.f_code
                filename = str(co.co_filename)
                line_no =  str(traceback.tb_lineno(tb))
                tb = tb.tb_next
            filename=filename.split('/')[-1]
            msgs.bug("There appears to be a bug on Line "+line_no+" of "+filename+" with error:"+msgs.newline()+str(ev)+msgs.newline()+"---> please contact the author")

def initialise(alispath, verbose=-1):
    argflag = load.optarg(alispath, verbose=verbose)
    slf = ClassMain(argflag,getinst=True)
    slf._argflag = argflag
    slf._argflag['out']['verbose'] = verbose
    slf._atomic = load.load_atomic(slf)
    slf._isonefits = False
    slf._funcarray = build_funcarray(slf._argflag, slf._atomic)
    return slf

