"""Post-fit fit-quality / residual report (Stage 3.2).

Builds a diagnostic report of the best-fit model. For each fitted region (a
snip -- a contiguous fitted wavelength interval of one specid) it reports the
number of fitted pixels, chi-squared and reduced chi-squared, the residual
mean and scatter, the worst outlier, the number of >Nsigma outliers, and a
Wald-Wolfowitz runs-test z (correlated-residual detector), and flags regions
that are poorly fit. The report is printed to the console and written to
``<modelname>.report`` (both controlled by the ``out report`` setting; the
flag threshold is ``out reportsig``, in sigma).

A region is flagged poorly-fit if either:
- its reduced chi-squared deviates from 1 by more than ``reportsig`` sigma,
  where the expected spread is sqrt(2/Npix) (so the test self-scales with the
  region size); or
- the runs-test z exceeds ``reportsig`` in magnitude (residuals are
  significantly correlated -- structure the model missed).

Generated by RJC and Claude.
"""

import numpy as np

from alis import logger

msgs = logger.msgs()


def _runs_z(resid):
    """Wald-Wolfowitz runs-test z-score on the signs of the residuals.

    Large |z| means the residuals switch sign far more or less often than
    random -- a sign of correlated (structured) residuals.

    Generated by RJC and Claude.
    """
    signs = np.sign(resid)
    signs = signs[signs != 0]
    n = signs.size
    if n < 2:
        return 0.0
    n_pos = int(np.count_nonzero(signs > 0))
    n_neg = n - n_pos
    if n_pos == 0 or n_neg == 0:
        return 0.0
    runs = 1 + int(np.count_nonzero(signs[1:] != signs[:-1]))
    mu = 1.0 + 2.0 * n_pos * n_neg / n
    var = (2.0 * n_pos * n_neg * (2.0 * n_pos * n_neg - n)) / (n ** 2 * (n - 1))
    if var <= 0.0:
        return 0.0
    return (runs - mu) / np.sqrt(var)


def _regions(slf):
    """Per-region residual diagnostics over the fitted pixels of each snip.

    Generated by RJC and Claude.
    """
    out = []
    for sp in range(len(slf._posnfull)):
        for sn in range(len(slf._posnfull[sp]) - 1):
            ll = slf._posnfull[sp][sn]
            lu = slf._posnfull[sp][sn + 1]
            wave = slf._wavefull[sp][ll:lu]
            w = np.where((wave >= slf._posnfit[sp][2 * sn + 0])
                         & (wave <= slf._posnfit[sp][2 * sn + 1]))
            # Restrict to the pixels ALIS actually fitted (as model_func /
            # save_modelfits do), so the per-region chi-squared matches the
            # fit's total; some snips have in-range pixels that were not fitted.
            wB = np.where(np.isin(wave[w], slf._wavefit[sp]))
            wv = wave[w][wB]
            flux = slf._fluxfull[sp][ll:lu][w][wB]
            flue = slf._fluefull[sp][ll:lu][w][wB]
            model = slf._modfinal[sp][ll:lu][w][wB]
            good = flue > 0.0
            resid = (flux[good] - model[good]) / flue[good]
            out.append({
                "specid": str(slf._specid[sp]),
                "name": str(slf._snipnames[sp][sn]),
                "wmin": float(wv.min()) if wv.size else float("nan"),
                "wmax": float(wv.max()) if wv.size else float("nan"),
                "resid": resid,
            })
    return out


def build_report(slf):
    """Return the fit-quality report as a string.

    Generated by RJC and Claude.
    """
    nsig = float(slf._argflag['out']['reportsig'])
    modname = slf._argflag['run']['modname']
    lines = []
    lines.append("# ALIS fit-quality report")
    lines.append("# Model: {0:s}".format(modname))
    fr = getattr(slf, "_fitresults", None)
    if fr is not None and getattr(fr, "dof", 0):
        red = fr.fnorm / fr.dof if fr.dof else float("nan")
        lines.append("# Bestfit chi-squared = {0:.6f}   DOF = {1:d}   "
                     "reduced = {2:.6f}   status = {3}".format(
                         fr.fnorm, int(fr.dof), red, fr.status))
    lines.append("# Poorly-fit flag: reduced chi-squared > {0:.1f} sigma from "
                 "1, or |runs z| > {0:.1f}".format(nsig))
    lines.append("#")
    hdr = ("# {0:<6s} {1:<34s} {2:>10s} {3:>10s} {4:>6s} {5:>10s} {6:>8s} "
           "{7:>8s} {8:>8s} {9:>8s} {10:>5s} {11:>7s}  {12}")
    lines.append(hdr.format("specid", "region", "wave_min", "wave_max", "Npix",
                            "chi2", "redchi2", "mean", "scatter", "max|r|",
                            "nout", "runs_z", "flag"))
    row = ("  {0:<6s} {1:<34s} {2:>10.3f} {3:>10.3f} {4:>6d} {5:>10.3f} "
           "{6:>8.3f} {7:>8.3f} {8:>8.3f} {9:>8.3f} {10:>5d} {11:>7.2f}  {12}")
    flagged = []
    for r in _regions(slf):
        resid = r["resid"]
        npix = resid.size
        if npix == 0:
            continue
        chi2 = float(np.sum(resid ** 2))
        redchi2 = chi2 / npix
        mean = float(np.mean(resid))
        scatter = float(np.std(resid))
        maxr = float(np.max(np.abs(resid)))
        nout = int(np.count_nonzero(np.abs(resid) > nsig))
        rz = _runs_z(resid)
        # Reduced chi-squared deviation in units of its expected spread.
        dev = (redchi2 - 1.0) / np.sqrt(2.0 / npix)
        is_flag = (dev > nsig) or (abs(rz) > nsig)
        tag = ""
        if is_flag:
            reasons = []
            if dev > nsig:
                reasons.append("redchi2 {0:+.1f}sigma".format(dev))
            if abs(rz) > nsig:
                reasons.append("runs {0:+.1f}".format(rz))
            tag = "<== " + ", ".join(reasons)
            flagged.append((r["specid"], r["name"], tag))
        lines.append(row.format(r["specid"], r["name"][:34], r["wmin"],
                                r["wmax"], npix, chi2, redchi2, mean, scatter,
                                maxr, nout, rz, tag))
    lines.append("#")
    if flagged:
        lines.append("# Flagged regions ({0:d}):".format(len(flagged)))
        for specid, name, tag in flagged:
            lines.append("#   {0:<6s} {1:<34s} {2}".format(specid, name, tag))
    else:
        lines.append("# No regions flagged (all within {0:.1f} sigma).".format(
            nsig))
    return "\n".join(lines)


def write_report(slf):
    """Build the report, print it to the console, and write ``<model>.report``.

    Defensive: never raises -- a report failure must not abort a fit.

    Generated by RJC and Claude.
    """
    try:
        text = build_report(slf)
    except Exception as err:
        msgs.warn("Could not build the fit-quality report: {0}".format(err),
                  verbose=slf._argflag['out']['verbose'])
        return
    msgs.info("Fit-quality report:", verbose=slf._argflag['out']['verbose'])
    print(text)
    outname = slf._argflag['out']['modelname']
    if not outname:
        outname = slf._argflag['run']['modname'] + '.out'
    # Replace a trailing .out with .report, else append .report.
    if outname.endswith('.out'):
        fname = outname[:-4] + '.report'
    else:
        fname = outname + '.report'
    try:
        with open(fname, 'w') as fh:
            fh.write(text + "\n")
        msgs.info("Saved fit-quality report: {0:s}".format(fname),
                  verbose=slf._argflag['out']['verbose'])
    except OSError as err:
        msgs.warn("Could not write the fit-quality report {0:s}: {1}".format(
            fname, err), verbose=slf._argflag['out']['verbose'])
