"""Zero-copy transport of the Jacobian's read-only arrays (Stage 4.5).

Every derivative chunk used to be handed its read-only inputs through
``pool.map``, i.e. through a pickle: the constant fit state and a slice of the
per-iteration profile cache. On DH_orders that is 259 MB per chunk and 6.4 GB
per Jacobian, and each of the ``ncpus`` workers keeps its own copy resident
while it works. None of it is ever written on the derivative path -- it is the
same data, re-materialised ``ncpus`` times.

This module puts those arrays in one ``multiprocessing.shared_memory`` segment
instead and ships a :class:`Handle` (a few dozen bytes) in their place. A worker
attaches the segment once and rebuilds each array as a **view** into it, so the
arrays exist once in RAM however many workers there are, and the pickle
disappears. Views are made read-only, which is not a nicety: writing to one
would corrupt a buffer every other worker is reading at the same time, so the
flag turns a silent data race into an immediate ``ValueError``.

The layout is one segment per publisher rather than one per array (DH_orders
would otherwise need ~4000 segments): a fixed header, a pickled *skeleton* --
the original structure with each large array replaced by a :class:`_Ref` -- and
then the array bytes, each 64-byte aligned.

Shared memory is best-effort. If a segment cannot be created (a container's
64 MB ``/dev/shm`` is the usual reason) :meth:`Publisher.publish` returns
``None``, the caller pickles as before, and the fit continues; ``run shmem
False`` forces that path.

Generated by RJC and Claude.
"""

import atexit
import copy
import pickle
import struct
import weakref
from dataclasses import fields, is_dataclass
from multiprocessing import shared_memory
from typing import Any, NamedTuple

import numpy as np

from alis import logger

msgs = logger.msgs()

#: Arrays below this stay in the pickle: a reference plus a rebuilt view costs
#: more than copying a few hundred bytes.
MIN_BYTES = 4096

#: Each array starts on a 64-byte boundary, so a view is as aligned as the
#: array numpy would have allocated for itself.
_ALIGN = 64

#: (length of the pickled skeleton, offset of the first array, generation).
#: The generation is stored as well as carried in the handle so that reading
#: through a stale handle raises instead of quietly returning whatever the
#: segment holds now.
_HEADER = struct.Struct("<QQQ")

#: Grow the segment by this factor when it has to be replaced, so a slowly
#: growing payload does not create a new segment every iteration.
_GROWTH = 1.25


class _Ref(NamedTuple):
    """Where one array lives inside the segment, and how to rebuild it."""

    offset: int
    shape: tuple
    dtype: str


class Handle(NamedTuple):
    """What travels in the pickle in place of the arrays.

    ``keys`` selects a subset of a published *dict* (the per-iteration profile
    cache, where each chunk is given only the entries its parameters
    influence); ``None`` means the whole published object.
    """

    tag: str
    name: str
    generation: int
    keys: Any = None


def _aligned(offset):
    return (offset + _ALIGN - 1) & ~(_ALIGN - 1)


def _shareable(obj):
    """Is ``obj`` an array worth putting in the segment?

    Object dtypes cannot live in a raw buffer, and a non-contiguous or
    structured array would have to be repacked -- for which pickle is already
    the right tool. 1D float arrays, which is what ALIS ships, all qualify.
    """
    return (
        isinstance(obj, np.ndarray)
        and obj.nbytes >= MIN_BYTES
        and obj.flags.c_contiguous
        and not obj.dtype.hasobject
        and np.dtype(obj.dtype.str) == obj.dtype
    )


def _mutable_dataclass(obj):
    """A dataclass instance whose fields can be replaced one at a time."""
    return (
        is_dataclass(obj)
        and not isinstance(obj, type)
        and not obj.__dataclass_params__.frozen
    )


def _walk(obj, hit, fn):
    """Rebuild ``obj``, replacing everything ``hit`` matches with ``fn(it)``.

    Containers are matched by exact type, not ``isinstance``: a ``list``
    subclass rebuilt as a plain list would quietly lose its behaviour, and
    leaving it to pickle costs nothing. Dataclasses are shallow-copied and
    written field by field rather than rebuilt through
    ``dataclasses.replace``, which would re-run ``__init__`` and drop any
    field the constructor does not take.
    """
    if hit(obj):
        return fn(obj)
    kind = type(obj)
    if kind is list:
        return [_walk(v, hit, fn) for v in obj]
    if kind is tuple:
        return tuple(_walk(v, hit, fn) for v in obj)
    if kind is dict:
        return {k: _walk(v, hit, fn) for k, v in obj.items()}
    if _mutable_dataclass(obj):
        out = copy.copy(obj)
        for field in fields(obj):
            setattr(out, field.name, _walk(getattr(obj, field.name), hit, fn))
        return out
    return obj


class _Layout:
    """Assigns each array an offset as the skeleton is built."""

    def __init__(self):
        self.arrays = []
        self.size = 0

    def add(self, arr):
        offset = _aligned(self.size)
        self.arrays.append((offset, arr))
        self.size = offset + arr.nbytes
        return _Ref(offset, arr.shape, arr.dtype.str)


#: Every live publisher, so an abnormal exit does not leave a segment behind
#: for the resource tracker to complain about. Weak, so a finished fit's
#: publisher is collected (and closed) without having to be deregistered.
_LIVE = weakref.WeakSet()


@atexit.register
def _release_all():
    for pub in list(_LIVE):
        pub.close()
    _LIVE.clear()


class Publisher:
    """Owns one shared segment for the life of a fit (parent side).

    The segment is reused across Jacobians and only replaced when the payload
    outgrows it, so its name is stable and a worker re-attaches rarely. The
    generation counter is what tells a worker its cached views are stale.
    """

    def __init__(self, tag):
        self.tag = tag
        self._shm = None
        self._generation = 0
        self._warned = False
        _LIVE.add(self)

    def publish(self, obj):
        """Copy ``obj``'s large arrays into the segment; return a Handle.

        Returns ``None`` if shared memory is unavailable, in which case the
        caller must ship ``obj`` itself.
        """
        layout = _Layout()
        skeleton = pickle.dumps(
            _walk(obj, _shareable, layout.add), protocol=pickle.HIGHEST_PROTOCOL
        )
        if not layout.arrays:
            return None  # nothing large enough to be worth a segment
        start = _aligned(_HEADER.size + len(skeleton))
        try:
            shm = self._segment(start + layout.size)
        except OSError as err:
            if not self._warned:
                msgs.warn(
                    "Could not use shared memory for the derivative payload "
                    "({0:s});".format(str(err))
                    + msgs.newline()
                    + "falling back to sending it with each chunk. Set "
                    "'run shmem False' to silence this."
                )
                self._warned = True
            return None
        self._generation += 1
        _HEADER.pack_into(shm.buf, 0, len(skeleton), start, self._generation)
        shm.buf[_HEADER.size : _HEADER.size + len(skeleton)] = skeleton
        for offset, arr in layout.arrays:
            dest = np.ndarray(
                arr.shape, dtype=arr.dtype, buffer=shm.buf, offset=start + offset
            )
            dest[...] = arr
        # A live view exports the segment's buffer, and a segment with exported
        # buffers cannot be closed -- so the last one must not outlive the copy.
        del dest
        return Handle(self.tag, shm.name, self._generation)

    def _segment(self, size):
        """The segment to publish into, grown if this payload does not fit."""
        if self._shm is not None and self._shm.size >= size:
            return self._shm
        self.close()
        self._shm = shared_memory.SharedMemory(create=True, size=int(size * _GROWTH))
        return self._shm

    def close(self):
        """Release the segment. Idempotent, and never raises."""
        shm, self._shm = self._shm, None
        if shm is None:
            return
        try:
            shm.close()
            shm.unlink()
        except Exception:
            pass

    def __del__(self):
        self.close()


# -- worker side -------------------------------------------------------------

#: tag -> (segment name, SharedMemory). One mapping per tag, so replacing a
#: segment does not leave the old one mapped in every worker.
_ATTACHED = {}

#: tag -> (name, generation, unpickled skeleton, first-array offset), and
#: tag -> (name, generation, hydrated object) for whole-object handles.
#: Rebuilding thousands of views per task would be wasted work, and a stable
#: object also keeps the GPU dispatcher's wave cache -- which is keyed on the
#: sub-pixel grid's identity -- valid across tasks. Only the current generation
#: is ever wanted, so each tag holds exactly one entry.
_SKELETONS = {}
_HYDRATED = {}


def _current(cache, handle):
    """The cached entry for ``handle``, or None if it is for another payload."""
    entry = cache.get(handle.tag)
    if entry is None or entry[:2] != (handle.name, handle.generation):
        return None
    return entry[2:]


def _forget(tag):
    _SKELETONS.pop(tag, None)
    _HYDRATED.pop(tag, None)


def _attach(handle):
    """Map ``handle``'s segment into this process, once.

    Only one segment per tag is ever mapped: when the parent has had to grow
    one, the old mapping is dropped rather than left to sit in every worker
    for the rest of the fit. The caches go first -- they hold views, and a
    mapping with live views cannot be closed.
    """
    current = _ATTACHED.get(handle.tag)
    if current is not None and current[0] == handle.name:
        return current[1]
    if current is not None:
        _forget(handle.tag)
        try:
            current[1].close()
        except Exception:
            pass
    # track=False: the parent owns the segment's lifetime. A worker that
    # registered it with its own resource tracker would unlink it on exit and
    # report it as leaked.
    shm = shared_memory.SharedMemory(name=handle.name, track=False)
    _ATTACHED[handle.tag] = (handle.name, shm)
    return shm


def _skeleton(handle, shm):
    cached = _current(_SKELETONS, handle)
    if cached is None:
        length, start, generation = _HEADER.unpack_from(shm.buf, 0)
        if generation != handle.generation:
            raise RuntimeError(
                "shared segment '{0:s}' holds generation {1:d}, not the {2:d} "
                "this handle names -- it has been republished since".format(
                    handle.name, generation, handle.generation
                )
            )
        cached = (
            pickle.loads(bytes(shm.buf[_HEADER.size : _HEADER.size + length])),
            start,
        )
        _SKELETONS[handle.tag] = (handle.name, handle.generation) + cached
    return cached


def hydrate(obj):
    """Rebuild what :meth:`Publisher.publish` replaced. A no-op otherwise.

    Arrays come back as read-only views into the shared segment, so they are
    never copied and never written.
    """
    if not isinstance(obj, Handle):
        return obj
    shm = _attach(obj)
    if obj.keys is None:
        cached = _current(_HYDRATED, obj)
        if cached is not None:
            return cached[0]
    skeleton, start = _skeleton(obj, shm)
    buf = shm.buf

    def view(ref):
        arr = np.ndarray(
            ref.shape, dtype=np.dtype(ref.dtype), buffer=buf, offset=start + ref.offset
        )
        arr.flags.writeable = False
        return arr

    is_ref = lambda item: isinstance(item, _Ref)  # noqa: E731
    if obj.keys is not None:
        # Strict: the keys are drawn from the dict that was published, so a
        # missing one is a bug. Dropping it silently would only lose a cache
        # hit -- the derivative would recompute that component to the same
        # value -- which is exactly why the mistake would never be noticed.
        return {k: _walk(skeleton[k], is_ref, view) for k in obj.keys}
    built = _walk(skeleton, is_ref, view)
    _HYDRATED[obj.tag] = (obj.name, obj.generation, built)
    return built


def select(handle, keys):
    """A handle onto just ``keys`` of a published dict.

    Every key must be one the dict was published with; ``hydrate`` raises
    rather than skip an unknown one. ``keys=None`` selects everything, which
    is what the caller means when it has no influence table to narrow the
    selection with.
    """
    if handle is None or keys is None:
        return handle
    return handle._replace(keys=tuple(keys))


def _reset_for_tests():
    """Drop every attachment and cache (used by the unit tests)."""
    _SKELETONS.clear()
    _HYDRATED.clear()
    for _, shm in _ATTACHED.values():
        try:
            shm.close()
        except Exception:
            pass
    _ATTACHED.clear()
