"""CUDA implementation of the Voigt profile (Stage 4.2).

This module is the GPU counterpart of ``Voigt.call_CPU`` in
:mod:`alis.functions.voigt`, and reproduces it to well inside the 1e-12
absolute tolerance required of a ``call_GPU`` (stage doc Q4.3), in float64
throughout (Q4.6).

**Import this module lazily.** The ``@cuda.jit`` decorators below run at import
time, so importing numba at ALIS start-up is exactly what Task 4.1 forbids: a
CPU-only install must never touch numba. The module therefore lives beside
``voigt.py`` rather than inside it, and is imported from within
``Voigt.call_GPU()`` -- the kernel still belongs to the function it implements,
but the lazy boundary set up in :mod:`alis.gpu` is preserved. Nothing in ALIS
imports this module at start-up.

The Faddeeva function
---------------------
``call_CPU`` computes the Voigt profile as ``Re w(v + i a)`` via
``scipy.special.wofz``, which *is* Steven G. Johnson's Faddeeva package. The
device functions below are a float64 port of that same algorithm, taken from
the worked example in ``context/voigt_gpu/`` (whose C++ original is kept
alongside it). Reproducing the algorithm operation-for-operation, rather than
substituting a cheaper approximation, is what lets the GPU agree with the CPU
to ~1e-15 instead of the ~1e-6 a Voigt lookup table would give -- and the
finite-difference Jacobian, hence the covariance matrix, needs that.

The two read-only coefficient tables are held in **constant memory**
(``cuda.const.array_like``, plan Q4.11). That is the right choice here rather
than merely an adequate one: constant memory broadcasts at full speed when a
warp reads a single address, and both lookups are warp-uniform in this kernel
-- ``erfcx`` is indexed by the damping parameter ``a``, which is a property of
the transition and so is identical across all threads, and ``expa2n2`` is
indexed by a series counter that starts at 1 for every thread.

Generated by RJC and Claude.
"""

import math
from pathlib import Path

import numpy as np
from numba import cuda

# Chebyshev coefficients for erfcx(x) on 0 <= x <= 50, as 100 intervals of
# seven coefficients each (5600 bytes -- comfortably inside the 64 KB constant
# memory limit). Shipped as package data; see context/voigt_gpu/ for the
# generating C++ original.
_COEFF_FILE = Path(__file__).resolve().parent.parent / "data" / "erfcx_coeffs.dat"
_ERFCX_COEFFS = np.loadtxt(_COEFF_FILE, delimiter=",").astype(np.float64)

# exp(-a^2 n^2) for n = 1..52, a = pi / sqrt(-log(eps/2)); the last entry
# underflows to zero, which is what terminates the series in _faddeeva_real.
# fmt: off
_EXPA2N2 = np.array(
    [
        7.64405281671221563e-01, 3.41424527166548425e-01, 8.91072646929412548e-02,
        1.35887299055460086e-02, 1.21085455253437481e-03, 6.30452613933449404e-05,
        1.91805156577114683e-06, 3.40969447714832381e-08, 3.54175089099469393e-10,
        2.14965079583260682e-12, 7.62368911833724354e-15, 1.57982797110681093e-17,
        1.91294189103582677e-20, 1.35344656764205340e-23, 5.59535712428588720e-27,
        1.35164257972401769e-30, 1.90784582843501167e-34, 1.57351920291442930e-38,
        7.58312432328032845e-43, 2.13536275438697082e-47, 3.51352063787195769e-52,
        3.37800830266396920e-57, 1.89769439468301000e-62, 6.22929926072668851e-68,
        1.19481172006938722e-73, 1.33908181133005953e-79, 8.76924303483223939e-86,
        3.35555576166254986e-92, 7.50264110688173024e-99, 9.80192200745410268e-106,
        7.48265412822268959e-113, 3.33770122566809425e-120, 8.69934598159861140e-128,
        1.32486951484088852e-135, 1.17898144201315253e-143, 6.13039120236180012e-152,
        1.86258785950822098e-160, 3.30668408201432783e-169, 3.43017280887946235e-178,
        2.07915397775808219e-187, 7.36384545323984966e-197, 1.52394760394085741e-206,
        1.84281935046532100e-216, 1.30209553802992923e-226, 5.37588903521080531e-237,
        1.29689584599763145e-247, 1.82813078022866562e-258, 1.50576355348684241e-269,
        7.24692320799294194e-281, 2.03797051314726829e-292, 3.34880215927873807e-304,
        0.0,
    ],
    dtype=np.float64,
)
# fmt: on

# Threads per block. 128 keeps register pressure low enough for good occupancy
# with a kernel this branchy, and matches the worked example.
_THREADS_PER_BLOCK = 128

# Frozen as module globals so numba can treat them as compile-time constants.
_INF = np.inf
_NAN = np.nan

# 1 / sqrt(pi)
_ISPI = 0.56418958354775628694807945156


# -- Faddeeva device functions -----------------------------------------------
# Ported from context/voigt_gpu/simple_test.py (and its C++ original,
# context/voigt_gpu/numba_test.py). Two deliberate departures from the numba
# example are marked inline; both are required by the float64 contract or by
# CPU agreement.


@cuda.jit(device=True, inline=True)
def _sqr(x):
    """Return ``x * x``. Generated by RJC and Claude."""
    return x * x


@cuda.jit(device=True, inline=True)
def _sinh_taylor(x):
    """Return ``sinh(x)`` by Taylor series, for small ``x``.

    Generated by RJC and Claude.
    """
    return x * (
        1.0 + (x * x) * (0.1666666666666666666667 + 0.00833333333333333333333 * (x * x))
    )


@cuda.jit(device=True, inline=True)
def _sinc(x, sinx):
    """Return ``sin(x) / x``, computed stably as ``x -> 0``.

    ``sinx`` is ``sin(x)``, already available at every call site.

    Generated by RJC and Claude.
    """
    if abs(x) < 1e-4:
        return 1.0 - 0.1666666666666666666667 * x * x
    return sinx / x


@cuda.jit(device=True)
def _erfcx_y100(y100, erfcx_cc):
    """Return ``erfcx(x)`` from the Chebyshev table, given ``y100 = 400/(4+x)``.

    Generated by RJC and Claude.
    """
    iy100 = int(y100)
    if iy100 == 100:
        return 1.0
    # NB the numba example casts iy100 to float32 here; that is a float64
    # violation (Q4.6) and is deliberately not reproduced.
    t = 2.0 * y100 - (2.0 * float(iy100) + 1.0)
    return (
        erfcx_cc[iy100, 0]
        + (
            erfcx_cc[iy100, 1]
            + (
                erfcx_cc[iy100, 2]
                + (
                    erfcx_cc[iy100, 3]
                    + (
                        erfcx_cc[iy100, 4]
                        + (erfcx_cc[iy100, 5] + erfcx_cc[iy100, 6] * t) * t
                    )
                    * t
                )
                * t
            )
            * t
        )
        * t
    )


@cuda.jit(device=True)
def _erfcx(x, erfcx_cc):
    """Return ``erfcx(x) = exp(x*x) * erfc(x)`` for real ``x``.

    This is ``faddeeva_re`` in the numba example -- it is ``Re w(i x)``, which
    for a real argument is exactly the scaled complementary error function.

    Generated by RJC and Claude.
    """
    if x >= 0.0:
        if x > 50.0:  # continued-fraction expansion is faster
            if x > 5e7:  # 1-term expansion, important to avoid overflow
                return _ISPI / x
            return (
                _ISPI
                * ((x * x) * (x * x + 4.5) + 2.0)
                / (x * ((x * x) * (x * x + 5.0) + 3.75))
            )
        return _erfcx_y100(400.0 / (4.0 + x), erfcx_cc)
    if x < -26.7:
        return _INF
    if x < -6.1:
        return 2.0 * math.exp(x * x)
    return 2.0 * math.exp(x * x) - _erfcx_y100(400.0 / (4.0 - x), erfcx_cc)


@cuda.jit(device=True)
def _faddeeva_real(zr, zi, erfcx_cc, expa2n2):
    """Return the real part of the Faddeeva function ``w(zr + i*zi)``.

    Equivalent to ``scipy.special.wofz(zr + 1j*zi).real``, which is the only
    part of ``w`` the optical depth needs. Taking ``zr``/``zi`` as two floats
    rather than a complex avoids constructing a complex128 per evaluation.

    Generated by RJC and Claude.
    """
    # DBL_EPSILON, *not* the 1e-7 the numba example uses. The a/c/a2 constants
    # below and the precomputed expa2n2 table are the ones the C original uses
    # only on its `relerr <= DBL_EPSILON` path, so pairing them with a loose
    # relerr truncates the series early while claiming full-precision
    # constants -- that mismatch costs ~8 digits in the large-|x| branch, and
    # scipy (which calls Faddeeva_w with relerr=0, i.e. DBL_EPSILON) does not
    # make it. This is the second deliberate departure from the example.
    relerr = 2.220446049250313e-16
    a = 0.518321480430085929872  # pi / sqrt(-log(eps*0.5))
    c = 0.329973702884629072537  # (2/pi) * a
    a2 = 0.268657157075235951582  # a^2
    x = abs(zr)
    y = zi
    ya = abs(y)

    sum1 = 0.0
    sum2 = 0.0
    sum3 = 0.0
    sum4 = 0.0
    sum5 = 0.0

    if ya > 7.0 or (x > 6.0 and (ya > 0.1 or (x > 8.0 and ya > 1e-10) or x > 28.0)):
        # -- continued-fraction regime -------------------------------------
        if y < 0.0:
            xs = -zr
        else:
            xs = zr
        if x + ya > 4000.0:  # nu <= 2
            if x + ya > 1e7:  # nu == 1, w(z) = i/sqrt(pi) / z
                if x > ya:
                    yax = ya / xs
                    denom = _ISPI / (xs + yax * ya)
                    ret = denom * yax
                elif math.isinf(ya):
                    if math.isnan(x) or y < 0.0:
                        return _NAN
                    return 0.0
                else:
                    xya = xs / ya
                    denom = _ISPI / (xya * xs + ya)
                    ret = denom
            else:  # nu == 2, w(z) = i/sqrt(pi) * z / (z*z - 0.5)
                dr = xs * xs - ya * ya - 0.5
                di = 2.0 * xs * ya
                denom = _ISPI / (dr * dr + di * di)
                ret = denom * (xs * di - ya * dr)
        else:  # estimate nu(z) and run the general continued fraction
            c0 = 3.9
            c1 = 11.398
            c2 = 0.08254
            c3 = 0.1421
            c4 = 0.2023
            nu = math.floor(c0 + c1 / (c2 * x + c3 * ya + c4))
            wr = xs
            wi = ya
            nu = 0.5 * (nu - 1.0)
            while nu > 0.4:
                denom = nu / (wr * wr + wi * wi)
                wr = xs - wr * denom
                wi = ya + wi * denom
                nu -= 0.5
            denom = _ISPI / (wr * wr + wi * wi)
            ret = denom * wi
        if y < 0.0:
            val = 2.0 * math.exp((ya - xs) * (xs + ya))
            if val == 0.0:
                return -ret
            return val * math.cos(2.0 * xs * y) - ret
        return ret

    if x < 10.0:
        # -- moderate |x|: full series -------------------------------------
        prod2ax = 1.0
        prodm2ax = 1.0
        if math.isnan(y):
            return y

        if x < 5e-4:
            # exp(-x*x), exp(2ax) and exp(-2ax) via Taylor, to double precision
            x2 = x * x
            expx2 = 1.0 - x2 * (1.0 - 0.5 * x2)
            ax2 = 1.036642960860171859744 * x  # 2*a*x
            exp2ax = 1.0 + ax2 * (1.0 + ax2 * (0.5 + 0.166666666666666666667 * ax2))
            expm2ax = 1.0 - ax2 * (1.0 - ax2 * (0.5 - 0.166666666666666666667 * ax2))
            n = 1
            while True:
                coef = expa2n2[n - 1] * expx2 / (a2 * (n * n) + y * y)
                prod2ax *= exp2ax
                prodm2ax *= expm2ax
                sum1 += coef
                sum2 += coef * prodm2ax
                sum3 += coef * prod2ax
                # really sum5 - sum4
                sum5 += coef * (2.0 * a) * n * _sinh_taylor((2.0 * a) * n * x)
                # convergence is tested on sum3
                if coef * prod2ax < relerr * sum3 or n >= expa2n2.shape[0]:
                    break
                n += 1
        else:
            expx2 = math.exp(-x * x)
            exp2ax = math.exp((2.0 * a) * x)
            expm2ax = 1.0 / exp2ax
            n = 1
            while True:
                coef = expa2n2[n - 1] * expx2 / (a2 * (n * n) + y * y)
                prod2ax *= exp2ax
                prodm2ax *= expm2ax
                sum1 += coef
                sum2 += coef * prodm2ax
                sum4 += (coef * prodm2ax) * (a * n)
                sum3 += coef * prod2ax
                sum5 += (coef * prod2ax) * (a * n)
                # sum5 has the slowest decay, so convergence is tested on it
                if (coef * prod2ax) * (a * n) < relerr * sum5 or n >= expa2n2.shape[0]:
                    break
                n += 1
        if y > -6.0:
            expx2erfcxy = expx2 * _erfcx(y, erfcx_cc)
        else:
            expx2erfcxy = 2.0 * math.exp(y * y - x * x)
        if y > 5.0:  # imaginary terms cancel
            sinxy = math.sin(x * y)
            ret = (expx2erfcxy - c * y * sum1) * math.cos(2.0 * x * y) + (
                c * x * expx2
            ) * sinxy * _sinc(x * y, sinxy)
        else:
            xs = zr
            sinxy = math.sin(xs * y)
            cos2xy = math.cos(2.0 * xs * y)
            coef1 = expx2erfcxy - c * y * sum1
            coef2 = c * xs * expx2
            ret = coef1 * cos2xy + coef2 * sinxy * _sinc(xs * y, sinxy)
        return ret + (0.5 * c) * y * (sum2 + sum3)

    # -- large |x| with negligible |y|: only sum3 and sum5 contribute --------
    if math.isnan(x):
        return x
    if math.isnan(y):
        return y

    ret = math.exp(-x * x)  # |y| < 1e-10, so only the exp(-x*x) term is needed
    # round rather than ceil (as in the original paper); note x/a > 1 here
    n0 = math.floor(x / a + 0.5)  # sum in both directions, starting at n0
    dx = a * n0 - x
    sum3 = math.exp(-dx * dx) / (a2 * (n0 * n0) + y * y)
    sum5 = a * n0 * sum3
    exp1 = math.exp(4.0 * a * dx)
    exp1dn = 1.0
    dn = 1.0
    while n0 - dn > 0.0:  # loop over the n0-dn and n0+dn terms together
        npl = n0 + dn
        nmi = n0 - dn
        tp = math.exp(-_sqr(a * dn + dx))
        exp1dn *= exp1
        tm = tp * exp1dn  # trick to get tm from tp
        tp /= a2 * (npl * npl) + y * y
        tm /= a2 * (nmi * nmi) + y * y
        sum3 += tp + tm
        sum5 += a * (npl * tp + nmi * tm)
        if a * (npl * tp + nmi * tm) < relerr * sum5:
            return ret + (0.5 * c) * y * (sum2 + sum3)
        dn += 1.0
    while True:  # only the n0+dn terms remain, since n0-dn <= 0
        # The index/exponent pairing here is C's `np = n0 + dn++` followed by a
        # use of the *incremented* dn, kept because scipy's wofz is that C. In
        # practice the loop above always converges first, so this is a
        # safety net rather than a live path.
        npl = n0 + dn
        dn += 1.0
        tp = math.exp(-_sqr(a * dn + dx)) / (a2 * (npl * npl) + y * y)
        sum3 += tp
        sum5 += a * npl * tp
        if a * npl * tp < relerr * sum5:
            return ret + (0.5 * c) * y * (sum2 + sum3)


# -- the Voigt kernel --------------------------------------------------------


@cuda.jit
def _voigt_kernel(wave, pin, keys, sumflag, out):
    """Evaluate a batch of Voigt profiles and combine them, one thread per pixel.

    Each thread owns one wavelength and loops over every row of ``pin``,
    accumulating the combined model as it goes. Reducing inside the thread
    avoids materialising the ``(nrow, nwave)`` intermediate that ``call_CPU``
    builds, and accumulates in the same order numpy does, so the result is not
    merely close but rounds identically.

    The per-row scalars (``wv``, ``bl``, ``a``, ``cne``) are recomputed by
    every thread rather than precomputed once on the host: that costs a few
    flops against the hundreds the Faddeeva evaluation needs, and it is what
    lets ``pin`` stay on the device untouched, as the ``call_GPU`` contract
    requires.

    Generated by RJC and Claude.
    """
    j = cuda.grid(1)
    if j >= wave.shape[0]:
        return

    erfcx_cc = cuda.const.array_like(_ERFCX_COEFFS)
    expa2n2 = cuda.const.array_like(_EXPA2N2)

    if sumflag == 1:
        acc = 0.0
    else:
        acc = 1.0

    for i in range(pin.shape[0]):
        # keys[i] = (freq, logN, ColDensScale) -- see _encode_keywords.
        if keys[i, 0] != 0.0:
            wavein = 1.0e10 * 299792458.0 / wave[j]
            wv = 29979245800.0 / pin[i, 3]
        else:
            wavein = wave[j]
            wv = pin[i, 3] * 1.0e-8
        if keys[i, 1] != 0.0:
            cold = 10.0 ** pin[i, 0]
        else:
            cold = keys[i, 2] * pin[i, 0]
        zp1 = pin[i, 1] + 1.0
        bl = pin[i, 2] * wv / 2.99792458e5
        a = pin[i, 5] * wv * wv / (3.76730313461770655e11 * bl)
        cns = wv * wv * pin[i, 4] / (bl * 2.002134602291006e12)
        cne = cold * cns
        ww = (wavein * 1.0e-8) / zp1
        v = wv * ((wv / ww) - 1.0) / bl
        tau = cne * _faddeeva_real(v, a, erfcx_cc, expa2n2)
        val = math.exp(-1.0 * tau)
        if sumflag == 1:
            acc += val
        else:
            acc *= val

    out[j] = acc


# -- host-side entry point ---------------------------------------------------

# Encoded keyword arrays, keyed by their contents. The keywords come from the
# model file and so never change during a fit, while call_GPU is invoked
# thousands of times; caching keeps the steady state genuinely transfer-free,
# which is what the call_GPU contract asks for. The number of distinct keyword
# configurations in a model is small, but the cache is capped anyway.
_KEY_CACHE = {}
_KEY_CACHE_MAX = 32


def _encode_keywords(mkey, nrow):
    """Pack the per-row Voigt keywords into a device array of shape ``(nrow, 3)``.

    ``mkey`` is a host-side list of dicts, so some transfer is unavoidable;
    the result is cached on its contents so it happens once per model rather
    than once per call.

    Columns are ``(freq, logN, ColDensScale)``, using the same defaults as
    ``Voigt._keywd`` when a key is absent.

    Generated by RJC and Claude.
    """
    if mkey is None:
        rows = ((0.0, 1.0, 1.0),) * nrow
    else:
        rows = tuple(
            (
                1.0 if karr.get("freq", False) else 0.0,
                1.0 if karr.get("logN", True) else 0.0,
                float(karr.get("ColDensScale", 1.0)),
            )
            for karr in mkey
        )
    cached = _KEY_CACHE.get(rows)
    if cached is None:
        if len(_KEY_CACHE) >= _KEY_CACHE_MAX:
            _KEY_CACHE.clear()
        cached = cuda.to_device(np.array(rows, dtype=np.float64))
        _KEY_CACHE[rows] = cached
    return cached


def evaluate(wave, pin, ae="ab", mkey=None, out=None):
    """Evaluate the combined Voigt model on the GPU.

    Parameters
    ----------
    wave : device array
        Wavelengths (or frequencies, if the ``freq`` keyword is set), float64.
    pin : device array
        Voigt parameters, shape ``(nrow, 6)``: column density, redshift, total
        Doppler parameter, rest wavelength, oscillator strength, Gamma -- one
        row per transition per component, exactly as ``call_CPU`` receives.
    ae : str, optional
        ``'em'`` sums the rows; anything else takes their product, matching
        ``call_CPU``.
    mkey : list of dict, optional
        Per-row keywords (``freq`` / ``logN`` / ``ColDensScale``).
    out : device array, optional
        Destination of shape ``(wave.size,)``; allocated if not supplied.

    Returns
    -------
    device array
        The combined model, float64, left on the device for the caller to
        reduce or transfer.

    Generated by RJC and Claude.
    """
    nwave = wave.shape[0]
    if out is None:
        out = cuda.device_array(nwave, dtype=np.float64)
    keys = _encode_keywords(mkey, pin.shape[0])
    blocks = (nwave + _THREADS_PER_BLOCK - 1) // _THREADS_PER_BLOCK
    _voigt_kernel[blocks, _THREADS_PER_BLOCK](
        wave, pin, keys, 1 if ae == "em" else 0, out
    )
    return out


def reset_key_cache():
    """Drop the cached keyword arrays.

    Only needed by the tests, and by anything that changes CUDA context.

    Generated by RJC and Claude.
    """
    _KEY_CACHE.clear()
