"""The ``alis`` command: open the ALIS dashboard (dashboard Stage 3, F14).

``alis`` opens the dashboard's start page; ``alis project.model`` opens a project;
``alis fit.mod`` imports an existing fit into a new, unsaved project. A spectrum is
not opened from the command line: a new project is made in the dashboard, with New
project (Q3.7). Fits are run from the command line with ``run_alis``.

The dashboard needs the optional ``gui`` extra (PySide6, qtpy and pyqtgraph). Without
it, ``alis`` says how to install it and stops with status 1.

Generated by RJC and Claude.
"""

import argparse
import importlib
import sys

# What the user is told when the gui extra is missing
INSTALL = (
    'The ALIS dashboard needs the optional "gui" extra (PySide6, qtpy and'
    " pyqtgraph). Install it with:\n"
    '    pip install "alis[gui]"'
)


def _description():
    """
    The ``--help`` preamble.

    Generated by RJC and Claude.
    """
    import alis

    return "ALIS dashboard v{0:s}: prepare, run and inspect ALIS fits.".format(
        alis.__version__
    )


def parser(options=None):
    """
    Parse the command line of ``alis``.

    Parameters
    ----------
    options : list of str, optional
        The arguments; by default ``sys.argv[1:]``.

    Returns
    -------
    argparse.Namespace
        With ``path`` (None when nothing is given).

    Generated by RJC and Claude.
    """
    args = argparse.ArgumentParser(
        prog="alis",
        description=_description(),
        epilog="To start a project from a spectrum, run alis and choose New"
        " project. To run a fit from the command line, use run_alis.",
    )
    args.add_argument(
        "path",
        nargs="?",
        default=None,
        help="a project (.model) to open, or a fit (.mod) to import; with nothing,"
        " the start page opens",
    )
    return args.parse_args(options)


def qt_available():
    """
    Whether the ``gui`` extra can be imported: qtpy, a Qt binding, and pyqtgraph.

    Returns
    -------
    bool

    Generated by RJC and Claude.
    """
    try:
        importlib.import_module("alis.dashboard.qt")
        importlib.import_module("qtpy.QtWidgets")
        importlib.import_module("pyqtgraph")
    except Exception:
        return False
    return True


def main(args):
    """
    Start the dashboard on what the command line names.

    Parameters
    ----------
    args : argparse.Namespace
        From :func:`parser`.

    Returns
    -------
    int
        The exit status: 0, 1 when the gui extra is missing, 2 when the path cannot
        be opened.

    Generated by RJC and Claude.
    """
    if not qt_available():
        print(INSTALL, file=sys.stderr)
        return 1
    from alis.dashboard import session

    try:
        target = session.launch_target(args.path)
    except session.LaunchError as err:
        print("alis: " + str(err), file=sys.stderr)
        return 2
    from alis.dashboard.qt import app

    return app.run(target)


def console_entry():
    """
    Console-script entry point for ``alis``.

    Generated by RJC and Claude.
    """
    sys.exit(main(parser()))


if __name__ == "__main__":
    # Clearing __spec__ lets ALIS's spawned worker processes start from here, as
    # run_alis does
    __spec__ = None
    console_entry()
