#!/usr/bin/env bash
#
# regen_harness.sh -- regenerate the Stage 0 golden references.
#
# For every regression case it:
#   1. cd's into the model directory and runs the model through run_alis;
#   2. mv's  <name>.mod.out          -> <name>.mod.out.reference
#   3. mv's  the 'out covar' file    -> <same name>.reference   (if written)
#   4. for each reference_fits/ directory belonging to the example, replaces
#      every file already in it with the file of the same name in the
#      directory above (the produced _fit.dat, etc).
#
# It does NOT touch the two hand-fixed `.mod.out.reference_adjusted` files
# (examples/lsf_hst, examples/spline/...splineContAbs). Those are RJC's
# corrected re-inputs for the writer bugs that Stage 5.4 will fix, and they
# cannot be produced by a run. After a regeneration they are stale and the
# mode-(b) fixed-parameter test for those two cases will fail until they are
# refreshed -- re-apply the same hand-fix to the new plain reference:
#   lsf_hst          : '=' -> ':' inside the resolution=lsf(...) call
#   ...splineContAbs : drop the trailing empty 'locations=' from splineabs lines
# Stage 5.4 removes the need for both.
#
# Only golden files are rewritten. The produced outputs are moved, not copied,
# so no stray files are left behind; nothing tracked by git is removed by that
# (the produced _fit.dat files and the generated data file are untracked --
# only the goldens and the *input* .dat files are tracked).
#
# EVERYTHING IT WRITES IS TRACKED BY GIT, so a run can be undone in full with
#     git checkout -- examples context
#
# Usage:
#   ./regen_harness.sh                     # every case (examples + context)
#   ./regen_harness.sh examples            # just the shipped examples
#   ./regen_harness.sh examples/metal_line_abs context/fitting_examples/DH
#   ./regen_harness.sh --dry-run examples  # list what would happen, do nothing
#   ./regen_harness.sh --clean examples    # also delete the .pdf/.png/.report
#                                          # byproducts, to keep the diff readable
#
# Generated by RJC and Claude.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_ALIS="$REPO/alis/scripts/run_alis.py"
PYTHON="${PYTHON:-python}"

DRY_RUN=0
CLEAN=0
declare -a ROOTS=()
for arg in "$@"; do
    case "$arg" in
        --dry-run|-n) DRY_RUN=1 ;;
        --clean)      CLEAN=1 ;;
        -h|--help)    sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
        -*)           echo "unknown option: $arg" >&2; exit 2 ;;
        *)            ROOTS+=("$arg") ;;
    esac
done
[ ${#ROOTS[@]} -eq 0 ] && ROOTS=("examples" "context")

# Cases whose committed references only reproduce on the machine that made
# them (tests/test_regression.py: MINIMISATION_MACHINE_DEPENDENT). Regenerating
# them here re-pins them to *this* machine.
MACHINE_DEPENDENT="HS0105p1619 J1358p0349 J1358p6522_original J1419p0829 \
J1558m0031_FINAL_MODEL Q0913p072 Q1243p307_converge_newstart76 \
J0035m0918_all_data J0903p2628"

# The filenames named in the model's `data read` ... `data end` block.
data_files() {
    sed 's/#.*//' "$1" | awk '
        tolower($1)=="data" && tolower($2)=="read" { inblock=1; next }
        tolower($1)=="data" && tolower($2)=="end"  { inblock=0 }
        inblock && NF { print $1 }'
}

# ---------------------------------------------------------------- discovery --
# A "fit" case is a .mod with a committed .mod.out.reference beside it -- the
# same rule tests/manifest.py uses. A "generate" case has no .mod.out.reference
# and is identified by its 'generate data True' setting.
declare -a MODS=()
for root in "${ROOTS[@]}"; do
    [ -e "$REPO/$root" ] || { echo "no such path: $root" >&2; exit 2; }
    while IFS= read -r ref; do
        MODS+=("${ref%.out.reference}")
    done < <(find "$REPO/$root" -type f -name '*.mod.out.reference' | sort)
    while IFS= read -r mod; do
        [ -f "${mod}.out.reference" ] && continue
        grep -qiE '^[[:space:]]*generate[[:space:]]+data[[:space:]]+True' "$mod" \
            || continue
        # ...and, as manifest.py requires, the data file it generates must have
        # a golden copy in a reference_fits/. Without this test the generate
        # models that *built* an example's input data (e.g. metal_line_abs's)
        # would be re-run, rewriting tracked input files rather than goldens.
        is_case=0
        for name in $(data_files "$mod"); do
            for gold in $(find "$(dirname "$(dirname "$mod")")" -type d -name reference_fits); do
                [ -f "$gold/$(basename "$name")" ] && is_case=1 && break 2
            done
        done
        [ "$is_case" = 1 ] && MODS+=("$mod")
    done < <(find "$REPO/$root" -type f -name '*.mod' | sort)
done

if [ ${#MODS[@]} -eq 0 ]; then
    echo "no regression cases found under: ${ROOTS[*]}" >&2
    exit 1
fi

echo "======================================================================"
echo " regenerating Stage 0 references"
echo " roots     : ${ROOTS[*]}"
echo " cases     : ${#MODS[@]}"
[ "$DRY_RUN" = 1 ] && echo " MODE      : DRY RUN -- nothing will be written"
for mod in "${MODS[@]}"; do
    for md in $MACHINE_DEPENDENT; do
        [ "$(basename "$mod" .mod)" = "$md" ] && \
            echo " note      : $md is machine-dependent -- this re-pins it here"
    done
done
echo "======================================================================"

# ------------------------------------------------------------------ helpers --
# The 'out covar' filename, if the model writes one. Comments are stripped and
# the last active setting wins, as ALIS does. The name is arbitrary -- it is
# not always <model>.covar (e.g. J0035m0918_all_data_covar.dat).
covar_name() {
    sed 's/#.*//' "$1" \
        | awk 'tolower($1)=="out" && tolower($2)=="covar" && NF>=3 {n=$3} END{print n}'
}

say() { printf '    %s\n' "$*"; }

LOG="$(mktemp -t regen_harness.XXXXXX)"
trap 'rm -f "$LOG"' EXIT

n_ok=0; n_fail=0; n_out=0; n_covar=0; n_fits=0; n_missing=0
declare -a FAILED=()
declare -a MISSING=()

# --------------------------------------------------------------------- main --
for mod in "${MODS[@]}"; do
    model_dir="$(dirname "$mod")"
    example_root="$(dirname "$model_dir")"
    mod_file="$(basename "$mod")"
    rel="${mod#"$REPO"/}"

    echo
    echo "--- $rel"

    if [ "$DRY_RUN" = 1 ]; then
        say "would run  : $mod_file  (in ${model_dir#"$REPO"/})"
        [ -f "${mod}.out.reference" ] && say "would write: ${mod_file}.out.reference"
        cv="$(covar_name "$mod")"
        [ -n "$cv" ] && say "would write: ${cv}.reference   (if the run produces it)"
        while IFS= read -r refdir; do
            say "would sync : ${refdir#"$REPO"/}  ($(find "$refdir" -maxdepth 1 -type f | wc -l) files)"
        done < <(find "$example_root" -type d -name reference_fits | sort)
        continue
    fi

    # 1. run the model, exactly as the harness does (-f write fits, -w clobber,
    #    -p 0 headless). run_alis takes the model from the last argument.
    is_fit=0
    [ -f "${mod}.out.reference" ] && is_fit=1
    rm -f "${mod}.out"          # so a stale output cannot masquerade as fresh
    start=$SECONDS
    ( cd "$model_dir" && MPLBACKEND=Agg "$PYTHON" "$RUN_ALIS" -f -w -p 0 "$mod_file" ) \
        > "$LOG" 2>&1
    rc=$?
    elapsed=$((SECONDS-start))

    # Success is judged on what the run *produced*, not on its exit status:
    # ALIS reports a fatal model error through msgs.error(), which calls a bare
    # sys.exit() and therefore exits **0**. Taking rc alone would silently mark
    # a broken model as regenerated and leave its reference untouched.
    why=""
    [ "$rc" -ne 0 ] && why="run_alis exited $rc"
    if grep -q '\[ERROR\]' "$LOG"; then
        why="${why:+$why; }ALIS reported an error"
    fi
    if [ "$is_fit" = 1 ] && [ ! -f "${mod}.out" ]; then
        why="${why:+$why; }no ${mod_file}.out was written"
    fi
    if [ -n "$why" ]; then
        say "FAILED after ${elapsed}s -- $why"
        say "last lines of output:"
        grep -E '\[ERROR\]|Traceback|Error' "$LOG" | tail -n 4 | sed 's/^/      /'
        tail -n 6 "$LOG" | sed 's/^/      /'
        FAILED+=("$rel  ($why)")
        n_fail=$((n_fail+1))
        # Nothing is moved for a failed case, so its references keep their
        # previous contents rather than being replaced by a partial run.
        continue
    fi
    say "ran in ${elapsed}s"
    n_ok=$((n_ok+1))

    # 2. the model output becomes the reference
    if [ -f "${mod}.out" ]; then
        mv -f "${mod}.out" "${mod}.out.reference"
        say "reference  : ${mod_file}.out.reference"
        n_out=$((n_out+1))
    fi

    # 3. the covariance, if this model writes one
    cv="$(covar_name "$mod")"
    if [ -n "$cv" ] && [ -f "$model_dir/$cv" ]; then
        mv -f "$model_dir/$cv" "$model_dir/${cv}.reference"
        say "reference  : ${cv}.reference"
        n_covar=$((n_covar+1))
    fi

    # 4. replace each golden fit file with the one just produced beside it.
    #    Driven by what is *already* in reference_fits/, so it needs no
    #    knowledge of which files this model writes. The directory is found
    #    rather than assumed: it is usually ../data/reference_fits, but
    #    DH_orders uses datafit_orders/ and J1358p6522_original has two.
    total_updated=0
    while IFS= read -r refdir; do
        updated=0
        for ref in "$refdir"/*; do
            [ -f "$ref" ] || continue
            base="$(basename "$ref")"
            src="$(dirname "$refdir")/$base"
            if [ -f "$src" ]; then
                mv -f "$src" "$ref"
                updated=$((updated+1))
            else
                MISSING+=("${ref#"$REPO"/}")
            fi
        done
        n_fits=$((n_fits+updated))
        total_updated=$((total_updated+updated))
        say "fit files  : $updated updated in ${refdir#"$REPO"/}"
    done < <(find "$example_root" -type d -name reference_fits | sort)

    # A generate case has no .mod.out to check, so its proof of success is
    # that it actually produced the data file its golden shadows.
    if [ "$is_fit" = 0 ] && [ "$total_updated" -eq 0 ]; then
        say "FAILED -- generated no data file to replace its golden"
        FAILED+=("$rel  (generated nothing)")
        n_fail=$((n_fail+1)); n_ok=$((n_ok-1))
    fi

    # 5. optional tidy-up. ALIS also writes a fit-quality report, a plot and a
    #    covariance image; none is a golden and none is tracked, but 42 cases'
    #    worth makes `git status` hard to read while reviewing the diff. Only
    #    untracked files are ever removed, so a tracked file cannot be lost.
    if [ "$CLEAN" = 1 ]; then
        removed=0
        while IFS= read -r junk; do
            git -C "$REPO" ls-files --error-unmatch "$junk" >/dev/null 2>&1 && continue
            rm -f "$junk" && removed=$((removed+1))
        done < <(find "$model_dir" -maxdepth 1 -type f \
                      \( -name '*.pdf' -o -name '*.png' -o -name '*.mod.report' \) )
        [ "$removed" -gt 0 ] && say "cleaned    : $removed byproduct file(s)"
    fi
done

# ------------------------------------------------------------------ summary --
echo
echo "======================================================================"
if [ "$DRY_RUN" = 1 ]; then
    echo " dry run complete -- nothing written"
    exit 0
fi
echo " cases run            : $n_ok ok, $n_fail failed"
echo " .mod.out.reference   : $n_out"
echo " .covar references    : $n_covar"
echo " reference_fits files : $n_fits"

# A golden with no freshly produced counterpart is the interesting case: it
# means this run did not reproduce that file, so it still holds its old
# contents. Expected when several models share one example (each writes only
# its own), and worth reading otherwise.
n_missing=${#MISSING[@]}
if [ "$n_missing" -gt 0 ]; then
    # a golden may be listed once per model in the same example; count uniques
    uniq_missing=$(printf '%s\n' "${MISSING[@]}" | sort -u)
    still=$(printf '%s\n' "$uniq_missing" | wc -l)
    echo " goldens not rewritten: $still (left at their previous contents)"
    echo "   -- normal where one example has several models; check if unexpected:"
    printf '%s\n' "$uniq_missing" | head -n 10 | sed 's/^/      /'
    [ "$still" -gt 10 ] && echo "      ... and $((still-10)) more"
fi

if [ "$n_fail" -gt 0 ]; then
    echo
    echo " FAILED CASES:"
    printf '      %s\n' "${FAILED[@]}"
fi
echo "======================================================================"
echo
[ "$CLEAN" = 0 ] && echo " note: ALIS also wrote .pdf/.png/.mod.report byproducts; they are"
[ "$CLEAN" = 0 ] && echo "       untracked and harmless -- re-run with --clean to remove them."
echo
echo " review with : git status --short && git diff --stat"
echo " undo all    : git checkout -- examples context"
[ "$n_fail" -gt 0 ] && exit 1
exit 0
