"""The ALIS dashboard: the project model, in plain Python (dashboard Stage 2).

Everything the dashboard knows about a project lives here, held in plain Python and
tested with pytest, before any window exists. Nothing in this package imports Qt or
pyqtgraph; the windows come in Stage 3, in a ``qt/`` subpackage that is the only
part of the dashboard to import Qt (Q2.1). The layers, from the bottom up:

- :mod:`~alis.dashboard.text`: the ``.mod`` text as lines and words, each with its
  position, and the patches that change it (D7);
- :mod:`~alis.dashboard.model`: the parsed model, rebuilt from the text after every
  edit;
- :mod:`~alis.dashboard.edit`: the targeted edits that the panels make;
- :mod:`~alis.dashboard.project`: the dashboard's concepts (datasets, snips,
  systems, components, continua), built from the layers above and the bundle;

and the services that work on them:

- :mod:`~alis.dashboard.validate`: the validator (F5);
- :mod:`~alis.dashboard.blinding`: the blinding gate (F8, D24);
- :mod:`~alis.dashboard.history`: undo and redo (F2);
- :mod:`~alis.dashboard.remove`: removal with dependents (S27, D23);
- :mod:`~alis.dashboard.modes`: the mode interface, and Voigt mode (F11).

Generated by RJC and Claude.
"""
