"""The continuum: evaluated as ALIS does, first guess, order, knots, sharing.

Dashboard Stage 4.3 (S8, S9, S10, D17). No Qt.

- **Evaluated by ALIS's own functions.** A continuum line is drawn with the class
  ALIS fits it with (``legendre``, ``chebyshev``, ``polynomial``, ``constant``),
  called through ALIS's ``call_CPU`` with the line's coefficients times its
  ``scale=`` factors, on the snip's wavelengths moved by its row's shift, as ALIS
  moves them. Its range is ``min=``/``max=`` when the line gives them; otherwise the
  range of the wavelengths ALIS evaluates it on, taken from ALIS's own loaders. A fit
  basis is the same functions called with one coefficient at a time, so the curve
  the dashboard fits is the curve ALIS evaluates.
- **The first guess** (S8, Q4.6, Q4.16, Q4.19): the snip's good pixels, leaving out
  ±15 km/s around the transitions of the model's absorption lines and of the systems'
  line IDs, are clipped in three passes of rising order: a straight line, then one
  order higher, then one more, each fitted to the pixels the last kept and rejecting
  those far below it (2.5σ: absorption) or above it (3σ). Every order is then fitted
  to the pixels left, and the one with the lowest BIC, up to 5, is chosen.
- **Knots** (Q4.7, Q4.13): points the starting continuum passes through; every refit
  is held through them (a least-squares fit with equality constraints). They set only
  the starting coefficients: ALIS then fits the continuum freely. They are kept in
  ``ui/project.json``, by snip.
- **The table of orders:** χ², Δχ² and ΔBIC for the orders either side of the
  current one, on the same pixels.
- **Sharing** (S10, Q4.8): one Legendre for the snips of one transition in several
  file rows, with one ``min=``/``max=`` (the union of their ranges).

A continuum the dashboard writes has its coefficients scaled to order unity by
``scale=`` factors (powers of ten), and a Legendre has ``min=``/``max=`` (the snip's
range), so that what is drawn does not depend on how finely ALIS sub-pixellates.

Generated by RJC and Claude.
"""

import copy
import hashlib
import math
from dataclasses import dataclass, field
from types import SimpleNamespace

import numpy as np

from alis import load
from alis.config import ArgFlag
from alis.dashboard import edit as E
from alis.dashboard import lines as L
from alis.dashboard import model as M
from alis.dashboard import project as P
from alis.dashboard import text as T

C_KMS = 299792.458
# The continuum functions placed interactively (D17, QF.12)
FUNCTIONS = ("legendre", "chebyshev", "polynomial", "constant")
# The highest order of each: ALIS's Legendre stops at 10 and its Chebyshev at 9; a
# polynomial in raw wavelength loses precision beyond a cubic
MAX_ORDER = {"legendre": 10, "chebyshev": 9, "polynomial": 3, "constant": 0}
# The functions whose range is set by min= and max=
RANGED = ("legendre",)
# Legendre's value for "no min= or max=" (alis.functions.legendre.maskval)
NO_RANGE = -1.0
# The first guess (the preferences override these)
CLIP = (2.5, 3.0)
AUTO_MAX = 5
LINE_KMS = 15.0
MAXITER = 25
# The passes that choose the continuum pixels (Q4.19): from a straight line, one
# order higher at each pass
FIRST_ORDER = 1
PASSES = 3
KNOTS = "knots"
# Keywords the dashboard writes itself, rather than keeping from the old line
_OWN = ("scale", "min", "max", "specid")


class ContinuumError(Exception):
    """A continuum action that cannot be done as asked."""


# -- Evaluating with ALIS's functions ------------------------------------------------


def _karr(function, xrange):
    """The keywords ALIS's ``call_CPU`` reads: a Legendre's range."""
    if function in RANGED and xrange is not None:
        return {"min": float(xrange[0]), "max": float(xrange[1])}
    return {"min": NO_RANGE, "max": NO_RANGE}


def _ncoef(function, order):
    return 1 if function == "constant" else order + 1


def _grid(function, x, xrange):
    """
    The wavelengths to call ALIS with: a Chebyshev takes its range from them, so the
    range's ends are put first (and dropped after).

    Generated by RJC and Claude.
    """
    x = np.asarray(x, dtype=float)
    if function == "chebyshev" and xrange is not None:
        return np.concatenate(([xrange[0], xrange[1]], x)), 2
    return x, 0


def curve(registry, function, coeffs, x, xrange):
    """
    A continuum at wavelengths ``x`` (in the model's frame), by ALIS's own function.

    Parameters
    ----------
    registry : Registry
    function : str
    coeffs : array
        The coefficients as ALIS uses them (the written values times ``scale=``).
    x : array
    xrange : tuple or None
        The range that maps onto [-1, 1].

    Returns
    -------
    numpy.ndarray

    Generated by RJC and Claude.
    """
    inst = registry.function(function)
    grid, cut = _grid(function, x, xrange)
    pars = np.asarray(coeffs, dtype=float).reshape(1, -1)
    return inst.call_CPU(grid, pars, mkey=[_karr(function, xrange)])[cut:]


def basis(registry, function, x, order, xrange):
    """
    The fit basis: ALIS's function with one coefficient at a time.

    Returns
    -------
    numpy.ndarray
        One column per coefficient.

    Generated by RJC and Claude.
    """
    ncoef = _ncoef(function, order)
    eye = np.eye(ncoef)
    return np.column_stack(
        [curve(registry, function, eye[k], x, xrange) for k in range(ncoef)]
    )


def model_wave(project, snip, wave):
    """
    A snip's wavelengths moved by its row's shift, as ALIS moves the wavelengths it
    evaluates the model on (``vshift``: ``λ / (1 + v/c)``).

    Generated by RJC and Claude.
    """
    wave = np.asarray(wave, dtype=float)
    item = snip.data
    if item.shift is None or item.shift.name != "vshift":
        return wave
    par = item.param("shift")
    if par is None:
        return wave
    inst = project.registry.function("vshift")
    return np.asarray(inst.call_CPU(wave, np.array([par.start])), dtype=float)


def data_wave(project, snip, wave):
    """The inverse of :func:`model_wave`."""
    wave = np.asarray(wave, dtype=float)
    item = snip.data
    if item.shift is None or item.shift.name != "vshift":
        return wave
    par = item.param("shift")
    return wave if par is None else wave * (1.0 + par.start / C_KMS)


# -- ALIS's own evaluation range -----------------------------------------------------

_GRIDS = {}


def _state_key(project):
    digest = hashlib.sha1(project.text.encode("utf-8"))
    for member in sorted(project.files):
        digest.update(member.encode("utf-8"))
        digest.update(hashlib.sha1(project.files[member]).digest())
    return digest.hexdigest()


def alis_ranges(project):
    """
    The range of the wavelengths ALIS evaluates each data line's model on: its
    sub-pixels, moved by the shift, as ALIS's loaders make them.

    Returns
    -------
    dict
        Data line index (``DataLine.index``) to ``(low, high)``; empty when ALIS
        cannot load the model as it is.

    Generated by RJC and Claude.
    """
    key = _state_key(project)
    if key in _GRIDS:
        return _GRIDS[key]
    if len(_GRIDS) > 32:
        _GRIDS.clear()
    out = {}
    try:
        state = _load_with_alis(project)
    except Exception:
        state = None
    if state is not None:
        shind = np.where(np.array(state._modpass["emab"]) == "sh")[0][0]
        lines_by_specid = {}
        for item in project.parsed.data:
            lines_by_specid.setdefault(item.specid, []).append(item.index)
        for sp in range(len(state._posnspx)):
            specid = str(state._specid[sp])
            order = lines_by_specid.get(specid, [])
            for sn in range(len(state._posnspx[sp]) - 1):
                low, high = state._posnspx[sp][sn], state._posnspx[sp][sn + 1]
                mtyp = state._modpass["mtyp"][shind]
                inst = state._funcarray[2][mtyp]
                cls = state._funcarray[1][mtyp]
                inst._keywd = state._modpass["mkey"][shind]
                pars = cls.set_vars(
                    inst,
                    state._modpass["p0"],
                    state._levadd[shind],
                    state._modpass,
                    shind,
                )
                wave = cls.call_CPU(inst, state._wavespx[sp][low:high], pars)
                shind += 1
                if sn < len(order):
                    out[order[sn]] = (float(np.min(wave)), float(np.max(wave)))
    _GRIDS[key] = out
    return out


def _load_with_alis(project):
    """
    ALIS's loaders, run quietly on the project in memory, as far as sub-pixels.

    Generated by RJC and Claude.
    """
    state = SimpleNamespace(_argflag=ArgFlag())
    state._argflag["out"]["verbose"] = -1
    with M.alis_quietly():
        _, datlines, modlines, lnklines = load.load_input(
            state, textstr=project.text.splitlines(keepends=True)
        )
        if not [d for d in datlines if d.split("#")[0].strip()]:
            return None
        state._atomic = project.registry.atomic
        state._funcarray = project.registry.instances()
        load.load_data(state, datlines, data=project.data_for_run())
        state._modpass = load.load_model(state, modlines)
        state._links = load.load_links(state, lnklines)
        state._modlines = modlines
        _, state._levadd = load.load_parinfo(state)
        load.load_par_influence(state, state._modpass["p0"])
        (
            state._wavespx,
            state._contspx,
            state._zerospx,
            state._posnspx,
            state._nexbins,
        ) = load.load_subpixels(state, state._modpass["p0"])
    return state


# -- A continuum line ----------------------------------------------------------------


def _keyword_float(line, name):
    value = line.keyword(name)
    try:
        return None if value is None else float(value)
    except ValueError:
        return None


def coefficients(project, line):
    """
    A continuum line's coefficients as ALIS uses them: each starting value times its
    ``scale=`` factor.

    Generated by RJC and Claude.
    """
    pm = project.parsed
    mkey = pm.modpass["mkey"][line.index] if pm.modpass else {}
    scale = list(mkey.get("scale", []) or [])
    values = [p.start for p in line.params]
    if line.function == "constant":
        return np.array(values[:1], dtype=float)
    return np.array(
        [v * (scale[k] if k < len(scale) else 1.0) for k, v in enumerate(values)]
    )


def order_of(line):
    """A continuum line's order (its number of coefficients less one)."""
    return 0 if line.function == "constant" else max(len(line.params) - 1, 0)


def xrange_of(project, snip, line=None):
    """
    The range a snip's continuum is evaluated over, in the model's frame: the line's
    ``min=``/``max=`` when it gives them; otherwise ALIS's own range for the snip's
    data line; otherwise (ALIS cannot load the model as it is) the snip's extent.

    Generated by RJC and Claude.
    """
    line = snip.continuum if line is None else line
    if line is not None and line.function in RANGED:
        low, high = _keyword_float(line, "min"), _keyword_float(line, "max")
        if low is not None and high is not None and low != NO_RANGE and high > low:
            return low, high
    found = alis_ranges(project).get(snip.data.index)
    if found is not None:
        return found
    extent = snip.extent
    if extent is None:
        return None
    ends = model_wave(project, snip, np.array(extent))
    return float(ends.min()), float(ends.max())


def evaluate(project, snip, wave=None, line=None):
    """
    A snip's continuum at data wavelengths (its pixels by default), as ALIS evaluates
    it; None when it has no continuum line.

    Generated by RJC and Claude.
    """
    line = snip.continuum if line is None else line
    if line is None or line.function not in FUNCTIONS:
        return None
    if wave is None:
        if snip.pixels is None:
            return None
        wave = snip.pixels.wave
    xrange = xrange_of(project, snip, line)
    return curve(
        project.registry,
        line.function,
        coefficients(project, line),
        model_wave(project, snip, wave),
        xrange,
    )


# -- Fitting -------------------------------------------------------------------------


@dataclass
class Fit:
    """
    A continuum fitted to a snip's pixels.

    Attributes
    ----------
    function : str
    order : int
    coeffs : numpy.ndarray
        As ALIS uses them.
    xrange : tuple
    keep : numpy.ndarray
        The pixels fitted, after clipping.
    chi2 : float
        On the pixels kept.
    nknots : int

    Generated by RJC and Claude.
    """

    function: str
    order: int
    coeffs: np.ndarray = field(repr=False)
    xrange: tuple = None
    keep: np.ndarray = field(default=None, repr=False)
    chi2: float = 0.0
    nknots: int = 0

    @property
    def npix(self):
        """The number of pixels fitted."""
        return int(np.count_nonzero(self.keep))

    @property
    def free(self):
        """The number of coefficients the pixels set (the knots set the others)."""
        return max(_ncoef(self.function, self.order) - self.nknots, 0)

    @property
    def bic(self):
        """The Bayesian information criterion, χ² + k ln N."""
        return self.chi2 + self.free * math.log(max(self.npix, 1))


def _solve(design, flux, weight, kdesign=None, kflux=None):
    """
    Weighted least squares, held through the knots when given (equality
    constraints, solved with their Lagrange multipliers).

    Generated by RJC and Claude.
    """
    ncoef = design.shape[1]
    norm = np.sqrt((design**2).sum(axis=0))
    if kdesign is not None and len(kdesign):
        norm = np.maximum(norm, np.sqrt((kdesign**2).sum(axis=0)))
    norm[norm == 0] = 1.0
    scaled = design / norm
    weight = weight / np.median(weight) if weight.size else weight
    if kdesign is None or not len(kdesign):
        root = np.sqrt(weight)
        coef, *_ = np.linalg.lstsq(scaled * root[:, None], flux * root, rcond=None)
        return coef / norm
    kscaled = kdesign / norm
    nk = kscaled.shape[0]
    if nk > ncoef:
        raise ContinuumError("There are more knots than the order allows.")
    normal = (scaled * weight[:, None]).T @ scaled
    fscale = np.max(np.abs(flux)) if flux.size and np.max(np.abs(flux)) > 0 else 1.0
    big = np.block([[2.0 * normal, kscaled.T], [kscaled, np.zeros((nk, nk))]])
    rhs = np.concatenate(
        (2.0 * (scaled * weight[:, None]).T @ (flux / fscale), kflux / fscale)
    )
    sol, *_ = np.linalg.lstsq(big, rhs, rcond=None)
    return sol[:ncoef] * fscale / norm


def fit(
    registry,
    function,
    order,
    x,
    flux,
    error,
    use,
    xrange,
    knots=(),
    clip=CLIP,
    maxiter=MAXITER,
    start=None,
):
    """
    Fit a continuum to pixels, clipped below and above, held through the knots.

    Parameters
    ----------
    registry : Registry
    function : str
    order : int
    x : array
        The pixels' wavelengths in the model's frame.
    flux, error : array
    use : array of bool
        The pixels that may be fitted.
    xrange : tuple or None
    knots : list of (x, flux)
        In the model's frame.
    clip : tuple or None
        ``(below, above)`` in σ; None for no clipping.
    maxiter : int
    start : array of bool, optional
        The pixels the first fit uses (``use`` by default); each clipping then
        judges every pixel of ``use`` again.

    Returns
    -------
    Fit

    Generated by RJC and Claude.
    """
    x = np.asarray(x, dtype=float)
    flux = np.asarray(flux, dtype=float)
    error = np.asarray(error, dtype=float)
    use = np.asarray(use, dtype=bool)
    ncoef = _ncoef(function, order)
    if len(knots) > ncoef:
        raise ContinuumError(
            "A {0} of order {1} cannot pass through {2} knots.".format(
                function, order, len(knots)
            )
        )
    design = basis(registry, function, x, order, xrange)
    kdesign = kflux = None
    if len(knots):
        kx = np.array([k[0] for k in knots], dtype=float)
        kflux = np.array([k[1] for k in knots], dtype=float)
        kdesign = basis(registry, function, kx, order, xrange)
    keep = use.copy() if start is None else use & np.asarray(start, dtype=bool)
    need = max(ncoef - len(knots), 1)
    if np.count_nonzero(keep) < need:
        raise ContinuumError("There are too few good pixels to fit the continuum.")
    coef = None
    for _ in range(maxiter):
        coef = _solve(design[keep], flux[keep], 1.0 / error[keep] ** 2, kdesign, kflux)
        if clip is None:
            break
        resid = (flux - design @ coef) / error
        new = use & (resid > -clip[0]) & (resid < clip[1])
        if np.count_nonzero(new) < need + 1 or np.array_equal(new, keep):
            break
        keep = new
    resid = (flux - design @ coef) / error
    chi2 = float(np.sum(resid[keep] ** 2))
    return Fit(function, order, coef, xrange, keep, chi2, len(knots))


# -- What the first guess fits -------------------------------------------------------


def line_cores(project, snip, wave=None, line_kms=LINE_KMS):
    """
    The pixels within ``line_kms`` of a known absorption line (Q4.6, Q4.16): the
    transitions of the model's absorption lines, at their own redshifts, and of the
    systems' ions and line IDs, at the systems' redshifts.

    Returns
    -------
    numpy.ndarray of bool

    Generated by RJC and Claude.
    """
    wave = snip.pixels.wave if wave is None else np.asarray(wave, dtype=float)
    xmod = model_wave(project, snip, wave)
    out = np.zeros(wave.size, dtype=bool)
    if not wave.size:
        return out
    low, high = float(xmod.min()), float(xmod.max())
    pad = 1.0 + line_kms / C_KMS
    centres = []
    reg = project.registry
    for line in project.parsed.lines:
        if line.section != "absorption" or not line.ion or line.ratio:
            continue
        zpar = line.param("redshift")
        if zpar is None:
            continue
        waves, _ = reg.transitions(line.ion)
        centres += [float(r) * (1.0 + zpar.start) for r in waves]
    for system in project.systems:
        for ion in L.system_ions(system):
            waves, _ = reg.transitions(ion)
            centres += [float(r) * (1.0 + system.z) for r in waves]
    for centre in centres:
        if low / pad <= centre <= high * pad:
            out |= np.abs(xmod - centre) <= centre * line_kms / C_KMS
    return out


def usable(project, snip, line_kms=LINE_KMS):
    """
    The pixels a first guess may fit: good (finite, positive error, not bad), and not
    in the core of a known line.

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    good = L.good_pixels(pix.wave, pix.flux, pix.error, L.snip_bad(snip))
    use = good & ~line_cores(project, snip, line_kms=line_kms)
    if np.count_nonzero(use) < 2:
        use = good
    return use


def knots_of(project, snip):
    """
    The knots of a snip's continuum, as ``[(λ, flux), ...]`` in its data's frame.

    Generated by RJC and Claude.
    """
    found = project.ui.get(KNOTS, {}).get(snip.specid, [])
    return [(float(a), float(b)) for a, b in found]


def _model_knots(project, snip, knots):
    if not knots:
        return []
    xs = model_wave(project, snip, np.array([k[0] for k in knots]))
    return [(float(x), float(k[1])) for x, k in zip(xs, knots)]


def new_range(project, snip):
    """
    The range a new Legendre is given: the snip's extent, in the model's frame.

    Generated by RJC and Claude.
    """
    extent = snip.extent
    ends = model_wave(project, snip, np.array(extent))
    return float(ends.min()), float(ends.max())


def continuum_pixels(
    project,
    snip,
    function="legendre",
    knots=None,
    xrange=None,
    clip=CLIP,
    line_kms=LINE_KMS,
    max_order=AUTO_MAX,
):
    """
    The pixels a snip's continuum is fitted to (Q4.19): its usable pixels, clipped in
    :data:`PASSES` passes of rising order. The first fits a low order (a straight
    line, or what the knots need) and rejects the pixels far below it (absorption) or
    above it (outliers); each next pass fits one order higher to the pixels the last
    kept, judging every usable pixel again against its curve until the pixels kept
    no longer change. A low order cannot follow the absorption; a higher one, started
    from what the lower kept, takes back the continuum that the lower could not
    follow (the ends of a curved snip). Every order is then fitted to the same
    pixels. No pass goes beyond ``max_order`` (or what the knots need) or the
    function's highest order.

    Generated by RJC and Claude.
    """
    if snip.pixels is None:
        raise ContinuumError("The snip's file cannot be read.")
    knots = knots_of(project, snip) if knots is None else knots
    use = usable(project, snip, line_kms)
    if clip is None:
        return use
    least = max(len(knots) - 1, 0)
    top = 0 if function == "constant" else MAX_ORDER[function]
    top = max(min(top, max_order), least)
    if xrange is None:
        xrange = _range_for(project, snip, function)
    x = model_wave(project, snip, snip.pixels.wave)
    model_knots = _model_knots(project, snip, knots)
    keep = use
    for step in range(PASSES):
        order = min(max(FIRST_ORDER, least) + step, top)
        keep = fit(
            project.registry,
            function,
            order,
            x,
            snip.pixels.flux,
            snip.pixels.error,
            use,
            xrange,
            model_knots,
            clip,
            start=keep,
        ).keep
    return keep


def _range_for(project, snip, function):
    """The range of a refit: the line's own for its own function, else a new one."""
    line = snip.continuum
    if line is not None and line.function == function:
        # Refitting the same function keeps its range (a Legendre without min= and
        # max= takes ALIS's own, and is then written with it)
        return xrange_of(project, snip)
    return new_range(project, snip)


def fit_snip(
    project,
    snip,
    function,
    order,
    knots=None,
    xrange=None,
    clip=CLIP,
    line_kms=LINE_KMS,
    use=None,
    max_order=AUTO_MAX,
):
    """
    Fit a snip's continuum at one order, held through its knots, to its continuum
    pixels (:func:`continuum_pixels`, unless ``use`` gives them).

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    if pix is None:
        raise ContinuumError("The snip's file cannot be read.")
    if xrange is None:
        xrange = _range_for(project, snip, function)
    knots = knots_of(project, snip) if knots is None else knots
    if use is None:
        use = continuum_pixels(
            project, snip, function, knots, xrange, clip, line_kms, max_order
        )
    return fit(
        project.registry,
        function,
        order,
        model_wave(project, snip, pix.wave),
        pix.flux,
        pix.error,
        use,
        xrange,
        _model_knots(project, snip, knots),
        None,
    )


@dataclass
class Guess:
    """
    The fits of every order tried, on the same pixels, and the one chosen.

    Attributes
    ----------
    fits : dict
        Order to :class:`Fit`, each on the snip's continuum pixels.
    best : int
        The order with the lowest BIC.

    Generated by RJC and Claude.
    """

    fits: dict
    best: int

    @property
    def fit(self):
        """The chosen fit (the one a change of order to it would make too)."""
        return self.fits[self.best]

    def table(self, order=None):
        """
        The table of orders (the mockup): for the orders either side of ``order``
        (the chosen one by default), ``(order, χ², Δχ², ΔBIC)`` against it.

        Generated by RJC and Claude.
        """
        order = self.best if order is None else order
        ref = self.fits[order]
        out = []
        for num in (order - 1, order, order + 1):
            if num in self.fits:
                one = self.fits[num]
                out.append((num, one.chi2, one.chi2 - ref.chi2, one.bic - ref.bic))
        return out


def guess(
    project,
    snip,
    function="legendre",
    max_order=AUTO_MAX,
    knots=None,
    clip=CLIP,
    line_kms=LINE_KMS,
    orders=None,
    xrange=None,
):
    """
    The automatic first guess (S8, Q4.6): every order from the least the knots allow
    to ``max_order``, fitted to the same continuum pixels; the one with the lowest
    BIC is chosen.

    Parameters
    ----------
    orders : iterable of int, optional
        The orders to try; by default 0 (or the knots less one) to ``max_order``.

    Returns
    -------
    Guess

    Generated by RJC and Claude.
    """
    knots = knots_of(project, snip) if knots is None else knots
    top = MAX_ORDER[function]
    least = max(len(knots) - 1, 0)
    if orders is None:
        orders = range(least, max(min(max_order, top), least) + 1)
    orders = [o for o in orders if least <= o <= top]
    if function == "constant":
        orders = [0]
    if not orders:
        raise ContinuumError(
            "No order of {0} fits {1} knots.".format(function, len(knots))
        )
    if xrange is None:
        xrange = _range_for(project, snip, function)
    use = continuum_pixels(
        project, snip, function, knots, xrange, clip, line_kms, max_order
    )
    fits = {
        o: fit_snip(project, snip, function, o, knots, xrange, use=use) for o in orders
    }
    best = min(fits, key=lambda o: (fits[o].bic, o))
    return Guess(fits, best)


# -- Writing a continuum line --------------------------------------------------------


def _scaled(coeffs):
    """Each coefficient as a value near unity and a power-of-ten scale."""
    values, scales = [], []
    for coef in coeffs:
        if coef == 0.0 or not np.isfinite(coef):
            values.append(0.0)
            scales.append(1.0)
            continue
        power = 10.0 ** math.floor(math.log10(abs(coef)))
        values.append(coef / power)
        scales.append(power)
    return values, scales


def line_words(fitted, specids, keywords=()):
    """
    The words of a continuum line for a fit.

    Parameters
    ----------
    fitted : Fit
    specids : list of str
    keywords : iterable of str
        Other ``key=value`` words to keep (``blind=True``).

    Returns
    -------
    list of str

    Generated by RJC and Claude.
    """
    words = [fitted.function]
    if fitted.function == "constant":
        words.append(E.format_value(float(fitted.coeffs[0]), 10))
    else:
        values, scales = _scaled(fitted.coeffs)
        words += [E.format_value(v, 10) for v in values]
        words.append("scale=" + ",".join(E.format_value(s) for s in scales))
    words.append("specid=" + ",".join(specids))
    if fitted.function in RANGED and fitted.xrange is not None:
        words.append("min=" + E.format_value(float(fitted.xrange[0]), 12))
        words.append("max=" + E.format_value(float(fitted.xrange[1]), 12))
    words += list(keywords)
    return words


# The widths of a continuum line's function name and values: every continuum the
# dashboard writes is laid out alike, so its text depends only on its words (an order
# up then down gives back the same text) and continua line up with each other
NAME_WIDTH = 10
VALUE_WIDTH = 15


def line_text(words, indent="  "):
    """
    A continuum line in the dashboard's layout: the function and each value in a
    column of its own, then the keywords.

    Generated by RJC and Claude.
    """
    out = indent + words[0].ljust(NAME_WIDTH)
    rest = words[1:]
    values = [w for w in rest if "=" not in w]
    keywords = [w for w in rest if "=" in w]
    for word in values:
        out += "  " + word.ljust(VALUE_WIDTH)
    out = out.rstrip()
    for word in keywords:
        out += "  " + word
    return out


def _indent(pm, line=None):
    """The indentation of model lines: the line's own, else the section's."""
    if line is not None:
        return pm.text[line.line].indent
    for item in pm.lines:
        return pm.text[item.line].indent
    return "  "


def insert_line(pm, words, section="emission"):
    """
    The change that adds a continuum line, in the dashboard's layout, after the last
    line of its section (made if the model lacks it).

    Generated by RJC and Claude.
    """
    change, pm2 = E._ensure_section(pm, section)
    header, end = E.section_lines(pm2, section)
    after = header
    for item in pm2.lines:
        if header < item.line < end:
            after = item.line
    patch = T.insert_lines(pm2.text, after + 1, [line_text(words, _indent(pm2))])
    return change.then(T.Change((patch,), "Add a continuum"))


def _kept_keywords(line):
    return [kw.token.text for name, kw in line.keywords.items() if name not in _OWN]


def _check_free(line):
    """A continuum with labelled coefficients is changed in the ``.mod`` panel."""
    if any(p.label for p in line.params):
        raise ContinuumError(
            "This continuum has tied or fixed coefficients; change it in the .mod"
            " panel."
        )


def write(project, snip, fitted, line=None, specids=None):
    """
    The change that writes a fit as a snip's continuum: its line replaced, keeping
    its other keywords, or a new line added.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    pm = project.parsed
    line = snip.continuum if line is None else line
    if line is None:
        return insert_line(pm, line_words(fitted, specids or [snip.specid]))
    _check_free(line)
    words = line_words(
        fitted, specids or line.specids or [snip.specid], _kept_keywords(line)
    )
    text = line_text(words, _indent(pm, line))
    return T.Change(
        (T.replace_line(pm.text, line.line, text),),
        "Set the continuum of " + snip.specid,
    )


def _step(project, change, description, ui=None):
    step = project.step(change, description)
    if ui is not None:
        step.ui = (copy.deepcopy(project.ui), ui)
    return step


def current(snip):
    """The function and order of a snip's continuum, or Legendre of order 0."""
    line = snip.continuum
    if line is None or line.function not in FUNCTIONS:
        return "legendre", 0
    return line.function, order_of(line)


def auto_step(project, snip, max_order=AUTO_MAX, clip=CLIP, line_kms=LINE_KMS):
    """
    The step that sets a snip's continuum to the first guess (S8).

    Generated by RJC and Claude.
    """
    project.require_reading()
    function = current(snip)[0]
    best = guess(project, snip, function, max_order, clip=clip, line_kms=line_kms)
    return _step(
        project,
        write(project, snip, best.fit),
        "First guess of the continuum of {0} (order {1})".format(
            snip.specid, best.best
        ),
    )


def order_step(project, snip, order, clip=CLIP, line_kms=LINE_KMS, max_order=AUTO_MAX):
    """
    The step that refits a snip's continuum at another order, held through its
    knots (S8, D17).

    Generated by RJC and Claude.
    """
    project.require_reading()
    function, _ = current(snip)
    knots = knots_of(project, snip)
    if order < max(len(knots) - 1, 0):
        raise ContinuumError(
            "The continuum passes through {0} knots, so its order cannot go below"
            " {1}.".format(len(knots), len(knots) - 1)
        )
    if order < 0 or order > MAX_ORDER[function]:
        raise ContinuumError(
            "A {0} can have orders 0 to {1}.".format(function, MAX_ORDER[function])
        )
    one = fit_snip(
        project,
        snip,
        function,
        order,
        clip=clip,
        line_kms=line_kms,
        max_order=max_order,
    )
    return _step(
        project,
        write(project, snip, one),
        "Continuum of {0}: order {1}".format(snip.specid, order),
    )


def function_step(
    project, snip, function, clip=CLIP, line_kms=LINE_KMS, max_order=AUTO_MAX
):
    """
    The step that changes a snip's continuum function, keeping its order where the
    new function allows it (D17).

    Generated by RJC and Claude.
    """
    project.require_reading()
    if function not in FUNCTIONS:
        raise ContinuumError("The continuum can be one of " + ", ".join(FUNCTIONS))
    _, order = current(snip)
    knots = knots_of(project, snip)
    order = max(min(order, MAX_ORDER[function]), max(len(knots) - 1, 0))
    if order > MAX_ORDER[function]:
        raise ContinuumError(
            "A {0} cannot pass through {1} knots.".format(function, len(knots))
        )
    one = fit_snip(
        project,
        snip,
        function,
        order,
        clip=clip,
        line_kms=line_kms,
        max_order=max_order,
    )
    return _step(
        project,
        write(project, snip, one),
        "Continuum of {0}: {1}".format(snip.specid, function),
    )


def knots_step(project, snip, knots, clip=CLIP, line_kms=LINE_KMS, max_order=AUTO_MAX):
    """
    The step that sets a snip's knots (Q4.7, Q4.13), and refits its continuum
    through them, raising the order if the knots need it.

    Parameters
    ----------
    knots : list of (λ, flux)
        In the data's frame.

    Generated by RJC and Claude.
    """
    project.require_reading()
    knots = sorted((float(a), float(b)) for a, b in knots)
    function, order = current(snip)
    if len(knots) - 1 > MAX_ORDER[function]:
        raise ContinuumError(
            "A {0} can pass through at most {1} knots.".format(
                function, MAX_ORDER[function] + 1
            )
        )
    order = max(order, len(knots) - 1)
    ui = copy.deepcopy(project.ui)
    store = ui.setdefault(KNOTS, {})
    if knots:
        store[snip.specid] = [[a, b] for a, b in knots]
    else:
        store.pop(snip.specid, None)
        if not store:
            ui.pop(KNOTS)
    one = fit_snip(
        project,
        snip,
        function,
        order,
        knots=knots,
        clip=clip,
        line_kms=line_kms,
        max_order=max_order,
    )
    count = len(knots)
    return _step(
        project,
        write(project, snip, one),
        "Continuum of {0}: {1} knot{2}".format(
            snip.specid, count, "" if count == 1 else "s"
        ),
        ui,
    )


# -- Sharing a continuum (S10, Q4.8) -------------------------------------------------


def shareable(project, snips):
    """
    Why some snips cannot share one continuum, or ``""`` when they can (Q4.8): they
    must be snips of one transition, in different file rows, and the continuum a
    Legendre.

    Generated by RJC and Claude.
    """
    if len(snips) < 2:
        return "Choose at least two snips."
    trans = L.snip_transitions(project)
    found = {trans.get(s.specid) for s in snips}
    if None in found or len(found) != 1:
        return "Only snips of one transition can share a continuum."
    rows = [s.row.id if s.row is not None else None for s in snips]
    if None in rows or len(set(rows)) != len(rows):
        return "Only snips from different datasets can share a continuum."
    for snip in snips:
        if snip.continuum is not None and snip.continuum.function != "legendre":
            return "Only a Legendre continuum can be shared."
        if snip.pixels is None:
            return "The file of {0} cannot be read.".format(snip.specid)
    return ""


def share_step(project, snips, clip=CLIP, line_kms=LINE_KMS):
    """
    The step that gives snips of one transition in several rows one Legendre, with
    one ``min=``/``max=``: the union of their ranges (S10, Q4.8).

    Generated by RJC and Claude.
    """
    project.require_reading()
    why = shareable(project, snips)
    if why:
        raise ContinuumError(why)
    ranges = [new_range(project, s) for s in snips]
    xrange = (min(r[0] for r in ranges), max(r[1] for r in ranges))
    order = max(current(s)[1] for s in snips)
    xs, fluxes, errors, uses, knots = [], [], [], [], []
    for snip in snips:
        pix = snip.pixels
        xs.append(model_wave(project, snip, pix.wave))
        fluxes.append(pix.flux)
        errors.append(pix.error)
        uses.append(
            continuum_pixels(
                project,
                snip,
                "legendre",
                None,
                new_range(project, snip),
                clip,
                line_kms,
            )
        )
        knots += _model_knots(project, snip, knots_of(project, snip))
    order = max(order, len(knots) - 1)
    one = fit(
        project.registry,
        "legendre",
        order,
        np.concatenate(xs),
        np.concatenate(fluxes),
        np.concatenate(errors),
        np.concatenate(uses),
        xrange,
        knots,
        None,
    )
    pm = project.parsed
    specids = [s.specid for s in snips]
    keep = snips[0].continuum
    patches = []
    removed = []
    for snip in snips:
        line = snip.continuum
        if line is None or line is keep or line.line in removed:
            continue
        _check_free(line)
        rest = [s for s in line.specids if s not in specids]
        if rest:
            patches.append(
                T.replace_token(pm.text, line.keywords["specid"].val, ",".join(rest))
            )
        else:
            patches.append(T.delete_lines(pm.text, line.line))
        removed.append(line.line)
    if keep is not None:
        _check_free(keep)
        words = line_words(one, specids, _kept_keywords(keep))
        patches.append(
            T.replace_line(pm.text, keep.line, line_text(words, _indent(pm, keep)))
        )
        change = T.Change.from_spans(patches, "Share one continuum")
    else:
        change = T.Change.from_spans(patches, "Share one continuum")
        pm2 = E.reread(pm, change)
        change = change.then(insert_line(pm2, line_words(one, specids)))
    return _step(
        project,
        change,
        "Share one continuum: {0}".format(", ".join(specids)),
    )


def unshare_step(project, line, clip=CLIP, line_kms=LINE_KMS):
    """
    The step that gives each snip of a shared continuum its own again, each refitted
    at the same order on its own range (S10).

    Generated by RJC and Claude.
    """
    project.require_reading()
    _check_free(line)
    snips = [s for s in project.snips if s.specid in line.specids]
    if len(snips) < 2:
        raise ContinuumError("This continuum is not shared.")
    pm = project.parsed
    order = order_of(line)
    new_lines = []
    for snip in snips:
        one = fit_snip(
            project,
            snip,
            line.function,
            max(order, len(knots_of(project, snip)) - 1),
            xrange=new_range(project, snip) if line.function in RANGED else None,
            clip=clip,
            line_kms=line_kms,
        )
        words = line_words(one, [snip.specid], _kept_keywords(line))
        new_lines.append(line_text(words, _indent(pm, line)))
    patch = T.replace_lines(pm.text, line.line, line.line + 1, new_lines)
    return _step(
        project,
        T.Change((patch,), "Unshare a continuum"),
        "Unshare the continuum of {0}".format(", ".join(s.specid for s in snips)),
    )


def reexpress(registry, function, coeffs, old_range, new_range_, order):
    """
    The coefficients that give the same curve over a new range (a snip's edge moved):
    exact, since a polynomial of one order stays one on any range.

    Generated by RJC and Claude.
    """
    if function not in RANGED or old_range is None or new_range_ is None:
        return np.asarray(coeffs, dtype=float)
    ncoef = _ncoef(function, order)
    # Chebyshev nodes of the new range
    nodes = np.cos(np.pi * (np.arange(ncoef) + 0.5) / ncoef)
    xs = (
        0.5 * (new_range_[0] + new_range_[1])
        + 0.5 * (new_range_[1] - new_range_[0]) * nodes
    )
    ys = curve(registry, function, coeffs, xs, old_range)
    design = basis(registry, function, xs, order, new_range_)
    return np.linalg.solve(design, ys)


__all__ = [
    "FUNCTIONS",
    "MAX_ORDER",
    "ContinuumError",
    "Fit",
    "Guess",
    "curve",
    "basis",
    "model_wave",
    "data_wave",
    "alis_ranges",
    "coefficients",
    "order_of",
    "xrange_of",
    "evaluate",
    "fit",
    "fit_snip",
    "guess",
    "line_cores",
    "usable",
    "knots_of",
    "new_range",
    "line_words",
    "write",
    "current",
    "auto_step",
    "order_step",
    "function_step",
    "knots_step",
    "shareable",
    "share_step",
    "unshare_step",
    "reexpress",
]
