"""Targeted edits of the model text, used by the panels (dashboard Stage 2.4).

Every action in a panel becomes an edit of the ``.mod`` text (D7, QF.3). Each function
here takes a :class:`~alis.dashboard.model.ParsedModel` and returns a
:class:`~alis.dashboard.text.Change` that touches only what it must: a value's digits,
a label, a keyword, or whole new lines laid out like their neighbours. The text is
then read again, so the parsed model and the project always follow it.

The operations:

- set a value (:func:`set_value`);
- set a parameter free, fixed or tied (S11), by writing its label's case and suffix
  (:func:`fix`, :func:`free`, :func:`tie`, :func:`untie`);
- set and clear limits (S15; :func:`set_limits`, :func:`clear_limits`);
- add, change and remove keywords such as ``blind=True`` and ``specid=``
  (:func:`set_keyword`, :func:`remove_keyword`);
- add a line of a kind: an ion of a component, a continuum, a zero level, a data line
  (:func:`add_ion`, :func:`add_continuum`, :func:`add_zero_level`,
  :func:`add_data_line`);
- set a dataset's FWHM, shift and zero level, and tie rows (D35; :func:`set_fwhm`,
  :func:`set_shift`, :func:`set_zero_level`, :func:`tie_rows`).

New labels follow one scheme (Q2.3): ``z``, ``b`` and ``t``, then the system's letter
and the component's number (``za1``); ``fwhm`` and ``vs`` and the row's number. A label
is upper case when its parameter is fixed (``TA1``). Column densities get no label;
when one is needed, the user names it (RJC, Q2.3), and the operation raises
:class:`LabelNeeded` until it is given.

Generated by RJC and Claude.
"""

import re

from alis.dashboard import model as M
from alis.dashboard import text as T


class EditError(Exception):
    """An edit that cannot be made as asked."""


class LabelNeeded(EditError):
    """
    The edit needs a label for a parameter that has none.

    Attributes
    ----------
    param : Param
        The parameter.
    suggestion : str or None
        A label from the scheme (Q2.3), or None when the user must choose one (a
        column density).

    Generated by RJC and Claude.
    """

    def __init__(self, param, suggestion=None):
        what = "this {0}".format(param.name)
        super().__init__("A label is needed to fix, tie or limit " + what + ".")
        self.param = param
        self.suggestion = suggestion


# -- Values ------------------------------------------------------------------------

_UNSIGNED_EXPONENT = re.compile(r"([eE])(\d)")
_LABEL = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def format_value(value, digits=None):
    """
    Write a value as ALIS reads it.

    A number is written in its shortest exact form, or with ``digits`` significant
    figures, always with a decimal point and with a signed exponent: ALIS reads
    ``1e4`` as the value 1 with the label ``e4`` (``check_tie_label``). Text is
    checked, and an unsigned exponent in it is given a sign.

    Parameters
    ----------
    value : float or str
    digits : int, optional

    Returns
    -------
    str

    Raises
    ------
    EditError
        If the value is not a finite number.

    Generated by RJC and Claude.
    """
    if isinstance(value, str):
        text = value.strip()
        try:
            number = float(text)
        except ValueError:
            raise EditError("'{0}' is not a number.".format(value)) from None
        if number != number or abs(number) == float("inf"):
            raise EditError("'{0}' is not a finite number.".format(value))
        return _UNSIGNED_EXPONENT.sub(r"\1+\2", text)
    number = float(value)
    if number != number or abs(number) == float("inf"):
        raise EditError("{0} is not a finite number.".format(value))
    text = repr(number) if digits is None else "{0:.{1}g}".format(number, digits)
    if "e" in text:
        mant, exp = text.split("e")
        if "." not in mant:
            mant += ".0"
        return "{0}E{1}{2:02d}".format(mant, exp[0], int(exp[1:]))
    if "." not in text:
        text += ".0"
    return text


def check_label(label):
    """
    Check that a label can be written after a value.

    It must start with a letter (or ``_``), and must not be ``e`` or ``E`` followed
    only by digits, which ALIS takes for an exponent.

    Raises
    ------
    EditError

    Generated by RJC and Claude.
    """
    if not _LABEL.match(label or ""):
        raise EditError(
            "'{0}' cannot be a label: use letters, digits and '_',"
            " starting with a letter.".format(label)
        )
    if re.match(r"^[eE][0-9]+$", label):
        raise EditError(
            "'{0}' cannot be a label: ALIS would read it as an exponent.".format(label)
        )


def reread(pm, change):
    """
    The model as it reads after ``change``.

    Generated by RJC and Claude.
    """
    return M.ParsedModel(pm.text.apply(change), pm.registry)


def _places(pm, param):
    """Every place of ``param``'s ALIS parameter (just ``param`` when unlabelled)."""
    if param.label and param.label in pm.labels:
        return list(pm.labels[param.label].params)
    return [param]


def _same(pm, param):
    """``param`` as found again in a re-read model (by its line and slot)."""
    for par in pm.params:
        if par.line == param.line and par.slot == param.slot and par.role == param.role:
            return par
    raise EditError("The parameter was not found after the edit.")


def set_value(pm, param, value, everywhere=True):
    """
    Set the value of a parameter.

    Parameters
    ----------
    pm : ParsedModel
    param : Param
    value : float or str
        A number, or the text the user typed.
    everywhere : bool
        Write the value in every place of the parameter's label, so that they agree
        (ALIS uses the first; the validator warns when they differ).

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    text = format_value(value)
    places = _places(pm, param) if everywhere else [param]
    patches = []
    for par in places:
        if par.value_token is None:
            if par is not param:
                continue
            patches.append(_append_word(pm, par.line, "{0}={1}".format(par.name, text)))
        else:
            patches.append(T.replace_token(pm.text, par.value_token, text))
    return T.Change.from_spans(patches, "Set {0} to {1}".format(param.name, text))


# -- Labels: free, fixed, tied -----------------------------------------------------


def label_uses(pm, name):
    """
    Every word that names a label: its places, its commands and its links.

    Returns
    -------
    list of Token

    Generated by RJC and Claude.
    """
    words = []
    for par in pm.params:
        if par.label == name and par.label_token is not None:
            words.append(par.label_token)
    for cmd in pm.commands:
        if cmd.target == "param" and cmd.name == name:
            words.append(cmd.tokens[2])
    for link in pm.links:
        if link.target == name:
            words.append(link.target_token)
        for tok in link.dep_tokens:
            if tok.text == name:
                words.append(tok)
        line = pm.text[link.line]
        start = line.text.index("=", link.target_token.end) + 1
        for match in re.finditer(
            r"(?<![\w.]){0}(?!\w)".format(re.escape(name)), line.text[start:]
        ):
            col = start + match.start()
            words.append(T.Token(name, link.line, col, col + len(name)))
    return words


def rename_label(pm, old, new):
    """
    Rename a label everywhere it is used: the user's rename, or a change of case.

    Raises
    ------
    EditError
        If ``new`` is already used by another parameter.

    Generated by RJC and Claude.
    """
    check_label(new)
    if new != old and pm.label_uses(new) != ([], [], []):
        raise EditError("The label '{0}' is already used.".format(new))
    patches = [
        T.replace_token(pm.text, tok, new, keep_columns=False)
        for tok in label_uses(pm, old)
    ]
    return T.Change.from_spans(patches, "Rename {0} to {1}".format(old, new))


def _fixed_case(label, fixed):
    """A label in the case that makes it fixed or free."""
    return label.upper() if fixed else label.lower()


def _set_label(pm, param, label):
    """The patch that gives one place of a parameter a label (or none)."""
    if param.value_token is None:
        raise EditError("This {0} is not written on its line.".format(param.name))
    word = param.token
    value = param.value_token
    if param.named:
        key = param.name + "="
        new = key + value.text + label
    else:
        new = value.text + label
    return T.replace_token(pm.text, word, new)


def _ensure_state(pm, change, param, fixed):
    """
    Add a ``fix param`` command when a function-wide ``fix`` overrides the label.

    Generated by RJC and Claude.
    """
    after = reread(pm, change)
    if not after.ok:
        return change
    par = _same(after, param)
    if par.fixed == fixed:
        return change
    if not par.label:
        raise LabelNeeded(param)
    extra = set_command(after, "fix", par.label, "True" if fixed else "False")
    return change.then(extra)


def fix(pm, param, label=None):
    """
    Hold a parameter fixed, by writing its label in upper case (S11).

    Parameters
    ----------
    pm : ParsedModel
    param : Param
    label : str, optional
        A label for a parameter that has none.

    Returns
    -------
    Change

    Raises
    ------
    LabelNeeded
        If the parameter has no label and none is given.

    Generated by RJC and Claude.
    """
    if param.linked:
        raise EditError("This {0} is computed by a link.".format(param.name))
    if param.label:
        new = _fixed_case(param.label, True)
        change = (
            rename_label(pm, param.label, new)
            if new != param.label
            else T.Change((), "")
        )
    else:
        if label is None:
            raise LabelNeeded(param, suggest_label(pm, param))
        new = _fixed_case(label, True)
        check_label(new)
        if pm.label_uses(new) != ([], [], []):
            raise EditError("The label '{0}' is already used.".format(new))
        change = T.Change((_set_label(pm, param, new),), "")
    change = T.Change(change.patches, "Fix " + param.name)
    return _ensure_state(pm, change, param, True)


def free(pm, param):
    """
    Let a parameter vary, by writing its label in lower case (S11).

    A parameter that is fixed because it is not written (voigt's ``damping``) is
    written out, with no label.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    if param.linked:
        raise EditError("This {0} is computed by a link.".format(param.name))
    if param.label:
        new = _fixed_case(param.label, False)
        change = (
            rename_label(pm, param.label, new)
            if new != param.label
            else T.Change((), "")
        )
    elif param.value_token is None:
        word = "{0}={1}".format(param.name, format_value(param.value))
        change = T.Change((_append_word(pm, param.line, word),), "")
    else:
        change = T.Change((), "")
    change = T.Change(change.patches, "Free " + param.name)
    return _ensure_state(pm, change, param, False)


def tie(pm, param, label):
    """
    Tie a parameter to a label: it takes the label, and the label's value (S11).

    Parameters
    ----------
    pm : ParsedModel
    param : Param
    label : str
        A label already in the model.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    if label not in pm.labels:
        raise EditError("There is no parameter labelled '{0}'.".format(label))
    if param.label == label:
        return T.Change((), "")
    if param.value_token is None:
        raise EditError("This {0} is not written on its line.".format(param.name))
    target = pm.labels[label].params[0]
    value = (
        format_value(target.value)
        if target.written is None
        else (target.value_token.text)
    )
    word = (param.name + "=" if param.named else "") + value + label
    patch = T.replace_token(pm.text, param.token, word)
    return T.Change((patch,), "Tie {0} to {1}".format(param.name, label))


def untie(pm, param, label=None):
    """
    Untie one place of a parameter from its label (D20: an ion untied from its
    component).

    A free parameter loses its label unless a new one is given; a fixed one needs a
    label of its own.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    if not param.label:
        return T.Change((), "")
    if label is None and param.fixed:
        raise LabelNeeded(param, suggest_label(pm, param))
    new = "" if label is None else _fixed_case(label, param.fixed)
    if new:
        check_label(new)
        if pm.label_uses(new) != ([], [], []):
            raise EditError("The label '{0}' is already used.".format(new))
    return T.Change((_set_label(pm, param, new),), "Untie " + param.name)


# -- The label scheme (Q2.3) -------------------------------------------------------

COMPONENT_PREFIX = {"redshift": "z", "bturb": "b", "temperature": "t"}


def used_labels(pm):
    """Every label in the model, in lower case."""
    names = set(pm.labels)
    names |= {c.name for c in pm.commands if c.target == "param"}
    for link in pm.links:
        names |= {link.target, *link.deps}
    return {n.lower() for n in names}


def new_component(pm, letter):
    """
    The labels of a new component of the system with this letter (Q2.3).

    Returns
    -------
    dict
        ``{"redshift": "za1", "bturb": "ba1", "temperature": "ta1"}``, with the
        first number that none of the three uses yet.

    Generated by RJC and Claude.
    """
    used = used_labels(pm)
    num = 1
    while any(
        "{0}{1}{2}".format(p, letter, num) in used for p in COMPONENT_PREFIX.values()
    ):
        num += 1
    return {
        name: "{0}{1}{2}".format(p, letter, num) for name, p in COMPONENT_PREFIX.items()
    }


def new_row_labels(pm, number):
    """
    The FWHM and shift labels of a dataset row (Q2.3): ``fwhm2`` and ``vs2``.

    Generated by RJC and Claude.
    """
    used = used_labels(pm)
    num = number
    while "fwhm{0}".format(num) in used or "vs{0}".format(num) in used:
        num += 1
    return {"resolution": "fwhm{0}".format(num), "shift": "vs{0}".format(num)}


def suggest_label(pm, param):
    """
    A label from the scheme for a parameter, or None for a column density (Q2.3).

    Generated by RJC and Claude.
    """
    if param.role == "resolution":
        return new_row_labels(pm, 1)["resolution"]
    if param.role == "shift":
        return new_row_labels(pm, 1)["shift"]
    if param.name in COMPONENT_PREFIX:
        return new_component(pm, "x")[param.name]
    return None


# -- Commands and limits -----------------------------------------------------------


def _model_header_end(pm):
    """The line after ``model read`` and the commands that follow it."""
    opened, _ = pm.text.block_lines("model")
    last = opened
    for line in pm.text.lines[opened + 1 :]:
        if line.kind in (T.FIX, T.LIM):
            last = line.num
        elif line.kind in (T.SECTION, T.FUNCTION, T.BLOCK):
            break
    return last + 1


def _command_line(pm, words):
    """A new command line, laid out like the model's other commands."""
    template = None
    for cmd in pm.commands:
        template = pm.text[cmd.line]
    if template is None:
        section = pm.text.of_kind(T.SECTION)
        indent = section[0].indent if section else " "
        return indent + " ".join(words)
    return T.layout_like(template, words)


def set_command(pm, kind, label, value):
    """
    Set a ``fix param`` or ``lim param`` command for a label.

    An existing command for the label has its value replaced; otherwise a new line is
    added after the model's other commands.

    Parameters
    ----------
    pm : ParsedModel
    kind : str
        ``"fix"`` or ``"lim"``.
    label : str
    value : str
        ``"True"``, ``"False"`` or a number for ``fix``; ``"[low,high]"`` for ``lim``.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    for cmd in pm.commands:
        if cmd.kind == kind and cmd.target == "param" and cmd.name == label:
            patch = T.replace_token(pm.text, cmd.tokens[3], value)
            return T.Change((patch,), "{0} {1}".format(kind, label))
    line = _command_line(pm, [kind, "param", label, value])
    patch = T.insert_lines(pm.text, _model_header_end(pm), [line])
    return T.Change((patch,), "{0} {1}".format(kind, label))


def _limit_text(value):
    return "None" if value is None else format_value(value)


def set_limits(pm, param, low, high, label=None):
    """
    Limit a parameter to ``[low, high]`` (S15), with a ``lim param`` command.

    Parameters
    ----------
    pm : ParsedModel
    param : Param
    low, high : float or None
        None for no limit on that side.
    label : str, optional
        A label for a parameter that has none (the change then also writes it).

    Returns
    -------
    Change

    Raises
    ------
    LabelNeeded
        If the parameter has no label and none is given.

    Generated by RJC and Claude.
    """
    value = "[{0},{1}]".format(_limit_text(low), _limit_text(high))
    if param.label:
        return set_command(pm, "lim", param.label, value)
    if label is None:
        raise LabelNeeded(param, suggest_label(pm, param))
    new = _fixed_case(label, param.fixed)
    check_label(new)
    if pm.label_uses(new) != ([], [], []):
        raise EditError("The label '{0}' is already used.".format(new))
    first = T.Change((_set_label(pm, param, new),), "")
    after = reread(pm, first)
    return first.then(set_command(after, "lim", new, value))


def clear_limits(pm, param):
    """
    Remove the ``lim param`` commands of a parameter's label (S15).

    Function-wide limits (``lim voigt bturb ...``) stay.

    Generated by RJC and Claude.
    """
    lines = [
        c.line
        for c in pm.commands
        if c.kind == "lim" and c.target == "param" and c.name == param.label
    ]
    patches = [T.delete_lines(pm.text, num) for num in lines]
    return T.Change.from_spans(patches, "Clear the limits of " + param.name)


# -- Keywords ----------------------------------------------------------------------


def _append_word(pm, num, word):
    """The patch that adds a word after the last word of a line's content."""
    line = pm.text[num]
    toks = line.tokens
    gap = toks[-1].start - toks[-2].end if len(toks) > 1 else 2
    gap = max(gap, 1)
    return T.Patch(pm.text.offset(num, line.content[1]), "", " " * gap + word)


def set_keyword(pm, item, name, value):
    """
    Set ``name=value`` on a line, replacing the value if the keyword is there.

    Parameters
    ----------
    pm : ParsedModel
    item : ModelLine or DataLine
    name, value : str

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    kw = item.keywords.get(name)
    if kw is not None:
        patch = T.replace_token(pm.text, kw.val, value)
    else:
        patch = _append_word(pm, item.line, "{0}={1}".format(name, value))
    return T.Change((patch,), "Set {0}={1}".format(name, value))


def remove_keyword(pm, item, name):
    """
    Remove a keyword from a line, with the space before it.

    Generated by RJC and Claude.
    """
    kw = item.keywords.get(name)
    if kw is None:
        return T.Change((), "")
    line = pm.text[item.line]
    toks = line.tokens
    pos = toks.index(kw.token)
    start = toks[pos - 1].end if pos > 0 else kw.token.start
    old = line.text[start : kw.token.end]
    patch = T.Patch(pm.text.offset(item.line, start), old, "")
    return T.Change((patch,), "Remove " + name)


def set_specids(pm, item, specids):
    """
    Set the specids a model line applies to (``specid=A,B``).

    Generated by RJC and Claude.
    """
    return set_keyword(pm, item, "specid", ",".join(specids))


def set_blind(pm, item, on=True):
    """
    Blind a model line, or not (D24): ``blind=True``.

    Generated by RJC and Claude.
    """
    return set_keyword(pm, item, "blind", "True" if on else "False")


# -- New lines ---------------------------------------------------------------------


def section_lines(pm, section):
    """
    The lines of a section: ``(header, end)``, or None when there is no section.

    ``end`` is the line after the section's last line (the next section, or
    ``model end``).

    Generated by RJC and Claude.
    """
    header = None
    for line in pm.text.lines:
        if header is None:
            if line.kind == T.SECTION and line.words[0] == section:
                header = line.num
        elif line.kind == T.SECTION or (
            line.kind == T.BLOCK and line.words[:2] == ["model", "end"]
        ):
            return header, line.num
    return None if header is None else (header, len(pm.text))


def _ensure_section(pm, section):
    """
    The change that adds a section header if the model lacks it, and the model
    after it.

    The sections are kept in ALIS's order: emission, absorption, zerolevel.

    Generated by RJC and Claude.
    """
    if section_lines(pm, section) is not None:
        return T.Change((), ""), pm
    order = T.SECTIONS
    before = None
    for later in order[order.index(section) + 1 :]:
        span = section_lines(pm, later)
        if span is not None:
            before = span[0]
            break
    if before is None:
        before = pm.text.block_lines("model")[1]
    headers = pm.text.of_kind(T.SECTION)
    indent = headers[0].indent if headers else " "
    patch = T.insert_lines(pm.text, before, [indent + section])
    change = T.Change((patch,), "")
    return change, reread(pm, change)


def _insert_in_section(pm, section, words, after=None, template=None):
    """
    Insert a new model line into a section, laid out like its neighbours.

    Parameters
    ----------
    after : int, optional
        Insert after this line; by default after the section's last model line.
    template : Line, optional
        The line to copy the layout of; by default the nearest model line of the
        same function.

    Generated by RJC and Claude.
    """
    change, pm2 = _ensure_section(pm, section)
    header, end = section_lines(pm2, section)
    if after is not None and change:
        after = change.map_line(pm.text, after)
    if after is None:
        after = header
        for item in pm2.lines:
            if header < item.line < end:
                after = item.line
    if template is None:
        same = [pm2.text[i.line] for i in pm2.lines if i.function == words[0]]
        near = [ln for ln in same if ln.num <= after] or same
        template = near[-1] if near else None
    if template is None:
        headers = pm2.text.of_kind(T.SECTION)
        indent = (headers[0].indent if headers else " ") + " "
        line = indent + "  ".join(words)
    else:
        line = T.layout_like(template, words)
    patch = T.insert_lines(pm2.text, after + 1, [line])
    return change.then(T.Change((patch,), ""))


def _param_word(value, label="", fixed=None):
    """A parameter's word: its value and its label."""
    if label and fixed is not None:
        label = _fixed_case(label, fixed)
    return format_value(value) + (label or "")


def add_ion(
    pm,
    ion,
    coldens,
    redshift,
    bturb,
    temperature,
    specids,
    labels=None,
    fixed=None,
    keywords=(),
    after=None,
):
    """
    Add a ``voigt`` line: an ion of a component (D20).

    Parameters
    ----------
    pm : ParsedModel
    ion : str
        The ion, such as ``16O_I``.
    coldens, redshift, bturb, temperature : float
        The starting values.
    specids : list of str
        The snips it applies to.
    labels : dict, optional
        Labels by parameter name (``"redshift"``, ``"bturb"``, ``"temperature"``,
        and ``"ColDens"`` if the user named one), e.g. from :func:`new_component`.
    fixed : dict, optional
        Whether each labelled parameter is fixed, by name; the label's case follows.
    keywords : iterable of str
        Other keywords, such as ``blind=True``.
    after : int, optional
        Add it after this line (the component's last line).

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    labels = labels or {}
    fixed = fixed or {}
    values = {
        "ColDens": coldens,
        "redshift": redshift,
        "bturb": bturb,
        "temperature": temperature,
    }
    words = ["voigt", "ion=" + ion]
    for name, value in values.items():
        words.append(_param_word(value, labels.get(name, ""), fixed.get(name)))
    words.append("specid=" + ",".join(specids))
    words += list(keywords)
    if after is None:
        zlab = labels.get("redshift")
        same = [
            i.line
            for i in pm.function_lines("voigt", "absorption")
            if zlab
            and i.param("redshift") is not None
            and i.param("redshift").label.lower() == zlab.lower()
        ]
        after = same[-1] if same else None
    change = _insert_in_section(pm, "absorption", words, after=after)
    return T.Change(change.patches, "Add " + ion)


def add_continuum(
    pm, specid, coefficients, function="legendre", scale=None, keywords=()
):
    """
    Add a continuum for a snip (D17): ``legendre c0 c1 ... scale=... specid=``.

    Parameters
    ----------
    pm : ParsedModel
    specid : str
    coefficients : list of float
    function : str
        The polynomial: ``legendre``, ``chebyshev`` or ``polynomial``.
    scale : list of float, optional
        The ``scale=`` factors, one per coefficient.
    keywords : iterable of str

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    words = [function] + [format_value(c) for c in coefficients]
    if scale is not None:
        words.append("scale=" + ",".join(format_value(s) for s in scale))
    words.append("specid=" + specid)
    words += list(keywords)
    change = _insert_in_section(pm, "emission", words)
    return T.Change(change.patches, "Add a continuum for " + specid)


def add_zero_level(pm, specids, value=0.0, label=""):
    """
    Add a zero level (D14): ``constant <value> specid=...`` in the zerolevel section.

    Generated by RJC and Claude.
    """
    words = ["constant", _param_word(value, label), "specid=" + ",".join(specids)]
    change = _insert_in_section(pm, "zerolevel", words)
    return T.Change(change.patches, "Add a zero level")


def add_data_line(
    pm,
    path,
    specid,
    fitrange,
    resolution=None,
    shift=None,
    columns=None,
    keywords=(),
    after=None,
):
    """
    Add a data line: one snip.

    Parameters
    ----------
    pm : ParsedModel
    path : str
        The snip's file, as written on the line (relative to ``run datadirc``).
    specid : str
    fitrange : str
        ``"columns"``, ``"all"`` or ``"[low,high]"``.
    resolution, shift : str, optional
        The functions, e.g. ``"vfwhm(7.0FWHM1)"`` and ``"vshift(0.0vs2)"``.
    columns : str, optional
        e.g. ``"[wave:0,flux:1,error:2,fitrange:3]"``.
    keywords : iterable of str
    after : int, optional
        Add it after this line; by default after the last data line.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    words = [path, "specid=" + specid, "fitrange=" + fitrange]
    if resolution:
        words.append("resolution=" + resolution)
    if shift:
        words.append("shift=" + shift)
    if columns:
        words.append("columns=" + columns)
    words += list(keywords)
    if after is None:
        after = pm.data[-1].line if pm.data else pm.text.block_lines("data")[0]
    near = [pm.text[d.line] for d in pm.data if d.line <= after] or [
        pm.text[d.line] for d in pm.data
    ]
    template = near[-1] if near else None
    line = T.layout_like(template, words) if template else "  " + "  ".join(words)
    patch = T.insert_lines(pm.text, after + 1, [line])
    return T.Change((patch,), "Add the data line " + specid)


# -- Datasets (D35) ----------------------------------------------------------------


def _function_word(name, value, label):
    return "{0}({1})".format(name, format_value(value) + (label or ""))


def set_fwhm(pm, rows, value):
    """
    Set the FWHM of a dataset row: every data line of the row (D35).

    Parameters
    ----------
    pm : ParsedModel
    rows : list of DataLine
        The row's data lines.
    value : float

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    text = format_value(value)
    patches, done = [], set()
    for item in rows:
        par = item.param("resolution")
        if par is not None and par.value_token is not None:
            for place in _places(pm, par):
                if place.value_token is not None and id(place) not in done:
                    done.add(id(place))
                    patches.append(T.replace_token(pm.text, place.value_token, text))
        else:
            word = "resolution=" + _function_word("vfwhm", value, "")
            patches.append(_append_word(pm, item.line, word))
    return T.Change.from_spans(patches, "Set the FWHM to " + text)


def set_shift(pm, rows, value, label=None):
    """
    Set the velocity shift of a dataset row (D35).

    Data lines that have no shift get ``shift=vshift(<value><label>)``.

    Parameters
    ----------
    pm : ParsedModel
    rows : list of DataLine
    value : float
    label : str, optional
        The label for lines that have no shift yet, e.g. from :func:`new_row_labels`.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    text = format_value(value)
    patches, done = [], set()
    for item in rows:
        par = item.param("shift")
        if item.shift is not None and par is not None and par.value_token is not None:
            for place in _places(pm, par):
                if place.value_token is not None and id(place) not in done:
                    done.add(id(place))
                    patches.append(T.replace_token(pm.text, place.value_token, text))
        else:
            word = "shift=" + _function_word("vshift", value, label or "")
            patches.append(_append_word(pm, item.line, word))
    return T.Change.from_spans(patches, "Set the shift to " + text)


def zero_level_line(pm, specids):
    """
    The zero-level ``constant`` whose specids include all of ``specids``, or None.

    Generated by RJC and Claude.
    """
    for item in pm.function_lines("constant", "zerolevel"):
        if set(specids) <= set(item.specids):
            return item
    return None


def set_zero_level(pm, specids, value):
    """
    Set a dataset's zero level (D14); None switches it off.

    An existing ``constant`` of the zerolevel section that covers the specids has its
    value set; switching it off removes the line, or the specids from it when it
    covers others too.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    item = zero_level_line(pm, specids)
    if value is None:
        if item is None:
            return T.Change((), "")
        rest = [s for s in item.specids if s not in specids]
        if rest:
            return set_specids(pm, item, rest)
        return T.Change((T.delete_lines(pm.text, item.line),), "Remove a zero level")
    if item is None:
        return add_zero_level(pm, specids, value)
    return set_value(pm, item.params[0], value)


def tie_rows(pm, rows_from, rows_to, what):
    """
    Tie a row's FWHM, shift or zero level to another row's (D35, Q0.8).

    Parameters
    ----------
    pm : ParsedModel
    rows_from : list of DataLine
        The row to tie: it takes the other row's label and value.
    rows_to : list of DataLine
        The row it is tied to.
    what : str
        ``"resolution"``, ``"shift"`` or ``"zerolevel"``.

    Returns
    -------
    Change

    Generated by RJC and Claude.
    """
    if what == "zerolevel":
        return _tie_zero_levels(pm, rows_from, rows_to)
    target = None
    for item in rows_to:
        target = item.param(what)
        if target is not None and target.value_token is not None:
            break
    if target is None or target.value_token is None:
        raise EditError("The row to tie to has no {0} written.".format(what))
    if not target.label:
        raise LabelNeeded(target, suggest_label(pm, target))
    word = target.value_token.text + target.label
    name = "vfwhm" if what == "resolution" else "vshift"
    patches = []
    for item in rows_from:
        par = item.param(what)
        call = item.resolution if what == "resolution" else item.shift
        if (
            par is not None
            and par.token is not None
            and call is not None
            and (len(call.args) == 1)
        ):
            patches.append(T.replace_token(pm.text, par.token, word))
        elif what in item.keywords:
            patches.append(
                T.replace_token(
                    pm.text, item.keywords[what].val, "{0}({1})".format(call.name, word)
                )
            )
        else:
            patches.append(
                _append_word(pm, item.line, "{0}={1}({2})".format(what, name, word))
            )
    return T.Change.from_spans(patches, "Tie the {0}".format(what))


def _tie_zero_levels(pm, rows_from, rows_to):
    """One zero level for both rows: the second row's specids join the first's."""
    sids_from = [r.specid for r in rows_from]
    sids_to = [r.specid for r in rows_to]
    target = zero_level_line(pm, sids_to)
    if target is None:
        raise EditError("The row to tie to has no zero level.")
    own = zero_level_line(pm, sids_from)
    change = set_specids(
        pm, target, target.specids + [s for s in sids_from if s not in target.specids]
    )
    if own is not None and own is not target:
        rest = [s for s in own.specids if s not in sids_from]
        if rest:
            second = set_specids(pm, own, rest)
        else:
            second = T.Change((T.delete_lines(pm.text, own.line),), "")
        change = T.Change.from_spans(
            list(change.patches) + list(second.patches), "Tie the zero level"
        )
    return change


__all__ = [
    "EditError",
    "LabelNeeded",
    "format_value",
    "check_label",
    "reread",
    "set_value",
    "label_uses",
    "rename_label",
    "fix",
    "free",
    "tie",
    "untie",
    "new_component",
    "new_row_labels",
    "suggest_label",
    "used_labels",
    "set_command",
    "set_limits",
    "clear_limits",
    "set_keyword",
    "remove_keyword",
    "set_specids",
    "set_blind",
    "section_lines",
    "add_ion",
    "add_continuum",
    "add_zero_level",
    "add_data_line",
    "set_fwhm",
    "set_shift",
    "zero_level_line",
    "set_zero_level",
    "tie_rows",
]
