"""Undo and redo: one history for the panels and the .mod panel (F2, Stage 2.8).

Every change to a project is a :class:`~alis.dashboard.project.Step`: a change to the
text, to a file (a snip's mask), to ``ui/project.json`` or to the hidden lines, which
can be undone exactly. A :class:`History` makes the steps and keeps them:

- **one history** for everything, whether done in a panel or typed in the ``.mod``
  panel;
- **typing is grouped**: steps of kind ``"typing"`` that follow each other with no
  pause longer than :attr:`History.pause` seconds become one step;
- **a drag is one step**: every step made inside ``with history.group(...)`` is joined
  into one;
- the history lives only while the project is open and is **not saved** in the bundle
  (Q2.8); autosave keeps the work (F1, Stage 3);
- **blinding** (Stage 3, Q3.13, Q3.14): with a guard
  (:class:`~alis.dashboard.blinding.Guard`), a step that would show a hidden value
  is undone and refused, and **undo stops** at a step that hides something, since
  undoing it would show what it hid;
- **tab markers** (Stage 3.8): with a tracker
  (:class:`~alis.dashboard.markers.Tracker`), a step that edits the components
  also records the fingerprints of the regions and components in
  ``ui/project.json``, as part of the same step.

Generated by RJC and Claude.
"""

import time
from contextlib import contextmanager

from alis.dashboard.project import Step

# Typing that pauses for longer than this, in seconds, starts a new step
PAUSE = 1.0
# The most steps kept; the oldest are forgotten
LIMIT = 1000


class History:
    """
    The undo and redo history of one project.

    Parameters
    ----------
    project : Project
    pause : float
        Typing steps closer together than this (seconds) are joined.
    limit : int
        The most steps kept.
    guard : Guard, optional
        Refuses steps that show a hidden value, and finds those that hide one.
    tracker : Tracker, optional
        Adds the markers' fingerprints to the steps that edit the components.

    Attributes
    ----------
    floor : int
        Undo stops at this many steps: the steps up to it include one that hid
        something.

    Generated by RJC and Claude.
    """

    def __init__(self, project, pause=PAUSE, limit=LIMIT, guard=None, tracker=None):
        self.project = project
        self.pause = pause
        self.limit = limit
        self.guard = guard
        self.tracker = tracker
        self.done = []
        self.undone = []
        self.floor = 0
        self._group = None
        self._group_barrier = False
        self._depth = 0
        self._last = None

    # -- making steps ---------------------------------------------------------------

    def do(self, step, kind=None, now=None):
        """
        Make a step, and record it.

        Parameters
        ----------
        step : Step
        kind : str, optional
            ``"typing"`` joins the step to the previous typing step, if it follows it
            within :attr:`pause` seconds.
        now : float, optional
            The time of the step (by default the clock's).

        Returns
        -------
        Step
            The step as made, with the markers' fingerprints when a tracker added
            them.

        Raises
        ------
        RevealError
            If the guard refuses the step; it has been undone.

        Generated by RJC and Claude.
        """
        snap = self.guard.snapshot() if self.guard is not None else None
        marks = self.tracker.before(self.project) if self.tracker is not None else None
        self.project.apply(step)
        barrier = False
        if self.guard is not None:
            try:
                barrier = self.guard.check(snap, step)
            except Exception:
                self.project.revert(step)
                raise
        if self.tracker is not None:
            extra = self.tracker.after(self.project, marks)
            if extra is not None:
                self.project.apply(extra)
                step = step.then(extra)
        self.record(step, kind, now, barrier)
        return step

    def edit(self, change, description="", kind=None, now=None):
        """
        Make a change to the text as a step (an edit of :mod:`~alis.dashboard.edit`,
        or typing in the ``.mod`` panel), and record it.

        Generated by RJC and Claude.
        """
        return self.do(self.project.step(change, description), kind, now)

    def type(self, change, now=None):
        """Typing in the ``.mod`` panel: an edit of kind ``"typing"``."""
        return self.edit(change, "Typing", kind="typing", now=now)

    def record(self, step, kind=None, now=None, barrier=False):
        """
        Record a step that has been made.

        Parameters
        ----------
        barrier : bool
            The step hid something: undo stops at it.

        Generated by RJC and Claude.
        """
        if not step:
            return
        now = time.monotonic() if now is None else now
        self.undone.clear()
        if self._group is not None:
            self._group = self._group.then(step)
            self._group_barrier = self._group_barrier or barrier
            return
        last = self._last
        if (
            kind == "typing"
            and last is not None
            and last[0] == "typing"
            and now - last[1] <= self.pause
            and len(self.done) > self.floor
        ):
            self.done[-1] = self.done[-1].then(step)
        else:
            self._append(step)
        if barrier:
            self.floor = len(self.done)
        self._last = (kind, now)

    def _append(self, step):
        """Keep a new step, forgetting the oldest beyond the limit."""
        self.done.append(step)
        if len(self.done) > self.limit:
            del self.done[0]
            self.floor = max(0, self.floor - 1)

    @contextmanager
    def group(self, description):
        """
        Join every step made inside into one step: a drag (F2).

        Groups may be nested; the outermost makes the step.

        Generated by RJC and Claude.
        """
        self.begin(description)
        try:
            yield self
        finally:
            self.end()

    def begin(self, description):
        """Start joining steps into one."""
        if self._depth == 0:
            self._group = Step(description)
            self._group_barrier = False
        self._depth += 1

    def end(self):
        """
        Stop joining steps, and record the joined step.

        Generated by RJC and Claude.
        """
        self._depth -= 1
        if self._depth > 0:
            return
        step, self._group = self._group, None
        self._last = None
        if step:
            self._append(step)
            self.undone.clear()
            if self._group_barrier:
                self.floor = len(self.done)

    # -- undoing --------------------------------------------------------------------

    def can_undo(self):
        """Whether there is a step to undo (undo stops at :attr:`floor`)."""
        return len(self.done) > self.floor and self._group is None

    def can_redo(self):
        """Whether there is a step to redo."""
        return bool(self.undone) and self._group is None

    def undo(self):
        """
        Undo the last step, and return it (None if there is none).

        Generated by RJC and Claude.
        """
        if not self.can_undo():
            return None
        step = self.done.pop()
        self.project.revert(step)
        self.undone.append(step)
        self._last = None
        return step

    def redo(self):
        """
        Make the last undone step again, and return it (None if there is none).

        Generated by RJC and Claude.
        """
        if not self.can_redo():
            return None
        step = self.undone.pop()
        self.project.apply(step)
        self.done.append(step)
        self._last = None
        return step

    def undo_description(self):
        """What undo would undo, for the menu ("Undo Set ColDens to 14.2")."""
        return self.done[-1].description if self.can_undo() else ""

    def redo_description(self):
        """What redo would make again."""
        return self.undone[-1].description if self.undone else ""

    def clear(self):
        """
        Forget every step (after unblinding, Q2.11).

        Generated by RJC and Claude.
        """
        self.done.clear()
        self.undone.clear()
        self.floor = 0
        self._group = None
        self._group_barrier = False
        self._depth = 0
        self._last = None


__all__ = ["History", "PAUSE", "LIMIT"]
