"""Transitions, line IDs, flags and coverage (dashboard Stage 4.1; S2, S5, D36).

No Qt: the Data and Regions tabs ask this module what to list and what to label, and
draw what it says.

- **Lines.** Every transition of ALIS's atomic table that belongs to a chemical
  element, with its ion, element, stage, rest wavelength and f-value. The transition
  list folds isotopes into their element: it lists the main isotope's transitions
  only, since D I is fitted in H I's snips (D36).
- **Where the data are.** A :class:`Coverage` holds the pixels of one file row: those
  of its source spectrum, or those of its snips when it has none (D12). Its good
  pixels (finite, with a positive error, not marked bad) form segments; a jump in
  wavelength splits them.
- **The transition list** (S2, D36): the transitions of one ion that fall on the
  data, ranked by fλ, with lines closer together than the resolution in one row
  ("O I 971.7 ×3"), flagged "gap" (no good pixels there) or "edge" (closer to an end
  of the data than a snip's half-width); no forest or telluric flags (Q4.5). A
  transition that already has a snip is listed whatever its flags.
- **Line IDs** (S5, Q4.4): for every system, the transitions of its ions (in the
  model, or named as its line IDs), the strong lines (by fλ and the solar abundance,
  as ``prepfit`` ranks them), or every line; and the number left unlabelled.
- **Identify a feature** (S24, D35): the transitions that could make a feature at a
  clicked wavelength, each with the redshift it implies.
- **Coverage** (Q0.5): which transitions of a system each file row has a snip of, or
  covers.
- **Snips' transitions:** the transition each snip was cut for, as SNIP records it
  in ``ui/project.json``, or guessed from its file name and its extent.

Generated by RJC and Claude.
"""

import posixpath
import re
from dataclasses import dataclass, field

import numpy as np

from alis.dashboard import project as P

C_KMS = 299792.458
# The rest wavelengths of Lyman alpha and of the Lyman limit, in Å
LYA = 1215.6701
LYMAN_LIMIT = 911.7536
# The Lyman lines with Greek names, by the upper level of the transition
GREEK = {2: "α", 3: "β", 4: "γ", 5: "δ", 6: "ε"}
# The chemical elements, in order of atomic number
SYMBOLS = (
    "H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu"
    " Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs"
    " Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl"
    " Pb Bi Po At Rn Fr Ra Ac Th Pa U"
).split()
# Solar abundances, log ε with H = 12 (Asplund et al. 2009), the table
# ``alis/prepfit/specplot.py`` ranks lines with
SOLAR = {
    "H": 12.0,
    "He": 10.93,
    "Li": 3.26,
    "Be": 1.30,
    "B": 2.79,
    "C": 8.43,
    "N": 7.83,
    "O": 8.69,
    "F": 4.42,
    "Ne": 7.93,
    "Na": 6.26,
    "Mg": 7.56,
    "Al": 6.44,
    "Si": 7.51,
    "P": 5.42,
    "S": 7.14,
    "Cl": 5.23,
    "Ar": 6.40,
    "K": 5.06,
    "Ca": 6.29,
    "Sc": 3.05,
    "Ti": 4.91,
    "V": 3.95,
    "Cr": 5.64,
    "Mn": 5.48,
    "Fe": 7.47,
    "Co": 4.93,
    "Ni": 6.21,
    "Cu": 4.25,
    "Zn": 4.63,
}
_ROMAN = {"I": 1, "V": 5, "X": 10}

# Defaults, which the preferences override (Stage 4)
# Half the width of a new snip, in km/s; a line closer than this to an end of the
# data is flagged "edge" (Q4.2)
HALF_WIDTH = 300.0
# A line is labelled as strong above this expected strength,
# log10(f λ) + log ε − 12 (Q4.4)
STRONG = -2.0
# Lines of one ion closer than this, in km/s, share one row of the list (D36): the
# resolution, when the rows do not give their own
GROUP_KMS = 7.0
# A step between good pixels of this many times the median step splits the data
SPLIT = 5.0
# A transition named in a snip's file name: ``_H_I_923.2_``, or ``_O_I_988_``
_NAMED = re.compile(r"_(\d*)([A-Z][a-z]?)_([IVX]+\**)_(\d+(?:\.\d+)?)(?=[_.])")


# -- The lines of the atomic table --------------------------------------------------


def roman(stage):
    """
    The number of an ionisation stage: ``"IV"`` is 4; ``"II*"`` is 2, its excited
    levels after it.

    Generated by RJC and Claude.
    """
    digits = stage.rstrip("*")
    total = 0
    for k, char in enumerate(digits):
        value = _ROMAN.get(char, 0)
        nxt = _ROMAN.get(digits[k + 1], 0) if k + 1 < len(digits) else 0
        total += -value if value < nxt else value
    return total + 0.1 * (len(stage) - len(digits))


def line_name(element, stage, rest):
    """
    A transition as people write it: ``Lyβ 1025.7`` for the Lyman lines, otherwise
    ``O I 1302.2``.

    Generated by RJC and Claude.
    """
    if element in ("H", "D") and stage == "I" and LYMAN_LIMIT < rest < 1216.0:
        upper = int(round(1.0 / np.sqrt(1.0 - LYMAN_LIMIT / rest)))
        lyman = "Ly" + GREEK.get(upper, "{0:d}".format(upper - 1))
        if element == "D":
            lyman = "D " + lyman
        return "{0} {1:.1f}".format(lyman, rest)
    return "{0} {1} {2:.1f}".format(element, stage, rest)


@dataclass(frozen=True)
class Line:
    """
    One transition of the atomic table.

    Attributes
    ----------
    ion : str
        ALIS's name for the ion, such as ``16O_I`` or ``2H_I``.
    element : str
        The chemical symbol (``O``; ``D`` for deuterium).
    stage : str
        The ionisation stage, such as ``I`` or ``II*``.
    rest : float
        The rest wavelength in Å.
    fval : float
        The oscillator strength.
    main : bool
        Whether it is a transition of the element's main isotope.

    Generated by RJC and Claude.
    """

    ion: str
    element: str
    stage: str
    rest: float
    fval: float
    main: bool = True

    @property
    def flam(self):
        """f λ, the list's ranking (S2)."""
        return self.fval * self.rest

    @property
    def strength(self):
        """
        The expected strength, ``log10(f λ) + log ε − 12`` with the solar abundance
        ε, or None for an element with no abundance in the table (Q4.4).
        """
        abundance = SOLAR.get("H" if self.element == "D" else self.element)
        if abundance is None or self.flam <= 0.0:
            return None
        return float(np.log10(self.flam)) + abundance - 12.0

    @property
    def name(self):
        """``O I 1302.2``, or ``Lyβ 1025.7``."""
        return line_name(self.element, self.stage, self.rest)


class Atomic:
    """
    The lines of an atomic table that belong to chemical elements.

    Parameters
    ----------
    registry : alis.dashboard.model.Registry

    Attributes
    ----------
    lines : list of Line
        Every such line, of every isotope, by ion and then by wavelength.
    by_ion : dict
        Lines by ion.
    main_ion : dict
        The main isotope's ion of each ``(element, stage)``: ``("O", "I")`` gives
        ``16O_I``.

    Generated by RJC and Claude.
    """

    def __init__(self, registry):
        atomic = registry.atomic
        ions = np.asarray(atomic["Ion"]).astype(str)
        waves = np.asarray(atomic["Wavelength"]).astype(float)
        fvals = np.asarray(atomic["fvalue"]).astype(float)
        masses = {}
        rows = []
        for ion, wave, fval in zip(ions, waves, fvals):
            if ion in P.GENERIC_IONS:
                continue
            mass, element, stage = P.split_ion(ion)
            if mass is None or mass <= 0 or element not in SYMBOLS:
                continue
            if not np.isfinite(wave) or not np.isfinite(fval) or fval <= 0.0:
                continue
            rows.append((ion, mass, element, stage, float(wave), float(fval)))
            masses.setdefault(element, []).append(mass)
        main_mass = {}
        for element, found in masses.items():
            main = P.MAIN_ISOTOPE.get(element)
            main_mass[element] = (
                main if main in found else int(np.bincount(found).argmax())
            )
        self.lines, self.by_ion, self.main_ion = [], {}, {}
        for ion, mass, element, stage, wave, fval in sorted(
            rows, key=lambda r: (r[0], r[4])
        ):
            main = mass == main_mass[element]
            shown = "D" if (element == "H" and mass == 2) else element
            line = Line(ion, shown, stage, wave, fval, main)
            self.lines.append(line)
            self.by_ion.setdefault(ion, []).append(line)
            if main:
                self.main_ion[(element, stage)] = ion

    def ion_lines(self, ion):
        """The lines of an ion, by wavelength."""
        return list(self.by_ion.get(ion, []))

    def main_lines(self):
        """The lines of every element's main isotope."""
        return [ln for ln in self.lines if ln.main]

    def stages(self, element):
        """The stages of an element's main isotope, in order."""
        found = {s for (e, s) in self.main_ion if e == element}
        return sorted(found, key=roman)


_ATOMIC = {}


def atomic(registry):
    """
    The :class:`Atomic` lines of a registry, made once.

    Generated by RJC and Claude.
    """
    key = id(registry.atomic)
    if key not in _ATOMIC:
        if len(_ATOMIC) > 8:
            _ATOMIC.clear()
        _ATOMIC[key] = (registry.atomic, Atomic(registry))
    return _ATOMIC[key][1]


# -- Where the data are --------------------------------------------------------------


def good_pixels(wave, flux, error, bad=None):
    """
    The pixels that can be fitted: finite, with a positive error, and not marked bad
    (S7, Q4.11).

    Generated by RJC and Claude.
    """
    wave = np.asarray(wave, dtype=float)
    flux = np.asarray(flux, dtype=float)
    error = np.asarray(error, dtype=float)
    with np.errstate(invalid="ignore"):
        good = np.isfinite(wave) & np.isfinite(flux) & np.isfinite(error) & (error > 0)
    if bad is not None:
        good &= ~np.asarray(bad, dtype=bool)
    return good


def segments(wave, good, split=SPLIT):
    """
    The runs of good pixels, as wavelength ranges ``[(low, high), ...]``: a step of
    more than ``split`` times the median step between good pixels ends a run.

    Generated by RJC and Claude.
    """
    wave = np.sort(np.asarray(wave, dtype=float)[np.asarray(good, dtype=bool)])
    if wave.size == 0:
        return []
    if wave.size == 1:
        return [(float(wave[0]), float(wave[0]))]
    step = np.diff(wave)
    positive = step[step > 0]
    median = float(np.median(positive)) if positive.size else 0.0
    breaks = np.flatnonzero(step > split * median) if median > 0 else []
    starts = np.concatenate(([0], np.asarray(breaks) + 1))
    stops = np.concatenate((np.asarray(breaks), [wave.size - 1]))
    return [(float(wave[a]), float(wave[b])) for a, b in zip(starts, stops)]


@dataclass
class Coverage:
    """
    Where one file row has data (D35): its pixels, and the runs of good pixels.

    Attributes
    ----------
    row : str
        The row's id.
    name : str
    wave : numpy.ndarray
    good : numpy.ndarray
        Which pixels can be fitted.
    source : bool
        True for the row's source spectrum, False for its snips (D12).
    runs : list of (low, high)

    Generated by RJC and Claude.
    """

    row: str
    name: str
    wave: np.ndarray = field(repr=False)
    good: np.ndarray = field(repr=False)
    source: bool = True
    runs: list = field(default_factory=list, repr=False)

    def __post_init__(self):
        if not self.runs:
            self.runs = segments(self.wave, self.good)

    @property
    def span(self):
        """The wavelength range of the row's pixels, or None."""
        if not self.runs:
            return None
        return self.runs[0][0], self.runs[-1][1]

    def run_at(self, wave):
        """The run of good pixels that holds a wavelength, or None."""
        for low, high in self.runs:
            if low <= wave <= high:
                return low, high
        return None

    def room(self, wave):
        """
        How far, in km/s, a wavelength is from the nearer end of its run of good
        pixels; None when it is not on a run.

        Generated by RJC and Claude.
        """
        run = self.run_at(wave)
        if run is None:
            return None
        return C_KMS * min(wave - run[0], run[1] - wave) / wave


def coverage_of_spectrum(row, name, spectrum):
    """
    A row's coverage from its source spectrum (a ``modes.Spectrum``).

    Generated by RJC and Claude.
    """
    good = good_pixels(spectrum.wave, spectrum.flux, spectrum.error, spectrum.mask)
    return Coverage(row, name, np.asarray(spectrum.wave, dtype=float), good, True)


def coverage_of_snips(row):
    """
    A row's coverage from its snips, for a row with no source spectrum (D12).

    Generated by RJC and Claude.
    """
    waves, goods = [], []
    for snip in row.snips:
        pix = snip.pixels
        if pix is None:
            continue
        waves.append(pix.wave)
        goods.append(good_pixels(pix.wave, pix.flux, pix.error, snip_bad(snip)))
    if not waves:
        return Coverage(row.id, row.name, np.zeros(0), np.zeros(0, bool), False)
    wave = np.concatenate(waves)
    good = np.concatenate(goods)
    # The snips' runs, kept apart: two snips do not make one run
    runs = []
    for wav, gd in zip(waves, goods):
        runs += segments(wav, gd)
    runs.sort()
    return Coverage(row.id, row.name, wave, good, False, runs)


def snip_bad(snip):
    """
    A snip's bad-pixel mask (its ``badpix`` column, Q4.17), or None when it has none:
    then every pixel is good (Q4.15).

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    return None if pix is None else getattr(pix, "bad", None)


def place(wave, coverages, half_width=HALF_WIDTH):
    """
    Whether a wavelength falls on the data, and its flags (S2, Q4.5).

    Returns
    -------
    tuple
        ``(on_data, flags)``: on the data when a row has good pixels there; flagged
        ``"gap"`` when none has, and ``"edge"`` when every row that has is closer
        than ``half_width`` km/s to an end of its run of good pixels.

    Generated by RJC and Claude.
    """
    best = None
    for cov in coverages:
        room = cov.room(wave)
        if room is not None and (best is None or room > best):
            best = room
    if best is None:
        return False, ("gap",)
    return True, (("edge",) if best < half_width else ())


# -- The transition list (S2, D36) ---------------------------------------------------


@dataclass
class Transition:
    """
    One row of the transition list: a line, or lines of one ion closer than the
    resolution (D36).

    Attributes
    ----------
    system : str
        The id of the system it is listed for.
    z : float
    ion : str
    element, stage : str
    rest : float
        The rest wavelength of its strongest line.
    flam : float
        f λ, summed over its lines.
    members : tuple of float
        The rest wavelengths of its lines.
    on_data : bool
    flags : tuple of str
    snipped : bool
        It has a snip (● in the list).

    Generated by RJC and Claude.
    """

    system: str
    z: float
    ion: str
    element: str
    stage: str
    rest: float
    flam: float
    members: tuple = ()
    on_data: bool = True
    flags: tuple = ()
    snipped: bool = False

    @property
    def observed(self):
        """Its observed wavelength at the system's redshift, in Å."""
        return self.rest * (1.0 + self.z)

    @property
    def name(self):
        """``Lyβ 1025.7``, or ``O I 971.7 ×3`` for several lines."""
        base = line_name(self.element, self.stage, self.rest)
        return (
            base if len(self.members) < 2 else base + " ×{0}".format(len(self.members))
        )

    def has(self, rest, tol=0.01):
        """Whether one of its lines has this rest wavelength (to ``tol`` Å)."""
        return any(abs(m - rest) <= tol for m in self.members)


def group_lines(lines, group_kms=GROUP_KMS):
    """
    Lines of one ion grouped where they are closer than ``group_kms`` (D36).

    Returns
    -------
    list of list of Line

    Generated by RJC and Claude.
    """
    groups = []
    for line in sorted(lines, key=lambda ln: ln.rest):
        if groups and C_KMS * (line.rest - groups[-1][0].rest) / line.rest < group_kms:
            groups[-1].append(line)
        else:
            groups.append([line])
    return groups


def transitions(
    lines,
    z,
    coverages,
    snipped=(),
    system="",
    group_kms=GROUP_KMS,
    half_width=HALF_WIDTH,
):
    """
    The transition list of one ion (S2, D36): its transitions that fall on the data,
    and any that has a snip, ranked by f λ.

    Parameters
    ----------
    lines : list of Line
        The ion's lines (its main isotope's).
    z : float
        The system's redshift.
    coverages : list of Coverage
    snipped : iterable of float
        Rest wavelengths of this ion that have a snip, for this system.
    system : str
    group_kms, half_width : float

    Returns
    -------
    list of Transition

    Generated by RJC and Claude.
    """
    snipped = list(snipped)
    out = []
    for group in group_lines(lines, group_kms):
        top = max(group, key=lambda ln: ln.fval)
        on_data, flags = place(top.rest * (1.0 + z), coverages, half_width)
        row = Transition(
            system,
            z,
            top.ion,
            top.element,
            top.stage,
            top.rest,
            sum(ln.flam for ln in group),
            tuple(ln.rest for ln in group),
            on_data,
            flags,
        )
        row.snipped = any(row.has(s) for s in snipped)
        if on_data or row.snipped:
            out.append(row)
    out.sort(key=lambda r: -r.flam)
    return out


def ion_transitions(
    atom, element, stage, z, coverages, snipped=(), system="", **kwargs
):
    """
    The transition list of an element's ion stage, from its main isotope (D36).

    Generated by RJC and Claude.
    """
    ion = atom.main_ion.get((element, stage))
    if ion is None:
        return []
    return transitions(atom.ion_lines(ion), z, coverages, snipped, system, **kwargs)


def elements_on_data(atom, z, coverages, snipped=None, half_width=HALF_WIDTH):
    """
    The elements, and their stages, with a transition on the data or a snip, in
    order of atomic number (D36: only these are offered).

    Parameters
    ----------
    snipped : dict, optional
        Rest wavelengths with a snip, by ion.

    Returns
    -------
    dict
        Element to its list of stages.

    Generated by RJC and Claude.
    """
    snipped = snipped or {}
    found = {}
    for (element, stage), ion in atom.main_ion.items():
        if ion in snipped and snipped[ion]:
            found.setdefault(element, set()).add(stage)
            continue
        for line in atom.ion_lines(ion):
            if place(line.rest * (1.0 + z), coverages, half_width)[0]:
                found.setdefault(element, set()).add(stage)
                break
    order = {s: k for k, s in enumerate(SYMBOLS)}
    return {
        e: sorted(found[e], key=roman)
        for e in sorted(found, key=lambda e: order.get(e, 999))
    }


# -- Line IDs (S5, Q4.4) -------------------------------------------------------------

HYDROGEN, METAL, OTHER = "hydrogen", "metal", "other"


@dataclass
class LineID:
    """
    A labelled line at its observed wavelength (S5).

    Attributes
    ----------
    observed : float
    label : str
        ``O I 1302.2``; a generic absorber's is ``Lyα forest``.
    kind : str
        ``"hydrogen"`` (H I or D I of the reference system), ``"metal"`` (its other
        ions) or ``"other"`` (another system, or a generic absorber), as the key
        colours them.
    system : str
        The system's id, or ``""`` for a generic absorber.
    ion : str
    rest : float

    Generated by RJC and Claude.
    """

    observed: float
    label: str
    kind: str
    system: str
    ion: str
    rest: float


def system_ions(system):
    """
    The ions a system labels in full: its model's and those of its line IDs (Q4.4).

    Generated by RJC and Claude.
    """
    found = list(system.ions)
    for entry in system.lines:
        ion = entry.get("ion")
        if ion and ion not in found:
            found.append(ion)
    return found


def line_ids(
    project,
    low,
    high,
    reference=None,
    show_all=False,
    strong=STRONG,
    group_kms=GROUP_KMS,
    systems=None,
):
    """
    The line IDs between two observed wavelengths (S5, Q4.4).

    Every system labels the transitions of its ions (in the model, or named as its
    line IDs) and its strong lines; with ``show_all``, every line. Generic absorbers
    label their own lines. The lines left unlabelled are counted, so that the user can
    see that there are more ("+ 23 lines not labelled").

    Parameters
    ----------
    project : Project
    low, high : float
        The observed range, in Å.
    reference : str, optional
        The id of the system whose lines are ``"hydrogen"`` and ``"metal"``; the
        primary by default.
    show_all : bool
    strong : float
        The expected strength above which a line is labelled.
    group_kms : float
        Lines of one ion closer than this share one label.
    systems : list of System, optional
        The systems to label; every system of the project by default.

    Returns
    -------
    tuple
        ``(ids, hidden)``: the :class:`LineID` in order of wavelength, and how many
        lines in the range are not labelled.

    Generated by RJC and Claude.
    """
    atom = atomic(project.registry)
    systems = project.systems if systems is None else systems
    if reference is None:
        reference = next((s.id for s in systems if s.primary), None)
    ids, hidden = [], 0
    for system in systems:
        named = set(system_ions(system))
        own = system.id == reference
        factor = 1.0 + system.z
        for ion, lines in _labelled_ions(atom, named).items():
            for group in group_lines(lines, group_kms):
                top = max(group, key=lambda ln: ln.fval)
                obs = top.rest * factor
                if not low <= obs <= high:
                    continue
                main = top.main
                strong_enough = main and (top.strength or -99.0) >= strong
                if show_all or ion in named or strong_enough:
                    kind = (
                        (HYDROGEN if top.element in ("H", "D") else METAL)
                        if own
                        else OTHER
                    )
                    label = top.name + (
                        " ×{0}".format(len(group)) if len(group) > 1 else ""
                    )
                    ids.append(LineID(obs, label, kind, system.id, ion, top.rest))
                else:
                    hidden += 1
    for line in project.absorbers:
        zpar = line.param("redshift")
        if zpar is None:
            continue
        waves, _ = project.registry.transitions(line.ion)
        for rest in waves:
            obs = float(rest) * (1.0 + zpar.start)
            if low <= obs <= high:
                name = (
                    "Lyα forest"
                    if line.ion == "1Ly_a"
                    else (line_name("H", "I", float(rest)) + " blend")
                )
                ids.append(LineID(obs, name, OTHER, "", line.ion, float(rest)))
    ids.sort(key=lambda i: i.observed)
    return ids, hidden


def _labelled_ions(atom, named):
    """
    The ions whose lines are labelled or counted: every main isotope, and the other
    isotopes a system names (D I of a D/H fit).

    Generated by RJC and Claude.
    """
    out = {}
    for line in atom.lines:
        if line.main or line.ion in named:
            out.setdefault(line.ion, []).append(line)
    return out


# -- Identify a feature (S24, D35) ---------------------------------------------------


@dataclass
class Candidate:
    """
    A transition that could make a feature at a clicked wavelength.

    Attributes
    ----------
    line : Line
    z : float
        The redshift it implies, ``λ / λ₀ − 1``.

    Generated by RJC and Claude.
    """

    line: Line
    z: float

    @property
    def name(self):
        """``Lyβ 1025.7``."""
        return self.line.name


def identify(atom, wave, data_max=None, systems_z=(), near_kms=500.0):
    """
    The transitions that could make a feature at ``wave``, with the redshift each
    implies; only those giving z ≥ 0 (S24, D35).

    Parameters
    ----------
    atom : Atomic
    wave : float
        The clicked wavelength, in Å.
    data_max : float, optional
        The reddest wavelength of the data: the first choice is the strongest
        transition whose system's Lyα would fall at or below it ("within the data's
        Lyα reach").
    systems_z : iterable of float
        The redshifts of the systems already known: a transition that puts the click
        within ``near_kms`` of one of them is the first choice (the user is
        refining a redshift, as the mockup shows), the strongest such.
    near_kms : float

    Returns
    -------
    tuple
        ``(candidates, first)``: the candidates, strongest first, and the index of
        the first choice (None when there is none).

    Generated by RJC and Claude.
    """
    found = []
    for line in atom.main_lines():
        if line.rest <= wave:
            found.append(Candidate(line, wave / line.rest - 1.0))
    found.sort(key=lambda c: -(c.line.strength if c.line.strength is not None else -99))
    first = None
    for k, cand in enumerate(found):
        if any(abs(C_KMS * (cand.z - z) / (1.0 + z)) <= near_kms for z in systems_z):
            return found, k
    for k, cand in enumerate(found):
        if cand.line.strength is None:
            continue
        if data_max is None or (1.0 + cand.z) * LYA <= data_max * (1.0 + 1.0e-9):
            first = k
            break
    if first is None and found:
        first = 0
    return found, first


def candidate_menus(candidates):
    """
    The candidates as the three menus of Identify a feature: element → stage →
    transitions (D35). Elements come H first, then by solar abundance; transitions
    strongest first.

    Returns
    -------
    dict
        ``{element: {stage: [Candidate, ...]}}``, in menu order.

    Generated by RJC and Claude.
    """
    tree = {}
    for cand in candidates:
        line = cand.line
        tree.setdefault(line.element, {}).setdefault(line.stage, []).append(cand)
    order = {s: k for k, s in enumerate(SYMBOLS)}

    def elem_key(elem):
        return (elem != "H", -SOLAR.get(elem, -99.0), order.get(elem, 999))

    out = {}
    for elem in sorted(tree, key=elem_key):
        out[elem] = {
            stage: sorted(tree[elem][stage], key=lambda c: -c.line.flam)
            for stage in sorted(tree[elem], key=roman)
        }
    return out


# -- The transitions of the snips ------------------------------------------------------


@dataclass(frozen=True)
class SnipTransition:
    """
    The transition a snip was cut for.

    Attributes
    ----------
    system : str
        The system's id, or ``""`` when no system has it.
    ion : str
    rest : float

    Generated by RJC and Claude.
    """

    system: str
    ion: str
    rest: float


SNIPS_KEY = "snips"


def snip_transitions(project):
    """
    The transition of each snip, by specid: as SNIP records it in
    ``ui/project.json``, or else guessed (from the transition its file name names,
    or the transition of a system's ions nearest the snip's middle).

    Returns
    -------
    dict
        Specid to :class:`SnipTransition`, or None for a snip whose transition is
        not known.

    Generated by RJC and Claude.
    """
    atom = atomic(project.registry)
    recorded = project.ui.get(SNIPS_KEY, {})
    out = {}
    for snip in project.snips:
        rec = recorded.get(snip.specid)
        if rec and rec.get("ion") and rec.get("rest") is not None:
            out[snip.specid] = SnipTransition(
                rec.get("system", ""), rec["ion"], float(rec["rest"])
            )
        else:
            out[snip.specid] = _guess_transition(project, atom, snip)
    return out


def _guess_transition(project, atom, snip):
    """
    The transition of a snip that SNIP did not record (an imported fit).

    Generated by RJC and Claude.
    """
    extent = snip.extent
    if extent is None:
        return None
    middle = 0.5 * (extent[0] + extent[1])
    base = posixpath.basename(snip.data.file.text)
    match = _NAMED.search(base)
    if match:
        element, stage, text = match.group(2), match.group(3), match.group(4)
        named = float(text)
        ion = atom.main_ion.get((element, stage))
        if "." in text:
            # Named to a tenth of an Å: the nearest line
            near = [
                ln for ln in atom.ion_lines(ion or "") if abs(ln.rest - named) <= 0.06
            ]
            pick = min(near, key=lambda ln: abs(ln.rest - named)) if near else None
        else:
            # Named in whole Å (``_O_I_988_``): the strongest line it may mean
            near = [
                ln
                for ln in atom.ion_lines(ion or "")
                if int(ln.rest) == int(named) or round(ln.rest) == int(named)
            ]
            pick = max(near, key=lambda ln: ln.fval) if near else None
        if pick is not None:
            line = pick
            best = None
            for system in project.systems:
                obs = line.rest * (1.0 + system.z)
                if extent[0] <= obs <= extent[1]:
                    gap = abs(obs - middle)
                    if best is None or gap < best[0]:
                        best = (gap, system.id)
            return SnipTransition(best[1] if best else "", line.ion, line.rest)
    best = None
    for system in project.systems:
        for ion in system.ions:
            for line in atom.ion_lines(ion):
                obs = line.rest * (1.0 + system.z)
                if extent[0] <= obs <= extent[1]:
                    gap = abs(obs - middle)
                    if best is None or gap < best[0]:
                        best = (gap, SnipTransition(system.id, line.ion, line.rest))
    return best[1] if best else None


def snipped_by_ion(snip_map, system):
    """
    The rest wavelengths with a snip for one system, by ion.

    Generated by RJC and Claude.
    """
    out = {}
    for trans in snip_map.values():
        if trans is not None and trans.system == system:
            out.setdefault(trans.ion, []).append(trans.rest)
    return out


# -- Coverage (Q0.5) -----------------------------------------------------------------

SNIP, COVERED, NONE = "snip", "covered", "none"


@dataclass
class GridRow:
    """
    One transition of the coverage grid, and its cell for each file row.

    Attributes
    ----------
    ion : str
    rest : float
    name : str
    cells : dict
        Row id to ``"snip"`` (■ it has a snip), ``"covered"`` (□ its source covers
        it, with no snip yet) or ``"none"`` (· not covered).

    Generated by RJC and Claude.
    """

    ion: str
    rest: float
    name: str
    cells: dict = field(default_factory=dict)


def coverage_grid(project, system, coverages, snip_map=None, half_width=HALF_WIDTH):
    """
    The coverage grid of a system (Q0.5): one row per transition that has a snip or
    is named among its line IDs, by rest wavelength; one cell per file row.

    Parameters
    ----------
    project : Project
    system : System
    coverages : list of Coverage
        One per file row.
    snip_map : dict, optional
        From :func:`snip_transitions`.

    Returns
    -------
    list of GridRow

    Generated by RJC and Claude.
    """
    atom = atomic(project.registry)
    snip_map = snip_transitions(project) if snip_map is None else snip_map
    wanted = {}
    for specid, trans in snip_map.items():
        if trans is not None and trans.system == system.id:
            wanted[(trans.ion, round(trans.rest, 3))] = trans.rest
    for entry in system.lines:
        if entry.get("ion") and entry.get("wave") is not None:
            wanted[(entry["ion"], round(float(entry["wave"]), 3))] = float(
                entry["wave"]
            )
    by_row = {}
    for snip in project.snips:
        trans = snip_map.get(snip.specid)
        if trans is not None and trans.system == system.id and snip.row is not None:
            by_row.setdefault(snip.row.id, set()).add((trans.ion, round(trans.rest, 3)))
    out = []
    for key, rest in sorted(wanted.items(), key=lambda kv: kv[1]):
        ion = key[0]
        mass, element, stage = P.split_ion(ion)
        name = line_name(
            "D" if (element == "H" and mass == 2) else element, stage, rest
        )
        row = GridRow(ion, rest, name)
        for cov in coverages:
            if key in by_row.get(cov.row, set()):
                row.cells[cov.row] = SNIP
            elif cov.source and place(rest * (1.0 + system.z), [cov], half_width)[0]:
                row.cells[cov.row] = COVERED
            else:
                row.cells[cov.row] = NONE
        out.append(row)
    return out


__all__ = [
    "Line",
    "Atomic",
    "atomic",
    "line_name",
    "roman",
    "Coverage",
    "coverage_of_spectrum",
    "coverage_of_snips",
    "good_pixels",
    "segments",
    "snip_bad",
    "place",
    "Transition",
    "group_lines",
    "transitions",
    "ion_transitions",
    "elements_on_data",
    "LineID",
    "line_ids",
    "system_ions",
    "Candidate",
    "identify",
    "candidate_menus",
    "SnipTransition",
    "snip_transitions",
    "snipped_by_ion",
    "GridRow",
    "coverage_grid",
    "HALF_WIDTH",
    "STRONG",
    "GROUP_KMS",
    "HYDROGEN",
    "METAL",
    "OTHER",
    "SNIP",
    "COVERED",
    "NONE",
]
