"""Tab markers: whether each tab's step is complete, out of date, or needs attention.

Dashboard Stage 3.8 (F12, D34; Q3.6). Each tab shows a marker with an icon and a
colour, and a tooltip that says why:

====== ================= ============================= ======================== =========
Tab    ○ not started     ! needs attention             ↻ out of date            ✓
====== ================= ============================= ======================== =========
Data   no file rows      a source missing or changed;  —                        otherwise
                         the structure inferred and
                         not yet confirmed
Regions no snips         a snip with no fitted pixels; —                        otherwise
                         pixels fitted twice
Comp.  no components     a notice (untied ions,        the regions changed      otherwise
                         isotopes)                     after the components
                                                       were last edited
Fit    no run            the last run stopped with an  the model changed since  otherwise
                         error                         the latest run (Q2.9)
Plot   always (built after v1)
====== ================= ============================= ======================== =========

"The regions changed after the components" is found from two fingerprints that the
project keeps in ``ui/project.json`` (``marks``): one of the components, and one of
the regions taken whenever the components are edited. :class:`Tracker` updates them
as part of the step that edits the components, so that undo restores them too.

Generated by RJC and Claude.
"""

import hashlib
import json
from dataclasses import dataclass

import numpy as np

from alis import bundle as B
from alis import load
from alis.dashboard import sources as SR
from alis.dashboard import validate as V

NONE, ATTENTION, STALE, COMPLETE = "none", "attention", "stale", "complete"
ICONS = {COMPLETE: "✓", STALE: "↻", ATTENTION: "!", NONE: "○"}
MARKS = "marks"


@dataclass(frozen=True)
class Marker:
    """
    One tab's marker.

    Attributes
    ----------
    state : str
        ``"none"`` (○), ``"attention"`` (!), ``"stale"`` (↻) or ``"complete"`` (✓).
    tip : str
        Why, in a sentence, for the tab's tooltip.

    Generated by RJC and Claude.
    """

    state: str
    tip: str

    @property
    def icon(self):
        """The marker's icon."""
        return ICONS[self.state]


# -- The fingerprints of the regions and of the components --------------------------


def regions_fingerprint(project):
    """
    A fingerprint of the regions: each snip's file and fitted range.

    Generated by RJC and Claude.
    """
    digest = hashlib.sha256()
    for snip in project.snips:
        content = project.files.get(snip.member, b"")
        digest.update(
            json.dumps(
                [
                    snip.specid,
                    snip.member,
                    hashlib.sha1(content).hexdigest(),
                    snip.data.keyword("fitrange"),
                    snip.data.keyword("columns"),
                ]
            ).encode("utf-8")
        )
    return digest.hexdigest()


def components_fingerprint(project):
    """
    A fingerprint of the components: the lines of the absorption section.

    Generated by RJC and Claude.
    """
    digest = hashlib.sha256()
    pm = project.parsed
    for item in pm.lines:
        if item.section == "absorption":
            digest.update(pm.text[item.line].text.strip().encode("utf-8") + b"\n")
    return digest.hexdigest()


def has_components(project):
    """Whether the project has any component or generic absorber."""
    return bool(project.components or project.absorbers)


class Tracker:
    """
    Keeps the fingerprints of ``ui/project.json`` up to date, as part of each step
    (the history calls it).

    Generated by RJC and Claude.
    """

    def before(self, project):
        """
        The fingerprints before a step: ``(components, regions)``, or None while the
        text does not read.

        Generated by RJC and Claude.
        """
        if project.paused:
            return None
        return components_fingerprint(project), regions_fingerprint(project)

    def after(self, project, before):
        """
        The step that records the fingerprints, when a step has edited the
        components (or the project has none recorded yet and the regions changed);
        None otherwise.

        Generated by RJC and Claude.
        """
        if before is None or project.paused or not has_components(project):
            return None
        comps, regions = components_fingerprint(project), regions_fingerprint(project)
        marks = project.ui.get(MARKS)
        if marks is None:
            if comps == before[0] and regions == before[1]:
                return None
            # The regions as they were when the components were last edited: before
            # this step, unless this step edited the components
            new = {"components": comps, "regions": regions}
            if comps == before[0]:
                new["regions"] = before[1]
        elif marks.get("components") != comps:
            new = {"components": comps, "regions": regions}
        else:
            return None
        data = dict(project.ui)
        data[MARKS] = new
        return project.set_ui(data, "Note the components' regions")


# -- The rules -----------------------------------------------------------------------


def _plural(num, word):
    return "{0} {1}{2}".format(num, word, "" if num == 1 else "s")


def data_marker(project, path=None):
    """
    The Data tab's marker.

    Generated by RJC and Claude.
    """
    if not project.rows:
        return Marker(NONE, "No spectra or snips yet.")
    bad = SR.problems(project.bundle, path)
    if bad:
        return Marker(ATTENTION, " ".join(SR.describe(e, s) for e, s in bad))
    if project.inferred:
        return Marker(
            ATTENTION,
            "The datasets and systems were worked out from the model: check them,"
            " then confirm them.",
        )
    nsnips = sum(len(r.snips) for r in project.rows)
    return Marker(
        COMPLETE,
        "{0}, {1}.".format(
            _plural(len(project.rows), "file row"), _plural(nsnips, "snip")
        ),
    )


def _fitted(snip):
    """The snip's fitted pixels, as a boolean array, or None if unknown."""
    if snip.pixels is None:
        return None
    return V._fitted(snip.data, snip.pixels)


def regions_marker(project):
    """
    The Regions tab's marker.

    Generated by RJC and Claude.
    """
    if not project.snips:
        return Marker(NONE, "No snips yet.")
    empty, arrays, names = [], [], []
    for snip in project.snips:
        fitted = _fitted(snip)
        if fitted is None:
            continue
        if not fitted.any():
            empty.append(snip.specid)
            continue
        px = snip.pixels
        arrays.append((px.wave[fitted], px.flux[fitted], px.error[fitted]))
        names.append(snip.specid)
    if empty:
        return Marker(
            ATTENTION,
            "No pixels are fitted in {0}: {1}.".format(
                "this snip" if len(empty) == 1 else "these snips", ", ".join(empty)
            ),
        )
    shared = load.find_shared_pixels(arrays) if len(arrays) > 1 else []
    if shared:
        pairs = [
            "{0} and {1} ({2} pixels)".format(names[i], names[j], len(idx))
            for i, j, idx, _ in shared[:3]
        ]
        more = len(shared) - len(pairs)
        return Marker(
            ATTENTION,
            "Pixels are fitted twice: {0}{1}.".format(
                "; ".join(pairs), "; and {0} more".format(more) if more else ""
            ),
        )
    return Marker(COMPLETE, "{0}.".format(_plural(len(project.snips), "snip")))


def components_marker(project):
    """
    The Components tab's marker.

    Generated by RJC and Claude.
    """
    if not has_components(project):
        return Marker(NONE, "No components yet.")
    notices = [n for n in project.notices if n.kind in ("untied", "isotopes")]
    if notices:
        extra = len(notices) - 1
        return Marker(
            ATTENTION,
            notices[0].message
            + (" ({0} more.)".format(_plural(extra, "notice")) if extra else ""),
        )
    marks = project.ui.get(MARKS)
    if marks is not None and marks.get("regions") != regions_fingerprint(project):
        return Marker(
            STALE, "The regions have changed since the components were last edited."
        )
    return Marker(
        COMPLETE, "{0}.".format(_plural(len(project.components), "component"))
    )


def _run_info(project):
    data = project.bundle.members.get(B.LATEST + "run.json")
    return None if data is None else json.loads(data.decode("utf-8"))


def fit_marker(project):
    """
    The Fit tab's marker.

    Generated by RJC and Claude.
    """
    info = _run_info(project)
    error = project.bundle.members.get(B.LAST_ERROR)
    error = None if error is None else json.loads(error.decode("utf-8"))
    if error is not None and (
        info is None or error.get("time", "") > info.get("finished", "")
    ):
        message = (error.get("message") or "").strip().splitlines()
        return Marker(
            ATTENTION,
            "The last run stopped with an error"
            + (": " + message[0] if message else "."),
        )
    if info is None:
        return Marker(NONE, "No fit has run yet.")
    if "model_sha256" not in info:
        # The outputs of an imported fit: which model made them is not known
        return Marker(
            COMPLETE,
            "The outputs of an earlier run, found beside the model when it was"
            " imported.",
        )
    if project.model_changed_since_run():
        return Marker(STALE, "The model has changed since the latest run.")
    chi2 = info.get("chi2_final")
    where = info.get("host", "")
    when = info.get("finished", "")[:16].replace("T", " ")
    text = "The latest run ({0})".format(info.get("status", "completed"))
    if chi2 is not None and np.isfinite(chi2):
        text += ", χ² = {0:.6g}".format(chi2)
    if when:
        text += ", finished {0}".format(when)
    if where:
        text += " on {0}".format(where)
    return Marker(COMPLETE, text + ".")


def plot_marker():
    """The Plot tab is built after v1."""
    return Marker(NONE, "Not yet available")


def markers(project, path=None):
    """
    Every tab's marker.

    Parameters
    ----------
    project : Project
    path : str, optional
        The bundle, for finding source spectra beside it.

    Returns
    -------
    dict
        Tab name to :class:`Marker`.

    Generated by RJC and Claude.
    """
    return {
        "Data": data_marker(project, path),
        "Regions": regions_marker(project),
        "Components": components_marker(project),
        "Fit": fit_marker(project),
        "Plot": plot_marker(),
    }


__all__ = [
    "Marker",
    "Tracker",
    "markers",
    "data_marker",
    "regions_marker",
    "components_marker",
    "fit_marker",
    "plot_marker",
    "regions_fingerprint",
    "components_fingerprint",
    "NONE",
    "ATTENTION",
    "STALE",
    "COMPLETE",
    "ICONS",
    "MARKS",
]
