"""Modes as plug-ins, and QSO Abs Line mode (F11, dashboard Stage 2.10).

A mode supplies five things (F11):

- a **data loader**, which reads a spectrum with its column roles (D13, S3);
- a **builder for the display spectrum**, the spectrum the user draws regions on;
- a **mapper from regions to fitted data**, which turns the regions drawn on the
  display spectrum into the fit masks of the snips;
- a **model template**, which makes a new project;
- **plot presets** for the Plot tab (D28, after v1).

**QSO Abs Line mode** is the only mode built now (named Voigt mode until
Stage 3, Q3.17). Each dataset is its own display spectrum,
and a region drawn on it maps straight onto the mask of the snip cut from it. Orders
mode, where the display spectrum is combined from many echelle orders and a region
is applied to every order (D29–D32), comes after v1 as a second :class:`Mode`.

Generated by RJC and Claude.
"""

import io
import json
import os
from dataclasses import dataclass, field

import numpy as np

import alis
from alis import bundle as B
from alis import load
from alis.dashboard import align as AL
from alis.dashboard import edit as E
from alis.dashboard import model as M
from alis.dashboard import preferences as PR
from alis.dashboard import project as P

C_KMS = 299792.458


class ModeError(Exception):
    """A mode cannot do what it was asked."""


@dataclass
class Spectrum:
    """
    A spectrum as a mode loads it.

    Attributes
    ----------
    wave, flux, error : numpy.ndarray
    mask : numpy.ndarray or None
        The bad-pixel mask, as booleans (True for a pixel to leave out of the fit),
        when the file has one.
    path : str
    columns : dict
        The role of each column used: ``{"wave": 0, "flux": 1, ...}``.
    notes : list of str
        What the user should be told (a continuum multiplied in, D13).

    Generated by RJC and Claude.
    """

    wave: np.ndarray
    flux: np.ndarray
    error: np.ndarray
    mask: np.ndarray | None = None
    path: str = ""
    columns: dict = field(default_factory=dict)
    notes: list = field(default_factory=list)


@dataclass
class PlotPreset:
    """
    A preset of the Plot tab (D28, D42): a name, what it is for, and its grid.

    Generated by RJC and Claude.
    """

    name: str
    description: str
    rows: int
    columns: int


def column_roles(table):
    """
    The columns' roles by D13's rule, where the column-role dialog starts (S3, D35).

    Three columns are wave, flux and error. A fourth column of 0s and 1s is a mask
    (a bad-pixel mask); any other fourth column is a continuum. Further columns are
    ignored until the user gives them a role.

    Parameters
    ----------
    table : numpy.ndarray
        The file's numbers, one row per pixel.

    Returns
    -------
    dict

    Generated by RJC and Claude.
    """
    ncols = table.shape[1]
    if ncols < 3:
        raise ModeError(
            "A spectrum needs at least three columns: wave, flux and" " error."
        )
    roles = {"wave": 0, "flux": 1, "error": 2}
    if ncols >= 4:
        fourth = table[:, 3]
        roles["mask" if np.all(np.isin(fourth, (0.0, 1.0))) else "continuum"] = 3
    return roles


# The kinds of spectrum file (RJC's review): text tables now; PypeIt spec1d FITS
# files with the mode that reads echelle orders, later
ASCII, FITS, UNKNOWN = "ascii", "fits", "unknown"
FITS_SUFFIXES = (".fits", ".fit", ".fts", ".fits.gz", ".fit.gz")
# The roles a column of a text spectrum can take (S3, D13), the first three required.
# Each may be given to one column only; a column with none is ignored (not loaded).
# The mask is a bad-pixel mask: a pixel whose mask is 1 is left out of the fit, even
# where a fit region covers it (RJC's review of the skeleton).
ROLES = ("wave", "flux", "error", "continuum", "mask")
REQUIRED = ("wave", "flux", "error")
ROLE_TITLES = {
    "wave": "Wavelength",
    "flux": "Flux",
    "error": "Error",
    "continuum": "Continuum",
    "mask": "Mask",
}
IGNORE = "Ignore"


def file_kind(path):
    """
    The kind of a spectrum file: ``"ascii"`` (a table of numbers), ``"fits"`` (such as
    a PypeIt spec1d file), or ``"unknown"``.

    Generated by RJC and Claude.
    """
    if str(path).lower().endswith(FITS_SUFFIXES):
        return FITS
    try:
        with open(path, "rb") as fil:
            head = fil.read(2880)
    except OSError:
        return UNKNOWN
    if head.startswith(b"SIMPLE  ="):
        return FITS
    try:
        text = head.decode("utf-8")
    except UnicodeDecodeError:
        return UNKNOWN
    for line in text.splitlines()[:-1] or text.splitlines():
        words = line.split("#")[0].split()
        if not words:
            continue
        return ASCII if all(M.is_number(w) for w in words) else UNKNOWN
    return UNKNOWN


def check_roles(choices, ncols):
    """
    What is wrong with the column roles chosen for a text spectrum, or ``""``.

    Parameters
    ----------
    choices : list or dict
        The role of each column (``None`` to ignore it), or a mapping from role to
        column number.
    ncols : int
        The number of columns of the file.

    Returns
    -------
    str
        Which roles to check: every one of wavelength, flux and error must be given,
        and each role to one column only (any number of columns may be ignored).

    Generated by RJC and Claude.
    """
    if isinstance(choices, dict):
        listed = [None] * ncols
        for role, col in choices.items():
            if not 0 <= col < ncols:
                return "The file has no column {0}.".format(col + 1)
            listed[col] = role
        choices = listed
    problems = []
    twice = [r for r in ROLES if choices.count(r) > 1]
    if twice:
        problems.append(
            "{0} is given to more than one column".format(
                ", ".join(ROLE_TITLES[r] for r in twice)
            )
        )
    missing = [r for r in REQUIRED if r not in choices]
    if missing:
        problems.append(
            "choose the {0} column{1}".format(
                ", ".join(ROLE_TITLES[r].lower() for r in missing),
                "" if len(missing) == 1 else "s",
            )
        )
    unknown = [r for r in choices if r is not None and r not in ROLES]
    if unknown:
        problems.append("'{0}' is not a role of a column".format(unknown[0]))
    if not problems:
        return ""
    text = "; ".join(problems)
    return text[0].upper() + text[1:] + "."


def roles_of(choices):
    """
    The roles chosen for the columns, as a mapping from role to column number (the
    ignored columns left out).

    Generated by RJC and Claude.
    """
    return {role: col for col, role in enumerate(choices) if role is not None}


def preview(path, rows=6):
    """
    The first rows of a text spectrum, and every column's roles as D13's rule would
    give them (the dialog's starting point, S3).

    Returns
    -------
    tuple
        ``(rows, roles, ncols, npix)``.

    Generated by RJC and Claude.
    """
    table = read_table(path)
    return table[:rows], column_roles(table), table.shape[1], table.shape[0]


def read_table(source):
    """
    The numbers of a text spectrum, from a path or bytes.

    Generated by RJC and Claude.
    """
    if isinstance(source, bytes):
        source = io.TextIOWrapper(io.BytesIO(source))
    table = np.loadtxt(source, ndmin=2)
    return table


def write_snip(wave, flux, error, mask):
    """
    A snip in ``prepfit``'s four-column format, at full precision (D4, Q2.7).

    Generated by RJC and Claude.
    """
    out = io.StringIO()
    np.savetxt(out, np.column_stack([wave, flux, error, mask.astype(float)]))
    return out.getvalue().encode("utf-8")


class Mode:
    """
    The interface of a mode (F11).

    Generated by RJC and Claude.
    """

    name = ""
    title = ""

    def load(self, source, columns=None):
        """The data loader: read a spectrum with its column roles."""
        raise NotImplementedError

    def display(self, spectra):
        """The display spectra, built from the loaded ones."""
        raise NotImplementedError

    def regions_to_mask(self, wave, regions):
        """The fit mask of a snip, from the regions drawn on the display spectrum."""
        raise NotImplementedError

    def new_project(self, *args, **kwargs):
        """The model template: a new project."""
        raise NotImplementedError

    def plot_presets(self):
        """The presets of the Plot tab."""
        raise NotImplementedError


class QSOAbsLineMode(Mode):
    """
    QSO Abs Line mode, the default (F11): one fitted dataset per display spectrum.

    Generated by RJC and Claude.
    """

    name = "qso_abs_line"
    title = "QSO Abs Line"

    # -- the data loader ------------------------------------------------------------

    def load(self, source, columns=None):
        """
        Read a spectrum (D13).

        A continuum column is multiplied into the flux and the error, with a note, so
        that the snips are written un-normalised (QF.7).

        Parameters
        ----------
        source : str or bytes
            A path, or the file's bytes.
        columns : dict, optional
            The roles from the column-role dialog (S3); D13's rule by default.

        Returns
        -------
        Spectrum

        Generated by RJC and Claude.
        """
        try:
            table = read_table(source)
        except (OSError, ValueError) as err:
            raise ModeError("The spectrum cannot be read: {0}".format(err)) from None
        roles = dict(columns) if columns else column_roles(table)
        wave = table[:, roles["wave"]]
        flux = table[:, roles["flux"]].copy()
        error = table[:, roles["error"]].copy()
        notes = []
        if "continuum" in roles:
            cont = table[:, roles["continuum"]]
            flux *= cont
            error *= cont
            notes.append(
                "The flux and error were multiplied by the continuum column"
                " (column {0}).".format(roles["continuum"] + 1)
            )
        # A bad-pixel mask: 1 marks a pixel to leave out of the fit
        mask = table[:, roles["mask"]] != 0 if "mask" in roles else None
        return Spectrum(
            wave,
            flux,
            error,
            mask,
            source if isinstance(source, str) else "",
            roles,
            notes,
        )

    # -- the display spectrum and the regions ---------------------------------------

    def display(self, spectra):
        """In QSO Abs Line mode, each dataset is its own display spectrum."""
        return list(spectra)

    def regions_to_mask(self, wave, regions):
        """
        A snip's mask: the pixels inside any region drawn on its dataset.

        Generated by RJC and Claude.
        """
        mask = np.zeros(np.size(wave), dtype=bool)
        for low, high in regions:
            mask |= (wave >= low) & (wave <= high)
        return mask

    def apply_regions(self, project, snip, regions):
        """
        The step that gives a snip the regions drawn on its display spectrum.

        Generated by RJC and Claude.
        """
        return project.set_regions(snip, regions)

    # -- the model template ---------------------------------------------------------

    # The settings of a new model, unless the user's preferences give others
    SETTINGS = PR.NEW_PROJECT_SETTINGS

    def new_project(
        self,
        source,
        z,
        transitions,
        name=None,
        fwhm=7.0,
        window=300.0,
        region=60.0,
        coldens=13.5,
        bturb=10.0,
        columns=None,
        registry=None,
        settings=None,
    ):
        """
        A new project: a model, its snips and its project data, from one spectrum.

        Parameters
        ----------
        source : str
            The source spectrum's path.
        z : float
            The primary system's redshift (D16).
        transitions : list of (str, float)
            ``(ion, rest wavelength)``, such as ``("16O_I", 1039.2304)``.
        name : str, optional
            The project's name; by default the source's file name.
        fwhm : float
            The dataset's FWHM in km/s, fixed by default (D14).
        window : float
            Half the width of each snip, in km/s.
        region : float
            Half the width of the fit region of each snip, in km/s.
        coldens, bturb : float
            The starting log N and b_turb of the component (S12 refines log N from
            the AOD in Stage 5).
        columns : dict, optional
            The column roles (S3).
        registry : Registry, optional
            ALIS's functions and the default atomic data.
        settings : iterable of (str, str, str), optional
            The model's settings; by default :attr:`SETTINGS`. The user's
            preferences (Stage 3) will set them.

        Returns
        -------
        Project

        Generated by RJC and Claude.
        """
        spec = self.load(source, columns)
        stem = os.path.splitext(os.path.basename(source))[0]
        name = name or stem
        if registry is None:
            registry = M.Registry.load()
        files, data_words, ion_specids = {}, [], {}
        for ion, rest in transitions:
            if ion not in registry.ions:
                raise ModeError("Unknown ion: " + ion)
            snip, specid = self._cut(spec, stem, ion, rest, z, window, region)
            files[snip[0]] = (snip[1], snip[2])
            data_words.append(
                [
                    "../data/" + snip[0],
                    "specid=" + specid,
                    "fitrange=columns",
                    "loadrange=all",
                    "resolution=vfwhm({0}FWHM1)".format(E.format_value(fwhm)),
                    "columns=[wave:0,flux:1,error:2,fitrange:3]",
                    "label=" + stem,
                ]
            )
            ion_specids.setdefault(ion, []).append((specid, snip[2]))
        text = AL.aligned(
            self._model_text(
                settings or self.SETTINGS, data_words, ion_specids, z, coldens, bturb
            )
        )
        bundle = self._bundle(
            name, text, files, source, stem, spec, ion_specids, z, transitions
        )
        return P.Project(bundle, registry)

    def _cut(self, spec, stem, ion, rest, z, window, region):
        """
        Cut the snip of one transition, with its fit region as its mask.

        Returns
        -------
        tuple
            ``((file name, bytes, continuum guess), specid)``.

        Generated by RJC and Claude.
        """
        centre = rest * (1.0 + z)
        vel = C_KMS * (spec.wave - centre) / centre
        keep = np.abs(vel) <= window
        if np.count_nonzero(keep) < 10:
            raise ModeError(
                "The spectrum does not cover {0} {1:.1f} at z = {2}.".format(
                    P.ion_name(ion), rest, z
                )
            )
        fit = np.abs(vel[keep]) <= region
        if spec.mask is not None:
            # Bad pixels are left out of the fit, even inside the fit region
            fit &= ~spec.mask[keep]
        _, elem, stage = P.split_ion(ion)
        label = "{0}_{1}_{2:d}".format(elem, stage, int(rest))
        fname = "{0}_{1}_reg.dat".format(stem, label)
        specid = "{0}{1}_{2:d}".format(elem, stage, int(rest))
        flux = spec.flux[keep]
        content = write_snip(spec.wave[keep], flux, spec.error[keep], fit)
        guess = float(np.median(flux[~fit])) if np.any(~fit) else float(np.median(flux))
        return (fname, content, guess), specid

    def empty_project(
        self,
        sources,
        name,
        z=None,
        blind=False,
        settings=None,
        fwhm=7.0,
        columns=None,
        registry=None,
        bundle_path=None,
    ):
        """
        A new project with no snips yet, from the New project dialog (Q3.12).

        Its model holds the settings and empty data and model blocks; each spectrum
        is one file row of the Data tab, recorded by path and checksum, with its
        columns read by D13's rule (the column-role dialog comes in Stage 4). Snips
        are cut from the rows in the Regions tab.

        Parameters
        ----------
        sources : list of str
            The spectra, one file row each; the first is the reference (D14).
        name : str
            The project's name, which its model file takes.
        z : float, optional
            The primary system's redshift; without it, the project has no system
            yet.
        blind : bool
            Blind the whole fit (``run blind True``, D24).
        settings : iterable of (str, str, str), optional
            The model's settings; by default :attr:`SETTINGS` (the preferences give
            the user's own).
        fwhm : float or dict
            The FWHM, in km/s, each row starts with when its first snip is cut: one
            for all, or one for each spectrum, by path.
        columns : dict, optional
            The column roles of each source, by path; D13's rule by default.
        registry : Registry, optional
        bundle_path : str, optional
            Where the project will be saved, so that each source's path is also
            kept relative to it (for relinking, F13).

        Returns
        -------
        tuple
            ``(project, notes)``: the project, and what the user should be told about
            the spectra (a continuum multiplied in).

        Generated by RJC and Claude.
        """
        if not sources:
            raise ModeError("A new project needs at least one spectrum.")
        columns = columns or {}
        spectra, notes = [], []
        for path in sources:
            spec = self.load(path, columns.get(path))
            spectra.append(spec)
            notes += ["{0}: {1}".format(os.path.basename(path), n) for n in spec.notes]
        settings = [
            (
                cat,
                key,
                (
                    ("True" if blind else "False")
                    if (cat, key) == ("run", "blind")
                    else value
                ),
            )
            for cat, key, value in (settings or self.SETTINGS)
        ]
        if blind and ("run", "blind") not in [(c, k) for c, k, _ in settings]:
            settings.append(("run", "blind", "True"))
        width = max(len(s[1]) for s in settings) if settings else 0
        lines = [
            "{0:<5s} {1:<{2}s}  {3}".format(cat, key, width, value)
            for cat, key, value in settings
        ]
        lines += ["", "data read", "data end", "", "model read", "model end"]
        text = AL.aligned("\n".join(lines) + "\n")
        bundle = B.Bundle()
        model_member = B.TREE + "model/" + name + ".mod"
        bundle.members[model_member] = text.encode("utf-8")
        atomic_path = load.atomic_table_path(load.DEFAULT_ATOMIC, verbose=-1)
        with open(atomic_path, "rb") as fil:
            atomic_member = B.ATOMIC + os.path.basename(atomic_path)
            bundle.members[atomic_member] = fil.read()
        created = B.now()
        bundle.manifest.update(
            {
                "format": B.FORMAT,
                "version": B.FORMAT_VERSION,
                "alis_version": alis.__version__,
                "created": created,
                "modified": created,
                "model": model_member,
                "atomic": atomic_member,
                "unblinding": [],
            }
        )
        rows, names = [], set()
        for num, (path, spec) in enumerate(zip(sources, spectra), 1):
            stem = os.path.splitext(os.path.basename(path))[0]
            label, extra = stem, 2
            while label in names:
                label, extra = "{0}_{1}".format(stem, extra), extra + 1
            names.add(label)
            entry = B.add_source(bundle, path, dataset=label, bundle_path=bundle_path)
            rows.append(
                {
                    "id": "r{0}".format(num),
                    "name": label,
                    "specids": [],
                    "reference": num == 1,
                    "source": entry["id"],
                    "columns": spec.columns,
                    "fwhm": float(
                        fwhm.get(path, 7.0) if isinstance(fwhm, dict) else fwhm
                    ),
                }
            )
        systems = []
        if z is not None:
            systems.append(
                {
                    "id": "a",
                    "name": "z = {0:.5f}".format(z),
                    "z": float(z),
                    "primary": True,
                    "lines": [],
                }
            )
        project = {
            "format": P.PROJECT_FORMAT,
            "mode": self.name,
            "systems": systems,
            "rows": rows,
        }
        bundle.members[P.PROJECT_JSON] = json.dumps(project, indent=1).encode("utf-8")
        if registry is None:
            registry = M.Registry.load()
        return P.Project(bundle, registry), notes

    @staticmethod
    def _model_text(settings, data_words, ion_specids, z, coldens, bturb):
        """
        The model text of a new project, laid out as ALIS's own models are.

        Generated by RJC and Claude.
        """
        width = max(len(s[1]) for s in settings)
        lines = [
            "{0:<5s} {1:<{2}s}  {3}".format(cat, key, width, value)
            for cat, key, value in settings
        ]
        lines += ["", "data read"]
        lines += ["  " + "  ".join(words) for words in data_words]
        lines += ["data end", "", "model read", " emission"]
        for ion, snips in ion_specids.items():
            for specid, guess in snips:
                lines.append(
                    "  legendre  {0}  0.0  0.0  scale=[1.0,1.0,1.0]"
                    "  specid={1}".format(E.format_value(guess, 6), specid)
                )
        lines.append(" absorption")
        labels = {"redshift": "za1", "bturb": "ba1", "temperature": "TA1"}
        for ion, snips in ion_specids.items():
            lines.append(
                "  voigt  ion={0}  {1}  {2}{3}  {4}{5}  0.0{6}  specid={7}".format(
                    ion,
                    E.format_value(coldens),
                    E.format_value(z),
                    labels["redshift"],
                    E.format_value(bturb),
                    labels["bturb"],
                    labels["temperature"],
                    ",".join(s for s, _ in snips),
                )
            )
        lines.append("model end")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _bundle(name, text, files, source, stem, spec, ion_specids, z, transitions):
        """
        The bundle of a new project, laid out as ``bundle.pack`` lays one out.

        Generated by RJC and Claude.
        """
        bundle = B.Bundle()
        model_member = B.TREE + "model/" + name + ".mod"
        bundle.members[model_member] = text.encode("utf-8")
        for fname, (content, _) in files.items():
            bundle.members[B.TREE + "data/" + fname] = content
        atomic_path = load.atomic_table_path(load.DEFAULT_ATOMIC, verbose=-1)
        with open(atomic_path, "rb") as fil:
            atomic_member = B.ATOMIC + os.path.basename(atomic_path)
            bundle.members[atomic_member] = fil.read()
        created = B.now()
        bundle.manifest.update(
            {
                "format": B.FORMAT,
                "version": B.FORMAT_VERSION,
                "alis_version": alis.__version__,
                "created": created,
                "modified": created,
                "model": model_member,
                "atomic": atomic_member,
                "unblinding": [],
            }
        )
        entry = B.add_source(bundle, source, dataset=stem)
        specids = [s for snips in ion_specids.values() for s, _ in snips]
        project = {
            "format": P.PROJECT_FORMAT,
            "mode": QSOAbsLineMode.name,
            "systems": [
                {
                    "id": "a",
                    "name": "z = {0:.5f}".format(z),
                    "z": z,
                    "primary": True,
                    "lines": [{"ion": ion, "wave": rest} for ion, rest in transitions],
                }
            ],
            "rows": [
                {
                    "id": "r1",
                    "name": stem,
                    "specids": specids,
                    "reference": True,
                    "source": entry["id"],
                    "columns": spec.columns,
                }
            ],
        }
        bundle.members[P.PROJECT_JSON] = json.dumps(project, indent=1).encode("utf-8")
        return bundle

    # -- plot presets ---------------------------------------------------------------

    def plot_presets(self):
        """
        The presets of the Plot tab (D28, D42; the tab is built after v1).

        Generated by RJC and Claude.
        """
        return [
            PlotPreset("metals", "The metal lines of one system", 4, 2),
            PlotPreset("DH", "The Lyman series of H I and D I", 4, 2),
            PlotPreset("blends", "Interlopers, one panel per transition", 4, 1),
            PlotPreset("helium", "The helium lines", 2, 2),
        ]


MODES = {QSOAbsLineMode.name: QSOAbsLineMode()}
# Names a mode had before: "voigt" until Stage 3 (Q3.17)
ALIASES = {"voigt": QSOAbsLineMode.name}


def get(name="qso_abs_line"):
    """
    A mode by its name (or a name it had before).

    Generated by RJC and Claude.
    """
    try:
        return MODES[ALIASES.get(name, name)]
    except KeyError:
        raise ModeError("There is no mode called '{0}'.".format(name)) from None


__all__ = [
    "Mode",
    "QSOAbsLineMode",
    "Spectrum",
    "PlotPreset",
    "ModeError",
    "MODES",
    "ALIASES",
    "get",
    "column_roles",
    "file_kind",
    "check_roles",
    "preview",
    "ROLES",
    "REQUIRED",
    "ROLE_TITLES",
    "IGNORE",
    "roles_of",
    "ASCII",
    "FITS",
    "UNKNOWN",
    "read_table",
    "write_snip",
]
