"""Sessions: a project open in the dashboard, and the file it lives in.

Dashboard Stage 3.3 (F1; Q3.2, Q3.8). A :class:`Session` holds:

- a :class:`~alis.dashboard.project.Project` and its
  :class:`~alis.dashboard.history.History`;
- the bundle's path (None for an imported fit that has not been saved yet), and
  whether there are unsaved changes;
- the view state, ``ui/view.json``: the tab, the ``.mod`` panel and the sizes of the
  panes, and what later stages add. It is not part of the history;
- what the bundle on disk held of the project when it was opened or last saved, so
  that a change made on disk by another program is noticed (S31, Q3.8).

What it does:

- **Save** writes the bundle, atomically and under its lock, keeping the runs that
  ``run_alis project.model`` wrote meanwhile (Q1.7). If the model, its files or the
  project data changed on disk since the session read them, Save stops with
  :class:`Conflict`, and the window asks whether to overwrite, reload, or save as
  another file (Q3.8).
- **Autosave** writes a recovery copy, never the bundle, while there are changes it
  has not yet kept (every minute by default, RJC, Q3.2). A clean close removes the
  copy; opening a project whose recovery copy is newer than the bundle offers it.
  The bundle therefore only ever holds what the user saved, which is what
  ``run_alis project.model`` fits.
- The undo history is not saved (Q2.8).

Generated by RJC and Claude.
"""

import copy
import datetime
import hashlib
import json
import os
import uuid
import zipfile
from dataclasses import dataclass

from alis import bundle as B
from alis.dashboard import blinding as BL
from alis.dashboard import history as H
from alis.dashboard import markers as MK
from alis.dashboard import modes as MO
from alis.dashboard import preferences as PR
from alis.dashboard import project as P
from alis.dashboard import text as T

VIEW_JSON = "ui/view.json"
# The view of a project that has none yet
DEFAULT_VIEW = {"tab": "Data", "mod_panel": {"open": True, "width": 460}}
# Disk states (check_disk)
SAME, RUNS, CHANGED, MISSING, UNSAVED = "same", "runs", "changed", "missing", "unsaved"


class SessionError(Exception):
    """A session action that cannot be done as asked."""


class LaunchError(Exception):
    """The ``alis`` command was given something it does not open."""


# -- The launcher (F14, Q3.7, Q3.12, Q3.15) ------------------------------------------

START, OPEN, IMPORT = "start", "open", "import"
SPECTRUM = (
    "{0} is not a project (.model) or a fit (.mod). To start a project from a"
    " spectrum, run alis and choose New project."
)


@dataclass(frozen=True)
class Target:
    """
    What the ``alis`` command opens: the start page, a project, or a fit to import.

    Attributes
    ----------
    kind : str
        ``"start"``, ``"open"`` or ``"import"``.
    path : str or None

    Generated by RJC and Claude.
    """

    kind: str
    path: str | None = None


def launch_target(path=None):
    """
    What ``alis [path]`` opens (F14).

    - nothing: the start page, with New project, Open, Import a fit and the recent
      projects;
    - a ``.model``: that project;
    - a ``.mod`` (or a ``.mod.out``): the fit, imported into a new, unsaved project
      (F4).

    Anything else is refused: a new project is made from its spectra in the New
    project dialog, not from the command line (RJC, Q3.7).

    Raises
    ------
    LaunchError

    Generated by RJC and Claude.
    """
    if path is None:
        return Target(START)
    if not os.path.exists(path):
        raise LaunchError("There is no file " + path)
    if os.path.isdir(path):
        raise LaunchError(
            "{0} is a folder, not a project (.model) or a fit (.mod).".format(path)
        )
    lower = path.lower()
    if lower.endswith(B.SUFFIX):
        if not zipfile.is_zipfile(path):
            raise LaunchError("{0} is not a project bundle.".format(path))
        return Target(OPEN, os.path.abspath(path))
    if lower.endswith(".mod") or lower.endswith(".mod.out"):
        return Target(IMPORT, os.path.abspath(path))
    raise LaunchError(SPECTRUM.format(path))


class Conflict(SessionError):
    """
    The bundle on disk has changed since the session read it (Q3.8).

    Attributes
    ----------
    state : str
        ``"changed"`` (the model, its files or the project data) or ``"missing"``.

    Generated by RJC and Claude.
    """

    def __init__(self, path, state):
        self.path = path
        self.state = state
        what = (
            "has been deleted"
            if state == MISSING
            else "was changed by another program since it was opened or saved"
        )
        super().__init__("The project file {0} {1}.".format(path, what))


def now():
    """The time now, with its time zone, to the second."""
    return datetime.datetime.now().astimezone().replace(microsecond=0)


# -- What a session owns of a bundle -------------------------------------------------


def _extra_hidden(stored, text):
    """The lines hidden besides those with ``blind=True``, as ``Project`` finds them."""
    blind = set(B.blind_line_numbers(text))
    marks = {ln.num for ln in T.ModelText(stored).lines if ln.kind == T.HIDDEN}
    return marks - blind


def _state(text, files, ui, hidden, sources):
    """
    A fingerprint of a project's state: what Save writes of it.

    Generated by RJC and Claude.
    """
    digest = hashlib.sha256()
    digest.update(text.encode("utf-8"))
    for member in sorted(files):
        digest.update(b"\0" + member.encode("utf-8") + b"\0" + files[member])
    digest.update(json.dumps(ui, sort_keys=True).encode("utf-8"))
    digest.update(json.dumps(sorted(hidden)).encode("utf-8"))
    digest.update(json.dumps(sources, sort_keys=True).encode("utf-8"))
    return digest.hexdigest()


def project_state(project):
    """
    The fingerprint of a project's state in memory.

    Generated by RJC and Claude.
    """
    return _state(
        project.text,
        project.files,
        project.ui,
        project.extra_hidden,
        project.bundle.sources,
    )


def bundle_state(bundle):
    """
    The fingerprint of the project a bundle holds, as :func:`project_state` gives it
    for the project opened from it.

    Generated by RJC and Claude.
    """
    model = bundle.model_member
    stored = bundle.model_text()
    text = bundle.model_text(restore=True)
    files = {
        m: c for m, c in bundle.members.items() if m.startswith(B.TREE) and m != model
    }
    ui = {}
    if P.PROJECT_JSON in bundle.members:
        ui = json.loads(bundle.members[P.PROJECT_JSON].decode("utf-8"))
    return _state(text, files, ui, _extra_hidden(stored, text), bundle.sources)


def runs_state(bundle):
    """
    The fingerprint of a bundle's runs: the latest run, its error, and the
    committed runs.

    Generated by RJC and Claude.
    """
    digest = hashlib.sha256()
    for member in sorted(m for m in bundle.members if m.startswith(B.RUNS)):
        digest.update(b"\0" + member.encode("utf-8") + b"\0" + bundle.members[member])
    return digest.hexdigest()


def _stamp(path):
    """A file's modification time and size, or None."""
    try:
        info = os.stat(path)
    except OSError:
        return None
    return (info.st_mtime_ns, info.st_size)


# -- Recovery copies ---------------------------------------------------------------


def recovery_key(path=None, ident=None, name="project"):
    """
    The name of a project's recovery copy, without its extension.

    A saved project's copy is named after its path, so that it is found again when
    the project is opened; an unsaved one's after the session.

    Generated by RJC and Claude.
    """
    if path is not None:
        digest = hashlib.sha1(os.path.abspath(path).encode("utf-8")).hexdigest()
        stem = os.path.splitext(os.path.basename(path))[0]
        return "p_{0}_{1}".format(digest[:16], stem)
    return "u_{0}_{1}".format(ident, name)


def recovery_files(key, folder=None):
    """The recovery copy and its note, ``(bundle, json)``."""
    base = os.path.join(PR.recovery_dir(folder), key)
    return base + B.SUFFIX, base + ".json"


def _remove(paths):
    for path in paths:
        try:
            os.remove(path)
        except OSError:
            pass


def find_recovery(path, folder=None):
    """
    The recovery copy of a saved project, when it is newer than the bundle.

    A copy older than the bundle is out of date (the project was saved after it), and
    is removed.

    Returns
    -------
    dict or None
        The copy's note: ``path``, ``name``, ``written``, and ``copy`` (its file).

    Generated by RJC and Claude.
    """
    copy_path, note_path = recovery_files(recovery_key(path), folder)
    if not os.path.isfile(copy_path) or not os.path.isfile(note_path):
        return None
    if os.path.exists(path) and os.path.getmtime(copy_path) <= os.path.getmtime(path):
        _remove((copy_path, note_path))
        return None
    try:
        with open(note_path, encoding="utf-8") as fil:
            note = json.load(fil)
    except (OSError, ValueError):
        return None
    note["copy"] = copy_path
    return note


def orphans(folder=None):
    """
    The recovery copies of projects that were never saved (an imported fit), for the
    start page.

    Returns
    -------
    list of dict
        Their notes, newest first.

    Generated by RJC and Claude.
    """
    found = []
    where = PR.recovery_dir(folder)
    if not os.path.isdir(where):
        return found
    for name in os.listdir(where):
        if not (name.startswith("u_") and name.endswith(".json")):
            continue
        note_path = os.path.join(where, name)
        copy_path = note_path[: -len(".json")] + B.SUFFIX
        try:
            with open(note_path, encoding="utf-8") as fil:
                note = json.load(fil)
        except (OSError, ValueError):
            continue
        if os.path.isfile(copy_path):
            note["copy"] = copy_path
            found.append(note)
    return sorted(found, key=lambda n: n.get("written", ""), reverse=True)


def discard_recovery(note):
    """Remove a recovery copy and its note."""
    _remove((note["copy"], note["copy"][: -len(B.SUFFIX)] + ".json"))


def view_of(bundle):
    """
    A bundle's view state, ``ui/view.json``, over the defaults.

    Generated by RJC and Claude.
    """
    view = copy.deepcopy(DEFAULT_VIEW)
    data = bundle.members.get(VIEW_JSON)
    if data is not None:
        try:
            view.update(json.loads(data.decode("utf-8")))
        except (ValueError, TypeError):
            pass
    return view


def _merge(disk, saved_copy):
    """
    The bundle on disk with the project of a recovery copy: its files tree, hidden
    lines, project data, view and sources. The runs are the disk's.

    Generated by RJC and Claude.
    """
    out = copy.deepcopy(disk)
    for member in [m for m in out.members if m.startswith(B.TREE)]:
        del out.members[member]
    out.members.update(
        {m: c for m, c in saved_copy.members.items() if m.startswith(B.TREE)}
    )
    out.manifest["model"] = saved_copy.manifest["model"]
    model = saved_copy.model_member
    out.hidden["lines"][model] = dict(saved_copy.hidden["lines"].get(model, {}))
    for member in (P.PROJECT_JSON, VIEW_JSON):
        if member in saved_copy.members:
            out.members[member] = saved_copy.members[member]
        else:
            out.members.pop(member, None)
    out.sources = copy.deepcopy(saved_copy.sources)
    return out


# -- The session -------------------------------------------------------------------


class Session:
    """
    A project open in the dashboard, with its history, its file and its view.

    Parameters
    ----------
    project : Project
    path : str or None
        The bundle; None until an imported fit is first saved.
    prefs : Preferences, optional
        The user's preferences; the defaults if not given.
    folder : str, optional
        The folder of the dashboard's own files (recovery copies, recent projects);
        by default :func:`alis.dashboard.preferences.home`.
    origin : str, optional
        The ``.mod`` an unsaved project was imported from.

    Attributes
    ----------
    project : Project
    history : History
    path : str or None
    view : dict
        ``ui/view.json``.
    autosaved : datetime or None
        When the last recovery copy was written.

    Generated by RJC and Claude.
    """

    def __init__(self, project, path=None, prefs=None, folder=None, origin=None):
        self.project = project
        self.prefs = prefs or PR.Preferences(folder)
        self.folder = folder or self.prefs.folder
        self.history = H.History(
            project,
            pause=self.prefs["editor.typing_pause"],
            guard=BL.Guard(project),
            tracker=MK.Tracker(),
        )
        self.path = None if path is None else os.path.abspath(path)
        self.origin = origin
        self.ident = uuid.uuid4().hex[:12]
        self.view = view_of(project.bundle)
        self._saved_view = copy.deepcopy(self.view)
        self._saved = project_state(project) if self.path is not None else None
        self._kept = self._saved
        self.autosaved = None
        self._disk = None
        if self.path is not None:
            self._note_disk(project.bundle)

    # -- making one -----------------------------------------------------------------

    @classmethod
    def open(cls, path, prefs=None, folder=None, recover=None, registry=None):
        """
        Open a project bundle.

        Parameters
        ----------
        path : str
        recover : dict, optional
            A recovery copy's note (:func:`find_recovery`): the project is opened as
            the copy holds it, with the runs on disk, and has unsaved changes.
        registry : Registry, optional
            ALIS's functions and atomic data, when the caller has them already; by
            default made from the bundle's packed atomic table.

        Generated by RJC and Claude.
        """
        disk = B.read(path)
        bundle = disk
        if recover is not None:
            bundle = _merge(disk, B.read(recover["copy"]))
        session = cls(P.Project(bundle, registry), path, prefs, folder)
        if recover is not None:
            session._saved = bundle_state(disk)
            session._saved_view = view_of(disk)
            session._note_disk(disk)
        return session

    @classmethod
    def new(
        cls,
        path,
        sources,
        z=None,
        blind=False,
        mode="qso_abs_line",
        prefs=None,
        folder=None,
        registry=None,
        overwrite=False,
        columns=None,
        fwhm=None,
    ):
        """
        A new project, from the New project dialog (Q3.12), written at once so that
        it is never untitled.

        Parameters
        ----------
        path : str
            The new bundle, ``<folder>/<name>.model``.
        sources : list of str
            Its spectra, one file row each.
        z : float, optional
            The primary system's redshift.
        blind : bool
            Blind the whole fit.
        mode : str
        overwrite : bool
            Write over an existing file (the dialog has asked).
        columns : dict, optional
            The column roles chosen for each spectrum, by path; D13's rule
            otherwise.
        fwhm : dict, optional
            The FWHM of each spectrum, in km/s, by path; the preferences' otherwise.

        Returns
        -------
        tuple
            ``(session, notes)``.

        Generated by RJC and Claude.
        """
        path = os.path.abspath(path)
        if not path.endswith(B.SUFFIX):
            raise SessionError("A project file ends in " + B.SUFFIX)
        if os.path.exists(path) and not overwrite:
            raise SessionError("There is already a file " + path)
        prefs = prefs or PR.Preferences(folder)
        name = os.path.splitext(os.path.basename(path))[0]
        project, notes = MO.get(mode).empty_project(
            sources,
            name,
            z=z,
            blind=blind,
            settings=prefs.settings(),
            fwhm=fwhm if fwhm else prefs["new_project.fwhm"],
            columns=columns,
            registry=registry,
            bundle_path=path,
        )
        session = cls(project, None, prefs, folder)
        session.save(path)
        return session, notes

    @classmethod
    def import_model(cls, modfile, prefs=None, folder=None, registry=None):
        """
        Import an existing fit, a plain ``.mod`` with its snips (F4), as a new
        project that is not saved until Save.

        Generated by RJC and Claude.
        """
        project = P.Project.import_model(modfile, registry)
        return cls(project, None, prefs, folder, origin=os.path.abspath(modfile))

    @classmethod
    def from_recovery(cls, note, prefs=None, folder=None, registry=None):
        """
        Reopen an unsaved project from its recovery copy (the start page offers it).

        Generated by RJC and Claude.
        """
        project = P.Project(B.read(note["copy"]), registry)
        session = cls(project, None, prefs, folder, origin=note.get("origin"))
        session.ident = note.get("ident", session.ident)
        return session

    # -- state ----------------------------------------------------------------------

    @property
    def name(self):
        """The project's name: its file's, or its model's when it is unsaved."""
        if self.path is not None:
            return os.path.basename(self.path)
        return os.path.splitext(self.project.bundle.model_name)[0] + B.SUFFIX

    @property
    def dirty(self):
        """
        Whether there are changes that Save has not written.

        An imported fit has them until it is first saved.

        Generated by RJC and Claude.
        """
        if self._saved is None:
            return True
        return project_state(self.project) != self._saved

    @property
    def view_changed(self):
        """Whether the view differs from what the bundle holds."""
        return self.view != self._saved_view

    def suggested_path(self):
        """
        Where Save as starts: the project's own file, or ``<name>.model`` beside the
        ``.mod`` it was imported from.

        Generated by RJC and Claude.
        """
        if self.path is not None:
            return self.path
        if self.origin is not None:
            return B.default_bundle_name(self.origin)
        return os.path.join(os.getcwd(), self.name)

    def set_view(self, key, value):
        """
        Change one entry of the view state (not a step of the history).

        Generated by RJC and Claude.
        """
        self.view[key] = copy.deepcopy(value)

    # -- the bundle on disk (S31, Q3.8) ---------------------------------------------

    def _note_disk(self, bundle):
        """Remember what the bundle on disk holds now."""
        self._disk = {
            "project": bundle_state(bundle),
            "runs": runs_state(bundle),
            "stamp": _stamp(self.path),
        }

    def check_disk(self):
        """
        Whether the bundle on disk has changed since the session read or wrote it.

        Returns
        -------
        str
            ``"same"``; ``"runs"`` when only its runs changed (a ``run_alis
            project.model`` finished, Q3.8(a)); ``"changed"`` when the model, its
            files or the project data changed (Q3.8(b)); ``"missing"`` when the
            file is gone; ``"unsaved"`` for a project with no file yet.

        Generated by RJC and Claude.
        """
        if self.path is None:
            return UNSAVED
        stamp = _stamp(self.path)
        if stamp is None:
            return MISSING
        if stamp == self._disk["stamp"]:
            return SAME
        try:
            disk = B.read(self.path)
        except (B.BundleError, OSError):
            return CHANGED
        if bundle_state(disk) != self._disk["project"]:
            return CHANGED
        if runs_state(disk) != self._disk["runs"]:
            return RUNS
        self._disk["stamp"] = stamp
        return SAME

    def take_runs(self):
        """
        Take the runs on disk into the project, when only they changed (Q3.8(a)):
        the Fit tab and its marker then show the new run.

        Returns
        -------
        bool
            Whether anything changed.

        Generated by RJC and Claude.
        """
        if self.check_disk() != RUNS:
            return False
        disk = B.read(self.path)
        bundle = self.project.bundle
        for member in [m for m in bundle.members if m.startswith(B.RUNS)]:
            del bundle.members[member]
        bundle.members.update(
            {m: c for m, c in disk.members.items() if m.startswith(B.RUNS)}
        )
        for kind in ("lines", "files"):
            store = bundle.hidden[kind]
            for member in [m for m in store if m.startswith(B.RUNS)]:
                del store[member]
            store.update(
                {m: v for m, v in disk.hidden[kind].items() if m.startswith(B.RUNS)}
            )
        self._note_disk(disk)
        return True

    def reload(self):
        """
        Read the project again from disk, dropping the changes made here and the
        history (the user chose to reload, Q3.8).

        Generated by RJC and Claude.
        """
        if self.path is None:
            raise SessionError("This project has no file to reload.")
        fresh = Session.open(
            self.path, self.prefs, self.folder, registry=self.project.registry
        )
        self.discard_recovery()
        self.__dict__.update(fresh.__dict__)

    # -- saving ---------------------------------------------------------------------

    def to_bundle(self):
        """
        The bundle as Save would write it: the project, and its view.

        Generated by RJC and Claude.
        """
        out = self.project.to_bundle()
        out.members[VIEW_JSON] = json.dumps(self.view, indent=1).encode("utf-8")
        return out

    def _owned(self, new):
        """
        A change of a bundle read from disk that writes this session's project into
        it, keeping its runs and the members the project does not own.

        Generated by RJC and Claude.
        """
        model = new.model_member

        def change(old):
            for member in [m for m in old.members if m.startswith(B.TREE)]:
                del old.members[member]
            old.members.update(
                {m: c for m, c in new.members.items() if m.startswith(B.TREE)}
            )
            old.manifest["model"] = model
            old.hidden["lines"][model] = dict(new.hidden["lines"].get(model, {}))
            for member in (P.PROJECT_JSON, VIEW_JSON):
                if member in new.members:
                    old.members[member] = new.members[member]
                else:
                    old.members.pop(member, None)
            old.sources = copy.deepcopy(new.sources)

        return change

    def save(self, path=None, overwrite=False):
        """
        Write the project to its bundle, or to ``path`` (Save as).

        Saving to the project's own file keeps the runs written there meanwhile
        (Q1.7). If the project on disk has changed since the session read it, Save
        stops with :class:`Conflict` unless ``overwrite`` is given (Q3.8). Saving to
        another file writes a new bundle there.

        Parameters
        ----------
        path : str, optional
            Another file (Save as); by default the project's own.
        overwrite : bool
            Write over a project changed on disk.

        Returns
        -------
        str
            The path written.

        Generated by RJC and Claude.
        """
        target = os.path.abspath(path) if path else self.path
        if target is None:
            raise SessionError("This project has no file yet: use Save as.")
        new = self.to_bundle()
        if target == self.path and os.path.exists(target):
            state = self.check_disk()
            if state == CHANGED and not overwrite:
                raise Conflict(target, state)
            written = B.update(target, self._owned(new))
        else:
            B.write(new, target)
            written = new
        old_key = self._recovery_key()
        self.path = target
        self.project.bundle = written
        self._saved = project_state(self.project)
        self._kept = self._saved
        self._saved_view = copy.deepcopy(self.view)
        self._note_disk(written)
        _remove(recovery_files(old_key, self.folder))
        PR.Recent(self.folder, self.prefs["recent.length"]).add(target)
        return target

    def unblind(self, note=""):
        """
        Unblind the project, after the user has confirmed (D24, Q2.11).

        The project is unblinded in memory (``blinding.unblind``: the text switched to
        ``blind=False`` and ``run blind False``, the history cleared), and, when it has
        a file, the bundle on disk is unblinded and saved at once, so that the
        unblinding is logged there and its runs are put back in plain form.

        Raises
        ------
        Conflict
            If the project on disk has changed since it was read: reload or save it
            first.

        Generated by RJC and Claude.
        """
        saved = self.path is not None and os.path.exists(self.path)
        if saved and self.check_disk() == CHANGED:
            raise Conflict(self.path, CHANGED)
        BL.unblind(self.project, confirmed=True, note=note, history=self.history)
        if not saved:
            return
        owned = self._owned(self.to_bundle())

        def change(old):
            B.unblind(old, note)
            owned(old)

        written = B.update(self.path, change)
        self.project.bundle = written
        self._saved = project_state(self.project)
        self._kept = self._saved
        self._saved_view = copy.deepcopy(self.view)
        self._note_disk(written)
        self.discard_recovery()

    def close(self):
        """
        Close cleanly: keep the view in the bundle when only it changed, and remove
        the recovery copy.

        Generated by RJC and Claude.
        """
        if (
            self.path is not None
            and self.view_changed
            and self.check_disk() in (SAME, RUNS)
        ):
            data = json.dumps(self.view, indent=1).encode("utf-8")
            B.update(self.path, lambda b: b.members.__setitem__(VIEW_JSON, data))
            self._saved_view = copy.deepcopy(self.view)
        self.discard_recovery()

    # -- autosave (F1, Q3.2) --------------------------------------------------------

    def _recovery_key(self):
        stem = os.path.splitext(self.name)[0]
        return recovery_key(self.path, self.ident, stem)

    @property
    def recovery_path(self):
        """The file of this session's recovery copy."""
        return recovery_files(self._recovery_key(), self.folder)[0]

    def autosave(self):
        """
        Write a recovery copy, if there are changes that neither Save nor an earlier
        autosave has kept. With no unsaved changes, an old copy is removed.

        Returns
        -------
        bool
            Whether a copy was written.

        Generated by RJC and Claude.
        """
        if not self.dirty:
            self.discard_recovery()
            self._kept = self._saved
            return False
        state = project_state(self.project)
        if state == self._kept and os.path.exists(self.recovery_path):
            return False
        copy_path, note_path = recovery_files(self._recovery_key(), self.folder)
        os.makedirs(os.path.dirname(copy_path), exist_ok=True)
        B.write(self.to_bundle(), copy_path)
        stamp = now()
        PR.write_json(
            note_path,
            {
                "path": self.path,
                "name": self.name,
                "origin": self.origin,
                "ident": self.ident,
                "written": stamp.isoformat(),
            },
        )
        self._kept = state
        self.autosaved = stamp
        return True

    def discard_recovery(self):
        """Remove this session's recovery copy."""
        _remove(recovery_files(self._recovery_key(), self.folder))


__all__ = [
    "Session",
    "SessionError",
    "LaunchError",
    "Target",
    "launch_target",
    "START",
    "OPEN",
    "IMPORT",
    "Conflict",
    "VIEW_JSON",
    "DEFAULT_VIEW",
    "view_of",
    "project_state",
    "bundle_state",
    "runs_state",
    "find_recovery",
    "orphans",
    "discard_recovery",
    "recovery_key",
    "recovery_files",
    "SAME",
    "RUNS",
    "CHANGED",
    "MISSING",
    "UNSAVED",
]
