"""Snips: SNIP and CLEAR, regions and masks, edges, copying, buffers, shared pixels.

Dashboard Stage 4.2 (S6, S7, S26, D18, D19; Q0.6, Q2.7, Q2.10, Q4.2, Q4.3, Q4.9,
Q4.11, Q4.15, Q4.17). No Qt: the Regions tab asks this module for every step, and
gives it to the history.

- **SNIP** (Q0.6, Q4.2) cuts one transition from every file row whose source
  spectrum covers it: the source's pixels within ± a half-width (300 km/s, a
  preference) of the transition, as a starting extent the user then moves. A snip is
  written in ``prepfit``'s four-column format at full precision, with a fifth
  ``badpix`` column when its source has a bad-pixel mask (Q4.17). It has no fit region
  until one is drawn. Its data line follows the row's resolution and shift; its
  continuum is the first guess (``continuum.py``); its specid is added to every
  absorption line whose transition falls in it (Q4.3). One step.
- **CLEAR** removes a snip, as ``remove.plan_snip`` plans it, with its record in
  ``ui/project.json``. One step.
- **Regions and masks** (S6, S7): a region is added, moved or removed, and pixels are
  masked by hand; a pixel that cannot be fitted (bad, NaN, an error ≤ 0) never is.
- **Edges** (S6, Q2.7, Q4.9(a)): moving an edge inwards keeps the lines that stay;
  moving one outwards keeps the old lines byte for byte and adds the source's pixels
  at full precision.
- **Copying regions** (D18) to the same transition in other rows, moved by the
  difference of their shifts.
- **The buffer** a snip has beyond its fitted pixels, against what its resolution
  needs (``getminmax``, as ALIS and the validator compute it).
- **Pixels fitted twice** (S26, D19, ``load.find_shared_pixels``) and their fixes:
  keep them in one snip only, or merge the snips (Q4.9: their lines kept, as one file
  in order of wavelength; the first snip's specid kept and the second's replaced in
  every line; always confirmed).

Every step is made on the project, read, and taken back, so that what it returns is
one step whose parts each saw the model as the parts before it left it.

Generated by RJC and Claude.
"""

import copy
import io
import posixpath
import re
from dataclasses import dataclass, field

import numpy as np

from alis import bundle as B
from alis import load
from alis.dashboard import continuum as CO
from alis.dashboard import edit as E
from alis.dashboard import lines as L
from alis.dashboard import model as M
from alis.dashboard import project as P
from alis.dashboard import remove as R
from alis.dashboard import text as T

C_KMS = 299792.458
# Half the width of a new snip, in km/s (a preference, Q4.2)
HALF_WIDTH = 300.0
# Merging is offered first when this fraction of either snip's fitted pixels is
# shared (a preference, D19)
MERGE_FIRST = 0.25
# A new snip has at least this many pixels
MIN_PIXELS = 10
SNIPS = L.SNIPS_KEY
# The columns of a new snip, without and with a bad-pixel mask (Q4.17)
COLUMNS = "[wave:0,flux:1,error:2,fitrange:3]"
COLUMNS_BAD = "[wave:0,flux:1,error:2,fitrange:3,badpix:4]"
# The value written for a column a merged or extended line has no value for
_FILL = {"continuum": 1.0, "zerolevel": 0.0, "systematics": 0.0, "loadrange": 1.0}


class SnipError(Exception):
    """A snip action that cannot be done as asked."""


# -- Steps made of steps ---------------------------------------------------------------


def compose(project, description, makers):
    """
    One step from several, each made on the project as the ones before left it.

    Each maker is called with the project and returns a step (or None); the step is
    applied, so that the next maker sees it; at the end every step is taken back, and
    the steps are joined into one.

    Parameters
    ----------
    project : Project
    description : str
    makers : iterable of callable

    Returns
    -------
    Step

    Generated by RJC and Claude.
    """
    done = []
    try:
        for maker in makers:
            step = maker(project)
            if step is None or not step:
                continue
            project.apply(step)
            done.append(step)
    finally:
        for step in reversed(done):
            project.revert(step)
    if not done:
        return P.Step(description)
    out = done[0]
    for step in done[1:]:
        out = out.then(step)
    out.description = description
    return out


def _ui_step(project, ui, description=""):
    return P.Step(description, ui=(copy.deepcopy(project.ui), copy.deepcopy(ui)))


def _structure(project):
    """
    ``ui/project.json`` with its rows and systems written out (an imported fit's
    still marked guessed until it is confirmed, Q4.18).
    """
    return project.working_structure()


# -- Where a transition is in a row ----------------------------------------------------


def row_shift(row):
    """
    A row's shift in km/s: the starting value of its snips' ``vshift``, or 0.

    Generated by RJC and Claude.
    """
    for snip in row.snips:
        item = snip.data
        if item.shift is not None and item.shift.name == "vshift":
            par = item.param("shift")
            if par is not None:
                return float(par.start)
    return 0.0


def window(rest, z, shift=0.0, half_width=HALF_WIDTH):
    """
    The wavelengths within ± ``half_width`` km/s of a transition, in a row's frame
    (a row with shift v sees a line at λ (1 + v/c), as ALIS's ``vshift`` moves it).

    Returns
    -------
    tuple
        ``(low, high)``.

    Generated by RJC and Claude.
    """
    centre = rest * (1.0 + z) * (1.0 + shift / C_KMS)
    return centre * (1.0 - half_width / C_KMS), centre * (1.0 + half_width / C_KMS)


def snips_of(project, system, ion, rest, snip_map=None):
    """
    The snips of one transition of a system, by row id.

    Generated by RJC and Claude.
    """
    snip_map = L.snip_transitions(project) if snip_map is None else snip_map
    out = {}
    for snip in project.snips:
        trans = snip_map.get(snip.specid)
        if (
            trans is not None
            and trans.system == system
            and trans.ion == ion
            and abs(trans.rest - rest) < 0.01
            and snip.row is not None
        ):
            out.setdefault(snip.row.id, snip)
    return out


# -- Snip files ------------------------------------------------------------------------


def snip_bytes(wave, flux, error, fit, bad=None):
    """
    A snip in ``prepfit``'s four-column format at full precision (D4, Q2.7), with a
    fifth ``badpix`` column when a bad-pixel mask is given (Q4.17).

    Generated by RJC and Claude.
    """
    cols = [wave, flux, error, np.asarray(fit, dtype=float)]
    if bad is not None:
        cols.append(np.asarray(bad, dtype=float))
    out = io.StringIO()
    np.savetxt(out, np.column_stack(cols))
    return out.getvalue().encode("utf-8")


def _line_text(values):
    """One line of a snip, as ``np.savetxt`` writes it."""
    return " ".join("{0:.18e}".format(v) for v in values)


def _names(project, row, system, line, taken_files, taken_specids):
    """
    A new snip's bundle member and specid: ``<row>_<El>_<stage>_<λ>_reg.dat`` beside
    the model's other snips, and ``<El><stage>_<λ>`` (with the row's id when there
    are several rows, and the system's when it is not the primary).

    Generated by RJC and Claude.
    """
    element, stage = line.element, line.stage.replace("*", "s")
    primary = system.primary
    stem = re.sub(r"[^\w.+-]", "_", row.name)
    base = "{0}_{1}{2}_{3}_{4:.1f}".format(
        stem, "" if primary else "z{0}_".format(system.id), element, stage, line.rest
    )
    folder = None
    for snip in row.snips + project.snips:
        folder = posixpath.dirname(snip.member)
        break
    if folder is None:
        model_dir = posixpath.dirname(project.model_member)
        folder = posixpath.normpath(posixpath.join(model_dir, "..", "data"))
    member = posixpath.join(folder, base + "_reg.dat")
    num = 2
    while member in project.files or member in taken_files:
        member = posixpath.join(folder, "{0}_{1}_reg.dat".format(base, num))
        num += 1
    specid = "{0}{1}_{2:d}".format(element, stage, int(line.rest))
    if len(project.rows) > 1:
        specid += "_" + row.id
    if not primary:
        specid += "_" + system.id
    used = {s.specid for s in project.snips} | set(taken_specids)
    base_id, num = specid, 2
    while specid in used:
        specid = "{0}_{1}".format(base_id, num)
        num += 1
    return member, specid


def _file_word(project, member):
    """A bundle member as a data line names it (relative to the model and datadirc)."""
    model_dir = posixpath.dirname(project.model_member)
    start = posixpath.normpath(
        posixpath.join(model_dir, project.parsed.datadirc or ".")
    )
    return posixpath.relpath(member, start)


def _row_entry(ui, row):
    for entry in ui.get("rows", []):
        if entry.get("id") == row.id:
            return entry
    return None


def _row_words(project, row):
    """
    The resolution and shift of a row's new data line: as its other snips have them
    (so they share their labels), or, for its first snip, its FWHM (fixed) and a free
    shift unless it is the reference (D14).

    Generated by RJC and Claude.
    """
    pm = project.parsed
    for snip in row.snips:
        res = snip.data.keywords.get("resolution")
        shift = snip.data.keywords.get("shift")
        return (
            res.value if res is not None else None,
            shift.value if shift is not None else None,
        )
    entry = _row_entry(project.ui, row) or {}
    fwhm = float(entry.get("fwhm", 7.0))
    number = [r.id for r in project.rows].index(row.id) + 1
    labels = E.new_row_labels(pm, number)
    res = "vfwhm({0}{1})".format(E.format_value(fwhm), labels["resolution"].upper())
    shift = None
    if not row.reference:
        shift = "vshift(0.0{0})".format(labels["shift"])
    return res, shift


# -- SNIP and CLEAR (Q0.6, Q4.2, Q4.3) ---------------------------------------------------


def covering(project, system, line, spectra, half_width=HALF_WIDTH, snip_map=None):
    """
    The rows whose source spectrum covers a transition and that have no snip of it
    yet (Q4.2(b)).

    Parameters
    ----------
    spectra : dict
        Row id to its source spectrum (``modes.Spectrum``); rows without one are
        left out.

    Returns
    -------
    list of Row

    Generated by RJC and Claude.
    """
    have = snips_of(project, system.id, line.ion, line.rest, snip_map)
    out = []
    for row in project.rows:
        spec = spectra.get(row.id)
        if spec is None or row.id in have:
            continue
        # Covered when the source has pixels there, good or bad: the bad ones are
        # carried in the snip, and never fitted
        cov = L.Coverage(row.id, row.name, spec.wave, np.isfinite(spec.wave))
        obs = line.rest * (1.0 + system.z) * (1.0 + row_shift(row) / C_KMS)
        if L.place(obs, [cov], half_width=0.0)[0]:
            out.append(row)
    return out


def _absorption_specids(pm, specid, low, high, shift, registry):
    """
    The patches that add a new snip's specid to every absorption line with a
    transition inside it (Q4.3), and how many lines they change.

    Generated by RJC and Claude.
    """
    patches = []
    for item in pm.lines:
        if item.section != "absorption" or not item.ion or not item.specids:
            continue
        if specid in item.specids:
            continue
        zpar = item.param("redshift")
        if zpar is None:
            continue
        ion = item.ion.split("/")[0]
        waves, _ = registry.transitions(ion)
        factor = (1.0 + zpar.start) * (1.0 + shift / C_KMS)
        if any(low <= float(w) * factor <= high for w in waves):
            kw = item.keywords["specid"]
            patches.append(
                T.replace_token(pm.text, kw.val, ",".join(item.specids + [specid]))
            )
    return patches


def snip_step(
    project,
    system,
    line,
    spectra,
    half_width=HALF_WIDTH,
    rows=None,
    max_order=CO.AUTO_MAX,
    line_kms=CO.LINE_KMS,
    clip=CO.CLIP,
):
    """
    The step that cuts a transition from every row whose source covers it (SNIP,
    Q0.6, Q4.2).

    Parameters
    ----------
    project : Project
    system : System
    line : lines.Line or lines.Transition
        The transition (its ion and rest wavelength).
    spectra : dict
        Row id to source spectrum.
    half_width : float
        The starting half-width, in km/s.
    rows : list of Row, optional
        The rows to cut it from; by default every row that covers it.

    Returns
    -------
    Step

    Raises
    ------
    SnipError
        When no row's source covers the transition.

    Generated by RJC and Claude.
    """
    project.require_reading()
    atom = L.atomic(project.registry)
    lines = [ln for ln in atom.ion_lines(line.ion) if abs(ln.rest - line.rest) < 0.01]
    if not lines:
        raise SnipError("{0} is not in the atomic data.".format(line.ion))
    tline = lines[0]
    rows = (
        covering(project, system, tline, spectra, half_width) if rows is None else rows
    )
    name = tline.name
    if not rows:
        raise SnipError(
            "No dataset's source spectrum covers {0} at this redshift, or it is a"
            " snip already. SNIP needs the source spectrum.".format(name)
        )
    plans = []
    taken_files, taken_specids = [], []
    for row in rows:
        spec = spectra[row.id]
        shift = row_shift(row)
        low, high = window(tline.rest, system.z, shift, half_width)
        keep = (spec.wave >= low) & (spec.wave <= high)
        if np.count_nonzero(keep) < MIN_PIXELS:
            raise SnipError(
                "{0} has fewer than {1} pixels within ±{2:g} km/s of {3}.".format(
                    row.name, MIN_PIXELS, half_width, name
                )
            )
        bad = None if spec.mask is None else spec.mask[keep]
        content = snip_bytes(
            spec.wave[keep],
            spec.flux[keep],
            spec.error[keep],
            np.zeros(np.count_nonzero(keep)),
            bad,
        )
        member, specid = _names(project, row, system, tline, taken_files, taken_specids)
        taken_files.append(member)
        taken_specids.append(specid)
        plans.append((row, member, specid, content, bad is not None, low, high, shift))
    counted = {"lines": 0}

    def files_and_lines(proj):
        pm = proj.parsed
        change = T.Change((), "")
        files = {}
        for row, member, specid, content, has_bad, _, _, _ in plans:
            res, shift = _row_words(proj, row)
            after = max((s.line for s in row.snips), default=None)
            pm2 = E.reread(pm, change) if change else pm
            if after is not None and change:
                after = change.map_line(pm.text, after)
            words = ["label=" + re.sub(r"\s+", "_", row.name)]
            add = E.add_data_line(
                pm2,
                _file_word(proj, member),
                specid,
                "columns",
                resolution=res,
                shift=shift,
                columns=COLUMNS_BAD if has_bad else COLUMNS,
                keywords=["loadrange=all"] + words,
                after=after,
            )
            change = change.then(add)
            files[member] = (None, content)
        step = proj.step(change, "")
        step.files = files
        ui = _structure(proj)
        for row, member, specid, _, _, _, _, _ in plans:
            entry = _row_entry(ui, row)
            if entry is not None:
                entry["specids"] = list(entry.get("specids", [])) + [specid]
            ui.setdefault(SNIPS, {})[specid] = {
                "system": system.id,
                "ion": tline.ion,
                "rest": tline.rest,
                "row": row.id,
            }
        for entry in ui.get("systems", []):
            if entry.get("id") == system.id:
                known = entry.setdefault("lines", [])
                if not any(
                    e.get("ion") == tline.ion
                    and abs(float(e.get("wave", -1.0)) - tline.rest) < 0.01
                    for e in known
                ):
                    known.append({"ion": tline.ion, "wave": tline.rest})
        step.ui = (copy.deepcopy(proj.ui), ui)
        return step

    def continuum_of(specid):
        def make(proj):
            snip = proj.snip(specid)
            best = CO.guess(
                proj, snip, "legendre", max_order, clip=clip, line_kms=line_kms
            )
            return proj.step(CO.write(proj, snip, best.fit), "")

        return make

    def specids_of(plan):
        specid, low, high, shift = plan[2], plan[5], plan[6], plan[7]

        def make(proj):
            found = _absorption_specids(
                proj.parsed, specid, low, high, shift, proj.registry
            )
            counted["lines"] += len(found)
            if not found:
                return None
            return proj.step(T.Change.from_spans(found, ""), "")

        return make

    def zero_level_of(plan):
        row_id, specid = plan[0].id, plan[2]

        def make(proj):
            row = proj.row(row_id)
            pm = proj.parsed
            others = [s for s in row.specids if s != specid]
            if others:
                line = E.zero_level_line(pm, others)
                if line is None:
                    return None
                return proj.step(E.set_specids(pm, line, line.specids + [specid]), "")
            entry = _row_entry(proj.ui, row) or {}
            if entry.get("zerolevel"):
                return proj.step(E.add_zero_level(pm, [specid], 0.0), "")
            return None

        return make

    step = compose(
        project,
        "",
        [files_and_lines]
        + [continuum_of(p[2]) for p in plans]
        + [specids_of(p) for p in plans]
        + [zero_level_of(p) for p in plans],
    )
    where = "{0} dataset{1}".format(len(plans), "" if len(plans) == 1 else "s")
    desc = "SNIP {0} in {1}".format(name, where)
    if counted["lines"]:
        desc += " (its specid added to {0} absorption line{1})".format(
            counted["lines"], "" if counted["lines"] == 1 else "s"
        )
    step.description = desc
    return step


def clear_plan(project, snip):
    """
    The plan that removes a snip and its regions (CLEAR, Q0.6): ``remove.plan_snip``,
    with the snip's record taken out of ``ui/project.json``. It is shown before it is
    made (S27).

    Returns
    -------
    remove.Plan

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    plan = R.plan_snip(project, snip, empty_sections=True)
    trans = L.snip_transitions(project).get(snip.specid)
    name = L.line_name(*_named(trans)) if trans else snip.specid
    row = snip.row.name if snip.row is not None else ""
    plan.description = "CLEAR {0}{1}".format(name, " in " + row if row else "")
    ui = _structure(project)
    for entry in ui.get("rows", []):
        if snip.specid in entry.get("specids", []):
            entry["specids"] = [s for s in entry["specids"] if s != snip.specid]
    for key in (SNIPS, CO.KNOTS):
        if snip.specid in ui.get(key, {}):
            del ui[key][snip.specid]
            if not ui[key]:
                del ui[key]
    plan.ui = ui
    return plan


def _named(trans):
    mass, element, stage = P.split_ion(trans.ion)
    element = "D" if (element == "H" and mass == 2) else element
    return element, stage, trans.rest


# -- Regions and masks (S6, S7) ----------------------------------------------------------


def current(project, snip):
    """
    The project's snip with this one's specid, as the model now reads: a snip held
    by a panel is out of date after any step.

    Generated by RJC and Claude.
    """
    try:
        return project.snip(snip.specid)
    except P.ProjectError:
        raise SnipError("There is no snip " + snip.specid + " any more.") from None


def fitted(snip):
    """
    The pixels a snip fits, as booleans (from its mask column, its fit range, or all
    of it).

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    if pix is None:
        raise SnipError("The snip's file cannot be read.")
    form = snip.data.fitrange
    if form is None:
        return np.zeros(pix.wave.size, dtype=bool)
    if form[0] == "all":
        mask = np.ones(pix.wave.size, dtype=bool)
    elif form[0] == "range":
        mask = (pix.wave >= form[1]) & (pix.wave <= form[2])
    elif pix.mask is None:
        mask = np.zeros(pix.wave.size, dtype=bool)
    else:
        mask = pix.mask != 0
    return mask & pix.fittable


def set_mask_step(project, snip, mask, description, copied_from=None):
    """
    The step that gives a snip a fit mask (Q2.7, Q2.10): only pixels that can be
    fitted are (Q4.11). A snip that SNIP recorded also records where its regions
    came from: copied from another dataset (D18), or drawn here.

    Parameters
    ----------
    copied_from : str, optional
        The dataset the regions were copied from; None when they are drawn here.

    Generated by RJC and Claude.
    """
    mask = np.asarray(mask, dtype=bool) & snip.pixels.fittable
    regions = P.mask_regions(snip.pixels.wave, mask)
    step = project.set_regions(snip, regions)
    step.description = description
    record = project.ui.get(SNIPS, {}).get(snip.specid)
    if (record or {}).get("copied_from") != copied_from:
        # An imported snip has no record until its regions are copied
        ui = _structure(project)
        records = ui.setdefault(SNIPS, {})
        rec = records.setdefault(snip.specid, {})
        if copied_from is None:
            rec.pop("copied_from", None)
            if not rec:
                del records[snip.specid]
        else:
            rec["copied_from"] = copied_from
        if not records:
            del ui[SNIPS]
        step.ui = (copy.deepcopy(project.ui), ui)
    return step


def add_region_step(project, snip, low, high):
    """
    The step that adds a fit region (Draw region, S6).

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    low, high = sorted((float(low), float(high)))
    wave = snip.pixels.wave
    mask = fitted(snip) | ((wave >= low) & (wave <= high))
    return set_mask_step(
        project, snip, mask, "Add a fit region to {0}".format(snip.specid)
    )


def mask_step(project, snip, low, high):
    """
    The step that leaves pixels out of the fit (Exclude pixels, S7), splitting a region
    where needed.

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    low, high = sorted((float(low), float(high)))
    wave = snip.pixels.wave
    hit = (wave >= low) & (wave <= high)
    if not hit.any():
        near = int(np.argmin(np.abs(wave - 0.5 * (low + high))))
        hit[near] = True
    mask = fitted(snip) & ~hit
    count = int(np.count_nonzero(hit & fitted(snip)))
    return set_mask_step(
        project,
        snip,
        mask,
        "Exclude {0} pixel{1} of {2}".format(
            count, "" if count == 1 else "s", snip.specid
        ),
    )


def regions_of(snip):
    """A snip's regions, from its fitted pixels."""
    return P.mask_regions(snip.pixels.wave, fitted(snip))


def move_region_step(project, snip, index, low, high):
    """
    The step that moves a region's edges (S6).

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    regions = regions_of(snip)
    if not 0 <= index < len(regions):
        raise SnipError("There is no such region.")
    wave = snip.pixels.wave
    old = (wave >= regions[index][0]) & (wave <= regions[index][1])
    low, high = sorted((float(low), float(high)))
    mask = (fitted(snip) & ~old) | ((wave >= low) & (wave <= high))
    return set_mask_step(
        project, snip, mask, "Move a fit region of {0}".format(snip.specid)
    )


def remove_region_step(project, snip, index):
    """
    The step that removes one region (Delete, or the right-click menu).

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    regions = regions_of(snip)
    if not 0 <= index < len(regions):
        raise SnipError("There is no such region.")
    wave = snip.pixels.wave
    gone = (wave >= regions[index][0]) & (wave <= regions[index][1])
    return set_mask_step(
        project,
        snip,
        fitted(snip) & ~gone,
        "Remove a fit region of {0}".format(snip.specid),
    )


def linked_snips(project, snip, snip_map=None):
    """
    The snips whose regions are the same as a snip's (Q4.19): its transition's snip
    in every dataset, itself first; only itself when its transition is not known.

    Generated by RJC and Claude.
    """
    snip_map = L.snip_transitions(project) if snip_map is None else snip_map
    trans = snip_map.get(snip.specid)
    if trans is None or not trans.system:
        return [snip]
    found = snips_of(project, trans.system, trans.ion, trans.rest, snip_map)
    others = [
        s for s in found.values() if s.specid != snip.specid and s.pixels is not None
    ]
    return [snip] + others


def linked_step(project, snip, edits, description, snip_map=None, linked=True):
    """
    A change of the fit regions made in one dataset and, the same, in every other
    dataset of the transition (Q4.19: one set of regions for a transition), moved by
    the difference of the datasets' shifts. Pixels excluded in one dataset alone
    (Exclude pixels) stay excluded there unless an edit adds them again.

    Parameters
    ----------
    snip : Snip
        The snip the edit was made on.
    edits : list of tuple
        ``("add" | "remove" | "drop", low, high)``, wavelengths in the snip's
        dataset: a pixel in ``[low, high]`` is added to the fit, or taken out of it;
        "drop" takes out each whole region that overlaps ``[low, high]`` (removing a
        region removes the one that stands for it in each dataset, even where its
        edges differ a little).
    description : str
    linked : bool
        False to change the snip's dataset alone (Tweak dataset regions).

    Returns
    -------
    Step

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    vsrc = row_shift(snip.row) if snip.row is not None else 0.0
    origin = snip.row.name if snip.row is not None else snip.specid
    makers = []
    targets = linked_snips(project, snip, snip_map) if linked else [snip]
    for target in targets:
        vdst = row_shift(target.row) if target.row is not None else 0.0
        factor = (1.0 + vdst / C_KMS) / (1.0 + vsrc / C_KMS)
        specid = target.specid

        def make(proj, specid=specid, factor=factor):
            one = proj.snip(specid)
            wave = one.pixels.wave
            had = fitted(one)
            mask = had.copy()
            for op, low, high in edits:
                low, high = low * factor, high * factor
                if op == "drop":
                    for a, b in P.mask_regions(wave, mask):
                        if b >= low and a <= high:
                            mask &= ~((wave >= a) & (wave <= b))
                    continue
                inside = (wave >= low) & (wave <= high)
                mask = mask | inside if op == "add" else mask & ~inside
            if specid == snip.specid:
                copied = None
            elif had.any():
                record = proj.ui.get(SNIPS, {}).get(specid) or {}
                copied = record.get("copied_from")
            else:
                copied = origin
            return set_mask_step(proj, one, mask, "", copied_from=copied)

        makers.append(make)
    return compose(project, description, makers)


def linked_name(project, snip, what, snip_map=None):
    """
    A linked step's name: "Add a fit region to O I 1302.2 in 3 datasets".

    Generated by RJC and Claude.
    """
    snip_map = L.snip_transitions(project) if snip_map is None else snip_map
    count = len(linked_snips(project, snip, snip_map))
    name = transition_name(snip_map.get(snip.specid)) or snip.specid
    return "{0} {1} in {2} dataset{3}".format(
        what, name, count, "" if count == 1 else "s"
    )


def copy_regions_step(project, source, targets, only_empty=True):
    """
    The step that copies a snip's regions to snips of the same transition in other
    rows (D18), moved by the difference of the rows' shifts.

    Parameters
    ----------
    source : Snip
    targets : list of Snip
    only_empty : bool
        Copy only to snips with no regions of their own ("Copy … to all" copies to
        every one).

    Generated by RJC and Claude.
    """
    source = current(project, source)
    targets = [current(project, t) for t in targets]
    regions = regions_of(source)
    if not regions:
        raise SnipError("{0} has no regions to copy.".format(source.specid))
    vsrc = row_shift(source.row) if source.row is not None else 0.0
    makers = []
    for target in targets:
        if target is source or target.pixels is None:
            continue
        if only_empty and fitted(target).any():
            continue
        vdst = row_shift(target.row) if target.row is not None else 0.0
        factor = (1.0 + vdst / C_KMS) / (1.0 + vsrc / C_KMS)
        moved = [(a * factor, b * factor) for a, b in regions]
        specid = target.specid

        origin = source.row.name if source.row is not None else source.specid

        def make(proj, specid=specid, moved=moved, origin=origin):
            snip = proj.snip(specid)
            wave = snip.pixels.wave
            mask = np.zeros(wave.size, dtype=bool)
            for low, high in moved:
                mask |= (wave >= low) & (wave <= high)
            return set_mask_step(proj, snip, mask, "", copied_from=origin)

        makers.append(make)
    if not makers:
        raise SnipError("Every other dataset already has regions for this transition.")
    row = source.row.name if source.row is not None else source.specid
    return compose(project, "Copy the regions of {0}".format(row), makers)


# -- The snip's edges (S6, Q2.7, Q4.9(a)) --------------------------------------------------


def _layout(content, item):
    """
    The words of each pixel line of a snip, with its column map.

    Generated by RJC and Claude.
    """
    text, lines, rows = P._data_rows(content)
    return text, lines, rows, P._column_map(item)


def _new_line(values, cols, ncols):
    """A pixel line with a value for each column of a snip's layout."""
    out = [0.0] * ncols
    for role, idx in cols.items():
        if 0 <= idx < ncols:
            out[idx] = values.get(role, _FILL.get(role, 0.0))
    return _line_text(out)


def _extend(content, item, spectrum, low, high):
    """
    A snip's bytes from ``low`` to ``high``: its own lines that stay, byte for byte,
    and the source's pixels beyond them at full precision (not fitted).

    Generated by RJC and Claude.
    """
    text, lines, rows, cols = _layout(content, item)
    ncols = len(rows[0][1]) if rows else 4
    waves = []
    for num, words in rows:
        body = lines[num][0]
        waves.append(float(body[words[cols["wave"]][0] : words[cols["wave"]][1]]))
    waves = np.array(waves)
    first, last = waves.min(), waves.max()
    newline = "\n"
    for _, ending, _ in lines:
        if ending:
            newline = ending
            break
    src = spectrum
    blue = (
        (src.wave >= low)
        & (src.wave < first)
        & ~np.isclose(src.wave, first, rtol=1e-12, atol=0)
    )
    red = (
        (src.wave <= high)
        & (src.wave > last)
        & ~np.isclose(src.wave, last, rtol=1e-12, atol=0)
    )

    def made(sel):
        out = []
        for k in np.flatnonzero(sel):
            values = {
                "wave": src.wave[k],
                "flux": src.flux[k],
                "error": src.error[k],
                "fitrange": 0.0,
            }
            if src.mask is not None:
                values["badpix"] = float(src.mask[k])
            out.append(_new_line(values, cols, ncols) + newline)
        return out

    keep_rows = {num for (num, _), w in zip(rows, waves) if low <= w <= high}
    data_nums = {num for num, _ in rows}
    head, body = [], []
    for num, (line, ending, _) in enumerate(lines):
        if num in data_nums:
            if num in keep_rows:
                body.append(line + (ending or newline))
        elif not body:
            head.append(line + ending)
        else:
            body.append(line + ending)
    out = "".join(head) + "".join(made(blue)) + "".join(body) + "".join(made(red))
    if not text.endswith(("\n", "\r")) and out.endswith(newline):
        out = out[: -len(newline)]
    return out.encode("utf-8")


def edges_step(project, snip, low, high, spectrum=None):
    """
    The step that moves a snip's edges (S6): inwards, keeping the lines that stay
    (Q2.7); outwards, keeping the old lines byte for byte and adding the source's
    pixels at full precision (Q4.9(a)). A Legendre with ``min=``/``max=`` takes the new
    range, with its coefficients re-expressed so that the curve does not change.

    Parameters
    ----------
    spectrum : modes.Spectrum, optional
        The row's source spectrum, needed to move an edge outwards.

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    project.require_reading()
    low, high = sorted((float(low), float(high)))
    extent = snip.extent
    if extent is None:
        raise SnipError("The snip's file cannot be read.")
    shared = [
        d
        for d in project.parsed.data
        if d is not snip.data and project.member_of(d) == snip.member
    ]
    if shared:
        raise SnipError(
            "Other data lines read this file too, so its edges cannot be moved."
        )
    content = project.files[snip.member]
    outwards = low < extent[0] or high > extent[1]
    if outwards:
        if spectrum is None:
            raise SnipError(
                "Moving an edge outwards needs the source spectrum, which this"
                " dataset does not have."
            )
        new = _extend(content, snip.data, spectrum, low, high)
    else:
        new = P.cut_snip(content, low, high)
    if new == content:
        return P.Step("Move the edges of " + snip.specid)
    specid = snip.specid
    line = snip.continuum
    old_range = CO.xrange_of(project, snip) if line is not None else None

    def files(proj):
        return P.Step("", files={snip.member: (content, new)})

    def continuum(proj):
        moved = proj.snip(specid)
        cont = moved.continuum
        if cont is None or cont.function not in CO.RANGED:
            return None
        if CO._keyword_float(cont, "min") is None:
            return None
        others = [
            s for s in proj.snips if s.specid in cont.specids and s.pixels is not None
        ]
        ranges = [CO.new_range(proj, s) for s in others] or [CO.new_range(proj, moved)]
        xrange = (min(r[0] for r in ranges), max(r[1] for r in ranges))
        if old_range is not None and np.allclose(xrange, old_range, rtol=1e-14, atol=0):
            return None
        if any(p.label for p in cont.params):
            return None
        order = CO.order_of(cont)
        coeffs = CO.reexpress(
            proj.registry,
            cont.function,
            CO.coefficients(proj, cont),
            old_range,
            xrange,
            order,
        )
        fitted_ = CO.Fit(cont.function, order, coeffs, xrange)
        return proj.step(CO.write(proj, moved, fitted_, cont), "")

    def knots(proj):
        found = CO.knots_of(proj, proj.snip(specid))
        inside = [k for k in found if low <= k[0] <= high]
        if len(inside) == len(found):
            return None
        ui = copy.deepcopy(proj.ui)
        if inside:
            ui[CO.KNOTS][specid] = [list(k) for k in inside]
        else:
            del ui[CO.KNOTS][specid]
            if not ui[CO.KNOTS]:
                del ui[CO.KNOTS]
        return _ui_step(proj, ui)

    return compose(
        project, "Move the edges of {0}".format(specid), [files, continuum, knots]
    )


# -- The buffer (S6, F5) -------------------------------------------------------------------


@dataclass
class Buffer:
    """
    The data a snip has beyond its fitted pixels on one side, against what its
    resolution needs (``getminmax``, as ALIS checks ``bufferpix``).

    Attributes
    ----------
    side : str
        ``"blue"`` or ``"red"``.
    have, need : float
        In km/s.

    Generated by RJC and Claude.
    """

    side: str
    have: float
    need: float

    @property
    def ok(self):
        """Whether the snip has the buffer it needs."""
        return self.have + 1.0e-6 >= self.need


def buffers(project, snip):
    """
    The blue and red buffers of a snip, or ``[]`` when it fits no pixel or its
    resolution is not known.

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    if pix is None:
        return []
    mask = fitted(snip)
    if not mask.any():
        return []
    call = snip.data.resolution
    pm = project.parsed
    if call is None or not call.args or call.name not in pm.registry.names:
        return []
    inst = pm.registry.function(call.name)
    wave = pix.wave[mask]
    span = [float(wave.min()), float(wave.max())]
    try:
        with M.alis_quietly():
            need = inst.getminmax([a.text for a in call.args], span)
    except Exception:
        return []
    low, high = float(pix.wave.min()), float(pix.wave.max())
    return [
        Buffer(
            "blue",
            C_KMS * (span[0] - low) / span[0],
            C_KMS * (span[0] - need[0]) / span[0],
        ),
        Buffer(
            "red",
            C_KMS * (high - span[1]) / span[1],
            C_KMS * (need[1] - span[1]) / span[1],
        ),
    ]


# -- Pixels fitted twice (S26, D19) ---------------------------------------------------------


@dataclass
class Shared:
    """
    Two snips that fit the same pixels.

    Attributes
    ----------
    a, b : Snip
    pix_a, pix_b : numpy.ndarray
        The shared pixels, as indices into each snip's pixels.

    Generated by RJC and Claude.
    """

    a: object = field(repr=False)
    b: object = field(repr=False)
    pix_a: np.ndarray = field(repr=False)
    pix_b: np.ndarray = field(repr=False)

    @property
    def count(self):
        """The number of shared pixels."""
        return int(self.pix_a.size)

    def fraction(self):
        """The largest fraction of either snip's fitted pixels that is shared."""
        na = int(np.count_nonzero(fitted(self.a)))
        nb = int(np.count_nonzero(fitted(self.b)))
        return max(self.count / max(na, 1), self.count / max(nb, 1))

    def other(self, snip):
        """The other snip of the pair."""
        return self.b if snip is self.a or snip.specid == self.a.specid else self.a

    def pixels_of(self, snip):
        """The shared pixels, as indices into one snip of the pair."""
        return (
            self.pix_a if snip is self.a or snip.specid == self.a.specid else self.pix_b
        )


def shared_pixels(project, snip=None):
    """
    Every pair of snips that fit the same pixels (``load.find_shared_pixels``), or
    only those with one snip.

    Returns
    -------
    list of Shared

    Generated by RJC and Claude.
    """
    snips, arrays, index = [], [], []
    for one in project.snips:
        if one.pixels is None:
            continue
        mask = fitted(one)
        idx = np.flatnonzero(mask)
        pix = one.pixels
        snips.append(one)
        arrays.append((pix.wave[idx], pix.flux[idx], pix.error[idx]))
        index.append(idx)
    out = []
    for i, j, idx_i, idx_j in load.find_shared_pixels(arrays):
        pair = Shared(snips[i], snips[j], index[i][idx_i], index[j][idx_j])
        if snip is None or snip.specid in (pair.a.specid, pair.b.specid):
            out.append(pair)
    return out


def merge_first(pairs, threshold=MERGE_FIRST):
    """Whether merging should be offered first (D19): a large overlap."""
    return any(p.fraction() >= threshold for p in pairs)


def keep_step(project, snip, pairs=None):
    """
    The step that keeps the shared pixels in one snip only (D19): they leave the
    other snips' fits.

    Generated by RJC and Claude.
    """
    snip = current(project, snip)
    pairs = shared_pixels(project, snip) if pairs is None else pairs
    if not pairs:
        raise SnipError("{0} shares no pixels with another snip.".format(snip.specid))
    drop = {}
    for pair in pairs:
        other = pair.other(snip)
        drop.setdefault(other.specid, []).append(pair.pixels_of(other))
    makers = []
    for specid, idxs in drop.items():

        def make(proj, specid=specid, idxs=idxs):
            other = proj.snip(specid)
            mask = fitted(other)
            for idx in idxs:
                mask[idx] = False
            return set_mask_step(proj, other, mask, "")

        makers.append(make)
    count = sum(p.count for p in pairs)
    return compose(
        project,
        "Keep {0} shared pixels in {1} only".format(count, snip.specid),
        makers,
    )


@dataclass
class MergePlan:
    """
    What merging two snips changes, shown for confirmation before it is made (Q4.9).

    Attributes
    ----------
    description : str
    keep, replaced : str
        The specid kept, and the one replaced by it in every line.
    plan : remove.Plan
        The lines that change, for the preview.
    step : Step

    Generated by RJC and Claude.
    """

    description: str
    keep: str
    replaced: str
    plan: object = field(repr=False)
    step: object = field(repr=False)

    def preview(self, gate):
        """The lines that change, through the blinding gate."""
        return self.plan.preview(gate)

    @property
    def notes(self):
        """What the user is told before confirming."""
        return list(self.plan.notes)


def _merged_bytes(project, a, b, spectrum=None):
    """
    One snip from two (Q4.9(b)): both files' lines, in order of wavelength, a pixel
    of both kept once (from the first); a gap between them filled from the source.

    Returns
    -------
    tuple
        ``(bytes, columns, has_bad)``: the file, and the data line's ``columns=``.

    Generated by RJC and Claude.
    """
    ca, cb = project.files[a.member], project.files[b.member]
    _, la, ra, cols_a = _layout(ca, a.data)
    _, lb, rb, cols_b = _layout(cb, b.data)
    has_bad = a.pixels.bad is not None or b.pixels.bad is not None
    cols = dict(cols_a)
    ncols = len(ra[0][1])
    if has_bad and "badpix" not in cols:
        cols["badpix"] = ncols
        ncols += 1
    same = cols == cols_b and len(rb[0][1]) == ncols
    newline = "\n"
    for _, ending, _ in la:
        if ending:
            newline = ending
            break

    def own_lines(lines, rows, colmap, keep_text, pix):
        out = []
        for k, (num, words) in enumerate(rows):
            body = lines[num][0]
            if keep_text:
                text = body
            else:
                values = {}
                for role, idx in colmap.items():
                    if 0 <= idx < len(words):
                        values[role] = float(body[words[idx][0] : words[idx][1]])
                text = _new_line(values, cols, ncols)
            out.append((float(pix.wave[k]), text))
        return out

    keep_a = cols == cols_a and len(ra[0][1]) == ncols
    lines = own_lines(la, ra, cols_a, keep_a, a.pixels)
    known = a.pixels.wave
    for wave, text in own_lines(lb, rb, cols_b, same, b.pixels):
        if np.any(np.abs(known - wave) <= 1.0e-9 * wave):
            continue
        lines.append((wave, text))
    lines.sort(key=lambda w: w[0])
    waves = np.array([w for w, _ in lines])
    steps = np.diff(waves)
    if steps.size and np.median(steps) > 0 and np.max(steps) > 5.0 * np.median(steps):
        if spectrum is None:
            raise SnipError(
                "These snips do not overlap; merging them needs the source spectrum"
                " to fill the gap between them."
            )
        gap = int(np.argmax(steps))
        lo, hi = waves[gap], waves[gap + 1]
        sel = (spectrum.wave > lo * (1 + 1e-12)) & (spectrum.wave < hi * (1 - 1e-12))
        for k in np.flatnonzero(sel):
            values = {
                "wave": spectrum.wave[k],
                "flux": spectrum.flux[k],
                "error": spectrum.error[k],
                "fitrange": 0.0,
            }
            if spectrum.mask is not None:
                values["badpix"] = float(spectrum.mask[k])
            lines.append((float(spectrum.wave[k]), _new_line(values, cols, ncols)))
        lines.sort(key=lambda w: w[0])
    body = "".join(text + newline for _, text in lines)
    order = sorted(cols.items(), key=lambda kv: kv[1])
    columns = "[" + ",".join("{0}:{1}".format(k, v) for k, v in order) + "]"
    return body.encode("utf-8"), columns, has_bad


def merge_plan(project, a, b, spectrum=None, clip=CO.CLIP, line_kms=CO.LINE_KMS):
    """
    The plan that merges two snips into one (D19, Q4.9): the union of their pixels and
    regions in the first snip's file, one continuum refitted, the second snip's data
    line and continuum removed, and its specid replaced by the first's in every line.

    Returns
    -------
    MergePlan

    Generated by RJC and Claude.
    """
    a, b = current(project, a), current(project, b)
    project.require_reading()
    if a.specid == b.specid:
        raise SnipError("A snip cannot be merged with itself.")
    if a.pixels is None or b.pixels is None:
        raise SnipError("The files of both snips must be readable to merge them.")
    for one in (a, b):
        if any(
            d is not one.data and project.member_of(d) == one.member
            for d in project.parsed.data
        ):
            raise SnipError(
                "Another data line reads the file of {0}, so it cannot be"
                " merged.".format(one.specid)
            )
    content, columns, _ = _merged_bytes(project, a, b, spectrum)
    mask_a, mask_b = fitted(a), fitted(b)
    regions = P.mask_regions(a.pixels.wave, mask_a) + P.mask_regions(
        b.pixels.wave, mask_b
    )
    keep, gone = a.specid, b.specid
    pm = project.parsed
    old_a = project.files[a.member]
    order = max(CO.current(a)[1], CO.current(b)[1])

    # The lines that change, for the confirmation
    entries = []
    entries.append(
        R.PlanLine(
            b.line, R.DELETE, "it is the data line of " + gone, pm.text[b.line].text
        )
    )
    for item in pm.lines:
        if gone not in item.specids:
            continue
        rest = [keep if s == gone else s for s in item.specids]
        rest = list(dict.fromkeys(rest))
        if item is b.continuum and a.continuum is not None and item is not a.continuum:
            if rest == [keep] or set(rest) <= set(a.continuum.specids):
                entries.append(
                    R.PlanLine(
                        item.line,
                        R.DELETE,
                        "it is the continuum of "
                        + gone
                        + "; one continuum is refitted",
                        pm.text[item.line].text,
                    )
                )
                continue
        entries.append(
            R.PlanLine(
                item.line,
                R.EDIT,
                "the specid {0} is replaced by {1}".format(gone, keep),
                pm.text[item.line].text,
            )
        )
    if a.continuum is not None:
        entries.append(
            R.PlanLine(
                a.continuum.line,
                R.EDIT,
                "the continuum is refitted to the merged snip",
                pm.text[a.continuum.line].text,
            )
        )
    entries.sort(key=lambda e: e.line)
    notes = [
        "{0} and {1} become one snip, {0}: its file holds both snips' pixels, in"
        " order of wavelength, and both snips' fit regions.".format(keep, gone),
        "The specid {0} is replaced by {1} in every line that names it.".format(
            gone, keep
        ),
    ]

    def text_and_files(proj):
        pmx = proj.parsed
        bb = proj.snip(gone)
        aa = proj.snip(keep)
        patches = [T.delete_lines(pmx.text, bb.line)]
        for item in pmx.lines:
            if gone not in item.specids:
                continue
            rest = list(dict.fromkeys(keep if s == gone else s for s in item.specids))
            if (
                item is bb.continuum
                and aa.continuum is not None
                and item is not aa.continuum
                and set(rest) <= set(aa.continuum.specids)
            ):
                patches.append(T.delete_lines(pmx.text, item.line))
                continue
            patches.append(
                T.replace_token(pmx.text, item.keywords["specid"].val, ",".join(rest))
            )
        item = aa.data
        if item.keyword("columns") != columns:
            patches.append(
                T.replace_token(pmx.text, item.keywords["columns"].val, columns)
                if "columns" in item.keywords
                else E._append_word(pmx, item.line, "columns=" + columns)
            )
        if item.fitrange is None or item.fitrange[0] != "columns":
            if "fitrange" in item.keywords:
                patches.append(
                    T.replace_token(pmx.text, item.keywords["fitrange"].val, "columns")
                )
        step = proj.step(T.Change.from_spans(patches, ""), "")
        files = {aa.member: (old_a, content)}
        if not any(
            proj.member_of(d) == bb.member for d in pmx.data if d is not bb.data
        ):
            files[bb.member] = (proj.files[bb.member], None)
        step.files = files
        ui = _structure(proj)
        for entry in ui.get("rows", []):
            if gone in entry.get("specids", []):
                entry["specids"] = [s for s in entry["specids"] if s != gone]
        if gone in ui.get(SNIPS, {}):
            del ui[SNIPS][gone]
        knots = ui.get(CO.KNOTS, {})
        if gone in knots:
            knots[keep] = sorted(knots.get(keep, []) + knots.pop(gone))
            if not knots:
                ui.pop(CO.KNOTS, None)
        step.ui = (copy.deepcopy(proj.ui), ui)
        return step

    def regions_step(proj):
        snip = proj.snip(keep)
        wave = snip.pixels.wave
        mask = np.zeros(wave.size, dtype=bool)
        for low, high in regions:
            mask |= (wave >= low) & (wave <= high)
        return set_mask_step(proj, snip, mask, "")

    def continuum_step(proj):
        snip = proj.snip(keep)
        if snip.continuum is None:
            return None
        cont = snip.continuum
        if any(p.label for p in cont.params):
            return None
        function = cont.function
        xrange = None
        if function in CO.RANGED:
            others = [
                s
                for s in proj.snips
                if s.specid in cont.specids and s.pixels is not None
            ]
            ranges = [CO.new_range(proj, s) for s in others]
            xrange = (min(r[0] for r in ranges), max(r[1] for r in ranges))
        knots = CO.knots_of(proj, snip)
        best = CO.fit_snip(
            proj,
            snip,
            function,
            max(order, len(knots) - 1),
            knots=knots,
            xrange=xrange,
            clip=clip,
            line_kms=line_kms,
        )
        return proj.step(CO.write(proj, snip, best), "")

    description = "Merge {0} into {1}".format(gone, keep)
    step = compose(project, description, [text_and_files, regions_step, continuum_step])
    plan = R.Plan(description, entries, [], None, notes, None)
    return MergePlan(description, keep, gone, plan, step)


# -- What the Regions tab shows (no Qt) ---------------------------------------------------


def strips(project, system, line, spectra, snip_map=None):
    """
    The datasets the Regions tab shows a transition in (D36): every row with a snip of
    it, and every row whose source spectrum has pixels there, in the rows' order.

    Returns
    -------
    list of tuple
        ``(row, snip or None)``.

    Generated by RJC and Claude.
    """
    have = snips_of(project, system.id, line.ion, line.rest, snip_map)
    out = []
    for row in project.rows:
        if row.id in have:
            out.append((row, have[row.id]))
            continue
        spec = spectra.get(row.id)
        if spec is None:
            continue
        cov = L.Coverage(row.id, row.name, spec.wave, np.isfinite(spec.wave))
        obs = line.rest * (1.0 + system.z) * (1.0 + row_shift(row) / C_KMS)
        if L.place(obs, [cov], half_width=0.0)[0]:
            out.append((row, None))
    return out


def summary(project, snip):
    """
    The Snip box's figures (S6): extent, pixels, fitted pixels and regions, and the
    buffers.

    Returns
    -------
    dict
        ``extent``, ``npix``, ``nfit``, ``nregions``, ``buffers``.

    Generated by RJC and Claude.
    """
    pix = snip.pixels
    if pix is None:
        return {"extent": None, "npix": 0, "nfit": 0, "nregions": 0, "buffers": []}
    mask = fitted(snip)
    return {
        "extent": snip.extent,
        "npix": int(pix.wave.size),
        "nfit": int(np.count_nonzero(mask)),
        "nregions": len(P.mask_regions(pix.wave, mask)),
        "buffers": buffers(project, snip),
    }


def transition_name(trans):
    """A snip's transition as people write it (``Ly8 923.2``), or ``""``."""
    if trans is None:
        return ""
    return L.line_name(*_named(trans))


def shared_text(pairs, snip, snip_map):
    """
    What the Snip box says of pixels fitted twice (D19, S26): "36 fitted pixels are
    also fitted by other snips (18 with Ly8 923.2, 18 with Ly6 930.7)."

    Generated by RJC and Claude.
    """
    if not pairs:
        return ""
    total = 0
    parts = []
    for pair in pairs:
        other = pair.other(snip)
        count = pair.count
        total += count
        name = transition_name(snip_map.get(other.specid)) or other.specid
        parts.append("{0} with {1}".format(count, name))
    return (
        "{0} fitted pixel{1} {2} also fitted by other snips ({3}). Each pixel should"
        " enter χ² once.".format(
            total,
            "" if total == 1 else "s",
            "is" if total == 1 else "are",
            ", ".join(parts),
        )
    )


def same_pairs(project, snip, pair, snip_map=None):
    """
    The same overlap in the other datasets (for "Apply the fix to all datasets"):
    the pairs of snips of the same two transitions, in every other row, that share
    pixels.

    Returns
    -------
    list of tuple
        ``(snip, Shared)``: in each other row, its snip of this transition and the
        pair.

    Generated by RJC and Claude.
    """
    snip_map = L.snip_transitions(project) if snip_map is None else snip_map
    mine = snip_map.get(snip.specid)
    theirs = snip_map.get(pair.other(snip).specid)
    if mine is None or theirs is None:
        return []
    out = []
    for row in project.rows:
        if snip.row is not None and row.id == snip.row.id:
            continue
        one = snips_of(project, mine.system, mine.ion, mine.rest, snip_map).get(row.id)
        two = snips_of(project, theirs.system, theirs.ion, theirs.rest, snip_map).get(
            row.id
        )
        if one is None or two is None:
            continue
        for found in shared_pixels(project, one):
            if found.other(one).specid == two.specid:
                out.append((one, found))
    return out


def keep_all_step(project, snip, also=()):
    """
    "Keep them in this snip only", in this dataset and in the others with the same
    overlap (``same_pairs``), as one step (D19).

    Generated by RJC and Claude.
    """
    names = [snip.specid] + [one.specid for one, _ in also]
    makers = [lambda proj, n=name: keep_step(proj, proj.snip(n)) for name in names]
    count = sum(p.count for p in shared_pixels(project, snip))
    count += sum(pair.count for _, pair in also)
    where = "" if not also else " in {0} datasets".format(len(names))
    return compose(
        project,
        "Keep {0} shared pixels in one snip only{1}".format(count, where),
        makers,
    )


def merge_all_plan(project, a, b, also=(), spectra=None, **kwargs):
    """
    "Merge the snips…", in this dataset and in the others with the same overlap
    (``same_pairs``): one plan, whose preview is this dataset's, and one step (D19,
    Q4.9).

    Parameters
    ----------
    spectra : dict, optional
        Row id to source spectrum, to fill a gap between snips that do not overlap.

    Generated by RJC and Claude.
    """
    spectra = spectra or {}

    def spec_of(snip):
        return spectra.get(snip.row.id) if snip.row is not None else None

    first = merge_plan(project, a, b, spec_of(a), **kwargs)
    if not also:
        return first
    pairs = [(a.specid, b.specid, spec_of(a))]
    for one, pair in also:
        pairs.append((one.specid, pair.other(one).specid, spec_of(one)))
    makers = [
        lambda proj, x=x, y=y, sp=sp: merge_plan(
            proj, proj.snip(x), proj.snip(y), sp, **kwargs
        ).step
        for x, y, sp in pairs
    ]
    description = "Merge {0} into {1} in {2} datasets".format(
        first.replaced, first.keep, len(pairs)
    )
    step = compose(project, description, makers)
    plan = R.Plan(
        description,
        first.plan.lines,
        [],
        None,
        first.plan.notes
        + [
            "The same merge is made in {0} other dataset{1}: {2}.".format(
                len(also),
                "" if len(also) == 1 else "s",
                ", ".join("{0} into {1}".format(y, x) for x, y, _ in pairs[1:]),
            )
        ],
        None,
    )
    return MergePlan(description, first.keep, first.replaced, plan, step)


def origin(project, snip):
    """
    Where a snip's regions came from (D18): ``drawn here``, ``copied from HIRES``, or
    ``no regions``.

    Generated by RJC and Claude.
    """
    if snip.pixels is None or not fitted(snip).any():
        return "no regions"
    record = project.ui.get(SNIPS, {}).get(snip.specid, {})
    if record.get("copied_from"):
        return "copied from " + record["copied_from"]
    return "drawn here"


__all__ = [
    "linked_snips",
    "linked_step",
    "linked_name",
    "keep_all_step",
    "merge_all_plan",
    "strips",
    "summary",
    "transition_name",
    "shared_text",
    "same_pairs",
    "origin",
    "SnipError",
    "compose",
    "row_shift",
    "window",
    "snips_of",
    "snip_bytes",
    "covering",
    "snip_step",
    "clear_plan",
    "fitted",
    "set_mask_step",
    "add_region_step",
    "mask_step",
    "regions_of",
    "move_region_step",
    "remove_region_step",
    "copy_regions_step",
    "edges_step",
    "Buffer",
    "buffers",
    "Shared",
    "shared_pixels",
    "merge_first",
    "keep_step",
    "MergePlan",
    "merge_plan",
    "HALF_WIDTH",
    "MERGE_FIRST",
]
