"""The model text: a ``.mod`` file as lines and words, each with its position.

Dashboard Stage 2.2. The text is the only part of a project that is ever edited
(D7, QF.3). This module reads it as ``alis.load.load_input`` does: the settings, the
data, model and link blocks, comments and long comments (``#-->`` ... ``<--#``),
``fix`` and ``lim`` lines, and values with their labels. It records the line and
columns of every word, so that a panel item can find its lines (S16) and a problem
can be shown on its line (F5).

A :class:`ModelText` never changes. An edit is a :class:`Patch`, or a
:class:`Change` made of several, which gives a new text and can be undone exactly.
Reading never changes the text: ``ModelText(text).text == text`` for every model,
byte for byte once encoded (QF.5).

Generated by RJC and Claude.
"""

import bisect
import re
from dataclasses import dataclass

# What a line is. Lines inside a block are one of DATA, SECTION, FIX, LIM, FUNCTION
# or LINK; the lines that open and close the blocks are BLOCK.
BLANK = "blank"  # nothing but white space
COMMENT = "comment"  # a comment, or a line that has been commented out
LONG = "long"  # inside a long comment, #--> ... <--#
HIDDEN = "hidden"  # the placeholder of a hidden line, <hidden:n> (Stage 1.6)
SETTING = "setting"  # a setting, outside the blocks: run ncpus 4
BLOCK = "block"  # data read, data end, model read, model end, link read, link end
DATA = "data"  # a data line
SECTION = "section"  # emission, absorption or zerolevel
FIX = "fix"  # fix voigt temperature True, fix param tval True
LIM = "lim"  # lim voigt bturb [0.5,None], lim param jc [20.0,21.0]
FUNCTION = "function"  # a model function: voigt ion=1H_I 20.3 ...
LINK = "link"  # a link: dha(hia,dhrand) = hia + dhrand

# The kinds of line whose words ALIS reads
CONTENT = (SETTING, BLOCK, DATA, SECTION, FIX, LIM, FUNCTION, LINK)
# The sections of the model block
SECTIONS = ("emission", "absorption", "zerolevel")
BLOCKS = ("data", "model", "link")
# The markers of a long comment
LONG_OPEN = "#-->"
LONG_CLOSE = "<--#"

_NEWLINE = re.compile(r"\r\n|\n|\r")
_WORD = re.compile(r"\S+")
_HIDDEN = re.compile(r"^<hidden:\d+>$")


class PatchError(Exception):
    """A patch does not fit the text it is applied to."""


@dataclass(frozen=True)
class Problem:
    """
    One problem with a model: where it is, how bad it is, and what it is.

    Attributes
    ----------
    line : int or None
        The line, from 0, or None for the model as a whole.
    severity : str
        ``"error"`` or ``"warning"``.
    message : str
        What is wrong, in words that need no design document (D44).
    source : str
        Which check found it: ``"text"``, ``"model"``, ``"check"`` or ``"alis"``.

    Generated by RJC and Claude.
    """

    line: int | None
    severity: str
    message: str
    source: str = "text"


@dataclass(frozen=True)
class Token:
    """
    A word of the text, and where it is.

    Attributes
    ----------
    text : str
        The word.
    line : int
        Its line, from 0.
    start, end : int
        Its first column, and one past its last, on that line.

    Generated by RJC and Claude.
    """

    text: str
    line: int
    start: int
    end: int

    def part(self, first, last=None):
        """
        A part of this token, as a token: ``self.text[first:last]``.

        Parameters
        ----------
        first : int
            The first character, from the start of the token.
        last : int, optional
            One past the last character; by default the end of the token.

        Returns
        -------
        Token

        Generated by RJC and Claude.
        """
        last = len(self.text) if last is None else last
        return Token(
            self.text[first:last], self.line, self.start + first, self.start + last
        )


@dataclass(frozen=True)
class Line:
    """
    One line of the text.

    Attributes
    ----------
    num : int
        The line number, from 0.
    text : str
        The line, without its ending.
    ending : str
        ``"\\n"``, ``"\\r\\n"``, ``"\\r"``, or ``""`` for a last line with none.
    offset : int
        Where the line starts in the whole text.
    kind : str
        What the line is (``BLANK``, ``COMMENT``, ``LONG``, ``HIDDEN``,
        ``SETTING``, ``BLOCK``, ``DATA``, ``SECTION``, ``FIX``, ``LIM``,
        ``FUNCTION`` or ``LINK``).
    block : str
        The block it is in (``"data"``, ``"model"`` or ``"link"``), or ``""``. A
        ``BLOCK`` line names the block it opens or closes.
    content : tuple of int
        The columns of the text that ALIS reads, ``(start, end)``. For a line with
        no content, the span is empty.
    tokens : tuple of Token
        The words of the content.

    Generated by RJC and Claude.
    """

    num: int
    text: str
    ending: str
    offset: int
    kind: str
    block: str
    content: tuple
    tokens: tuple

    @property
    def words(self):
        """The words of the content, as strings."""
        return [tok.text for tok in self.tokens]

    @property
    def indent(self):
        """The white space before the line's first character."""
        return self.text[: len(self.text) - len(self.text.lstrip())]

    @property
    def comment(self):
        """The text after the content (a trailing comment), or ``""``."""
        return self.text[self.content[1] :].strip() if self.kind in CONTENT else ""

    @property
    def end(self):
        """Where the line's ending starts in the whole text."""
        return self.offset + len(self.text)


def split_lines(text):
    """
    Split a text into ``(text, ending, offset)`` for each line.

    Lines end at ``\\r\\n``, ``\\n`` or ``\\r``, as Python's universal newlines read
    a model file. Joining ``text + ending`` over the lines gives back the text.

    Parameters
    ----------
    text : str
        The text.

    Returns
    -------
    list of tuple
        One ``(text, ending, offset)`` per line.

    Generated by RJC and Claude.
    """
    lines, pos = [], 0
    for match in _NEWLINE.finditer(text):
        lines.append((text[pos : match.start()], match.group(), pos))
        pos = match.end()
    if pos < len(text):
        lines.append((text[pos:], "", pos))
    return lines


def _words(text, start, end, num):
    """The words of ``text[start:end]``, as tokens of line ``num``."""
    return tuple(
        Token(m.group(), num, m.start(), m.end())
        for m in _WORD.finditer(text, start, end)
    )


def _model_kind(first):
    """The kind of a line of the model block, from its first word."""
    if first in SECTIONS:
        return SECTION
    if first == "fix":
        return FIX
    if first == "lim":
        return LIM
    return FUNCTION


class ModelText:
    """
    A model's text, read as ALIS reads it.

    Parameters
    ----------
    text : str
        The whole model, as written.

    Attributes
    ----------
    text : str
        The text, unchanged.
    lines : tuple of Line
        Every line, in order.
    problems : tuple of Problem
        What is wrong with the text's structure: a block that is not closed, a
        long comment closed before it is opened, and so on.

    Generated by RJC and Claude.
    """

    def __init__(self, text):
        self.text = text
        self.lines, self.problems = self._read(text)
        self._starts = [line.offset for line in self.lines]

    def __len__(self):
        return len(self.lines)

    def __iter__(self):
        return iter(self.lines)

    def __getitem__(self, num):
        return self.lines[num]

    # -- reading --------------------------------------------------------------------

    @staticmethod
    def _read(text):
        """
        Classify every line, as ``alis.load.load_input`` does.

        Returns
        -------
        tuple
            ``(lines, problems)``.

        Generated by RJC and Claude.
        """
        lines, problems = [], []
        state = {name: 0 for name in BLOCKS}  # 0 not seen, 1 open, 2 closed
        inlong = False
        for num, (body, ending, offset) in enumerate(split_lines(text)):
            stripped = body.strip()
            hash_at = body.find("#")
            start = len(body) - len(body.lstrip())
            stop = hash_at if hash_at >= 0 else len(body)
            if inlong:
                if LONG_CLOSE not in body:
                    lines.append(Line(num, body, ending, offset, LONG, "", (0, 0), ()))
                    continue
                inlong = False
                start = body.index(LONG_CLOSE) + len(LONG_CLOSE)
                stop = len(body)
                if LONG_OPEN in body[start:]:
                    problems.append(
                        Problem(
                            num,
                            "error",
                            "Only one long comment"
                            " marker ('#-->' or '<--#') may be"
                            " used on a line.",
                        )
                    )
                if not body[start:].strip():
                    lines.append(Line(num, body, ending, offset, LONG, "", (0, 0), ()))
                    continue
                problems.append(
                    Problem(
                        num,
                        "error",
                        "ALIS does not read text that"
                        " follows '<--#' on the same line correctly."
                        " Move it to a line of its own.",
                    )
                )
            elif LONG_CLOSE in body:
                problems.append(
                    Problem(
                        num,
                        "error",
                        "This line ends a long comment"
                        " ('<--#') that was never started ('#-->').",
                    )
                )
            if LONG_OPEN in body:
                inlong = True
                if LONG_CLOSE in body.split(LONG_OPEN, 1)[1]:
                    problems.append(
                        Problem(
                            num,
                            "error",
                            "Only one long comment"
                            " marker ('#-->' or '<--#') may be"
                            " used on a line.",
                        )
                    )
            tokens = _words(body, start, stop, num)
            if not tokens:
                kind = BLANK if not stripped else COMMENT
                lines.append(
                    Line(num, body, ending, offset, kind, "", (stop, stop), ())
                )
                continue
            content = (tokens[0].start, tokens[-1].end)
            words = [tok.text for tok in tokens]
            if len(words) == 1 and _HIDDEN.match(words[0]):
                lines.append(
                    Line(num, body, ending, offset, HIDDEN, "", content, tokens)
                )
                continue
            kind, block = SETTING, ""
            for name in BLOCKS:
                if state[name] == 1:
                    block = name
                    if words[:2] == [name, "end"]:
                        state[name] = 2
                        kind = BLOCK
                    elif name == "data":
                        kind = DATA
                    elif name == "model":
                        kind = _model_kind(words[0])
                    else:
                        kind = LINK
                    break
                if state[name] == 0 and words[:2] == [name, "read"]:
                    state[name] = 1
                    kind, block = BLOCK, name
                    break
            lines.append(Line(num, body, ending, offset, kind, block, content, tokens))
        if state["data"] == 0:
            problems.append(
                Problem(
                    None,
                    "error",
                    "The model has no data block" " ('data read' ... 'data end').",
                )
            )
        elif state["data"] == 1:
            problems.append(
                Problem(
                    None,
                    "error",
                    "The data block is not closed:" " 'data end' is missing.",
                )
            )
        if state["model"] == 0:
            problems.append(
                Problem(
                    None,
                    "error",
                    "The model has no model block" " ('model read' ... 'model end').",
                )
            )
        elif state["model"] == 1:
            problems.append(
                Problem(
                    None,
                    "error",
                    "The model block is not closed:" " 'model end' is missing.",
                )
            )
        if state["link"] == 1:
            problems.append(
                Problem(
                    None,
                    "warning",
                    "The link block is not closed:" " 'link end' is missing.",
                )
            )
        return tuple(lines), tuple(problems)

    # -- finding things -------------------------------------------------------------

    def of_kind(self, *kinds):
        """
        The lines of the given kinds, in order.

        Parameters
        ----------
        *kinds : str
            Line kinds, such as ``DATA`` or ``FUNCTION``.

        Returns
        -------
        list of Line

        Generated by RJC and Claude.
        """
        return [line for line in self.lines if line.kind in kinds]

    def block_lines(self, block):
        """
        The lines that open and close a block, as ``(open, close)``.

        Either is None when the block lacks it.

        Generated by RJC and Claude.
        """
        opened = closed = None
        for line in self.lines:
            if line.kind == BLOCK and line.block == block:
                if line.words[1] == "read" and opened is None:
                    opened = line.num
                elif line.words[1] == "end":
                    closed = line.num
        return opened, closed

    def offset(self, line, col=0):
        """
        The offset in the whole text of a line and column.

        Parameters
        ----------
        line : int
            The line, from 0. ``len(self)`` is the end of the text.
        col : int
            The column on that line.

        Returns
        -------
        int

        Generated by RJC and Claude.
        """
        if line == len(self.lines):
            return len(self.text)
        return self.lines[line].offset + col

    def token_offset(self, token):
        """Where a token starts in the whole text."""
        return self.offset(token.line, token.start)

    def position(self, offset):
        """
        The ``(line, column)`` of an offset in the whole text.

        Generated by RJC and Claude.
        """
        if not self.lines:
            return 0, 0
        num = max(0, bisect.bisect_right(self._starts, offset) - 1)
        return num, offset - self.lines[num].offset

    def token_at(self, line, col):
        """
        The word at a line and column, or None.

        Generated by RJC and Claude.
        """
        for tok in self.lines[line].tokens:
            if tok.start <= col < tok.end:
                return tok
        return None

    def newline(self):
        """The line ending used most in the text (``"\\n"`` if none)."""
        counts = {}
        for line in self.lines:
            if line.ending:
                counts[line.ending] = counts.get(line.ending, 0) + 1
        return max(counts, key=counts.get) if counts else "\n"

    # -- changing it ----------------------------------------------------------------

    def apply(self, change):
        """
        The text that a patch or a change gives.

        Parameters
        ----------
        change : Patch or Change

        Returns
        -------
        ModelText

        Generated by RJC and Claude.
        """
        return ModelText(change.apply(self.text))


# -- Values, labels and keywords ---------------------------------------------------

_SIGNED_EXPONENT = ("E+", "e+", "E-", "e-")


def split_value(token):
    """
    Split a parameter into its value and its label, as ALIS does.

    ``5.0da`` is the value ``5.0`` with the label ``da``. The only exponent ALIS
    reads is a signed one (``1.0E+04``), so ``1e4`` is the value ``1`` with the label
    ``e4`` (``alis.functions.base.check_tie_label``).

    Parameters
    ----------
    token : Token
        The parameter, without any ``name=`` before it.

    Returns
    -------
    tuple
        ``(value, label)``: two tokens, the label None when there is none.

    Generated by RJC and Claude.
    """
    text = token.text
    tie = text.lstrip("+-.0123456789")
    if tie[:2] in _SIGNED_EXPONENT:
        tie = tie[2:].lstrip(".0123456789")
    cut = len(text) - len(tie)
    return token.part(0, cut), (token.part(cut) if tie else None)


def split_keyword(token):
    """
    Split ``key=value`` into two tokens, or None if there is no ``=``.

    Generated by RJC and Claude.
    """
    if "=" not in token.text:
        return None
    cut = token.text.index("=")
    return token.part(0, cut), token.part(cut + 1)


def function_args(token):
    """
    Split a function call such as ``vfwhm(6.974va)`` into its name and arguments.

    The arguments are separated by commas, as the resolution and shift functions
    read them. Anything after a ``;`` holds keywords (``lsfspline(...;locations:...)``)
    and is not returned.

    Parameters
    ----------
    token : Token
        The call, e.g. the value of ``resolution=``.

    Returns
    -------
    tuple
        ``(name, args)``: the name as a token, and a list of tokens, one per
        argument; ``(token, [])`` if the token is not a call.

    Generated by RJC and Claude.
    """
    text = token.text
    if "(" not in text:
        return token, []
    cut = text.index("(")
    close = text.rindex(")") if text.endswith(")") else len(text)
    inner = text[cut + 1 : close].split(";")[0]
    args, pos = [], cut + 1
    for piece in inner.split(","):
        args.append(token.part(pos, pos + len(piece)))
        pos += len(piece) + 1
    return token.part(0, cut), [arg for arg in args if arg.text]


# -- Patches -----------------------------------------------------------------------


@dataclass(frozen=True)
class Patch:
    """
    Replace ``old`` with ``new`` at ``start`` in a text.

    A patch changes only its own span, and its inverse gives the text back.

    Attributes
    ----------
    start : int
        Where the span starts in the whole text.
    old : str
        The text the span holds now.
    new : str
        The text it will hold.

    Generated by RJC and Claude.
    """

    start: int
    old: str
    new: str

    @property
    def end(self):
        """One past the end of the span, before the patch."""
        return self.start + len(self.old)

    def apply(self, text):
        """
        The text with this patch applied.

        Raises
        ------
        PatchError
            If the span does not hold ``old``.

        Generated by RJC and Claude.
        """
        if text[self.start : self.end] != self.old:
            raise PatchError("The text has changed: the patch does not fit it.")
        return text[: self.start] + self.new + text[self.end :]

    def inverse(self):
        """The patch that undoes this one."""
        return Patch(self.start, self.new, self.old)

    def map_line(self, mtext, num):
        """
        Where line ``num`` of ``mtext`` is after this patch, or None if it is gone.

        A line that starts before the replaced span keeps its number. A line that
        starts after it moves by the number of line endings added. A line that
        starts inside it is gone, unless the span starts with the line and holds
        no line ending (an edit within the line).

        Parameters
        ----------
        mtext : ModelText
            The text before the patch.
        num : int
            A line of that text.

        Returns
        -------
        int or None

        Generated by RJC and Claude.
        """
        start = mtext[num].offset
        if start < self.start:
            return num
        if start >= self.end:
            added = len(_NEWLINE.findall(self.new)) - len(_NEWLINE.findall(self.old))
            return num + added
        if start == self.start and not _NEWLINE.search(self.old):
            return num
        return None


@dataclass(frozen=True)
class Change:
    """
    Several patches, applied in order: one edit of the text.

    Each patch's ``start`` refers to the text left by the patches before it.

    Attributes
    ----------
    patches : tuple of Patch
    description : str
        What the change does, for the history (F2).

    Generated by RJC and Claude.
    """

    patches: tuple = ()
    description: str = ""

    def __bool__(self):
        return any(p.old != p.new for p in self.patches)

    def apply(self, text):
        """The text with every patch applied, in order."""
        for patch in self.patches:
            text = patch.apply(text)
        return text

    def inverse(self):
        """The change that undoes this one."""
        return Change(
            tuple(p.inverse() for p in reversed(self.patches)), self.description
        )

    def then(self, other):
        """This change, followed by ``other`` (applied to this one's result)."""
        return Change(
            self.patches + other.patches, self.description or other.description
        )

    def map_line(self, mtext, num):
        """
        Where line ``num`` of ``mtext`` is after the whole change, or None.

        Generated by RJC and Claude.
        """
        for patch in self.patches:
            if num is None:
                return None
            num = patch.map_line(mtext, num)
            mtext = ModelText(patch.apply(mtext.text))
        return num

    @staticmethod
    def from_spans(patches, description=""):
        """
        A change made of patches that were all computed on the same text.

        The patches must not overlap. They are applied from the end of the text
        backwards, so that each one's offset is still right when it is applied.

        Generated by RJC and Claude.
        """
        ordered = sorted(patches, key=lambda p: (p.start, p.end), reverse=True)
        for later, earlier in zip(ordered, ordered[1:]):
            if earlier.end > later.start:
                raise PatchError("Two patches of one change overlap.")
        return Change(tuple(ordered), description)


def replace_token(mtext, token, new, keep_columns=True):
    """
    The patch that replaces one word, or part of one (Q2.6).

    When the word changes length, the word after it keeps its column if the gap
    allows; otherwise one space is left. A gap that holds a tab is kept as it is,
    and so is the white space after the last word of a line. Nothing else on the
    line changes. When ``token`` is part of a word, such as the value of
    ``13.0ra``, the rest of the word moves with it.

    Parameters
    ----------
    mtext : ModelText
        The text.
    token : Token
        The word, or part of a word, to replace.
    new : str
        Its new text.
    keep_columns : bool
        Respace the gap after the word so that the next word keeps its column.

    Returns
    -------
    Patch

    Generated by RJC and Claude.
    """
    body = mtext[token.line].text
    start = mtext.offset(token.line, token.start)
    wend = token.end
    while wend < len(body) and body[wend] not in " \t":
        wend += 1
    nextcol = wend
    while nextcol < len(body) and body[nextcol] in " \t":
        nextcol += 1
    gap = body[wend:nextcol]
    tail = body[token.end : wend]
    delta = len(new) - len(token.text)
    if not keep_columns or not delta or not gap or "\t" in gap or nextcol == len(body):
        return Patch(start, token.text, new)
    newgap = " " * max(nextcol - (wend + delta), 1)
    return Patch(start, token.text + tail + gap, new + tail + newgap)


def replace_line(mtext, num, new):
    """
    The patch that replaces the text of line ``num`` (not its ending).

    Generated by RJC and Claude.
    """
    line = mtext[num]
    return Patch(line.offset, line.text, new)


def replace_lines(mtext, first, last, new_lines):
    """
    The patch that replaces lines ``first`` to ``last - 1`` with ``new_lines``.

    With ``first == last`` it inserts the new lines before line ``first``; with no
    new lines it deletes. New lines take the text's usual line ending. Inserting
    after a last line that has no ending gives that line one, and leaves the new
    last line without one, as the text was.

    Parameters
    ----------
    mtext : ModelText
    first, last : int
        The lines to replace, ``first <= last <= len(mtext)``.
    new_lines : list of str
        The new lines, without endings.

    Returns
    -------
    Patch

    Generated by RJC and Claude.
    """
    newline = mtext.newline()
    nlines = len(mtext)
    if first == last == nlines and nlines and not mtext[nlines - 1].ending:
        # Appending after a last line with no ending
        if not new_lines:
            return Patch(len(mtext.text), "", "")
        return Patch(len(mtext.text), "", newline + newline.join(new_lines))
    start = mtext.offset(first)
    stop = mtext.offset(last)
    old = mtext.text[start:stop]
    new = "".join(line + newline for line in new_lines)
    if last == nlines and nlines and not mtext[nlines - 1].ending and new:
        # Replacing the last line, which has no ending: keep it without one
        new = new[: -len(newline)]
    elif last == nlines and nlines and not mtext[nlines - 1].ending and not new:
        # Deleting the last line: the line before it loses its ending instead
        if first > 0:
            start = mtext.offset(first - 1) + len(mtext[first - 1].text)
            old = mtext.text[start:stop]
    return Patch(start, old, new)


def insert_lines(mtext, before, new_lines):
    """The patch that inserts ``new_lines`` before line ``before``."""
    return replace_lines(mtext, before, before, new_lines)


def delete_lines(mtext, first, last=None):
    """The patch that deletes lines ``first`` to ``last - 1`` (one line by default)."""
    return replace_lines(mtext, first, first + 1 if last is None else last, [])


def layout_like(template, words):
    """
    Lay out a new line in the style of an existing one (the text-sync contract).

    The new line takes the template's indentation, and each word starts at the
    column of the template's word in the same place when there is room, and one
    space later otherwise. Words beyond the template's are separated by the
    template's last gap.

    Parameters
    ----------
    template : Line or None
        A line of the same kind, or None for two spaces of indentation and two
        spaces between words.
    words : list of str
        The words of the new line.

    Returns
    -------
    str

    Generated by RJC and Claude.
    """
    if template is None or not template.tokens:
        return "  " + "  ".join(words)
    toks = template.tokens
    gap = toks[-1].start - toks[-2].end if len(toks) > 1 else 2
    gap = max(gap, 1)
    out = template.indent
    for num, word in enumerate(words):
        if num == 0:
            out += word
            continue
        want = toks[num].start if num < len(toks) else len(out) + gap
        out += " " * max(want - len(out), 1) + word
    return out


__all__ = [
    "BLANK",
    "COMMENT",
    "LONG",
    "HIDDEN",
    "SETTING",
    "BLOCK",
    "DATA",
    "SECTION",
    "FIX",
    "LIM",
    "FUNCTION",
    "LINK",
    "CONTENT",
    "SECTIONS",
    "Problem",
    "Token",
    "Line",
    "ModelText",
    "Patch",
    "Change",
    "PatchError",
    "split_lines",
    "split_value",
    "split_keyword",
    "function_args",
    "replace_token",
    "replace_line",
    "replace_lines",
    "insert_lines",
    "delete_lines",
    "layout_like",
]
