"""
Staging and execution helpers for the ALIS regression harness
(Stage 0.2).

Every test run is staged in a disposable copy of the whole example
directory (made under pytest's tmp_path), so no file in the
repository -- in particular no ``.mod.out.reference``,
``reference_fits/`` golden file, or covariance reference -- is ever
touched by a test. ALIS itself is executed in a subprocess (running
``alis/scripts/run_alis.py``) with the working directory set to the staged
model directory, exactly as a user would run it, with the ``-f``
(write model fits) and ``-w`` (overwrite) flags and a non-interactive
matplotlib backend.

Two run modes are provided (Stage 0.2):

- :func:`stage_case` + :func:`run_alis` on the staged ``.mod`` file
  implements the minimisation test (mode a);
- :func:`make_fixedparam_mod` writes a copy of the case's
  ``.mod.out.reference`` (itself a valid ``.mod`` input) with
  ``chisq miniter 0`` / ``chisq maxiter 0`` forced, implementing the
  fixed-parameter gate (mode b, "option A").
"""

import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from manifest import REPO_ROOT, RegressionCase

# The run_alis entry point shipped with the repository (guarantees
# the subprocess exercises this checkout, not another installation).
# Executed as a script directly; its ``__main__`` guard calls
# ``console_entry`` -- the same code path as the pyproject console
# script -- so the harness and installed ``run_alis`` command agree.
RUN_ALIS = REPO_ROOT / "alis" / "scripts" / "run_alis.py"

# Baseline subprocess timeout (seconds) plus a generous multiple of
# the reference runtime, to tolerate slower machines.
BASE_TIMEOUT_S = 600.0
RUNTIME_TIMEOUT_FACTOR = 4.0

# Active settings lines to strip when building a fixed-parameter
# .mod file from a .mod.out.reference (they are re-inserted as 0).
_CHISQ_ITER_RE = re.compile(r"^\s*chisq\s+(miniter|maxiter)\b", re.IGNORECASE)
# The fixed-parameter gate compares chi-squared, DOF and the model
# column only -- never the covariance. Computing/writing the
# covariance for the large real-world models is expensive (a
# 339-parameter numerical Hessian for DH/HS0105p1619 pushed a single
# evaluation past a 19-minute timeout), so drop the "out covar"
# setting from the fixed-parameter input: it removes that cost with
# no loss of what mode (b) checks (the covariance is still exercised
# by the mode-(a) minimisation test).
_OUT_COVAR_RE = re.compile(r"^\s*out\s+covar\b", re.IGNORECASE)
# "run convergence True" puts ALIS in convergence-testing mode, which
# re-fits the model repeatedly from perturbed starts -- for a single
# fixed-parameter evaluation that is an unbounded loop (DH/HS0105p1619
# spun past the timeout re-printing "ITERATION 1 ... CONVERGENCE").
# Strip it so mode (b) performs exactly one evaluation.
_RUN_CONVERGENCE_RE = re.compile(r"^\s*run\s+convergence\b", re.IGNORECASE)
# ALIS prints the voigt default damping explicitly (as a suffixless
# "damping=0.0000000") in .mod.out even when the input did not set
# it, and on re-read an explicit suffixless keyword parameter is
# treated as FREE whereas the implicit default is fixed -- changing
# the DOF (e.g. helium34/tet02OriA: 3 such lines, DOF 618 vs 621).
# Strip the artifact when building the fixed-parameter input.
_ZERO_DAMPING_RE = re.compile(r"\s+damping=0\.0+(?=\s)")
# Stage 4.3a: the harness pins every regression run to the CPU backend, so the
# suite stays deterministic and CPU-only whatever a model file asks for (Q4.2).
# GPU coverage is the on-demand `gpu`-marked tests (Q4.9). Set by replacing any
# existing line rather than prepending one, because settings are applied in file
# order and a later "run backend" would otherwise win.
_RUN_BACKEND_RE = re.compile(r"^\s*run\s+backend\b", re.IGNORECASE)


@dataclass(frozen=True)
class StagedCase:
    """
    A regression case staged in a disposable working copy.

    Attributes
    ----------
    case : RegressionCase
        The manifest entry being run.
    root : Path
        The staged copy of ``case.example_dir``.

    Generated by RJC and Claude.
    """

    case: RegressionCase
    root: Path

    def staged(self, path):
        """
        Map a repository path of this case into the staged copy.

        Parameters
        ----------
        path : Path
            A path inside ``case.example_dir``.

        Returns
        -------
        Path
            The corresponding path under ``root``.

        Generated by RJC and Claude.
        """
        return self.root / path.relative_to(self.case.example_dir)

    @property
    def model_dir(self):
        """
        Return the staged model directory (cwd for run_alis).

        Generated by RJC and Claude.
        """
        return self.staged(self.case.mod_file.parent)

    def fit_output_for(self, reference):
        """
        Return the staged path ALIS will write for a golden file.

        The produced ``_fit.dat`` (or generated data file) has the
        same basename as its golden copy but lives in the data
        directory itself, not in ``reference_fits/``.

        Parameters
        ----------
        reference : Path
            A golden file from ``<datadir>/reference_fits/``.

        Returns
        -------
        Path
            ``<staged datadir>/<reference basename>``.

        Generated by RJC and Claude.
        """
        return self.staged(reference.parent.parent) / reference.name


def stage_case(case, tmp_path):
    """
    Copy a case's example directory into a disposable location.

    Stale working outputs that may be checked in alongside the
    example (the ``.mod.out``, previously produced ``_fit.dat``
    files, a previous covariance output, and -- for generate cases --
    the data file itself) are removed from the copy so every test
    starts clean and the overwrite behaviour of ALIS never matters.

    Parameters
    ----------
    case : RegressionCase
        The manifest entry to stage.
    tmp_path : Path
        A per-test temporary directory (pytest's tmp_path fixture).

    Returns
    -------
    StagedCase
        Handle for the staged copy.

    Generated by RJC and Claude.
    """
    root = tmp_path / case.example_dir.name
    shutil.copytree(case.example_dir, root)
    staged = StagedCase(case=case, root=root)
    stale = [staged.staged(case.mod_file).with_suffix(".mod.out")]
    if case.covar_output is not None:
        stale.append(staged.staged(case.covar_output))
    for pair in case.data_pairs:
        if case.kind == "generate":
            stale.append(staged.staged(pair.input_file))
        for ref in pair.reference_fits:
            stale.append(staged.fit_output_for(ref))
    for path in stale:
        if path.exists():
            path.unlink()
    return staged


def force_cpu_backend(mod_file):
    """
    Pin a staged .mod file to ``run backend cpu`` (Stage 4.3a).

    Any existing ``run backend`` line is removed first: settings are applied in
    file order, so prepending an override to a file that already sets the key
    would do nothing -- the later line would win. Same strip-then-insert shape
    as :func:`make_fixedparam_mod`'s handling of ``chisq miniter``/``maxiter``.

    Parameters
    ----------
    mod_file : Path
        A staged (disposable) .mod file.

    Generated by RJC and Claude.
    """
    kept = [
        ln for ln in mod_file.read_text().splitlines() if not _RUN_BACKEND_RE.match(ln)
    ]
    mod_file.write_text("run backend cpu\n" + "\n".join(kept) + "\n")


def run_alis(mod_file, runtime_hrs=None):
    """
    Run ALIS on a staged .mod file in a subprocess.

    The subprocess runs with cwd set to the .mod file's directory
    (as a user would), with ``-f -w`` so model fits are written and
    overwritten, and with MPLBACKEND=Agg so any ``plot fits True``
    example cannot open an interactive window.

    Parameters
    ----------
    mod_file : Path
        The staged .mod file to run.
    runtime_hrs : float | None
        Reference runtime of the case, used to scale the timeout.

    Returns
    -------
    subprocess.CompletedProcess
        The finished process (raises AssertionError on a non-zero
        exit status, with the tail of the combined output).

    Generated by RJC and Claude.
    """
    timeout = BASE_TIMEOUT_S
    if runtime_hrs is not None:
        timeout += RUNTIME_TIMEOUT_FACTOR * runtime_hrs * 3600.0
    force_cpu_backend(mod_file)
    env = dict(os.environ)
    env["MPLBACKEND"] = "Agg"
    # "-p 0" disables on-screen plotting: some examples set
    # "plot fits True", which blocks on an interactive figure and
    # hangs a headless run (lineemission, voigtconv timed out at
    # ~10 min). Plotting does not affect the compared outputs
    # (.mod.out / _fit.dat / covar), so this only makes the run
    # headless. NB: run_alis takes the mod filename from sys.argv[-1],
    # so the .mod file must stay the last argument.
    proc = subprocess.run(
        [
            sys.executable,
            str(RUN_ALIS),
            "-f",
            "-w",
            "-p",
            "0",
            mod_file.name,
        ],
        cwd=mod_file.parent,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if proc.returncode != 0:
        tail = (proc.stdout + proc.stderr)[-3000:]
        raise AssertionError(
            f"run_alis {mod_file.name} exited with status "
            f"{proc.returncode}; output tail:\n{tail}"
        )
    return proc


def make_fixedparam_mod(staged):
    """
    Build the fixed-parameter (mode b) input for a staged case.

    Copies the case's ``.mod.out.reference`` -- which is itself a
    valid ``.mod`` input holding the best-fit parameters -- into the
    staged model directory as ``<stem>_fixedparam.mod``, with any
    active ``chisq miniter`` / ``chisq maxiter`` settings removed and
    both forced to 0, so ALIS evaluates the model at the best-fit
    values without minimising ("option A", Stage 0.2b).

    Where a ``.mod.out.reference_adjusted`` sibling exists (RJC's
    hand-fixed re-input for cases whose plain reference is not a
    faithful re-input on the current code -- an output-writer
    round-trip bug), that adjusted file is used as the source
    instead; the χ²/DOF are still compared against the plain
    reference by the caller.

    The ``out covar`` setting is dropped (mode b never compares the
    covariance, and computing it is expensive for large models), and
    ``run convergence True`` is dropped (it re-fits repeatedly, which
    for a single evaluation never terminates).

    Two write-out artifacts of the .mod.out format are corrected so
    the re-read model matches the original fit's structure:
    - any active ``random`` model line is rewritten as the
      equivalent ``variable`` line (dropping ``command=``/``start=``):
      ``random`` would re-draw a new value on every run, whereas
      ``variable`` keeps the best-fit value from the reference;
    - suffixless ``damping=0.0000000`` keywords (the explicitly
      printed voigt default) are stripped, because on re-read they
      would become free parameters and change the DOF.

    Parameters
    ----------
    staged : StagedCase
        The staged case (must have a .mod.out.reference).

    Returns
    -------
    Path
        The staged fixed-parameter .mod file.

    Generated by RJC and Claude.
    """
    case = staged.case
    source = case.mod_out_reference_adjusted or case.mod_out_reference
    kept = []
    in_model = False
    for raw in source.read_text().splitlines():
        stripped = raw.strip()
        if stripped.startswith("#"):
            kept.append(raw)
            continue
        if _CHISQ_ITER_RE.match(raw):
            continue
        if _OUT_COVAR_RE.match(raw):
            continue
        if _RUN_CONVERGENCE_RE.match(raw):
            continue
        low = stripped.lower()
        if low.startswith("model read"):
            in_model = True
        elif low.startswith("model end"):
            in_model = False
        elif in_model:
            raw = _ZERO_DAMPING_RE.sub(" ", raw)
            if stripped.split()[:1] == ["random"]:
                tokens = [
                    t
                    for t in stripped.split()[1:]
                    if not t.startswith(("command=", "start="))
                ]
                raw = "  variable   " + "      ".join(tokens)
        kept.append(raw)
    text = "chisq miniter 0\nchisq maxiter 0\n" + "\n".join(kept)
    out = staged.model_dir / (case.mod_file.stem + "_fixedparam.mod")
    out.write_text(text + "\n")
    return out


def timeout_note(case):
    """
    Return a short human-readable runtime hint for a case.

    Parameters
    ----------
    case : RegressionCase
        The manifest entry.

    Returns
    -------
    str
        E.g. "reference runtime 0.9 min" (empty if unknown).

    Generated by RJC and Claude.
    """
    if case.runtime_hrs is None:
        return ""
    return f"reference runtime {case.runtime_hrs * 60.0:.1f} min"
