"""
Output parsing and tolerance comparisons for the ALIS regression
harness (Stage 0.2 / 0.4).

This module knows how to parse an ALIS ``.mod.out`` file (best-fit
parameters, their 1-sigma errors, the convolution/shift models, the
chi-squared and degrees-of-freedom from the header) and how to compare
every output artifact against its committed golden reference within
the Stage 0.4 tolerances:

- best-fit parameters: within ``PARAM_HARD_NSIGMA`` (10%) of the
  parameter's 1-sigma error (hard failure), with the softer
  ``PARAM_SOFT_NSIGMA`` (50%) bound reported in the message when it
  is also exceeded;
- chi-squared: 1% relative (minimisation test) or 0.1% relative
  (fixed-parameter gate) -- passed in by the caller;
- ``_fit.dat`` model column: 1e-4 relative (with a small absolute
  floor for near-zero pixels, e.g. saturated line cores);
- covariance matrix: 1% relative, with an absolute floor of 1% of
  sqrt(C_ii * C_jj) for near-zero off-diagonal elements.

Blinded parameters are handled per Stage 0.2a: ``blind=True`` lines
are rendered as ``------ BLIND MODEL ------`` and are skipped (both
files must be blind at the same position), while ``blindrange``
parameters keep a visible fixed-offset value and are compared
directly (the offset is identical in both files and cancels).

All comparison functions return a list of human-readable failure
strings (empty when the artifact matches), so one test can report
every mismatch of a run at once.
"""

import re
from dataclasses import dataclass, field

import numpy as np

# ----------------------------------------------------------------- #
# Stage 0.4 tolerances                                               #
# ----------------------------------------------------------------- #
# Best-fit parameters: |out - ref| as a fraction of the 1-sigma error.
PARAM_HARD_NSIGMA = 0.10
PARAM_SOFT_NSIGMA = 0.50
# 1-sigma errors themselves: relative tolerance on the error value.
ERROR_RTOL = 0.10
# Parameters whose reference 1-sigma error is printed as zero:
# - with a tie/fix suffix (e.g. "ratrand", "TA"): tied followers
#   inherit their host's variance but print sigma = 0, and can
#   jitter at the print-precision level, so use a tight relative
#   fallback instead of exact equality;
# - without a suffix: a free but degenerate parameter (e.g. an
#   unconstrained nuisance component) that can move arbitrarily with
#   no effect on the model -- skip it; the chi-squared and the
#   _fit.dat model-column comparisons gate any change that matters.
ZERO_SIGMA_RTOL = 1.0e-4
ZERO_SIGMA_ATOL = 1.0e-8
# Chi-squared relative tolerances (picked by the caller per mode).
CHISQ_RTOL_MINIMISATION = 0.01
CHISQ_RTOL_FIXEDPARAM = 0.001
# _fit.dat model column: relative, with an absolute floor for pixels
# where the model is essentially zero (saturated line cores).
FITDAT_RTOL = 1.0e-4
FITDAT_ATOL = 1.0e-6
# The fixed-parameter gate evaluates the model at the *printed*
# (8-significant-digit) best-fit parameters, and steep saturated
# line cores amplify that truncation in the model column: measured
# up to 3.4e-4 (examples/random O I core) and 1.5e-3 (DH_orders,
# J1358p6522 C II core walls) across the otherwise-clean cases, so
# mode (b) uses a looser relative tolerance; its sharp gate is the
# 0.1% chi-squared check. Cases whose amplification is pathological
# (sharp tophat/brokenpowerlaw edges, saturated Lyman cores) are
# excluded from the gate instead (see FIXEDPARAM_EXCLUDE).
FITDAT_RTOL_FIXEDPARAM = 2.0e-3
# Covariance matrix: relative, with an absolute floor of
# COVAR_RTOL * sqrt(C_ii * C_jj) per element.
COVAR_RTOL = 0.01

# The sentinel ALIS writes for pixels outside the fitrange.
SENTINEL = -9.999999999e9

# The placeholder ALIS writes in place of a blind=True model line.
BLIND_MARKER = "------ BLIND MODEL ------"

# Leading numeric part of a parameter token (the remainder is the
# tied/fixed-parameter suffix, e.g. "4.998963da" -> 4.998963 + "da").
_NUM_RE = re.compile(
    r"^([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)(.*)$"
)
_CHISQ_RE = re.compile(r"Bestfit Chi-Squared\s*=\s*([0-9.eE+\-]+)")
_DOF_RE = re.compile(r"Degrees-of-Freedom\s*=\s*(\d+)")


@dataclass
class ModOut:
    """
    Parsed content of an ALIS .mod.out file.

    Attributes
    ----------
    chisq : float
        Best-fit chi-squared from the header.
    dof : int
        Degrees of freedom from the header.
    sections : dict[str, tuple[list[str], list[str]]]
        Maps section name ("model", "convolution", "shift") to a
        (value lines, error lines) tuple. Value lines of the model
        section are the active lines between "model read" and
        "model end"; the other sections and all error lines come from
        the commented blocks that follow (leading "#" stripped).

    Generated by RJC and Claude.
    """

    chisq: float
    dof: int
    sections: dict = field(default_factory=dict)


def parse_mod_out(path):
    """
    Parse a .mod.out (or .mod.out.reference) file.

    Parameters
    ----------
    path : Path
        The .mod.out file to parse.

    Returns
    -------
    ModOut
        Header statistics plus the model/convolution/shift value and
        error lines. Volatile header lines (Generated by, Running
        Time, Num. of Iterations) are ignored.

    Generated by RJC and Claude.
    """
    text = path.read_text()
    chisq_m = _CHISQ_RE.search(text)
    dof_m = _DOF_RE.search(text)
    if chisq_m is None or dof_m is None:
        raise ValueError(
            "could not find chi-squared / DOF in header of "
            f"{path}"
        )
    result = ModOut(
        chisq=float(chisq_m.group(1)), dof=int(dof_m.group(1))
    )
    values = {"model": [], "convolution": [], "shift": []}
    errors = {"model": [], "convolution": [], "shift": []}
    in_model = False
    after_model = False
    section = "model"
    target = None  # collecting list once "Errors:" etc. is seen
    for raw in text.splitlines():
        stripped = raw.strip()
        low = stripped.lower()
        if not after_model:
            # Active region: collect the model block value lines.
            if low.startswith("model read"):
                in_model = True
                continue
            if low.startswith("model end"):
                in_model = False
                after_model = True
                continue
            if in_model and stripped and not stripped.startswith("#"):
                values["model"].append(stripped)
            continue
        # Commented region after "model end": errors + conv/shift.
        if stripped.startswith("####"):
            break  # banner of the input-model copy: stop parsing
        if not stripped.startswith("#"):
            continue
        content = stripped.lstrip("#").strip()
        if not content:
            continue
        if content == "Errors:":
            target = errors[section]
            continue
        if content == "Convolution Models:":
            section = "convolution"
            target = values[section]
            continue
        if content == "Shift Models:":
            section = "shift"
            target = values[section]
            continue
        if target is None:
            target = values[section]
        target.append(content)
    for name in values:
        result.sections[name] = (values[name], errors[name])
    return result


def _is_function_line(line):
    """
    Decide whether a model-block line carries fitted parameters.

    Parameters
    ----------
    line : str
        A stripped model-block (or errors-block) line.

    Returns
    -------
    bool
        False for section markers (single-token lines such as
        "emission"/"absorption"/"zerolevel") and for "fix"/"lim"
        settings lines, True otherwise.

    Generated by RJC and Claude.
    """
    tokens = line.split()
    if len(tokens) <= 1:
        return False
    if tokens[0].lower() in ("fix", "lim"):
        return False
    return True


def _token_parts(token):
    """
    Split a parameter token into keyword, numeric value and suffix.

    Handles both positional tokens ("4.998963da" -> ("", 4.998963,
    "da")) and keyword tokens ("damping=11.2300905dampb" ->
    ("damping", 11.2300905, "dampb")). Non-numeric bodies return
    None for the value ("ion=16O_I" -> ("ion", None, "16O_I")).

    Parameters
    ----------
    token : str
        A whitespace token of a model or errors line.

    Returns
    -------
    tuple[str, float | None, str]
        (keyword or "", numeric value or None, suffix / raw body).

    Generated by RJC and Claude.
    """
    key = ""
    body = token
    if "=" in token:
        key, body = token.split("=", 1)
    match = _NUM_RE.match(body)
    if match is None:
        return key, None, body
    try:
        return key, float(match.group(1)), match.group(2)
    except ValueError:
        return key, None, body


def _compare_value_line(out_line, ref_line, err_line, where):
    """
    Compare one best-fit model line against the reference line.

    Numeric tokens must agree within PARAM_HARD_NSIGMA of the
    corresponding 1-sigma error from ``err_line``; tokens with a zero
    error (fixed parameters) must be identical; non-numeric tokens
    (ion=, specid=, ...) must match exactly.

    Parameters
    ----------
    out_line : str
        Line from the produced .mod.out.
    ref_line : str
        Corresponding line from the reference.
    err_line : str | None
        Corresponding 1-sigma error line from the reference (None if
        it could not be aligned; numeric differences then fail).
    where : str
        Location label used in failure messages.

    Returns
    -------
    list[str]
        Failure messages (empty when the line matches).

    Generated by RJC and Claude.
    """
    fails = []
    otok = out_line.split()
    rtok = ref_line.split()
    etok = err_line.split() if err_line is not None else []
    if len(otok) != len(rtok):
        return [
            f"{where}: token count differs\n"
            f"    out: {out_line}\n    ref: {ref_line}"
        ]
    for k, (ot, rt) in enumerate(zip(otok, rtok)):
        if ot == rt:
            continue
        okey, oval, osuf = _token_parts(ot)
        rkey, rval, rsuf = _token_parts(rt)
        if oval is None or rval is None:
            fails.append(
                f"{where}, token {k}: '{ot}' != '{rt}'"
            )
            continue
        if okey != rkey or osuf != rsuf:
            fails.append(
                f"{where}, token {k}: '{ot}' != '{rt}' "
                "(keyword/suffix mismatch)"
            )
            continue
        sigma = 0.0
        if k < len(etok):
            _, eval_, _ = _token_parts(etok[k])
            if eval_ is not None:
                sigma = abs(eval_)
        delta = abs(oval - rval)
        if sigma == 0.0:
            # Zero printed error: tied/fixed (has a suffix) -> tight
            # relative fallback; free-but-degenerate (no suffix) ->
            # skip (gated by chi-squared and the model column).
            if rsuf and delta > (
                ZERO_SIGMA_RTOL * abs(rval) + ZERO_SIGMA_ATOL
            ):
                fails.append(
                    f"{where}, token {k}: {oval!r} != {rval!r} "
                    "(zero 1-sigma error, relative fallback "
                    f"{ZERO_SIGMA_RTOL} exceeded)"
                )
        elif delta > PARAM_HARD_NSIGMA * sigma:
            soft = ""
            if delta > PARAM_SOFT_NSIGMA * sigma:
                soft = (
                    " [also exceeds the soft "
                    f"{PARAM_SOFT_NSIGMA:.0%} bound]"
                )
            fails.append(
                f"{where}, token {k}: |{oval} - {rval}| = "
                f"{delta:.6g} > {PARAM_HARD_NSIGMA:.0%} of "
                f"1-sigma ({sigma:.6g}){soft}"
            )
    return fails


def _compare_error_line(out_line, ref_line, where):
    """
    Compare one 1-sigma error line against the reference line.

    Numeric tokens must agree within ERROR_RTOL relative; a zero
    reference error must stay zero.

    Parameters
    ----------
    out_line : str
        Error line from the produced .mod.out.
    ref_line : str
        Corresponding error line from the reference.
    where : str
        Location label used in failure messages.

    Returns
    -------
    list[str]
        Failure messages (empty when the line matches).

    Generated by RJC and Claude.
    """
    fails = []
    otok = out_line.split()
    rtok = ref_line.split()
    if len(otok) != len(rtok):
        return [
            f"{where}: token count differs\n"
            f"    out: {out_line}\n    ref: {ref_line}"
        ]
    for k, (ot, rt) in enumerate(zip(otok, rtok)):
        if ot == rt:
            continue
        okey, oval, osuf = _token_parts(ot)
        rkey, rval, rsuf = _token_parts(rt)
        if oval is None or rval is None:
            fails.append(f"{where}, token {k}: '{ot}' != '{rt}'")
            continue
        if okey != rkey or osuf != rsuf:
            fails.append(
                f"{where}, token {k}: '{ot}' != '{rt}' "
                "(keyword/suffix mismatch)"
            )
            continue
        if abs(oval - rval) > ERROR_RTOL * abs(rval) + 1.0e-10:
            fails.append(
                f"{where}, token {k}: 1-sigma error {oval} vs "
                f"{rval} (> {ERROR_RTOL:.0%} relative)"
            )
    return fails


def _compare_section(name, out_sec, ref_sec):
    """
    Compare one section (model/convolution/shift) of two .mod.out.

    Value lines are compared with the parameter tolerance (using the
    reference errors as the 1-sigma scale); error lines are compared
    with ERROR_RTOL. Blind placeholder lines must appear at the same
    positions in both files and are skipped.

    Parameters
    ----------
    name : str
        Section name for failure messages.
    out_sec : tuple[list[str], list[str]]
        (value lines, error lines) of the produced .mod.out.
    ref_sec : tuple[list[str], list[str]]
        (value lines, error lines) of the reference.

    Returns
    -------
    list[str]
        Failure messages (empty when the section matches).

    Generated by RJC and Claude.
    """
    fails = []
    out_vals, out_errs = out_sec
    ref_vals, ref_errs = ref_sec
    if len(out_vals) != len(ref_vals):
        return [
            f"{name}: {len(out_vals)} value lines vs "
            f"{len(ref_vals)} in reference"
        ]
    if len(out_errs) != len(ref_errs):
        return [
            f"{name}: {len(out_errs)} error lines vs "
            f"{len(ref_errs)} in reference"
        ]
    # The errors block mirrors the value block minus fix/lim settings
    # lines; blinded parameters keep their (real) 1-sigma error line
    # even though the value is hidden, so a blind placeholder still
    # consumes one error slot.
    err_fn = [ln for ln in ref_errs if _is_function_line(ln)]
    j = 0
    for i, (ov, rv) in enumerate(zip(out_vals, ref_vals)):
        where = f"{name} line {i + 1}"
        oblind = ov == BLIND_MARKER
        rblind = rv == BLIND_MARKER
        if oblind != rblind:
            fails.append(
                f"{where}: blind placeholder in only one file\n"
                f"    out: {ov}\n    ref: {rv}"
            )
            continue
        if rblind:
            j += 1  # its error line exists; skip the hidden value
            continue
        if not _is_function_line(rv):
            # Section marker or fix/lim settings line: must be
            # identical, and has no error counterpart.
            if ov != rv:
                fails.append(
                    f"{where}: '{ov}' != '{rv}'"
                )
            continue
        err_line = err_fn[j] if j < len(err_fn) else None
        j += 1
        fails += _compare_value_line(ov, rv, err_line, where)
    # Compare the error blocks of the two files line by line.
    for i, (oe, re_) in enumerate(zip(out_errs, ref_errs)):
        where = f"{name} errors line {i + 1}"
        if not _is_function_line(re_):
            if oe != re_:
                fails.append(f"{where}: '{oe}' != '{re_}'")
            continue
        fails += _compare_error_line(oe, re_, where)
    return fails


def compare_mod_out(out_path, ref_path, chisq_rtol,
                    compare_params=True):
    """
    Compare a produced .mod.out against its golden reference.

    Checks the best-fit chi-squared (relative tolerance) and the
    degrees of freedom (exact); with ``compare_params`` also every
    model/convolution/shift parameter and 1-sigma error per the
    Stage 0.4 tolerances.

    Parameters
    ----------
    out_path : Path
        The .mod.out produced by the test run.
    ref_path : Path
        The committed .mod.out.reference.
    chisq_rtol : float
        Relative tolerance on the best-fit chi-squared
        (CHISQ_RTOL_MINIMISATION or CHISQ_RTOL_FIXEDPARAM).
    compare_params : bool
        Compare the parameter/error blocks too (the minimisation
        test). The fixed-parameter gate passes False: a zero-
        iteration run does not reproduce the reference 1-sigma
        errors (per Stage 0.2b it gates on chi-squared and the
        model column only).

    Returns
    -------
    list[str]
        Failure messages (empty when the files agree).

    Generated by RJC and Claude.
    """
    if not out_path.exists():
        return [f"missing output file {out_path}"]
    try:
        out = parse_mod_out(out_path)
        ref = parse_mod_out(ref_path)
    except ValueError as err:
        return [str(err)]
    fails = []
    denom = max(abs(ref.chisq), 1.0e-30)
    if abs(out.chisq - ref.chisq) > chisq_rtol * denom:
        fails.append(
            f"chi-squared {out.chisq} vs {ref.chisq} "
            f"(> {chisq_rtol:.2%} relative)"
        )
    if out.dof != ref.dof:
        fails.append(f"DOF {out.dof} != {ref.dof}")
    if compare_params:
        for name in ("model", "convolution", "shift"):
            fails += _compare_section(
                name, out.sections[name], ref.sections[name]
            )
    return [f"{out_path.name}: {f}" for f in fails]


def compare_fit_dat(out_path, ref_path, rtol=FITDAT_RTOL):
    """
    Compare a produced _fit.dat against its golden reference.

    The model is the last column (per alsave.save_asciifits). The
    sentinel rows (pixels outside the fitrange) must occupy the same
    positions in both files and are excluded; the remaining model
    values must agree within ``rtol`` relative (FITDAT_ATOL absolute
    floor).

    Parameters
    ----------
    out_path : Path
        The _fit.dat produced by the test run.
    ref_path : Path
        The golden copy in reference_fits/.
    rtol : float
        Relative tolerance on the model column (FITDAT_RTOL for the
        minimisation test, FITDAT_RTOL_FIXEDPARAM for the fixed-
        parameter gate).

    Returns
    -------
    list[str]
        Failure messages (empty when the files agree).

    Generated by RJC and Claude.
    """
    if not out_path.exists():
        return [f"missing output file {out_path}"]
    out = np.atleast_2d(np.loadtxt(out_path))
    ref = np.atleast_2d(np.loadtxt(ref_path))
    label = f"{out_path.name} vs {ref_path}"
    if out.shape != ref.shape:
        return [f"{label}: shape {out.shape} != {ref.shape}"]
    omod = out[:, -1]
    rmod = ref[:, -1]
    osent = omod == SENTINEL
    rsent = rmod == SENTINEL
    if not np.array_equal(osent, rsent):
        ndiff = int(np.sum(osent != rsent))
        return [
            f"{label}: sentinel rows differ at {ndiff} pixels"
        ]
    keep = ~rsent
    bad = ~np.isclose(
        omod[keep], rmod[keep], rtol=rtol, atol=FITDAT_ATOL
    )
    if np.any(bad):
        delta = np.abs(omod[keep] - rmod[keep])
        scale = np.maximum(np.abs(rmod[keep]), FITDAT_ATOL)
        worst = float(np.max(delta / scale))
        return [
            f"{label}: model column differs at {int(np.sum(bad))}"
            f"/{int(np.sum(keep))} pixels "
            f"(max relative difference {worst:.3e})"
        ]
    return []


def compare_covar(out_path, ref_path):
    """
    Compare a produced covariance matrix against its golden copy.

    Elements must agree within COVAR_RTOL relative, with an absolute
    floor of COVAR_RTOL * sqrt(C_ii * C_jj) per element (so that
    near-zero covariances of quasi-independent parameters do not fail
    on tiny absolute wiggles).

    Parameters
    ----------
    out_path : Path
        The covariance file written by the test run (named by the
        ``out covar`` setting).
    ref_path : Path
        The committed golden copy (same name + ".reference").

    Returns
    -------
    list[str]
        Failure messages (empty when the matrices agree).

    Generated by RJC and Claude.
    """
    if not out_path.exists():
        return [f"missing covariance output {out_path}"]
    out = np.atleast_2d(np.loadtxt(out_path))
    ref = np.atleast_2d(np.loadtxt(ref_path))
    label = f"{out_path.name} vs {ref_path.name}"
    if out.shape != ref.shape:
        return [f"{label}: shape {out.shape} != {ref.shape}"]
    diag = np.clip(np.diag(ref), 0.0, None)
    floor = COVAR_RTOL * np.sqrt(np.outer(diag, diag))
    tol = np.maximum(COVAR_RTOL * np.abs(ref), floor)
    bad = np.abs(out - ref) > tol
    if np.any(bad):
        return [
            f"{label}: {int(np.sum(bad))}/{ref.size} elements "
            f"outside {COVAR_RTOL:.0%} relative "
            "(with sqrt(Cii*Cjj) floor)"
        ]
    return []


def compare_generated_data(out_path, ref_path):
    """
    Compare a generated data file against its golden copy.

    Used by the "generate" special case (noise-free data generation,
    ``generate peaksnr -1``): every column must agree within
    FITDAT_RTOL relative (FITDAT_ATOL absolute floor).

    Parameters
    ----------
    out_path : Path
        The data file created by running generate_spectra.mod.
    ref_path : Path
        The golden copy in reference_fits/.

    Returns
    -------
    list[str]
        Failure messages (empty when the files agree).

    Generated by RJC and Claude.
    """
    if not out_path.exists():
        return [f"missing generated data file {out_path}"]
    out = np.atleast_2d(np.loadtxt(out_path))
    ref = np.atleast_2d(np.loadtxt(ref_path))
    label = f"{out_path.name} vs {ref_path}"
    if out.shape != ref.shape:
        return [f"{label}: shape {out.shape} != {ref.shape}"]
    bad = ~np.isclose(out, ref, rtol=FITDAT_RTOL, atol=FITDAT_ATOL)
    if np.any(bad):
        return [
            f"{label}: {int(np.sum(bad))}/{ref.size} values differ "
            f"(> {FITDAT_RTOL} relative)"
        ]
    return []
