"""
Pytest bootstrap for the ALIS regression harness (Stage 0).

Makes the harness modules in this directory (manifest, alisrun,
compare) importable when pytest is invoked from the repository root,
and gates the ``slow`` batch behind ``--run-slow`` so the slowest
minimisations (e.g. DH/J0814p5029, ~16 min) only run on demand. The
batch markers (fast / medium / slow) are declared in the top-level
``pytest.ini``.

Generated by RJC and Claude.
"""

import sys
from pathlib import Path

import pytest

# Make manifest.py / alisrun.py / compare.py importable regardless of
# the directory pytest is invoked from.
sys.path.insert(0, str(Path(__file__).resolve().parent))


def pytest_addoption(parser):
    """
    Add ``--run-slow`` to opt into the slow batch.

    The astropy test plugins (present in this environment) register
    the same option; if so, adding it again raises ValueError, which
    is caught so the harness works both with and without them.

    Generated by RJC and Claude.
    """
    try:
        parser.addoption(
            "--run-slow",
            action="store_true",
            default=False,
            help="run the slow batch (>= 10 min/test)",
        )
    except ValueError:
        # Already registered (e.g. by pytest-astropy).
        pass
    try:
        parser.addoption(
            "--run-gpu",
            action="store_true",
            default=False,
            help="require the gpu batch to run (error, not skip, if no GPU)",
        )
    except ValueError:
        pass


def pytest_collection_modifyitems(config, items):
    """
    Gate the ``slow`` and ``gpu`` batches.

    ``slow`` is opt-in (``--run-slow``): those tests always *could* run, they
    are simply too slow to run every time.

    ``gpu`` is the other way round -- the tests are fast, so there is no reason
    to hide them behind a flag on a machine that can run them, but they are
    impossible on a machine with no CUDA device (CI, in particular). They
    therefore run automatically wherever a GPU is present and skip where one is
    not. ``--run-gpu`` makes a missing GPU a *failure* instead of a skip, so a
    run that is meant to exercise the GPU cannot pass silently on the back of a
    broken CUDA install.

    Generated by RJC and Claude.
    """
    if not config.getoption("--run-slow"):
        skip_slow = pytest.mark.skip(reason="need --run-slow option to run")
        for item in items:
            if "slow" in item.keywords:
                item.add_marker(skip_slow)

    if not any("gpu" in item.keywords for item in items):
        return
    # Probed only when a gpu test was actually collected: the probe imports
    # numba and initialises a CUDA context, which is slow.
    from alis import gpu

    if gpu.is_available():
        return
    reason = gpu.unavailable_reason()
    if config.getoption("--run-gpu"):
        raise pytest.UsageError(f"--run-gpu was given but no GPU is usable: {reason}")
    skip_gpu = pytest.mark.skip(reason=f"no usable GPU: {reason}")
    for item in items:
        if "gpu" in item.keywords:
            item.add_marker(skip_gpu)
