"""
Pytest configuration for the ALIS regression harness (Stage 0).

Registers the three batch markers (fast / medium / slow, Stage 0.3)
and makes the harness modules in this directory importable when
pytest is invoked from the repository root.
"""

import sys
from pathlib import Path

# Make manifest.py / alisrun.py / compare.py importable regardless of
# the directory pytest is invoked from.
sys.path.insert(0, str(Path(__file__).resolve().parent))


def pytest_configure(config):
    """
    Register the batch markers used by the regression suite.

    Parameters
    ----------
    config : pytest.Config
        The pytest configuration object.

    Generated by RJC and Claude.
    """
    config.addinivalue_line(
        "markers",
        "fast: runs on every commit (< 1 min per test, plus all "
        "fixed-parameter evaluations)",
    )
    config.addinivalue_line(
        "markers",
        "medium: runs nightly (< 10 min per test)",
    )
    config.addinivalue_line(
        "markers",
        "slow: runs on demand (>= 10 min per test)",
    )
