"""
Pytest bootstrap for the ALIS regression harness (Stage 0).

Makes the harness modules in this directory (manifest, alisrun,
compare) importable when pytest is invoked from the repository root,
and gates the ``slow`` batch behind ``--run-slow`` so the slowest
minimisations (e.g. DH/J0814p5029, ~16 min) only run on demand. The
batch markers (fast / medium / slow) are declared in the top-level
``pytest.ini``.

Generated by RJC and Claude.
"""

import importlib.util
import logging
import os
import sys
from pathlib import Path

import pytest

# Make manifest.py / alisrun.py / compare.py importable regardless of
# the directory pytest is invoked from.
sys.path.insert(0, str(Path(__file__).resolve().parent))

# The dashboard's window tests (dashboard Stage 3, the `gui` marker) run
# off-screen, on the binding the dashboard itself uses: QT_API, PySide6 unless
# the user chose another. pytest-qt reads PYTEST_QT_API rather than QT_API, so
# the two are kept in step here, before pytest-qt picks its binding.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("QT_API", "pyside6")
_QT_MODULES = {"pyside6": "PySide6", "pyqt6": "PyQt6"}
if "PYTEST_QT_API" not in os.environ:
    _api = os.environ["QT_API"].lower()
    if _api in _QT_MODULES and importlib.util.find_spec(_QT_MODULES[_api]):
        os.environ["PYTEST_QT_API"] = _api


@pytest.fixture
def logmsgs():
    """Messages emitted through ``msgs``, as a list of formatted strings.

    Neither ``capsys`` nor ``capfd`` sees them: the shared 'alis' logger binds
    its stderr handler at import, before pytest installs its capture. Attaching
    a handler is what ``tests/test_logger.py`` does too. Lives here because
    four test modules now want it (Stage 5.5).

    Generated by RJC and Claude.
    """
    from alis import logger

    records = []

    class _Collect(logging.Handler):
        def __init__(self):
            super().__init__(level=logging.DEBUG)

        def emit(self, record):
            records.append(record.getMessage())

    log = logger.msgs()
    handler = _Collect()
    log.addHandler(handler)
    try:
        yield records
    finally:
        log.removeHandler(handler)


@pytest.fixture(scope="session")
def atomic_data():
    """The shipped atomic data, loaded once for the whole session.

    Reading ``alis/data/atomic.ecsv`` costs about a second, and every test that
    builds a model function registry needs it. The result is read-only as far
    as the loaders are concerned, so one copy is safe to share.

    Generated by RJC and Claude.
    """
    from types import SimpleNamespace

    from alis import load
    from alis.config import ArgFlag

    cfg = ArgFlag()
    cfg["out"]["verbose"] = -1
    return load.load_atomic(SimpleNamespace(_argflag=cfg))


def pytest_addoption(parser):
    """
    Add ``--run-slow`` to opt into the slow batch.

    The astropy test plugins (present in this environment) register
    the same option; if so, adding it again raises ValueError, which
    is caught so the harness works both with and without them.

    Generated by RJC and Claude.
    """
    try:
        parser.addoption(
            "--run-slow",
            action="store_true",
            default=False,
            help="run the slow batch (>= 10 min/test)",
        )
    except ValueError:
        # Already registered (e.g. by pytest-astropy).
        pass
    try:
        parser.addoption(
            "--run-gpu",
            action="store_true",
            default=False,
            help="require the gpu batch to run (error, not skip, if no GPU)",
        )
    except ValueError:
        pass
    try:
        parser.addoption(
            "--skip-machine-dependent",
            action="store_true",
            default=False,
            help=(
                "skip the mode (a) minimisations whose references only "
                "reproduce on the machine that generated them"
            ),
        )
    except ValueError:
        pass


def pytest_collection_modifyitems(config, items):
    """
    Gate the ``slow`` and ``gpu`` batches.

    ``slow`` is opt-in (``--run-slow``): those tests always *could* run, they
    are simply too slow to run every time.

    ``gpu`` is the other way round -- the tests are fast, so there is no reason
    to hide them behind a flag on a machine that can run them, but they are
    impossible on a machine with no CUDA device (CI, in particular). They
    therefore run automatically wherever a GPU is present and skip where one is
    not. ``--run-gpu`` makes a missing GPU a *failure* instead of a skip, so a
    run that is meant to exercise the GPU cannot pass silently on the back of a
    broken CUDA install.

    Generated by RJC and Claude.
    """
    if not config.getoption("--run-slow"):
        skip_slow = pytest.mark.skip(reason="need --run-slow option to run")
        for item in items:
            if "slow" in item.keywords:
                item.add_marker(skip_slow)

    if config.getoption("--skip-machine-dependent"):
        skip_md = pytest.mark.skip(
            reason="reference only reproduces on the machine that generated it"
        )
        for item in items:
            if "machine_dependent" in item.keywords:
                item.add_marker(skip_md)

    # linetools is an optional dependency -- only the 'lsf' model function
    # needs it -- so cases that use it are skipped where it is absent rather
    # than failing the whole batch. Same principle as the gpu gate below.
    if any("linetools" in item.keywords for item in items):
        try:
            import linetools  # noqa: F401
        except ImportError:
            skip_lt = pytest.mark.skip(
                reason="linetools is not installed (needed by the 'lsf' function)"
            )
            for item in items:
                if "linetools" in item.keywords:
                    item.add_marker(skip_lt)

    # The window tests need the gui extra and pytest-qt (its qtbot fixture);
    # where either is missing they are skipped, as the gpu tests are below.
    if any("gui" in item.keywords for item in items):
        missing = [
            name
            for name in ("pytestqt", "qtpy", "pyqtgraph")
            if importlib.util.find_spec(name) is None
        ]
        if missing:
            skip_gui = pytest.mark.skip(
                reason="the dashboard's window tests need the gui extra and"
                " pytest-qt (missing: " + ", ".join(missing) + ")"
            )
            for item in items:
                if "gui" in item.keywords:
                    item.add_marker(skip_gui)

    if not any("gpu" in item.keywords for item in items):
        return
    # Probed only when a gpu test was actually collected: the probe imports
    # numba and initialises a CUDA context, which is slow.
    from alis import gpu

    if gpu.is_available():
        return
    reason = gpu.unavailable_reason()
    if config.getoption("--run-gpu"):
        raise pytest.UsageError(f"--run-gpu was given but no GPU is usable: {reason}")
    skip_gpu = pytest.mark.skip(reason=f"no usable GPU: {reason}")
    for item in items:
        if "gpu" in item.keywords:
            item.add_marker(skip_gpu)
