"""
Test-case manifest discovery for the ALIS regression harness (Stage 0.1).

This module scans the repository for the committed "golden" reference
files and builds a data-driven inventory (manifest) of regression test
cases. A fit test case is any ``<name>.mod`` file that has a sibling
``<name>.mod.out.reference`` (discovery is by the presence of the
reference file, not by filename pattern). The special "generate" test
cases are ``.mod`` files that set ``generate data True`` and whose
generated data file has a golden copy in ``reference_fits/``.

For each case the manifest records: the example directory, the fit
``.mod`` file, its ``.mod.out.reference``, the optional
``.covar.reference`` (and the ``out covar`` output name), the input
data files with their paired ``<datadir>/reference_fits/`` golden fit
files, whether the model is blinded (``blind=True`` or a non-empty
``blindrange=``), whether it uses randomness (``random`` model lines or
active ``sim`` settings), and the reference runtime (read from the
``#   Running Time (hrs)`` header line), which assigns the case to the
fast / medium / slow batch.

The harness (tests/test_regression.py, Stage 0.2) consumes
``discover_cases()`` to parametrise the pytest suite. Run this module
directly to print a human-readable summary table:

    python tests/manifest.py
"""

import re
from dataclasses import dataclass
from pathlib import Path

# ----------------------------------------------------------------- #
# Repository layout                                                  #
# ----------------------------------------------------------------- #
REPO_ROOT = Path(__file__).resolve().parent.parent
SEARCH_ROOTS = (
    REPO_ROOT / "examples",
    REPO_ROOT / "context" / "fitting_examples",
)

# Batch wall-time thresholds, in minutes (Stage 0.3):
#   < 1 min  -> "fast"   (runs on every commit)
#   < 10 min -> "medium" (runs nightly)
#   >= 10min -> "slow"   (runs on demand)
FAST_MAX_MIN = 1.0
MEDIUM_MAX_MIN = 10.0

# The sentinel value ALIS writes for pixels outside the fitrange.
SENTINEL = -9.999999999e9

# ----------------------------------------------------------------- #
# Regexes used to parse .mod / .mod.out.reference files              #
# ----------------------------------------------------------------- #
# blind=True / blind=T on an active model line -> value is hidden.
_BLIND_TRUE_RE = re.compile(r"blind\s*=\s*(?:True|TRUE|T)\b")
# A non-empty blindrange=lo,hi -> value visible but offset (this is a
# blinding mechanism even when blind=False on the same line).
_BLINDRANGE_RE = re.compile(r"blindrange\s*=\s*\S")
# Runtime header line in the .mod.out.reference file.
_RUNTIME_RE = re.compile(r"Running Time.*?=\s*([0-9.eE+\-]+)")


@dataclass(frozen=True)
class DataFilePair:
    """
    One input data file of a test case and its golden reference(s).

    Attributes
    ----------
    input_file : Path
        Resolved path of the input data file read by the fit. For
        "generate" cases the file may not exist until ALIS creates it.
    reference_fits : tuple[Path, ...]
        Golden files in ``<datadir>/reference_fits/`` paired with this
        input: ``<stem>_fit*.dat`` for fit cases (the glob also catches
        the numbered ``_fit02`` outputs written when one file is used
        by several snips), or ``<stem>.dat`` for generate cases. Empty
        if no golden file exists (that data file is then not compared).

    Generated by RJC and Claude.
    """

    input_file: Path
    reference_fits: tuple[Path, ...]


@dataclass(frozen=True)
class RegressionCase:
    """
    One regression test case for the ALIS test harness.

    Attributes
    ----------
    name : str
        Unique identifier (path of the .mod file relative to the
        repository root, without the .mod suffix).
    kind : str
        "fit" (run the model and compare fit outputs) or "generate"
        (run the model and compare the generated data file).
    example_dir : Path
        Directory of the example (parent of the model/ directory).
    mod_file : Path
        The .mod file the harness must run.
    mod_out_reference : Path | None
        Golden .mod.out.reference (None for "generate" cases).
    covar_reference : Path | None
        Golden .covar.reference, if it exists.
    covar_output : Path | None
        The covariance file the fit writes (parsed from the active
        ``out covar`` setting), if any.
    data_pairs : tuple[DataFilePair, ...]
        The input data files and their golden references.
    is_blind : bool
        True if any active line uses blind=True or a non-empty
        blindrange= (either mechanism excludes the case from the
        fixed-parameter gate).
    uses_random : bool
        True if the model uses the ``random`` function or any active
        ``sim`` setting (outputs then jitter at the ~1e-5 level).
    runtime_hrs : float | None
        Runtime parsed from the reference header (None if absent).
    batch : str
        "fast", "medium" or "slow" (from the runtime thresholds).

    Generated by RJC and Claude.
    """

    name: str
    kind: str
    example_dir: Path
    mod_file: Path
    mod_out_reference: Path | None
    covar_reference: Path | None
    covar_output: Path | None
    data_pairs: tuple[DataFilePair, ...]
    is_blind: bool
    uses_random: bool
    runtime_hrs: float | None
    batch: str


def _active_lines(text: str) -> list[str]:
    """
    Split file text into stripped, non-empty, non-comment lines.

    Parameters
    ----------
    text : str
        Full text of a .mod file.

    Returns
    -------
    list[str]
        Active (uncommented) lines, stripped of whitespace.

    Generated by RJC and Claude.
    """
    lines = []
    for raw in text.splitlines():
        # Strip inline trailing comments (e.g. "... #blindrange=-10,10"
        # in HD319718) as well as whole-line comments.
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        lines.append(line)
    return lines


def _split_blocks(
    lines: list[str],
) -> tuple[list[str], list[str], list[str]]:
    """
    Separate a .mod file's active lines into its three sections.

    Parameters
    ----------
    lines : list[str]
        Active lines from :func:`_active_lines`.

    Returns
    -------
    tuple[list[str], list[str], list[str]]
        (settings lines, data block lines, model block lines). Lines
        of the link block are ignored (no manifest info needed).

    Generated by RJC and Claude.
    """
    settings: list[str] = []
    datalines: list[str] = []
    modellines: list[str] = []
    section = "settings"
    for line in lines:
        low = line.lower()
        # Track block starts/ends ("data read" ... "data end" etc.).
        if low.startswith("data read"):
            section = "data"
            continue
        if low.startswith("data end"):
            section = "settings"
            continue
        if low.startswith("model read"):
            section = "model"
            continue
        if low.startswith("model end"):
            section = "settings"
            continue
        if low.startswith("link read"):
            section = "link"
            continue
        if low.startswith("link end"):
            section = "settings"
            continue
        if section == "data":
            datalines.append(line)
        elif section == "model":
            modellines.append(line)
        elif section == "settings":
            settings.append(line)
    return settings, datalines, modellines


def _get_setting(settings: list[str], key: str) -> str | None:
    """
    Return the value of a two-word global setting, if present.

    Parameters
    ----------
    settings : list[str]
        Settings lines from :func:`_split_blocks`.
    key : str
        Two-word setting name, e.g. "run datadirc" or "out covar".

    Returns
    -------
    str | None
        The setting value (third token), or None if not set.

    Generated by RJC and Claude.
    """
    kparts = key.split()
    for line in settings:
        parts = line.split()
        if len(parts) >= 3 and [p.lower() for p in parts[:2]] == kparts:
            return parts[2]
    return None


def _detect_blind(lines: list[str]) -> bool:
    """
    Decide whether a case is blinded (either blinding mechanism).

    Parameters
    ----------
    lines : list[str]
        All active lines of the .mod file.

    Returns
    -------
    bool
        True if ``run blind True`` is set, or any line carries
        ``blind=True``/``blind=T`` or a non-empty ``blindrange=``.

    Generated by RJC and Claude.
    """
    for line in lines:
        parts = line.split()
        # Global blind-analysis switch.
        if (
            len(parts) >= 3
            and parts[0].lower() == "run"
            and parts[1].lower() == "blind"
            and parts[2].lower() == "true"
        ):
            return True
        if _BLIND_TRUE_RE.search(line):
            return True
        if _BLINDRANGE_RE.search(line):
            return True
    return False


def _detect_random(settings: list[str], modellines: list[str]) -> bool:
    """
    Decide whether a case involves randomness.

    Parameters
    ----------
    settings : list[str]
        Settings lines of the .mod file.
    modellines : list[str]
        Model block lines of the .mod file.

    Returns
    -------
    bool
        True if the model uses the ``random`` function, or any active
        ``sim`` setting (other than an explicit False) is present.

    Generated by RJC and Claude.
    """
    for line in modellines:
        if line.split()[0].lower() == "random":
            return True
    for line in settings:
        parts = line.split()
        if parts[0].lower() == "sim" and len(parts) >= 3:
            if parts[2].lower() != "false":
                return True
    return False


def _resolve_data_file(
    token: str, model_dir: Path, datadirc: str | None
) -> Path:
    """
    Resolve a data-block filename token to an absolute path.

    Parameters
    ----------
    token : str
        First whitespace token of a data-block line (the filename,
        possibly prefixed with a relative directory).
    model_dir : Path
        Directory containing the .mod file.
    datadirc : str | None
        Value of the ``run datadirc`` setting, if set (bare filenames
        are then relative to this directory).

    Returns
    -------
    Path
        The resolved path. If neither candidate exists on disk the
        datadirc-based candidate (or model-dir candidate) is returned
        anyway so the caller can flag it (generate cases create their
        data file at run time).

    Generated by RJC and Claude.
    """
    candidates = []
    if datadirc:
        candidates.append((model_dir / datadirc / token).resolve())
    candidates.append((model_dir / token).resolve())
    for cand in candidates:
        if cand.exists():
            return cand
    # Fall back to the first candidate (may not exist yet).
    return candidates[0]


def _pair_references(input_file: Path, kind: str) -> tuple[Path, ...]:
    """
    Find the golden reference file(s) paired with one input data file.

    Parameters
    ----------
    input_file : Path
        Resolved input data file (its parent is the data directory).
    kind : str
        "fit" (references are ``<stem>_fit*.dat``) or "generate"
        (reference is the same filename, ``<stem>.dat``).

    Returns
    -------
    tuple[Path, ...]
        Sorted golden files found in ``<datadir>/reference_fits/``
        (empty when none exist -> not compared, per plan Q15).

    Generated by RJC and Claude.
    """
    refdir = input_file.parent / "reference_fits"
    if not refdir.is_dir():
        return ()
    stem = input_file.name
    for suffix in (".dat", ".fits"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    if kind == "generate":
        ref = refdir / input_file.name
        return (ref,) if ref.exists() else ()
    return tuple(sorted(refdir.glob(stem + "_fit*.dat")))


def _build_case(
    mod_file: Path, mod_out_reference: Path | None, kind: str
) -> RegressionCase:
    """
    Construct the :class:`RegressionCase` for one .mod file.

    Parameters
    ----------
    mod_file : Path
        The .mod file to describe.
    mod_out_reference : Path | None
        Its sibling .mod.out.reference (None for generate cases).
    kind : str
        "fit" or "generate".

    Returns
    -------
    RegressionCase
        The populated manifest entry.

    Generated by RJC and Claude.
    """
    model_dir = mod_file.parent
    lines = _active_lines(mod_file.read_text())
    settings, datalines, modellines = _split_blocks(lines)
    datadirc = _get_setting(settings, "run datadirc")

    # Resolve the (deduplicated, order-preserving) input data files.
    seen: dict[Path, None] = {}
    for line in datalines:
        token = line.split()[0]
        resolved = _resolve_data_file(token, model_dir, datadirc)
        seen.setdefault(resolved, None)
    pairs = tuple(
        DataFilePair(path, _pair_references(path, kind))
        for path in seen
    )

    # Covariance: the fit writes the file named by the active
    # "out covar" setting; its golden copy is that name + ".reference"
    # (e.g. J1419p0829.covar.reference, but also the longer
    # J0814p5029.mod.out.covar.reference naming in VMP_DLA).
    covar_out = _get_setting(settings, "out covar")
    covar_output = (
        (model_dir / covar_out).resolve() if covar_out else None
    )
    covar_reference = None
    if covar_output is not None:
        cand = Path(str(covar_output) + ".reference")
        if cand.exists():
            covar_reference = cand

    # Runtime from the reference header -> batch classification.
    runtime_hrs: float | None = None
    if mod_out_reference is not None:
        match = _RUNTIME_RE.search(mod_out_reference.read_text())
        if match:
            runtime_hrs = float(match.group(1))
    if runtime_hrs is None:
        batch = "fast"  # generate case / missing header: quick to run
    else:
        minutes = runtime_hrs * 60.0
        if minutes < FAST_MAX_MIN:
            batch = "fast"
        elif minutes < MEDIUM_MAX_MIN:
            batch = "medium"
        else:
            batch = "slow"

    return RegressionCase(
        name=str(
            mod_file.relative_to(REPO_ROOT).with_suffix("")
        ),
        kind=kind,
        example_dir=model_dir.parent,
        mod_file=mod_file,
        mod_out_reference=mod_out_reference,
        covar_reference=covar_reference,
        covar_output=covar_output,
        data_pairs=pairs,
        is_blind=_detect_blind(lines),
        uses_random=_detect_random(settings, modellines),
        runtime_hrs=runtime_hrs,
        batch=batch,
    )


def discover_cases() -> list[RegressionCase]:
    """
    Discover every regression test case in the repository.

    Fit cases: every ``<name>.mod`` with a sibling
    ``<name>.mod.out.reference`` under the search roots. Generate
    cases: every ``.mod`` that sets ``generate data True`` and whose
    generated data file has a golden copy in ``reference_fits/``
    (currently ``examples/generate``).

    Returns
    -------
    list[RegressionCase]
        All cases, sorted by (kind, name) for stable pytest ids.

    Generated by RJC and Claude.
    """
    cases: list[RegressionCase] = []
    for root in SEARCH_ROOTS:
        # ---- fit cases: discovery by reference presence -----------
        for ref in sorted(root.rglob("*.mod.out.reference")):
            mod_file = ref.parent / ref.name[: -len(".out.reference")]
            if not mod_file.exists():
                continue  # orphan reference; reported by main()
            cases.append(_build_case(mod_file, ref, "fit"))
        # ---- generate cases: "generate data True" + golden data ---
        for mod_file in sorted(root.rglob("*.mod")):
            ref = mod_file.parent / (mod_file.name + ".out.reference")
            if ref.exists():
                continue  # already covered as a fit case
            lines = _active_lines(mod_file.read_text())
            settings, _, _ = _split_blocks(lines)
            gen = _get_setting(settings, "generate data")
            if gen is None or gen.lower() != "true":
                continue
            case = _build_case(mod_file, None, "generate")
            # Only a test case if a golden generated file exists.
            if any(p.reference_fits for p in case.data_pairs):
                cases.append(case)
    return sorted(cases, key=lambda c: (c.kind, c.name))


def main() -> int:
    """
    Print the manifest as a table, with a summary and sanity checks.

    Returns
    -------
    int
        0 on success, 1 if any sanity problem was found (orphan
        references, missing input data, or fit cases without any
        golden fit file).

    Generated by RJC and Claude.
    """
    cases = discover_cases()
    header = (
        f"{'case':66s} {'kind':8s} {'batch':6s} {'min':>7s} "
        f"{'blind':5s} {'rand':4s} {'ndata':>5s} {'nref':>4s} "
        f"{'covar':5s}"
    )
    print(header)
    print("-" * len(header))
    problems: list[str] = []
    for case in cases:
        minutes = (
            f"{case.runtime_hrs * 60.0:7.2f}"
            if case.runtime_hrs is not None
            else "      -"
        )
        nref = sum(len(p.reference_fits) for p in case.data_pairs)
        print(
            f"{case.name:66s} {case.kind:8s} {case.batch:6s} "
            f"{minutes} {str(case.is_blind):5s} "
            f"{str(case.uses_random):4s} "
            f"{len(case.data_pairs):5d} {nref:4d} "
            f"{str(case.covar_reference is not None):5s}"
        )
        # Sanity checks -------------------------------------------- #
        if case.kind == "fit":
            for pair in case.data_pairs:
                if not pair.input_file.exists():
                    problems.append(
                        f"{case.name}: missing input data file "
                        f"{pair.input_file}"
                    )
            if nref == 0:
                problems.append(
                    f"{case.name}: no golden _fit.dat paired with any "
                    "of its data files"
                )
    # Orphan references (a golden file not paired with any case).
    paired_covars = {
        case.covar_reference
        for case in cases
        if case.covar_reference is not None
    }
    for root in SEARCH_ROOTS:
        # Scan every *.reference file: anything that is neither a
        # paired .mod.out.reference nor a paired covar reference is
        # an orphan (covar names vary, e.g. *_covar.dat.reference,
        # so match broadly rather than on '.covar.reference').
        for ref in sorted(root.rglob("*.reference")):
            if ref.name.endswith(".mod.out.reference"):
                mod_file = (
                    ref.parent / ref.name[: -len(".out.reference")]
                )
                if not mod_file.exists():
                    problems.append(f"orphan reference: {ref}")
            elif ref not in paired_covars:
                problems.append(f"orphan covar reference: {ref}")
    # Summary ------------------------------------------------------ #
    counts = {b: 0 for b in ("fast", "medium", "slow")}
    for case in cases:
        counts[case.batch] += 1
    nblind = sum(c.is_blind for c in cases)
    nrand = sum(c.uses_random for c in cases)
    ncovar = sum(c.covar_reference is not None for c in cases)
    print("-" * len(header))
    print(
        f"total {len(cases)} cases | fast {counts['fast']}, "
        f"medium {counts['medium']}, slow {counts['slow']} | "
        f"blind {nblind}, random {nrand}, covar {ncovar}"
    )
    if problems:
        print("\nPROBLEMS:")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print("no problems found")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
