"""Stage 3.2 fit-quality report tests.

- Unit test of the Wald-Wolfowitz runs-test z (no fit needed).
- Integration test: a fit writes a ``<model>.report`` whose per-region
  chi-squared sums to the fit's total chi-squared (the self-consistency that a
  wrong pixel selection would break).

Generated by RJC and Claude.
"""

import os
import re
import shutil
import subprocess
import sys
from types import SimpleNamespace

import numpy as np
import pytest

from manifest import REPO_ROOT

RUN_ALIS = REPO_ROOT / "alis" / "scripts" / "run_alis.py"


@pytest.mark.unit
def test_runs_z_detects_correlation():
    from alis.report import _runs_z
    rng = np.random.default_rng(0)
    # Independent residuals -> |z| small.
    assert abs(_runs_z(rng.normal(size=400))) < 3.0
    # Perfectly alternating signs -> far too many runs -> large positive z.
    alt = np.array([1.0, -1.0] * 200)
    assert _runs_z(alt) > 5.0
    # One long block of each sign -> far too few runs -> large negative z.
    block = np.array([1.0] * 200 + [-1.0] * 200)
    assert _runs_z(block) < -5.0


@pytest.mark.unit
def test_runs_z_degenerate_inputs_return_zero():
    from alis.report import _runs_z
    # All the same sign -> only one run, undefined variance -> defined as 0.
    assert _runs_z(np.ones(50)) == 0.0
    # Fewer than two non-zero residuals -> 0.
    assert _runs_z(np.array([0.0, 0.0, 1.0])) == 0.0
    assert _runs_z(np.array([])) == 0.0


@pytest.mark.unit
def test_regions_restricts_to_fitted_pixels():
    from alis.report import _regions
    wave = np.arange(1000.0, 1010.0)          # 1000 .. 1009 (10 pixels)
    model = np.zeros(10)
    # Residual = (flux - model)/flue; set model so fitted pixels give a pattern.
    for idx, val in {2: -0.5, 3: 0.5, 5: -0.5, 6: 0.5, 7: -0.5}.items():
        model[idx] = val
    slf = SimpleNamespace(
        _posnfull=[[0, 10]],                  # one specid, one snip: pixels 0..10
        _posnfit=[[1002.0, 1007.0]],          # fit range covers 1002 .. 1007
        # 1004 is in range but NOT fitted -> must be excluded by the isin mask.
        _wavefit=[np.array([1002.0, 1003.0, 1005.0, 1006.0, 1007.0])],
        _wavefull=[wave],
        _fluxfull=[np.zeros(10)],
        _fluefull=[np.ones(10)],
        _modfinal=[model],
        _specid=[0],
        _snipnames=[["reg1"]],
    )
    regs = _regions(slf)
    assert len(regs) == 1
    r = regs[0]
    assert r["wmin"] == 1002.0 and r["wmax"] == 1007.0
    # 5 fitted pixels (the in-range-but-unfitted 1004 is dropped).
    assert r["resid"].size == 5
    assert np.allclose(r["resid"], [0.5, -0.5, 0.5, -0.5, 0.5])


@pytest.mark.unit
def test_regions_excludes_zero_error_pixels():
    from alis.report import _regions
    wave = np.arange(1000.0, 1005.0)          # 1000 .. 1004
    flue = np.ones(5)
    flue[3] = 0.0                             # one bad pixel inside the fit range
    slf = SimpleNamespace(
        _posnfull=[[0, 5]],
        _posnfit=[[1000.0, 1004.0]],
        _wavefit=[wave.copy()],
        _wavefull=[wave],
        _fluxfull=[np.zeros(5)],
        _fluefull=[flue],
        _modfinal=[np.zeros(5)],
        _specid=[0],
        _snipnames=[["reg1"]],
    )
    r = _regions(slf)[0]
    assert r["resid"].size == 4               # flue == 0 pixel excluded


@pytest.mark.fast
@pytest.mark.examples
def test_report_chi2_self_consistent(tmp_path):
    ex = tmp_path / "metal_line_abs"
    shutil.copytree(REPO_ROOT / "examples" / "metal_line_abs", ex)
    mod = "fit_spectra.mod"
    env = dict(os.environ)
    env["MPLBACKEND"] = "Agg"
    proc = subprocess.run(
        [sys.executable, str(RUN_ALIS), "-f", "-w", "-p", "0", mod],
        cwd=str(ex / "model"), env=env, capture_output=True, text=True,
        timeout=600,
    )
    assert proc.returncode == 0, (proc.stdout + proc.stderr)[-2000:]

    reports = list((ex / "model").glob("*.report"))
    assert len(reports) == 1, "no .report file was written"
    text = reports[0].read_text()

    total = float(re.search(r"chi-squared = ([0-9.eE+-]+)", text).group(1))
    # Region rows begin with two spaces then the specid (not a '#' comment).
    region_chi2 = [float(ln.split()[5]) for ln in text.splitlines()
                   if re.match(r"  \S", ln)]
    assert region_chi2, "no region rows in the report"
    assert np.isclose(sum(region_chi2), total, rtol=0, atol=1e-3), (
        "per-region chi-squared %.4f != fit total %.4f"
        % (sum(region_chi2), total))
