"""The dashboard's parsed model (dashboard Stage 2.3).

For every model that ALIS reads, the parsed model agrees with ALIS's own reading --
``load_input``, ``load_data`` with the snips held in memory, ``load_model``,
``load_links`` and ``load_parinfo`` -- on the number of parameters, which are tied
together, which are free, and the line each comes from (``modpass['line']``). It also
checks that every parameter is matched to the right word of its line.

Generated by RJC and Claude.
"""

import copy
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from alis import load
from alis.config import ArgFlag
from alis.dashboard import model as M
from alis.dashboard import text as T
from alis.main import build_funcarray

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]


def model_files():
    """Every model in the two model folders, reference outputs included."""
    found = []
    for folder in ("examples", "context/fitting_examples"):
        base = ROOT / folder
        if base.is_dir():
            found += sorted(base.rglob("*.mod"))
            found += sorted(base.rglob("*.mod.out.reference"))
    return found


MODELS = model_files()


@pytest.fixture(scope="module")
def registry(atomic_data):
    return M.Registry(atomic_data)


def alis_reading(path, atomic):
    """
    ALIS's own reading of a model, with its data loaded from memory.

    Returns None when ALIS cannot read the model on its own, when the model
    generates data, or when its data files are not present.
    """
    text = path.read_text()
    state = SimpleNamespace(_argflag=ArgFlag())
    state._argflag["out"]["verbose"] = -1
    try:
        with M.alis_quietly():
            _, dat, mod, lnk = load.load_input(
                state, textstr=text.splitlines(keepends=True)
            )
    except M.AlisStop:
        return None
    if state._argflag["generate"]["data"]:
        return None
    paths = load.data_file_paths(dat, state._argflag["run"]["datadirc"])
    data = {}
    for rel in paths:
        where = path.parent / rel
        if not where.is_file():
            return None
        data[rel] = where.read_bytes()
    state._atomic = atomic
    state._funcarray = build_funcarray(state._argflag, atomic)
    try:
        with M.alis_quietly():
            load.load_data(state, dat, data=data)
            state._modpass = load.load_model(state, mod)
            mtie = copy.deepcopy(state._modpass["mtie"])
            state._links = load.load_links(state, lnk)
            state._modlines = mod
            parinfo, _ = load.load_parinfo(state)
    except M.AlisStop:
        return None
    return SimpleNamespace(
        modpass=state._modpass,
        mtie=mtie,
        parinfo=parinfo,
        modlines=mod,
        links=state._links,
    )


def _ids(paths):
    return [str(p.relative_to(ROOT)) for p in paths]


def test_there_are_models():
    assert len(MODELS) >= 40


@pytest.mark.parametrize("path", MODELS, ids=_ids(MODELS))
def test_the_parsed_model_agrees_with_alis(path, registry, atomic_data):
    ref = alis_reading(path, atomic_data)
    if ref is None:
        pytest.skip("ALIS does not read this model on its own from memory")
    pm = M.ParsedModel(path.read_text(), registry)
    assert pm.ok, pm.errors
    mine, theirs = pm.modpass, ref.modpass
    # The number of parameters, their starting values and the tie table
    assert pm.n_params == len(theirs["p0"])
    assert np.array_equal(mine["p0"], theirs["p0"])
    assert mine["tpar"] == theirs["tpar"]
    assert mine["mtie"] == theirs["mtie"]
    assert mine["mfix"] == theirs["mfix"]
    assert mine["mtyp"] == theirs["mtyp"]
    # Which are free: neither fixed nor computed by a link
    free = sum(1 for p in ref.parinfo if p["fixed"] != 1 and not p.get("tied"))
    assert pm.n_free == free
    # Which are tied together: each label's places share one ALIS parameter
    for name, (lab, num) in zip([t[0] for t in theirs["tpar"]], theirs["tpar"]):
        assert pm.labels[name].params[0].index == num
        assert {p.index for p in pm.labels[name].params} == {num}
    # Each parameter's line: modpass['line'] counts the model block's lines
    model_lines = [
        ln for ln in pm.text.lines if ln.kind in (T.SECTION, T.FIX, T.LIM, T.FUNCTION)
    ]
    assert [ln.text for ln in model_lines] == [m.rstrip("\r\n") for m in ref.modlines]
    for num, where in enumerate(theirs["line"]):
        if not isinstance(where, int):
            break
        par = pm.defining()[num]
        assert par.index == num
        assert par.line == model_lines[where].num
    # Every place is matched to the right word: its label and its value
    for par in pm.params:
        if par.token is None:
            continue
        assert par.label == ("" if par.label_token is None else par.label_token.text)
        line = pm.text[par.line].text
        assert line[par.token.start : par.token.end] == par.token.text
        # ALIS strips the label's characters from the end of the word
        word = par.value_token.text + par.label
        assert par.value == float(word.rstrip(par.label) if par.label else word)
        assert par.written == float(par.value_token.text)


# -- Small models ------------------------------------------------------------------

B_LINE = (
    "  b.dat specid=B fitrange=columns columns=[wave,flux,error,fitrange]"
    " resolution=vfwhm(7.0va) shift=vshift(1.5SH)"
)
SMALL = """run ncpus 1
run blind False
data read
  a.dat  specid=A  fitrange=[1300.0,1310.0]  resolution=vfwhm(7.0va)
{B_LINE}
data end
model read
 lim voigt bturb [0.5,None]
 lim param nb [12.0,16.0]
 emission
  legendre 1.0  0.01  0.02  scale=[1.0,1.0,1.0]  specid=A
  legendre 1.0  specid=B
 absorption
  voigt  ion=16O_I   14.0    2.5ra   5.0da   0.0TA   specid=A,B
  voigt  ion=28Si_II 13.0nb  2.5ra   5.0da   0.0TA   specid=A,B   blind=True
  voigt  ion=1H_I    ColDens=15.0  redshift=2.5ra  bturb=12.0  specid=A
  variable  -4.6dhrand  specid=A
model end
link read
  nb(dhrand) = dhrand + 17.6
link end
""".replace("{B_LINE}", B_LINE)


@pytest.fixture(scope="module")
def small(registry):
    return M.ParsedModel(SMALL, registry)


def test_a_small_model_is_read(small):
    pm = small
    assert pm.ok, pm.problems
    assert [s.key for s in pm.settings] == ["ncpus", "blind"]
    assert [d.specid for d in pm.data] == ["A", "B"]
    assert pm.data[1].fitrange == ("columns",)
    assert pm.data[0].fitrange == ("range", 1300.0, 1310.0)
    assert [ln.function for ln in pm.lines] == [
        "legendre",
        "legendre",
        "voigt",
        "voigt",
        "voigt",
        "variable",
    ]
    assert [ln.section for ln in pm.lines] == ["emission"] * 2 + ["absorption"] * 4
    assert pm.lines[3].blind and not pm.lines[2].blind
    assert pm.lines[2].specids == ["A", "B"]
    assert [c.kind + " " + c.target for c in pm.commands] == ["lim voigt", "lim param"]
    assert pm.links[0].target == "nb" and pm.links[0].deps == ["dhrand"]


def test_labels_and_their_states(small):
    labels = small.labels
    assert labels["ra"].state == "tied"
    assert len(labels["ra"].params) == 3
    assert labels["TA"].state == "fixed"
    assert labels["va"].state == "tied"
    assert labels["SH"].state == "fixed"
    assert labels["nb"].state == "linked"
    assert labels["dhrand"].state == "free"
    assert [c.line for c in labels["nb"].commands] == [8]
    assert [k.target for k in labels["dhrand"].links] == ["nb"]


def test_parameters_know_their_words(small):
    oxygen = small.lines[2]
    nval = oxygen.param("ColDens")
    assert nval.value == 14.0 and nval.label == "" and nval.free
    zval = oxygen.param("redshift")
    assert (zval.value_token.text, zval.label_token.text) == ("2.5", "ra")
    damping = oxygen.param("damping")
    assert damping.token is None and damping.fixed
    assert oxygen.param("bturb").limits == (0.5, None)
    hydrogen = small.lines[4]
    assert hydrogen.param("ColDens").named
    assert hydrogen.param("ColDens").value_token.text == "15.0"
    assert hydrogen.param("redshift").label == "ra"
    assert hydrogen.param("redshift").first is False
    silicon = small.lines[3]
    assert silicon.param("ColDens").limits == (12.0, 16.0)
    # The legendre has one parameter per coefficient
    assert [p.value for p in small.lines[0].params] == [1.0, 0.01, 0.02]
    # Data lines: resolution and shift
    assert small.data[1].param("shift").label == "SH"
    assert small.data[0].param("shift").token is None
    assert small.data[0].param("resolution").value_token.text == "7.0"


def test_items_and_parameters_are_found_by_position(small):
    oxygen = small.lines[2]
    assert small.item_at(oxygen.line) is oxygen
    word = oxygen.param("redshift").token
    assert small.param_at(oxygen.line, word.start + 1) is oxygen.param("redshift")
    assert small.param_at(oxygen.line, 0) is None
    assert isinstance(small.item_at(0), M.Setting)
    assert isinstance(small.item_at(3), M.DataLine)


def test_the_counts(small, registry):
    # 3 + 1 legendre, 4 x 7 voigt (the ratio-free lines), 1 variable,
    # 2 resolutions (tied: 1) and 2 shifts
    pm = small
    assert pm.n_params == len(pm.modpass["p0"])
    assert pm.n_free == len({p.index for p in pm.params if p.free})
    assert not any(p.free for p in pm.labels["nb"].params)


def test_a_ratio_line_has_one_parameter(registry):
    text = SMALL.replace(
        "variable  -4.6dhrand  specid=A", "voigt  ion=2H_I/1H_I  -4.6dhtie  specid=A"
    )
    text = text.replace("nb(dhrand) = dhrand + 17.6", "")
    pm = M.ParsedModel(text, registry)
    assert pm.ok, pm.problems
    ratio = pm.lines[-1]
    assert ratio.ratio and len(ratio.params) == 1
    assert ratio.params[0].label == "dhtie"


# -- Problems, on their lines ------------------------------------------------------


def problems(registry, old, new):
    pm = M.ParsedModel(SMALL.replace(old, new), registry)
    return pm, [(p.line, p.message) for p in pm.problems if p.severity == "error"]


@pytest.mark.parametrize(
    "old, new, line, words",
    [
        ("run ncpus 1", "run ncpu 1", 0, "Unknown setting"),
        ("run blind False", "run blind", 1, "Bad value"),
        (
            "specid=A  fitrange=[1300.0,1310.0]",
            "specid=A  fitrange=[1310.0,1300.0]",
            3,
            "upper limit",
        ),
        ("specid=A  fitrange=[1300.0,1310.0]", "specid=A", 3, "no fitrange"),
        ("specid=A  fitrange", "spec=A  fitrange", 3, "Unknown keyword"),
        (
            "legendre 1.0  specid=B",
            "legendr 1.0  specid=B",
            11,
            "Unknown model function",
        ),
        ("lim voigt bturb", "lim voigt bturbo", 7, "has no parameter"),
        ("lim param nb", "lim nb", 8, "takes three words"),
        ("nb(dhrand) = dhrand + 17.6", "nb(dhrand) dhrand", 19, "A link has the form"),
    ],
)
def test_problems_found_before_alis_reads_the_model(registry, old, new, line, words):
    pm, errs = problems(registry, old, new)
    assert not pm.ok
    assert any(n == line and words in msg for n, msg in errs), errs


@pytest.mark.parametrize(
    "old, new, line, words",
    [
        ("specid=A,B   blind=True", "specid=A,B   blnd=True", 14, "unknown"),
        ("specid=A,B   blind=True", "specid=A,C   blind=True", 14, "specid: C"),
        ("lim param nb [12.0,16.0]", "lim param nx [12.0,16.0]", 8, "nx"),
        ("nb(dhrand) = dhrand + 17.6", "nb(dhrnd) = dhrnd + 17.6", 19, "dhrnd"),
        (
            "0.0TA   specid=A,B   blind",
            "1e4   specid=A,B   blind",
            14,
            "Ambiguous parameter",
        ),
    ],
)
def test_alis_errors_are_placed_on_their_lines(registry, old, new, line, words):
    pm, errs = problems(registry, old, new)
    assert not pm.ok
    assert any(n == line and words in msg for n, msg in errs), errs


def test_alis_messages_stay_off_the_terminal(registry, capsys, logmsgs):
    M.ParsedModel(SMALL.replace("blind=True", "blind=Maybe"), registry)
    out = capsys.readouterr()
    assert "Maybe" not in out.err + out.out
    assert not any("boolean" in msg for msg in logmsgs)


def test_alis_quietly_turns_an_exit_into_an_exception(logmsgs):
    from alis import logger

    with pytest.raises(M.AlisStop) as stop:
        with M.alis_quietly() as notes:
            logger.msgs().warn("first")
            logger.msgs().error("it stopped")
    assert stop.value.message == "it stopped"
    assert notes[0][1] == "first"
    assert not logmsgs


def test_an_unknown_ion_is_an_error_that_does_not_stop_the_reading(registry):
    pm = M.ParsedModel(SMALL.replace("ion=16O_I", "ion=16X_I"), registry)
    assert pm.ok
    assert [(p.line, p.message) for p in pm.problems] == [(13, "Unknown ion: '16X_I'.")]


def test_a_warning_from_alis_is_kept(registry):
    pm = M.ParsedModel(SMALL.replace("blind=True", "blind=Maybe"), registry)
    assert pm.ok
    warn = [p for p in pm.problems if p.severity == "warning"]
    assert any(p.line == 14 and "boolean" in p.message for p in warn), warn


def test_structural_problems_stop_the_reading(registry):
    pm = M.ParsedModel(SMALL.replace("model end\n", ""), registry)
    assert not pm.ok
    assert pm.modpass is None and pm.params == []
