"""Stage 3.2 fit-quality report tests.

- Unit test of the Wald-Wolfowitz runs-test z (no fit needed).
- Integration test: a fit writes a ``<model>.report`` whose per-region
  chi-squared sums to the fit's total chi-squared (the self-consistency that a
  wrong pixel selection would break).

Generated by RJC and Claude.
"""

import os
import re
import shutil
import subprocess
import sys

import numpy as np
import pytest

from manifest import REPO_ROOT

RUN_ALIS = REPO_ROOT / "alis" / "scripts" / "run_alis.py"


def test_runs_z_detects_correlation():
    from alis.report import _runs_z
    rng = np.random.default_rng(0)
    # Independent residuals -> |z| small.
    assert abs(_runs_z(rng.normal(size=400))) < 3.0
    # Perfectly alternating signs -> far too many runs -> large positive z.
    alt = np.array([1.0, -1.0] * 200)
    assert _runs_z(alt) > 5.0
    # One long block of each sign -> far too few runs -> large negative z.
    block = np.array([1.0] * 200 + [-1.0] * 200)
    assert _runs_z(block) < -5.0


@pytest.mark.fast
@pytest.mark.examples
def test_report_chi2_self_consistent(tmp_path):
    ex = tmp_path / "metal_line_abs"
    shutil.copytree(REPO_ROOT / "examples" / "metal_line_abs", ex)
    mod = "fit_spectra.mod"
    env = dict(os.environ)
    env["MPLBACKEND"] = "Agg"
    proc = subprocess.run(
        [sys.executable, str(RUN_ALIS), "-f", "-w", "-p", "0", mod],
        cwd=str(ex / "model"), env=env, capture_output=True, text=True,
        timeout=600,
    )
    assert proc.returncode == 0, (proc.stdout + proc.stderr)[-2000:]

    reports = list((ex / "model").glob("*.report"))
    assert len(reports) == 1, "no .report file was written"
    text = reports[0].read_text()

    total = float(re.search(r"chi-squared = ([0-9.eE+-]+)", text).group(1))
    # Region rows begin with two spaces then the specid (not a '#' comment).
    region_chi2 = [float(ln.split()[5]) for ln in text.splitlines()
                   if re.match(r"  \S", ln)]
    assert region_chi2, "no region rows in the report"
    assert np.isclose(sum(region_chi2), total, rtol=0, atol=1e-3), (
        "per-region chi-squared %.4f != fit total %.4f"
        % (sum(region_chi2), total))
