"""The contract every ALIS model function has to satisfy (Stage 4.4).

Adding a model function means filling in a dozen parallel class attributes and
registering it in two places, and most of the ways to get that wrong surface far
from the mistake -- a keyword silently ignored, an ``IndexError`` deep in
``parout``, or ``'NoneType' object is not subscriptable`` from inside a fit
because the function was never added to the atomic-data list. These tests turn
each of those into a named failure at collection time, so a new function is
checked in seconds rather than by running a fit.

They run over *every registered function*, so they also protect the shipped
ones: all 32 satisfy every invariant here today.

Generated by RJC and Claude.
"""

import importlib
import inspect
import pkgutil
import re

import numpy as np
import pytest

from alis import functions, gpu_dispatch
from alis.functions import base

pytestmark = pytest.mark.unit

# Attributes that must run in parallel with _parid, one entry per parameter.
_PARALLEL = ("_parid", "_defpar", "_fixpar", "_limited", "_limits", "_svfmt")

# A *read* of the atomic data, as opposed to the "self._atomic = atomic" line
# that every __init__ carries.
_ATOMIC_READ = re.compile(r"self\._atomic(?!\s*=[^=])")


@pytest.fixture(scope="module")
def registry():
    """Every model function ALIS knows about, instantiated."""
    return base.call(getinst=True)


def _registered():
    """Names of the registered functions, for parametrisation."""
    return sorted(base.call(getfuncs=True))


def _own_source(cls):
    """Source of ``cls`` and its subclasses' ancestors, stopping at Base."""
    src = ""
    for klass in cls.__mro__:
        if klass in (base.Base, object):
            break
        try:
            src += inspect.getsource(klass)
        except OSError:  # pragma: no cover - only for dynamically built classes
            pass
    return src


# -- the class attributes ----------------------------------------------------


@pytest.mark.parametrize("name", _registered())
def test_the_registry_key_is_the_functions_idstr(name, registry):
    # The model file refers to a function by the registry key, but nearly every
    # error message quotes _idstr; if they disagree the message names something
    # the user cannot find in their .mod file.
    assert registry[name]._idstr == name


@pytest.mark.parametrize("name", _registered())
def test_the_per_parameter_attributes_run_in_parallel(name, registry):
    # _parid/_defpar/_fixpar/_limited/_limits/_svfmt are indexed by the same
    # parameter number all over load/parout/set_pinfo. A short list there is an
    # IndexError a long way from the typo.
    inst = registry[name]
    lengths = {attr: len(getattr(inst, attr)) for attr in _PARALLEL}
    assert len(set(lengths.values())) == 1, lengths


@pytest.mark.parametrize("name", _registered())
def test_there_are_at_least_pnumr_parameters(name, registry):
    # ">=" not "==": lsfspline declares _pnumr 1 and reads a variable number of
    # spline coefficients from the model file, so _pnumr is the minimum.
    inst = registry[name]
    assert len(inst._parid) >= inst._pnumr


@pytest.mark.parametrize("name", _registered())
def test_limits_are_given_as_pairs(name, registry):
    inst = registry[name]
    assert all(len(lim) == 2 for lim in inst._limited)
    assert all(len(lim) == 2 for lim in inst._limits)


@pytest.mark.parametrize("name", _registered())
def test_the_three_keyword_dicts_describe_the_same_keywords(name, registry):
    # _keywd holds the default value, _keych whether the user must set it, and
    # _keyfm how to print it. A keyword missing from _keych is never validated;
    # one missing from _keyfm raises KeyError when the model is written out.
    inst = registry[name]
    keywords = set(inst._keywd) - {"input"}
    assert keywords == set(inst._keych), keywords ^ set(inst._keych)
    assert keywords == set(inst._keyfm), keywords ^ set(inst._keyfm)


@pytest.mark.parametrize("name", _registered())
def test_the_input_map_covers_every_parameter_and_keyword(name, registry):
    # _keywd['input'] records what the user actually supplied, and parout skips
    # anything absent from it. A parameter missing here is simply dropped from
    # the written model -- silently.
    inst = registry[name]
    tracked = inst._keywd["input"]
    for entry in list(inst._parid) + [k for k in inst._keych]:
        assert entry in tracked, f"'{entry}' is not tracked in _keywd['input']"


@pytest.mark.parametrize("name", _registered())
def test_prekw_names_real_keywords(name, registry):
    # _prekw reorders keywords ahead of the parameters when printing; a name
    # that is not a keyword reaches msgs.bug("prekw variable ... bad argument").
    inst = registry[name]
    for keyword in inst._prekw:
        assert keyword in inst._keywd, f"_prekw names unknown keyword '{keyword}'"


# -- registration ------------------------------------------------------------


def _import_function_module(name):
    """Import one module under ``alis/functions/``, or None if it needs a GPU.

    A ``<name>_gpu`` module holds CUDA kernels and imports numba at module
    scope, because ``@cuda.jit`` compiles at import time -- that is exactly why
    Task 4.1 keeps such a module out of the normal import path and has
    ``call_GPU`` import it lazily. So on an install without the ``gpu`` extra
    it cannot be imported at all, and sweeping the package must tolerate that.
    Only that one case is tolerated: an ImportError from any other module is a
    real failure and is left to propagate.

    Generated by RJC and Claude.
    """
    try:
        return importlib.import_module(f"alis.functions.{name}")
    except ImportError:
        if name.endswith("_gpu"):
            return None
        raise


def _function_modules():
    """Modules under ``alis/functions/`` that define a model function."""
    out = []
    for info in pkgutil.iter_modules(functions.__path__):
        if info.name in ("base", "user"):
            continue
        module = _import_function_module(info.name)
        if module is None:
            continue
        defined = [
            obj
            for _, obj in inspect.getmembers(module, inspect.isclass)
            if issubclass(obj, base.Base)
            and obj is not base.Base
            and obj.__module__ == module.__name__
        ]
        if defined:
            out.append((info.name, defined))
    return out


_FUNCTION_MODULES = _function_modules()


@pytest.mark.parametrize(
    "module,defined", _FUNCTION_MODULES, ids=[m for m, _ in _FUNCTION_MODULES]
)
def test_every_function_module_is_registered(module, defined, registry):
    # Writing the module is only half of adding a function: it also has to go
    # into the fd dict in functions/base.py's call(). Until it does, the model
    # file just reports an unknown function.
    registered = {type(inst) for inst in registry.values()}
    assert any(cls in registered for cls in defined), (
        f"alis/functions/{module}.py defines "
        f"{[c.__name__ for c in defined]} but none is registered in "
        "functions/base.py's call()"
    )


def test_functions_that_read_atomic_data_are_given_it():
    # The second registration step: a function using the atomic table must also
    # be listed in `sendatomic`, or self._atomic stays None and the fit dies
    # with "'NoneType' object is not subscriptable" from inside set_vars.
    sentinel = object()
    registry = base.call(getinst=True, atomic=sentinel)
    for name, inst in sorted(registry.items()):
        if _ATOMIC_READ.search(_own_source(type(inst))):
            assert inst._atomic is sentinel, (
                f"'{name}' reads self._atomic but is not in the `sendatomic` "
                "list in functions/base.py's call()"
            )


# -- the GPU opt-in ----------------------------------------------------------


def test_gpu_capable_functions_are_discovered_without_the_registry():
    # warm_up() runs inside a Pool initializer, so it walks the subclass tree
    # instead of calling base.call() (which loads the user's function module and
    # prints while doing it).
    discovered = {cls.__name__ for cls in gpu_dispatch.gpu_capable_functions()}
    from_registry = {
        type(inst).__name__
        for inst in base.call(getinst=True).values()
        if inst.supports_gpu()
    }
    assert discovered == from_registry


@pytest.mark.parametrize("name", _registered())
def test_a_gpu_function_can_be_warmed(name, registry):
    # Without a warm-up hook the kernel's ~0.9 s compile lands inside the
    # 'run backend auto' timing probe, which then mis-picks the CPU.
    inst = registry[name]
    if not inst.supports_gpu():
        pytest.skip(f"'{name}' has no GPU implementation")
    args = inst.gpu_warmup_args()
    assert args is not None, (
        f"'{name}' sets _gpu_supported = True but does not implement "
        "gpu_warmup_args()"
    )
    x, p, kwargs = args
    x, p = np.asarray(x), np.asarray(p)
    assert x.ndim == 1 and x.size > 0, "warm-up x must be a 1D wavelength array"
    assert p.ndim == 2 and p.shape[0] > 0, "warm-up p must be (nrows, nparams)"
    assert isinstance(kwargs, dict)
    # Tiny on purpose: the point is to compile the kernel, not to compute.
    assert x.size <= 1024 and p.shape[0] <= 8


def test_a_function_without_a_gpu_path_has_no_warmup_args():
    assert base.Base(getinst=True).gpu_warmup_args() is None


# -- the sweep's own import rule ---------------------------------------------


def test_a_gpu_kernel_module_is_skipped_when_numba_is_absent(monkeypatch):
    # The sweep above imports every module in the package, and a *_gpu module
    # imports numba at module scope by design -- so on a CPU-only install it
    # cannot be imported, and importing it anyway took the whole pytest session
    # down with a collection error (which also aborted the examples batch).
    def refuse(name):
        raise ImportError("No module named 'numba'")

    monkeypatch.setattr(importlib, "import_module", refuse)
    assert _import_function_module("voigt_gpu") is None


def test_an_ordinary_module_that_will_not_import_is_still_a_failure(monkeypatch):
    # Only the GPU-kernel case is tolerated: a real breakage anywhere else must
    # not be swallowed by the same rule.
    def refuse(name):
        raise ImportError("something is genuinely broken")

    monkeypatch.setattr(importlib, "import_module", refuse)
    with pytest.raises(ImportError):
        _import_function_module("voigt")
