"""Transitions, line IDs, flags and coverage (dashboard Stage 4.1; S2, S5, D36).

J1358p6522's H I list and its flags must match the Regions mockup (Lyα in the gap of
its source spectrum, Lyβ to Ly10 on the data, no forest flag: Q4.5), and Q1243p307's
coverage grid the Data mockup (16 transitions in three files). Synthetic spectra
check the gap and edge flags, a click on J1358p6522's Lyβ must offer its redshift,
and the line IDs must count what they leave unlabelled (Q4.4).

Generated by RJC and Claude.
"""

from pathlib import Path

import numpy as np
import pytest

from alis.dashboard import lines as L
from alis.dashboard import model as M
from alis.dashboard import modes
from alis.dashboard import project as P

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]
CTX = ROOT / "context/fitting_examples"
J1358 = CTX / "VMP_DLA/J1358p6522/model/J1358p6522.mod"
J1358_SOURCE = CTX / "VMP_DLA/J1358p6522/data/J1358p6522_fluxcal.dat"
Q1243 = CTX / "DH/Q1243p307/model/Q1243p307_converge_newstart76.mod"
Z_J1358 = 3.0672596


@pytest.fixture(scope="module")
def registry(atomic_data):
    return M.Registry(atomic_data)


@pytest.fixture(scope="module")
def atom(registry):
    return L.atomic(registry)


def need(path):
    if not path.exists():
        pytest.skip("not present: " + str(path.relative_to(ROOT)))
    return path


@pytest.fixture(scope="module")
def j1358(registry):
    project = P.Project.import_model(str(need(J1358)), registry=registry)
    spec = modes.get().load(str(need(J1358_SOURCE)))
    return project, L.coverage_of_spectrum("r1", "J1358p6522_fluxcal", spec)


def synthetic(low=4000.0, high=4100.0, step=0.05, gap=None, bad=None):
    """A flat spectrum, perhaps with a gap (no pixels) or bad pixels."""
    wave = np.arange(low, high, step)
    if gap is not None:
        wave = wave[(wave < gap[0]) | (wave > gap[1])]
    flux = np.ones_like(wave)
    error = np.full_like(wave, 0.1)
    mask = None
    if bad is not None:
        mask = (wave >= bad[0]) & (wave <= bad[1])
    spec = modes.Spectrum(wave, flux, error, mask)
    return L.coverage_of_spectrum("r1", "synthetic", spec)


# -- Lines -------------------------------------------------------------------------


def test_lyman_lines_have_their_names():
    assert L.line_name("H", "I", 1215.6701) == "Lyα 1215.7"
    assert L.line_name("H", "I", 1025.7223) == "Lyβ 1025.7"
    assert L.line_name("H", "I", 926.2257) == "Ly7 926.2"
    assert L.line_name("O", "I", 1302.16849) == "O I 1302.2"
    # A Balmer line is not a Lyman line
    assert L.line_name("H", "I", 6564.623) == "H I 6564.6"


def test_isotopes_are_folded_into_their_element(atom):
    assert atom.main_ion[("H", "I")] == "1H_I"
    assert atom.main_ion[("O", "I")] == "16O_I"
    assert atom.main_ion[("Si", "II")] == "28Si_II"
    # D I is an isotope of H, not a main ion of its own
    assert all(ion != "2H_I" for ion in atom.main_ion.values())
    assert not any(ln.main for ln in atom.ion_lines("2H_I"))
    # Pseudo-ions (generic absorbers, molecules, tests) are not elements
    assert "1Ly_a" not in atom.by_ion and "1H_IB" not in atom.by_ion
    assert atom.stages("C")[:3] == ["I", "I*", "I**"]


def test_roman_numerals_order_the_stages():
    assert sorted(["IV", "II*", "I", "II", "VI"], key=L.roman) == [
        "I",
        "II",
        "II*",
        "IV",
        "VI",
    ]


# -- The transition list (S2, D36, Q4.5) ---------------------------------------------


def test_j1358_hydrogen_list_matches_the_mockup(atom, j1358):
    project, cov = j1358
    snips = L.snip_transitions(project)
    snipped = L.snipped_by_ion(snips, "a")["1H_I"]
    rows = L.ion_transitions(atom, "H", "I", Z_J1358, [cov], snipped, "a")
    names = [r.name.split()[0] for r in rows[:10]]
    assert names == ["Lyα", "Lyβ", "Lyγ", "Lyδ", "Lyε"] + [
        "Ly{0}".format(n) for n in range(6, 11)
    ]
    # Lyα falls in the source's gap (4535-5593 Å), and is listed for its snip
    assert rows[0].flags == ("gap",) and rows[0].snipped and not rows[0].on_data
    # Lyβ to Ly8 have snips (H7 ... H1); Ly9 and Ly10 do not; no forest flag
    assert [r.snipped for r in rows[1:10]] == [True] * 7 + [False] * 2
    assert all(r.flags == () for r in rows[1:10])
    assert not any("forest" in r.flags or "telluric" in r.flags for r in rows)
    # Ranked by f lambda, whatever its strength (Q4.4): the series to its limit
    assert [r.flam for r in rows] == sorted((r.flam for r in rows), reverse=True)
    assert len(rows) == len(atom.ion_lines("1H_I")) - 4  # the Balmer lines are off


def test_near_coincident_lines_share_one_row(atom, j1358):
    _, cov = j1358
    rows = L.ion_transitions(atom, "O", "I", Z_J1358, [cov])
    names = [r.name for r in rows]
    assert "O I 971.7 ×3" in names
    triple = rows[names.index("O I 971.7 ×3")]
    assert triple.rest == pytest.approx(971.73827) and len(triple.members) == 3
    # The 988 lines are further apart than the resolution: one row each
    assert sum(n.startswith("O I 988") for n in names) == 3


def test_gap_and_edge_flags_on_a_synthetic_spectrum():
    cov = synthetic(gap=(4040.0, 4050.0), bad=(4070.0, 4070.12))
    on, flags = L.place(4020.0, [cov])
    assert on and flags == ()
    # In the gap: no pixels at all
    assert L.place(4045.0, [cov]) == (False, ("gap",))
    # Beyond the data
    assert L.place(4200.0, [cov]) == (False, ("gap",))
    # 2 Å (150 km/s) from the blue end: closer than a snip's half-width
    assert L.place(4002.0, [cov]) == (True, ("edge",))
    # Near the gap's edge, too
    assert L.place(4038.0, [cov]) == (True, ("edge",))
    assert L.place(4038.0, [cov], half_width=100.0) == (True, ())
    # A run of three bad pixels does not split the data; a longer one would
    assert L.place(4070.06, [cov]) == (True, ())
    assert len(cov.runs) == 2


def test_bad_pixels_and_nonpositive_errors_are_not_data():
    wave = np.arange(4000.0, 4100.0, 0.05)
    error = np.full_like(wave, 0.1)
    error[(wave > 4040) & (wave < 4050)] = 0.0
    flux = np.ones_like(wave)
    flux[(wave > 4060) & (wave < 4062)] = np.nan
    bad = (wave > 4080) & (wave < 4090)
    cov = L.coverage_of_spectrum("r1", "x", modes.Spectrum(wave, flux, error, bad))
    assert L.place(4045.0, [cov]) == (False, ("gap",))
    assert L.place(4085.0, [cov]) == (False, ("gap",))
    assert len(cov.runs) == 4


def test_a_gap_transition_is_listed_only_with_a_snip(atom):
    cov = synthetic(low=1200.0 * 1.0, high=1300.0)
    off = L.ion_transitions(atom, "H", "I", 0.0, [cov])
    assert [r.name for r in off] == ["Lyα 1215.7"]
    cov = synthetic(low=1250.0, high=1300.0)
    assert L.ion_transitions(atom, "H", "I", 0.0, [cov]) == []
    kept = L.ion_transitions(atom, "H", "I", 0.0, [cov], snipped=[1215.6701])
    assert [(r.name, r.flags, r.snipped) for r in kept] == [
        ("Lyα 1215.7", ("gap",), True)
    ]


def test_elements_offered_have_a_transition_on_the_data(atom, j1358):
    _, cov = j1358
    found = L.elements_on_data(atom, Z_J1358, [cov])
    assert list(found)[0] == "H" and found["H"] == ["I"]
    assert "O" in found and "I" in found["O"]
    # In order of atomic number
    order = [L.SYMBOLS.index(e) for e in found]
    assert order == sorted(order)
    # Nothing is offered where there are no data
    assert L.elements_on_data(atom, 0.0, [synthetic(low=100.0, high=101.0)]) == {}


# -- Identify a feature (S24, D35) -------------------------------------------------


def test_a_click_on_lybeta_offers_its_redshift(atom, j1358):
    _, cov = j1358
    click = 1025.7223 * (1.0 + Z_J1358)
    cands, first = L.identify(atom, click, cov.span[1])
    lyb = [c for c in cands if c.name == "Lyβ 1025.7"]
    assert len(lyb) == 1 and round(lyb[0].z, 5) == 3.06726
    # Only transitions that put the click at z >= 0
    assert all(c.z >= 0 for c in cands)
    # The first choice is the strongest line whose Lyα is within the data
    assert cands[first].name == "Lyα 1215.7"
    menus = L.candidate_menus(cands)
    assert list(menus)[0] == "H" and list(menus["H"]) == ["I"]
    assert menus["H"]["I"][0].name == "Lyα 1215.7"


def test_identify_skips_a_first_choice_beyond_the_data(atom):
    # Data that end at 2000 Å: Lyα at the z that a click at 1900 Å gives for C IV
    # (1548) is at 1492 Å, within reach; for Lyα itself z=0.56, Lyα at 1900 Å
    cands, first = L.identify(atom, 1900.0, data_max=1800.0)
    assert (1.0 + cands[first].z) * L.LYA <= 1800.0
    assert cands[first].name != "Lyα 1215.7"


# -- Snips and coverage --------------------------------------------------------------


def test_the_transitions_of_imported_snips(j1358):
    project, _ = j1358
    found = L.snip_transitions(project)
    assert found["H2"] == L.SnipTransition("a", "1H_I", pytest.approx(926.2257))
    # "_O_I_988_" means the strongest of the three O I lines at 988 Å
    assert found["O2"].rest == pytest.approx(988.77356)
    assert found["O4"].ion == "16O_I"


def test_snip_transition_recorded_by_snip_wins(j1358):
    project, _ = j1358
    project.ui = dict(project.ui)
    project.ui["snips"] = {"O2": {"system": "a", "ion": "16O_I", "rest": 988.65505}}
    try:
        assert L.snip_transitions(project)["O2"].rest == pytest.approx(988.65505)
    finally:
        project.ui.pop("snips")


def test_q1243_coverage_grid_matches_the_mockup(registry):
    project = P.Project.import_model(str(need(Q1243)), registry=registry)
    covs = [L.coverage_of_snips(r) for r in project.rows]
    assert [c.name for c in covs] == ["HIRES", "PROCHASKA", "KIRKMAN"]
    assert not any(c.source for c in covs)
    primary = next(s for s in project.systems if s.primary)
    grid = L.coverage_grid(project, primary, covs)
    assert len(grid) == 16
    assert [g.name for g in grid[:3]] == ["Ly8 923.2", "Ly7 926.2", "Ly6 930.7"]
    assert [g.rest for g in grid] == sorted(g.rest for g in grid)
    counts = [sum(g.cells[c.row] == L.SNIP for g in grid) for c in covs]
    assert counts == [16, 16, 12]
    # Without source spectra a cell is a snip or nothing (D12)
    assert {v for g in grid for v in g.cells.values()} == {L.SNIP, L.NONE}
    # The other systems' snips are theirs, not the primary's
    others = {t.system for t in L.snip_transitions(project).values()}
    assert len(others) == 5


def test_a_source_covers_transitions_with_no_snip_yet(atom, registry):
    project, _ = modes.get().empty_project(
        [str(ROOT / "examples/metal_line_abs/data/OI_SiII.dat")],
        "test",
        z=0.0,
        registry=registry,
    )
    spec = modes.get().load(str(ROOT / "examples/metal_line_abs/data/OI_SiII.dat"))
    cov = L.coverage_of_spectrum(project.rows[0].id, project.rows[0].name, spec)
    system = project.systems[0]
    system.lines = [
        {"ion": "16O_I", "wave": 1302.16849},
        {"ion": "28Si_II", "wave": 1260.4221},
    ]
    grid = L.coverage_grid(project, system, [cov])
    cells = {g.name: g.cells[cov.row] for g in grid}
    assert cells == {"Si II 1260.4": L.NONE, "O I 1302.2": L.COVERED}


# -- Line IDs (S5, Q4.4) -------------------------------------------------------------


def test_line_ids_count_what_they_leave_out(j1358):
    project, _ = j1358
    ids, hidden = L.line_ids(project, 3740.0, 3800.0)
    assert ids and hidden > 0
    kinds = {i.kind for i in ids}
    assert kinds <= {L.HYDROGEN, L.METAL, L.OTHER}
    # The model's ions are labelled in full: every H I and O I line in the range
    hydrogen = [i for i in ids if i.ion == "1H_I"]
    assert {round(i.rest, 1) for i in hydrogen} >= {923.2, 926.2, 930.7}
    # The Lyman alpha forest is labelled as such
    assert any(i.label == "Lyα forest" and i.kind == L.OTHER for i in ids)
    every, none_left = L.line_ids(project, 3740.0, 3800.0, show_all=True)
    assert none_left == 0
    assert len(every) == len(ids) + hidden
    assert [i.observed for i in every] == sorted(i.observed for i in every)


def test_a_line_id_named_for_a_system_is_labelled(registry, j1358):
    project, _ = j1358
    system = project.systems[0]
    before, _ = L.line_ids(project, 5000.0, 6300.0, strong=99.0)
    assert not any(i.ion == "26Fe_II" or i.ion == "56Fe_II" for i in before)
    system.lines = [{"ion": "56Fe_II"}]
    try:
        after, _ = L.line_ids(project, 5000.0, 6300.0, strong=99.0)
        assert any(i.ion == "56Fe_II" and i.kind == L.METAL for i in after)
    finally:
        system.lines = []


def test_strong_lines_of_other_systems_are_other(registry, j1358):
    project, _ = j1358
    extra = P.System("x", "other", 2.0, False, [], [], False)
    ids, _ = L.line_ids(project, 3600.0, 4600.0, systems=project.systems + [extra])
    theirs = [i for i in ids if i.system == "x"]
    assert theirs and {i.kind for i in theirs} == {L.OTHER}
    assert any(i.label == "Lyα 1215.7" for i in theirs)
