"""Pixels fitted by more than one snip (dashboard Stage 1.3, D19).

The same pixel of the same parent data must not enter the fit twice. Two pixels
are the same when their wavelengths and their flux/error ratios agree: the
ratio survives a snip being multiplied by its continuum, but differs between
independent files on a common wavelength grid, which are not flagged (RJC,
Q1.8). ``run_alis`` warns, and the fit still runs.

Generated by RJC and Claude.
"""

import os
from pathlib import Path

import numpy as np
import pytest

from alis import load
from alis.config import ArgFlag
from alis.main import build_funcarray

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]


def _spectrum(seed=1, npix=400):
    """A noisy synthetic spectrum on a log-linear wavelength grid."""
    rng = np.random.default_rng(seed)
    wave = 1290.0 * (1.0 + 2.5 / 299792.458) ** np.arange(npix)
    error = 0.05 + 0.01 * rng.random(npix)
    flux = 1.0 + error * rng.standard_normal(npix)
    return wave, flux, error


def _cut(spec, lo, hi, scale=1.0):
    """The pixels lo:hi of ``spec``, multiplied by ``scale`` (a continuum)."""
    wave, flux, error = spec
    return wave[lo:hi], scale * flux[lo:hi], scale * error[lo:hi]


def test_overlapping_snips_of_one_spectrum_are_flagged():
    spec = _spectrum()
    shared = load.find_shared_pixels([_cut(spec, 0, 120), _cut(spec, 100, 250)])
    assert len(shared) == 1
    i, j, idx_i, idx_j = shared[0]
    assert (i, j) == (0, 1)
    assert idx_i.size == 20
    assert np.array_equal(idx_i, np.arange(100, 120))
    assert np.array_equal(idx_j, np.arange(0, 20))


def test_a_snip_multiplied_by_its_continuum_still_matches():
    spec = _spectrum()
    cont = np.linspace(0.8, 1.2, 150)
    a = _cut(spec, 0, 150)
    b = (a[0][100:], a[1][100:] * cont[100:], a[2][100:] * cont[100:])
    shared = load.find_shared_pixels([a, b])
    assert len(shared) == 1 and shared[0][2].size == 50


def test_independent_files_on_one_grid_are_not_flagged():
    wave, flux1, err1 = _spectrum(seed=1)
    _, flux2, err2 = _spectrum(seed=2)
    assert load.find_shared_pixels([(wave, flux1, err1), (wave, flux2, err2)]) == []


def test_the_same_file_loaded_twice_is_flagged():
    spec = _spectrum()
    shared = load.find_shared_pixels([spec, spec])
    assert len(shared) == 1 and shared[0][2].size == spec[0].size


def test_disjoint_snips_are_not_flagged():
    spec = _spectrum()
    assert load.find_shared_pixels([_cut(spec, 0, 100), _cut(spec, 100, 200)]) == []


def test_isolated_chance_matches_are_ignored():
    """Fewer than three consecutive matching pixels are not a shared block."""
    wave, flux1, err1 = _spectrum(seed=1)
    _, flux2, err2 = _spectrum(seed=2)
    flux2[[50, 51, 200]] = flux1[[50, 51, 200]]
    err2[[50, 51, 200]] = err1[[50, 51, 200]]
    assert load.find_shared_pixels([(wave, flux1, err1), (wave, flux2, err2)]) == []
    flux2[52], err2[52] = flux1[52], err1[52]
    shared = load.find_shared_pixels([(wave, flux1, err1), (wave, flux2, err2)])
    assert np.array_equal(shared[0][2], [50, 51, 52])


def test_zero_flux_and_bad_errors_are_ignored():
    wave = np.linspace(1300.0, 1301.0, 50)
    zero = (wave, np.zeros(50), np.ones(50))
    assert load.find_shared_pixels([zero, zero]) == []
    bad = (wave, np.ones(50), np.zeros(50))
    assert load.find_shared_pixels([bad, bad]) == []


def test_the_warning_names_both_files_and_counts_the_rest(logmsgs):
    spec = _spectrum(npix=2000)
    snips = [_cut(spec, 100 * k, 100 * k + 120) for k in range(13)]
    shared = load.find_shared_pixels(snips)
    assert len(shared) == 12
    names = ["snip{0:02d}.dat".format(k) for k in range(13)]
    load.warn_shared_pixels(shared, names, waves=[s[0] for s in snips], verbose=2)
    listed = [m for m in logmsgs if "are fitted twice" in m]
    assert len(listed) == load.SHARED_MAX_LISTED
    assert "snip00.dat" in listed[0] and "snip01.dat" in listed[0]
    assert "20 pixels" in listed[0]
    assert any("2 more pairs of snips" in m for m in logmsgs)


class _State:
    def __init__(self, atomic):
        self._argflag = ArgFlag()
        self._argflag["out"]["verbose"] = -1
        self._atomic = atomic
        self._funcarray = build_funcarray(self._argflag, atomic)


def _shared_in(model, atomic, monkeypatch):
    """Load ``model`` and return the shared pixels found, by file name."""
    monkeypatch.chdir(model.parent)
    slf = _State(atomic)
    _, datlines, _, _ = load.load_input(slf, filename=model.name)
    found = []
    monkeypatch.setattr(load, "warn_shared_pixels",
                        lambda sh, names, waves=None, verbose=2:
                        found.extend((os.path.basename(names[i]),
                                      os.path.basename(names[j]), a.size)
                                     for i, j, a, _ in sh))
    load.load_data(slf, datlines)
    return found


def test_the_lyman_series_snips_of_j1358p6522_share_pixels(atomic_data, monkeypatch):
    model = ROOT / "context/fitting_examples/VMP_DLA/J1358p6522/model/J1358p6522.mod"
    if not model.exists():
        pytest.skip("context model not present")
    found = _shared_in(model, atomic_data, monkeypatch)
    pre = "J1358p6522_fluxcal_H_I_"
    assert (pre + "923_reg.dat", pre + "926_reg.dat", 18) in found
    assert (pre + "926_reg.dat", pre + "930_reg.dat", 18) in found
    assert (pre + "930_reg.dat", pre + "937_reg.dat", 23) in found


def test_o_i_and_si_ii_of_q1243p307_share_pixels_in_every_dataset(
        atomic_data, monkeypatch):
    model = (ROOT / "context/fitting_examples/DH/Q1243p307/model/"
             "Q1243p307_converge_newstart76.mod")
    if not model.exists():
        pytest.skip("context model not present")
    found = _shared_in(model, atomic_data, monkeypatch)
    for pre in ("Q1243p307_", "Q1243p307_prochaska_", "Q1243p307_kirkman_"):
        assert (pre + "O_I_1302.2_reg.dat", pre + "Si_II_1304.4_reg.dat", 97) in found


@pytest.mark.parametrize("model", sorted(ROOT.glob("examples/*/model/fit_spectra.mod")),
                         ids=lambda p: p.parts[-3])
def test_the_shipped_examples_fit_each_pixel_once(model, atomic_data, monkeypatch):
    assert _shared_in(model, atomic_data, monkeypatch) == []
