"""The per-snip component plan (Stage 4.7).

Which model components apply to a given spectrum/snip, and how they group into
emission/absorption blocks, follows from the parsed model and the data alone --
never from the parameter values. It used to be re-derived inside every model
evaluation, which measured at 41.6% of a DH_orders derivative column;
``build_model_plan`` resolves it once per fit instead.

These tests pin the resolution rules directly, on small synthetic models, so a
mistake in them is named here rather than surfacing as a wrong model a fit
later. The equivalence with the old per-call derivation is held by the Stage 0
bitwise gate, which is the right instrument for that.

Generated by RJC and Claude.
"""

import pickle

import numpy as np
import pytest

from alis import model_eval

pytestmark = pytest.mark.unit


class _Model:
    """The smallest ``state`` ``build_model_plan`` reads."""

    def __init__(self, components, specids=("A",), nsnip=1):
        # components: list of (emab, mtyp, [specid, ...])
        self._modpass = {
            "emab": [c[0] for c in components],
            "mtyp": [c[1] for c in components],
            "mkey": [{"specid": list(c[2])} for c in components],
        }
        self._specid = list(specids)
        self._snipid = [f"snip{i}" for i in range(len(specids))]
        self._mplan = None
        self.pos = [np.arange(nsnip + 1) for _ in specids]


def _plan(components, **kw):
    model = _Model(components, **kw)
    return model, model_eval.build_model_plan(model, model.pos)


# -- what is filtered out ----------------------------------------------------


def test_convolution_and_shift_components_are_not_model_components():
    # 'cv' and 'sh' are applied elsewhere in model_func; they must never appear
    # as an emission/absorption entry or they would be evaluated twice.
    _, plan = _plan(
        [("em", "legendre", "A"), ("cv", "vfwhm", "A"), ("sh", "Ashift", "A")]
    )
    assert [e[1] for e in plan[0][0].entries] == ["legendre"]


def test_a_component_for_another_specid_is_left_out():
    _, plan = _plan(
        [("em", "legendre", "AB"), ("ab", "voigt", "A")], specids=("A", "B")
    )
    assert [e[1] for e in plan[0][0].entries] == ["legendre", "voigt"]
    assert [e[1] for e in plan[1][0].entries] == ["legendre"]


def test_absorption_without_emission_is_still_rejected():
    # The model-validity check moved into the plan builder with the loop it
    # came from; it now fires once, at the first evaluation, instead of on
    # every call -- but it must still fire.
    with pytest.raises(SystemExit):
        _plan([("ab", "voigt", "A")])


def test_a_component_shared_by_two_specids_appears_in_both():
    _, plan = _plan([("em", "legendre", "AB")], specids=("A", "B"))
    assert [e[1] for e in plan[0][0].entries] == ["legendre"]
    assert [e[1] for e in plan[1][0].entries] == ["legendre"]


# -- the zero level ----------------------------------------------------------


def test_the_zero_level_is_separated_from_the_other_components():
    # It is read before the influence test in model_func, so it has to be a
    # separate list: an un-influenced snip still needs its zero level.
    _, plan = _plan([("em", "legendre", "A"), ("zl", "const", "A")])
    snip = plan[0][0]
    assert snip.zl == [1]
    assert [e[1] for e in snip.entries] == ["legendre"]


def test_the_zero_level_belongs_to_the_first_snip_only():
    _, plan = _plan([("em", "legendre", "A"), ("zl", "const", "A")], nsnip=3)
    assert plan[0][0].zl == [1]
    assert plan[0][1].zl == []
    assert plan[0][2].zl == []


# -- grouping ----------------------------------------------------------------


def test_a_change_of_emab_starts_a_new_group():
    # model_func alternates: even groups are summed (emission), odd multiplied
    # (absorption), so the grouping decides the arithmetic.
    _, plan = _plan(
        [("em", "legendre", "A"), ("ab", "voigt", "A"), ("em", "gaussian", "A")]
    )
    snip = plan[0][0]
    assert snip.nea == 3
    assert [e[2] for e in snip.entries] == [0, 1, 2]
    assert snip.slots == [["legendre"], ["voigt"], ["gaussian"]]


def test_consecutive_components_of_the_same_kind_share_a_group():
    _, plan = _plan(
        [("em", "legendre", "A"), ("em", "gaussian", "A"), ("ab", "voigt", "A")]
    )
    snip = plan[0][0]
    assert snip.nea == 2
    assert [e[2] for e in snip.entries] == [0, 0, 1]
    assert snip.slots == [["legendre", "gaussian"], ["voigt"]]


def test_the_same_model_type_twice_shares_one_slot():
    # Both voigt components are evaluated in one batched call, so they must
    # land in the same (group, slot) -- that is what lets the dispatcher send
    # them to the GPU together.
    _, plan = _plan(
        [("em", "legendre", "A"), ("ab", "voigt", "A"), ("ab", "voigt", "A")]
    )
    snip = plan[0][0]
    assert [(e[2], e[3]) for e in snip.entries] == [(0, 0), (1, 0), (1, 0)]
    assert snip.slots == [["legendre"], ["voigt"]]


def test_different_model_types_in_one_group_get_different_slots():
    _, plan = _plan(
        [("em", "legendre", "A"), ("ab", "voigt", "A"), ("ab", "tophat", "A")]
    )
    assert [(e[2], e[3]) for e in plan[0][0].entries] == [(0, 0), (1, 0), (1, 1)]


def test_a_variable_component_does_not_start_a_group():
    # 'va' components carry no model of their own (the evaluation loop skips
    # them by name), so they must not open a new emission/absorption block.
    _, plan = _plan(
        [("em", "legendre", "A"), ("va", "variable", "A"), ("ab", "voigt", "A")]
    )
    snip = plan[0][0]
    assert snip.nea == 2
    assert [(e[1], e[2]) for e in snip.entries] == [
        ("legendre", 0),
        ("variable", 0),
        ("voigt", 1),
    ]


def test_every_snip_of_a_spectrum_gets_the_same_structure():
    _, plan = _plan([("em", "legendre", "A"), ("ab", "voigt", "A")], nsnip=4)
    assert len(plan[0]) == 4
    for snip in plan[0]:
        assert snip.slots == [["legendre"], ["voigt"]]


# -- caching -----------------------------------------------------------------


def test_the_plan_is_built_once_and_reused():
    # The whole point: 413 derivative columns must not each rebuild it.
    model = _Model([("em", "legendre", "A"), ("ab", "voigt", "A")])
    first = model_eval.model_plan(model, model.pos)
    assert model_eval.model_plan(model, model.pos) is first


def test_a_different_snip_layout_rebuilds_the_plan():
    # The plotting and simulation paths evaluate different position lists, and
    # the iterate path reloads the model outright; a stale plan would silently
    # evaluate the wrong components.
    model = _Model([("em", "legendre", "A"), ("ab", "voigt", "A")], nsnip=1)
    first = model_eval.model_plan(model, model.pos)
    wider = [np.arange(4)]
    second = model_eval.model_plan(model, wider)
    assert second is not first
    assert len(second[0]) == 3


def test_the_plan_survives_pickling():
    # It is a FitState field, so under Stage 4.5 it travels to every derivative
    # worker through the shared-memory skeleton.
    _, plan = _plan([("em", "legendre", "A"), ("ab", "voigt", "A")])
    out = pickle.loads(pickle.dumps(plan))
    assert out[0][0].entries == plan[0][0].entries
    assert out[0][0].slots == plan[0][0].slots
    assert out[0][0].nea == plan[0][0].nea


def test_a_state_with_no_plan_attribute_yet_gets_one():
    # model_func is handed a ClassMain on the plotting and simulation paths,
    # which has no _mplan until the plan is built and cached on it.
    model = _Model([("em", "legendre", "A")])
    del model._mplan
    assert len(model_eval.model_plan(model, model.pos)) == 1
    assert model._mplan is not None


# -- the accumulation the plan feeds -----------------------------------------


def test_concatenating_the_pieces_matches_appending_them_one_by_one():
    # 4.7 replaced a per-component np.append (which recopied the whole block
    # every time) with one concatenate. Same bytes, one copy.
    rng = np.random.default_rng(0)
    pieces = [rng.random((rng.integers(1, 4), 6)) for _ in range(8)]
    appended = pieces[0]
    for piece in pieces[1:]:
        appended = np.append(appended, piece, axis=0)
    assert np.array_equal(np.concatenate(pieces, axis=0), appended)


# -- the fitted-pixel counts (Stage 4.8) -------------------------------------


class _Windows:
    """The smallest ``state`` ``build_fit_windows`` reads."""

    def __init__(self, wave, fitrange, fitted):
        self._posnfit = [np.asarray(fitrange, dtype=float)]
        self._wavefit = [np.asarray(fitted, dtype=float)]
        self._nfitpix = None
        self.x = [np.asarray(wave, dtype=float)]


def _windows(wave, fitrange, fitted, pos=None):
    state = _Windows(wave, fitrange, fitted)
    pos = pos if pos is not None else [np.array([0, len(wave)])]
    return state, model_eval.build_fit_windows(state, state.x, pos), pos


def test_a_fit_window_counts_the_pixels_inside_it():
    # The count is what the convolution loop uses to step over a snip it is
    # not evaluating; miscounting would slide every later snip's model along
    # the packed vector.
    wave = [1.0, 2.0, 3.0, 4.0, 5.0]
    _, sizes, _ = _windows(wave, [2.0, 4.0], wave)
    assert sizes == [[3]]


def test_pixels_outside_the_fit_range_are_not_counted():
    wave = [1.0, 2.0, 3.0, 4.0, 5.0]
    _, sizes, _ = _windows(wave, [2.5, 3.5], wave)
    assert sizes == [[1]]


def test_only_pixels_that_are_actually_fitted_are_counted():
    # _wavefit holds the wavelengths that survived the fitrange mask, so a
    # pixel inside the range but absent from it must not be counted.
    wave = [1.0, 2.0, 3.0, 4.0, 5.0]
    _, sizes, _ = _windows(wave, [1.0, 5.0], [1.0, 3.0, 5.0])
    assert sizes == [[3]]


def test_each_snip_is_counted_separately():
    wave = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
    state = _Windows(wave, [1.0, 3.0, 4.0, 6.0], wave)
    pos = [np.array([0, 3, 6])]
    assert model_eval.build_fit_windows(state, state.x, pos) == [[3, 3]]


def test_the_counts_are_cached_and_reused():
    state, _, pos = _windows([1.0, 2.0, 3.0], [1.0, 3.0], [1.0, 2.0, 3.0])
    first = model_eval.fit_windows(state, state.x, pos)
    assert model_eval.fit_windows(state, state.x, pos) is first


def test_a_different_wavelength_array_rebuilds_the_counts():
    # Unlike the component plan these depend on the wavelengths, and
    # ClassMain.model_func lets a caller pass a different array with the same
    # snip layout -- so the layout check alone would return a stale count.
    state, _, pos = _windows([1.0, 2.0, 3.0], [1.0, 3.0], [1.0, 2.0, 3.0])
    first = model_eval.fit_windows(state, state.x, pos)
    other = [np.array([1.0, 1.5, 2.0])]
    state._wavefit = [np.array([1.0, 1.5, 2.0])]
    second = model_eval.fit_windows(state, other, pos)
    assert second is not first
    assert second == [[3]]
