"""The example fits, re-run on the GPU backend, against the CPU references
(Stage 4.6, Q4.9).

Everything else in the harness is pinned to ``run backend cpu`` so the suite
stays deterministic (Q4.2). These tests are the counterpart: each shipped
example fit is run again with ``run backend gpu`` -- at one device and at four
-- and its output compared against the **same golden references**, which were
produced on the CPU. The GPU and CPU profiles agree to 1e-12 (Q4.3), orders of
magnitude inside the Stage 0 tolerances, so a real difference shows up as a
failure rather than as noise.

Two things make this a real test rather than a slow way of re-running the CPU:

* ``run gputhresh 0`` forces every group of a GPU-capable function onto the
  device. At the shipped default (10000 pixel-components) *none* of these
  examples is large enough to dispatch, so a GPU run of them is a CPU run
  wearing a different hat.
* Each test asserts that the fit actually launched kernels, by reading the
  count ALIS prints at the end of the fit. Without that, a broken CUDA install,
  a mis-set threshold or a silently-ignored ``run backend`` would all leave the
  test passing on CPU-computed numbers -- the exact trap that cost a whole
  benchmark in Stage 4.3.

Marked ``gpu``, so they run wherever a device is present and skip where one is
not; ``pytest --run-gpu -m gpu`` makes a missing device an error instead.

Generated by RJC and Claude.
"""

import re
import shutil

import pytest
from alisrun import run_alis, stage_case
from compare import (
    CHISQ_RTOL_MINIMISATION,
    FITDAT_ERRFRAC_MINIMISATION,
    compare_fit_dat,
    compare_mod_out,
)
from manifest import discover_cases

pytestmark = [pytest.mark.gpu, pytest.mark.examples]

# Device counts to cover: one device is the simple case, four exercises the
# multi-worker GPU pool (one CUDA context per worker, spawned not forked).
# resolve_backend clamps to the devices actually present, so on a single-GPU
# machine the second variant repeats the first rather than failing.
NGPUS = (1, 4)

# What alfit prints at the end of a fit (minimise._report_dispatch).
_LAUNCHES = re.compile(r"GPU dispatch \(base evaluations\): (\d+) kernel launches")

# ``voigt`` is the only model function with a GPU implementation, so it is the
# presence of a voigt line that decides whether a fit can exercise a kernel at
# all. Matched at the start of a model line, which is how ALIS writes it.
_VOIGT_LINE = re.compile(r"^\s*voigt\b", re.MULTILINE)


def _example_fits():
    """The shipped example fit cases, in manifest order."""
    return [
        case
        for case in discover_cases()
        if case.kind == "fit" and case.name.startswith("examples/")
    ]


def _uses_voigt(case):
    try:
        return bool(_VOIGT_LINE.search(case.mod_file.read_text()))
    except OSError:  # pragma: no cover - a manifest case always has its .mod
        return False


_FITS = _example_fits()
_VOIGT_FITS = [c for c in _FITS if _uses_voigt(c)]
# The cheapest fit with no GPU-capable function, for the fallback check below.
_NO_VOIGT_FIT = min(
    (c for c in _FITS if not _uses_voigt(c)),
    key=lambda c: c.runtime_hrs or 0.0,
    default=None,
)


def _launch_count(proc):
    """Kernel launches the fit reported, or None if it reported nothing.

    Both streams are searched: ALIS's logger writes to stderr, so looking only
    at stdout finds nothing and every test fails claiming the run was on the
    CPU.
    """
    found = _LAUNCHES.search(proc.stdout + proc.stderr)
    return int(found.group(1)) if found else None


def _run_on_gpu(case, tmp_path, ngpus, gputhresh=0):
    """Stage ``case``, fit it on ``ngpus`` devices, return (staged, proc)."""
    staged = stage_case(case, tmp_path)
    mod = staged.staged(case.mod_file)
    proc = run_alis(
        mod,
        runtime_hrs=case.runtime_hrs,
        backend={"backend": "gpu", "ngpus": ngpus, "gputhresh": gputhresh},
    )
    return staged, proc


def _compare_against_cpu_references(staged, mod):
    """The mode (a) comparisons, against the CPU-produced golden files."""
    case = staged.case
    failures = compare_mod_out(
        mod.parent / (mod.name + ".out"),
        case.mod_out_reference,
        CHISQ_RTOL_MINIMISATION,
    )
    for pair in case.data_pairs:
        for ref in pair.reference_fits:
            failures += compare_fit_dat(
                staged.fit_output_for(ref),
                ref,
                errfrac=FITDAT_ERRFRAC_MINIMISATION,
            )
    return failures


def _assert_clean(failures, case, note):
    if failures:
        body = "\n  - ".join(failures)
        pytest.fail(
            f"{case.name} [{note}]: {len(failures)} comparison "
            f"failure(s):\n  - {body}",
            pytrace=False,
        )


@pytest.mark.parametrize("ngpus", NGPUS, ids=[f"ngpus{n}" for n in NGPUS])
@pytest.mark.parametrize("case", _VOIGT_FITS, ids=[c.name for c in _VOIGT_FITS])
def test_gpu_fit_matches_the_cpu_reference(case, ngpus, tmp_path):
    """A GPU-backend fit reproduces the reference the CPU produced.

    Generated by RJC and Claude.
    """
    staged, proc = _run_on_gpu(case, tmp_path, ngpus)
    launches = _launch_count(proc)
    assert launches is not None, (
        f"{case.name}: the fit printed no GPU dispatch report, so the "
        "dispatcher was never enabled -- this ran on the CPU"
    )
    assert launches > 0, (
        f"{case.name}: the GPU backend was selected but launched no kernels, "
        "so the comparison below would pass on CPU-computed numbers"
    )
    _assert_clean(
        _compare_against_cpu_references(staged, staged.staged(case.mod_file)),
        case,
        f"gpu ngpus={ngpus}",
    )
    shutil.rmtree(staged.root, ignore_errors=True)


@pytest.mark.skipif(_NO_VOIGT_FIT is None, reason="every example fit uses voigt")
def test_gpu_backend_is_correct_when_nothing_can_be_dispatched(tmp_path):
    """A GPU fit of a model with no GPU-capable function still fits correctly.

    Only ``voigt`` has a ``call_GPU``, so this model runs every component on
    the CPU path *inside* the GPU backend: a spawned worker pool, one CUDA
    context per worker, and the shared-memory payload of Stage 4.5 travelling
    through ``spawn`` rather than ``fork``. Zero launches is the correct
    outcome here, which is why this case is separated from the ones above --
    there the same number would mean the test had stopped testing anything.

    Generated by RJC and Claude.
    """
    case = _NO_VOIGT_FIT
    staged, proc = _run_on_gpu(case, tmp_path, ngpus=2)
    assert _launch_count(proc) == 0, (
        f"{case.name} has no GPU-capable model function, so it cannot launch "
        "a kernel; a non-zero count means the dispatcher's opt-in is broken"
    )
    _assert_clean(
        _compare_against_cpu_references(staged, staged.staged(case.mod_file)),
        case,
        "gpu, no dispatchable function",
    )
    shutil.rmtree(staged.root, ignore_errors=True)


def test_the_default_threshold_keeps_the_examples_off_the_device(tmp_path):
    """At the shipped ``gputhresh`` these fits dispatch nothing.

    This is why every test above forces ``run gputhresh 0``. It is asserted
    rather than assumed because if the default ever drops far enough for the
    examples to dispatch, the forcing becomes redundant -- and if a future
    change makes the examples large enough, the reason for the forcing has
    changed and should be re-read.

    Generated by RJC and Claude.
    """
    case = next(c for c in _VOIGT_FITS if c.name.startswith("examples/metal_line_abs"))
    staged, proc = _run_on_gpu(case, tmp_path, ngpus=1, gputhresh=10000)
    assert _launch_count(proc) == 0, (
        "metal_line_abs now dispatches at the default gputhresh; the size "
        "threshold or the example has changed, so re-read why these tests "
        "force gputhresh 0"
    )
    shutil.rmtree(staged.root, ignore_errors=True)
