"""The spectrum view and its zoom bar (dashboard Stage 4.5; D38, D43).

Home, ← and →, the zoom box, and + and − along the wavelength axis only; the
40,402 pixels of J1358p6522's spectrum drawn in under half a second off-screen;
steps that break at the data's gaps; a signed velocity axis; and no value in the
view's tooltips.

Generated by RJC and Claude.
"""

import time
from pathlib import Path

import numpy as np
import pytest

pytestmark = pytest.mark.gui

pg = pytest.importorskip("pyqtgraph")

from alis.dashboard.qt import plots as PL  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
J1358 = ROOT / "context/fitting_examples/VMP_DLA/J1358p6522/data/J1358p6522_fluxcal.dat"


@pytest.fixture
def view(qtbot):
    widget = PL.SpectrumView()
    bar = PL.ZoomBar()
    bar.attach(widget)
    qtbot.addWidget(widget)
    qtbot.addWidget(bar)
    widget.resize(1000, 320)
    widget.show()
    qtbot.waitExposed(widget)
    wave = np.linspace(4000.0, 4100.0, 2001)
    flux = 1.0 + 0.1 * np.sin(wave / 3.0)
    widget.set_data(wave, flux, np.full_like(wave, 0.05))
    widget.home()
    bar.remember()
    return widget, bar


def xr(widget):
    return widget.view_range()[0]


def test_steps_are_centred_and_break_at_gaps():
    wave = np.array([1.0, 2.0, 3.0, 10.0, 11.0])
    flux = np.array([5.0, 6.0, 7.0, 8.0, 9.0])
    x, y = PL.step_curve(wave, flux)
    # Two points per pixel, and one break at the gap
    assert x.size == 2 * wave.size + 1 and np.isnan(x).sum() == 1
    assert list(x[:6]) == [0.5, 1.5, 1.5, 2.5, 2.5, 3.5]
    assert list(y[:6]) == [5.0, 5.0, 6.0, 6.0, 7.0, 7.0]
    # Either side of the gap, the pixels keep their own half widths
    assert x[7] == 9.5 and x[8] == 10.5
    bx, by = PL.broken_line(wave, flux)
    assert np.isnan(bx).sum() == 1 and bx.size == wave.size + 1


def test_plus_and_minus_zoom_the_wavelength_axis_only(view, qtbot):
    widget, bar = view
    x0, x1 = xr(widget)
    bar.zoom(1.0 / PL.ZOOM_STEP)
    a0, a1 = xr(widget)
    assert (a1 - a0) == pytest.approx(0.5 * (x1 - x0), rel=1e-6)
    assert 0.5 * (a0 + a1) == pytest.approx(0.5 * (x0 + x1), rel=1e-9)
    bar.zoom(PL.ZOOM_STEP)
    assert xr(widget) == pytest.approx((x0, x1), rel=1e-9)


def test_back_forward_and_home(view, qtbot):
    widget, bar = view
    first = xr(widget)
    bar.zoom(0.5)
    second = xr(widget)
    bar.zoom(0.5)
    third = xr(widget)
    assert bar.buttons["back"].isEnabled() and not bar.buttons["forward"].isEnabled()
    bar.back()
    assert xr(widget) == pytest.approx(second, rel=1e-9)
    bar.back()
    assert xr(widget) == pytest.approx(first, rel=1e-9)
    assert not bar.buttons["back"].isEnabled()
    bar.forward()
    bar.forward()
    assert xr(widget) == pytest.approx(third, rel=1e-9)
    bar.home()
    assert xr(widget)[0] < 4000.0 and xr(widget)[1] > 4100.0


def test_the_zoom_box_and_the_modes(view, qtbot):
    widget, bar = view
    bar.set_mode(PL.ZOOM)
    assert widget.box.state["mouseMode"] == pg.ViewBox.RectMode
    assert bar.buttons["zoom"].isChecked() and not bar.buttons["pan"].isChecked()
    # The box zoom pyqtgraph makes, then remembered for ←
    widget.box.showAxRect(pg.QtCore.QRectF(4020.0, 0.9, 20.0, 0.2))
    bar.remember()
    # pyqtgraph pads the box a little
    assert xr(widget) == pytest.approx((4020.0, 4040.0), abs=1.0)
    bar.back()
    assert xr(widget)[1] - xr(widget)[0] > 90.0
    bar.set_mode(PL.PAN)
    assert widget.box.state["mouseMode"] == pg.ViewBox.PanMode


def test_the_wheel_zooms_wavelength_only(view, qtbot):
    from qtpy import QtCore

    widget, _ = view
    widget.box.enableAutoRange(y=False)
    (x0, x1), y_before = widget.view_range()

    class Wheel:
        def delta(self):
            return 120

        def pos(self):
            return QtCore.QPointF(400.0, 120.0)

        def accept(self):
            pass

    widget.box.wheelEvent(Wheel())
    (a0, a1), y_after = widget.view_range()
    assert (a1 - a0) < (x1 - x0)
    assert y_after == pytest.approx(y_before)


def test_j1358_draws_in_under_half_a_second(qtbot):
    if not J1358.exists():
        pytest.skip("J1358p6522's spectrum is not present")
    table = np.loadtxt(str(J1358))
    assert table.shape[0] == 40402
    widget = PL.SpectrumView()
    qtbot.addWidget(widget)
    widget.resize(1030, 310)
    widget.show()
    qtbot.waitExposed(widget)
    start = time.perf_counter()
    widget.set_data(table[:, 0], table[:, 1], table[:, 2])
    widget.home()
    widget.grab()
    took = time.perf_counter() - start
    assert took < 0.5, took
    # The gap of its source (4535-5593 Å) is not bridged
    item = widget._items["data"]
    assert np.isnan(item.xData).sum() >= 1


def test_the_velocity_axis_is_signed(view):
    widget, _ = view
    widget.set_velocity_centre(4050.0)
    axis = widget.top
    values = axis.tickValues(4045.0, 4055.0, 900)[0][1]
    labels = axis.tickStrings(values, 1.0, 1.0)
    assert "0" in labels
    assert any(lab.startswith("+") for lab in labels)
    assert any(lab.startswith("−") for lab in labels)
    assert PL.signed(100.0) == "+100" and PL.signed(-100.0) == "−100"


def test_log_and_normalised_views(view):
    widget, _ = view
    widget.set_continuum(widget._wave, np.full(widget._wave.size, 2.0))
    widget.set_normalised(np.full(widget._wave.size, 2.0))
    ys = widget._items["data"].yData
    assert np.nanmax(ys) == pytest.approx(0.55, abs=0.01)
    assert np.nanmax(widget._items["continuum"].yData) == pytest.approx(1.0)
    widget.set_normalised(None)
    assert np.nanmax(widget._items["data"].yData) == pytest.approx(1.1, abs=0.01)
    widget.set_log(True)
    assert widget.getPlotItem().ctrl.logYCheck.isChecked()
    widget.set_log(False)


def test_overlays_and_their_signals(view, qtbot):
    widget, _ = view
    widget.set_regions("fit", [(4010.0, 4020.0), (4030.0, 4031.0)], movable=True)
    widget.set_regions("other", [(4040.0, 4045.0)])
    widget.set_regions("shared", [(4018.0, 4019.0)])
    assert len(widget._lists["fit"]) == 2 and len(widget._lists["shared"]) == 1
    widget.set_edges(4005.0, 4095.0)
    moved = []
    widget.edgeMoved.connect(lambda side, x, done: moved.append((side, round(x), done)))
    widget._lists["edges"][1].setValue(4090.0)
    assert moved[-1][:2] == ("high", 4090)
    widget.set_line_ids(
        [(4050.0, "Lyα 1215.7", "hydrogen"), (4051.0, "O I 1302.2", "metal")],
        hidden=7,
    )
    assert len(widget._ids) == 2
    note = widget._lists["note"][0]
    assert note.toPlainText() == "+ 7 lines not labelled"
    widget.set_marker(4050.0)
    widget.set_knots([(4020.0, 1.0), (4060.0, 1.1)])
    assert len(widget._lists["knots"]) == 2
    widget.set_edges()
    assert "edges" not in widget._lists or not widget._lists["edges"]


def test_clicks_and_spans_report_data_coordinates(view, qtbot):
    widget, _ = view
    got = []
    widget.clicked.connect(lambda x, y: got.append(("click", round(x))))
    widget.spanned.connect(lambda m, a, b: got.append((m, round(a), round(b))))
    widget.set_mode(PL.MASK)
    widget.box.spanned.emit(PL.MASK, 4020.0, 4022.0, True)
    widget.box.clicked.emit(4050.0, 1.0)
    assert ("mask", 4020, 4022) in got and ("click", 4050) in got


class FakeDrag:
    """A finished drag across the view, from one wavelength to another."""

    def __init__(self, box, button, start, end):
        from qtpy import QtCore

        self.box = box
        self._button = button
        y = 0.5 * sum(box.viewRange()[1])
        self._start = box.mapViewToScene(QtCore.QPointF(start, y))
        self._end = box.mapViewToScene(QtCore.QPointF(end, y))

    def button(self):
        return self._button

    def buttonDownScenePos(self):
        return self._start

    def scenePos(self):
        return self._end

    def isFinish(self):
        return True

    def accept(self):
        pass


def test_in_draw_mode_a_right_drag_masks(view, qtbot):
    """As in prepfit: a left drag adds a region, a right drag leaves pixels out."""
    from qtpy import QtCore

    widget, _ = view
    got = []
    widget.spanned.connect(lambda m, a, b: got.append((m, round(a), round(b))))
    widget.set_mode(PL.DRAW)
    widget.box.setXRange(4000.0, 4100.0, padding=0)
    left, right = QtCore.Qt.MouseButton.LeftButton, QtCore.Qt.MouseButton.RightButton
    widget.box.mouseDragEvent(FakeDrag(widget.box, left, 4020.0, 4030.0))
    widget.box.mouseDragEvent(FakeDrag(widget.box, right, 4040.0, 4045.0))
    assert got == [("draw", 4020, 4030), ("mask", 4040, 4045)]


def test_no_value_in_the_tooltips(view):
    widget, bar = view
    from qtpy import QtWidgets

    tips = [w.toolTip() for w in bar.findChildren(QtWidgets.QWidget) if w.toolTip()]
    tips += [widget.toolTip()]
    assert all(not any(ch.isdigit() for ch in tip) for tip in tips), tips
