"""Blinding and export in the window (dashboard Stage 3.10, D24, D10, Q3.9, Q3.13).

- Unblinding needs the confirmation, is logged in the bundle and clears the history.
- Export warns when anything is blinded.
- Switching global blind on is one step, which undo does not pass.
- The pill says what is blinded.

Generated by RJC and Claude.
"""

import os
import re

import pytest
from dashboard_qt_helpers import BLIND, METAL, make_window, wait_idle

pytestmark = pytest.mark.gui

pytest.importorskip("qtpy.QtWidgets")
pytest.importorskip("pyqtgraph")

from qtpy import QtWidgets  # noqa: E402

from alis import bundle as B  # noqa: E402
from alis.dashboard import blinding as BL  # noqa: E402
from alis.dashboard.qt import dialogs as D  # noqa: E402


@pytest.fixture
def window(qtbot, tmp_path, monkeypatch):
    monkeypatch.setenv("ALIS_HOME", str(tmp_path / "home"))
    win = make_window(qtbot, tmp_path / "home")
    yield win
    if win.session is not None:
        win.session.discard_recovery()
        win.session = None


def open_saved(window, qtbot, model, tmp_path):
    path = tmp_path / "project.model"
    B.pack_to(str(model), str(path), with_outputs=False)
    window.open_path(str(path))
    wait_idle(qtbot, window)
    return str(path)


def ok_button(dialog):
    return dialog.box.button(QtWidgets.QDialogButtonBox.StandardButton.Ok)


def test_the_pill_says_what_is_blinded(window, qtbot, tmp_path):
    open_saved(window, qtbot, BLIND, tmp_path)
    assert window.pill.text() == "Blinded: Si II"
    assert window.pill.property("blinded") == "true"
    window.do_file_close()
    assert window.pill.text() == "Not blinded"


def test_blind_the_analysis_is_one_step_undo_does_not_pass(window, qtbot, tmp_path):
    open_saved(window, qtbot, METAL, tmp_path)
    assert window.pill.text() == "Not blinded"
    # Cancelled: nothing happens
    window.qactions["model.blind"].trigger()
    assert window.pill.text() == "Not blinded"
    window.answers.answers["blind"] = "Blind"
    window.qactions["model.blind"].trigger()
    assert window.pill.text() == "Blind analysis"
    assert not window.qactions["edit.undo"].isEnabled()
    window.qactions["edit.undo"].trigger()
    assert window.session.project.parsed.blind
    # Asked again, it says so
    window.qactions["model.blind"].trigger()
    assert window.answers.asked[-1][2] == "The analysis is blinded already."


def test_blind_lines(window, qtbot, tmp_path):
    open_saved(window, qtbot, METAL, tmp_path)
    project = window.session.project

    def answer(dialog):
        assert isinstance(dialog, D.BlindLinesDialog)
        items = dialog.items()
        # Lines are listed by system, component and ion, with no values
        texts = [i.text(0) for i in items]
        assert any(t.startswith("O I · line") for t in texts)
        assert not any(re.search(r"\d\.\d", t) for t in texts)
        items[0].setCheckState(0, items[0].checkState(0).__class__.Checked)
        return 1

    window.on_dialog = answer
    window.qactions["model.blind_lines"].trigger()
    assert len(project.hidden_lines()) == 1
    assert window.pill.text().startswith("Blinded: ")
    assert not window.qactions["edit.undo"].isEnabled()


def test_unblinding_needs_the_confirmation_and_is_logged(window, qtbot, tmp_path):
    path = open_saved(window, qtbot, BLIND, tmp_path)
    project = window.session.project
    seen = []

    def refuse(dialog):
        assert isinstance(dialog, D.UnblindDialog)
        assert "cannot be undone" in dialog.findChild(QtWidgets.QLabel).text()
        assert not ok_button(dialog).isEnabled()
        dialog.note.setText("A reason")
        assert not ok_button(dialog).isEnabled()
        dialog.confirm.setChecked(True)
        dialog.note.setText("")
        assert not ok_button(dialog).isEnabled()
        seen.append("refused")
        return 0

    window.on_dialog = refuse
    window.qactions["model.unblind"].trigger()
    assert seen == ["refused"] and project.hidden_lines()

    def confirm(dialog):
        dialog.note.setText("The paper is submitted")
        dialog.confirm.setChecked(True)
        assert ok_button(dialog).isEnabled()
        return 1

    # A step to undo, which unblinding clears
    window.panel.editor.selectAll()
    window.on_dialog = confirm
    window.qactions["model.unblind"].trigger()
    assert not project.hidden_lines()
    assert window.pill.text() == "Not blinded"
    assert not window.session.history.done
    shown = window.panel.editor.toPlainText()
    si = next(ln for ln in shown.splitlines() if "28Si_II" in ln)
    assert BL.MASK not in si and "13.0" in si and "blind=False" in si
    log = B.read(path).manifest["unblinding"]
    assert log[-1]["note"] == "The paper is submitted"
    assert not window.session.dirty
    # Nothing is blinded any more
    window.qactions["model.unblind"].trigger()
    assert window.answers.asked[-1][2] == "Nothing is blinded in this project."


def test_export_warns_when_anything_is_blinded(window, qtbot, tmp_path):
    open_saved(window, qtbot, BLIND, tmp_path)
    out = tmp_path / "exported"
    out.mkdir()
    window.chosen["folder"] = str(out)
    # Cancelled at the warning: nothing is written
    window.qactions["file.export"].trigger()
    assert window.answers.asked[-1][0] == "export_blind"
    assert "plain text" in window.answers.asked[-1][2]
    assert os.listdir(out) == []
    window.answers.answers["export_blind"] = "Export"
    window.qactions["file.export"].trigger()
    model = out / "model" / "fit_spectra.mod"
    assert model.exists()
    assert "ion=28Si_II 13.0" in " ".join(model.read_text().split())
    assert window.answers.asked[-1][0] == "tell"
    assert "Wrote" in window.answers.asked[-1][2]
    assert "(D10)" not in window.answers.asked[-1][2]


def test_export_of_an_unblinded_project_does_not_warn(window, qtbot, tmp_path):
    open_saved(window, qtbot, METAL, tmp_path)
    out = tmp_path / "exported"
    out.mkdir()
    window.chosen["folder"] = str(out)
    window.qactions["file.export"].trigger()
    assert [a[0] for a in window.answers.asked] == ["tell"]
    assert (out / "model" / "fit_spectra.mod").exists()
    # Exporting again asks before overwriting
    window.qactions["file.export"].trigger()
    assert window.answers.asked[-1][0] == "export_overwrite"
