"""Unit tests for the stable, non-file-format logic in ``alis.load``.

Covers CPU-count resolution, wavelength bin-size computation, tied-parameter
expression remapping (``getis`` / ``load_tied``), and an atomic-data schema
smoke test. The file-format loaders (FITS/ASCII/full model parsing) are
intentionally *not* covered here -- they are deferred to Stage 5, which
reshapes I/O.

Generated by RJC and Claude.
"""

from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

import alis
from alis import load
from alis.config import ArgFlag, AtomicData

pytestmark = pytest.mark.unit

CLIGHT = 2.99792458e5  # km/s (as used inside get_binsize)


# -- cpucheck -----------------------------------------------------------------


@pytest.fixture
def fixed_cpu_count(monkeypatch):
    """Pin the reported core count so the resolution logic is deterministic."""
    monkeypatch.setattr(load, "cpu_count", lambda: 8)
    return 8


def test_cpucheck_all_uses_every_core(fixed_cpu_count):
    assert load.cpucheck("all", verbose=0) == 8


def test_cpucheck_none_leaves_one_free(fixed_cpu_count):
    assert load.cpucheck(None, verbose=0) == 7


def test_cpucheck_explicit_value(fixed_cpu_count):
    assert load.cpucheck(4, verbose=0) == 4


def test_cpucheck_negative_counts_back_from_total(fixed_cpu_count):
    # -1 means "all but one" (ncpu += cpucnt).
    assert load.cpucheck(-1, verbose=0) == 7


def test_cpucheck_over_request_clamps(fixed_cpu_count):
    assert load.cpucheck(100, verbose=0) == 8


# -- get_binsize --------------------------------------------------------------


def test_get_binsize_angstrom_uniform_grid():
    wave = np.array([100.0, 101.0, 102.0, 103.0])
    assert np.isclose(load.get_binsize(wave, bintype="A"), 1.0)
    full = load.get_binsize(wave, bintype="A", maxonly=False)
    assert full.shape == wave.shape
    assert np.allclose(full, 1.0)


def test_get_binsize_kms_conversion():
    wave = np.array([100.0, 101.0, 102.0, 103.0])
    full = load.get_binsize(wave, bintype="km/s", maxonly=False)
    # Interior pixels: 1 Angstrom step scaled to km/s at that wavelength.
    assert np.isclose(full[1], CLIGHT * 1.0 / 101.0, rtol=1e-6)


def test_get_binsize_unknown_bintype_is_defensive():
    # Unknown bintype logs a bug (msgs.bug) but does not sys.exit.
    wave = np.array([100.0, 101.0, 102.0])
    load.get_binsize(wave, bintype="nonsense", verbose=0)


# -- getis / load_tied (tied-parameter expression remapping) ------------------


def test_getis_remaps_global_indices_to_free_indices():
    # infl = [opinfl (free ids), pinfl (global ids)], indexed [sp][sn][j].
    pinfl = [[[5, 3]]]  # region (0,0) contains global params 5 and 3
    opinfl = [[[1, 0]]]  # global 5 -> free 1, global 3 -> free 0
    infl = [opinfl, pinfl]
    jval, pstr = load.getis("p[3]*2.0", 5, infl)
    assert jval == 1  # LHS (global 5) -> free 1
    assert pstr == "p[0]*2.0"  # RHS global 3 -> free 0


def test_getis_retlhs_false_returns_expression_only():
    infl = [[[[1, 0]]], [[[5, 3]]]]
    pstr = load.getis("p[3]*2.0", 5, infl, retlhs=False)
    assert pstr == "p[0]*2.0"


def test_load_tied_applies_direct_expressions():
    # infl=None branch: execute each tied expression against the array in place.
    p = np.array([1.0, 2.0, 0.0])
    ptied = ["", "", "p[0]+p[1]"]
    out = load.load_tied(p, ptied)
    assert out[2] == 3.0  # p[2] = p[0] + p[1]


# -- load_atomic (schema / smoke) --------------------------------------------


def test_load_atomic_schema_and_lya_present():
    cfg = ArgFlag()
    cfg["run"]["atomic"] = str(Path(alis.__file__).parent / "data" / "atomic.xml")
    cfg["out"]["verbose"] = 0
    atm = load.load_atomic(SimpleNamespace(_argflag=cfg))

    assert isinstance(atm, AtomicData)
    n = len(atm["Ion"])
    assert n > 100
    # Parallel arrays are the same length.
    assert len(atm["Wavelength"]) == n
    assert len(atm["fvalue"]) == n
    assert len(atm["Gamma"]) == n

    # A known transition: HI Lyman-alpha near 1215.67 A with f ~ 0.416.
    lya = atm["Ion"] == "1H_I"
    assert lya.any()
    waves = atm["Wavelength"][lya]
    near = np.abs(waves - 1215.67) < 0.1
    assert near.any(), "HI Lyman-alpha not found in atomic data"
    assert atm["fvalue"][lya][near][0] > 0.0


# -- pinfl_changed (Stage 3.5.2 influence-stability check) --------------------


def _pinfl(pinfl):
    """Wrap a pinfl table (global param ids per [sp][sn]) as [opinfl, pinfl]."""
    return [None, pinfl]


def test_pinfl_changed_identical_is_empty():
    ref = _pinfl([[np.array([0, 1]), np.array([2])]])
    assert load.pinfl_changed(ref, ref) == []


def test_pinfl_changed_is_order_insensitive():
    # Same influence set, different array order -> not "changed" (compared as sets).
    ref = _pinfl([[np.array([0, 1])]])
    new = _pinfl([[np.array([1, 0])]])
    assert load.pinfl_changed(ref, new) == []


def test_pinfl_changed_detects_added_parameter():
    ref = _pinfl([[np.array([0, 1]), np.array([2])]])
    new = _pinfl([[np.array([0, 1]), np.array([2, 3])]])  # region (0,1) gained 3
    assert load.pinfl_changed(ref, new) == [(0, 1)]


def test_pinfl_changed_reports_every_changed_region():
    ref = _pinfl([[np.array([0]), np.array([1])], [np.array([2])]])
    new = _pinfl([[np.array([9]), np.array([1])], [np.array([2, 5])]])
    assert load.pinfl_changed(ref, new) == [(0, 0), (1, 0)]


# -- set_params duplicate detection -------------------------------------------


class _Recorder:
    """Collects what ``alis.load`` reports, without going through logging."""

    def __init__(self):
        self.said = []

    def info(self, text, verbose=None):
        self.said.append(text)

    def warn(self, text, verbose=None):
        self.said.append(text)

    def error(self, text, verbose=None):  # pragma: no cover - must not fire
        raise AssertionError(text)

    def newline(self, verbose=None):
        return "\n"


@pytest.fixture
def recorder(monkeypatch):
    rec = _Recorder()
    monkeypatch.setattr(load, "msgs", rec)
    return rec


def test_set_params_applies_the_last_value_of_a_repeated_setting(recorder):
    # Last-one-wins is the documented behaviour and must not change: it is how a
    # model file overrides settings.alis.
    cfg = load.set_params(["run ngpus 4\n", "run ngpus 0\n"], ArgFlag())
    assert cfg["run"]["ngpus"] == 0


def test_set_params_warns_when_a_setting_is_repeated_in_one_block(recorder):
    # Silent last-one-wins is how a benchmark that prepended 'run ngpus 4' to a
    # file already carrying 'run ngpus 0' ran on the CPU while claiming the GPU
    # (Stage 4.3). The values must appear so the message is actionable.
    load.set_params(["run ngpus 4\n", "run ngpus 0\n"], ArgFlag(), setstr="Model ")
    hits = [t for t in recorder.said if "set more than once" in t]
    assert len(hits) == 1
    assert "run ngpus" in hits[0]
    assert "Model " in hits[0]
    assert "'4'" in hits[0] and "'0'" in hits[0]


def test_set_params_is_silent_when_every_setting_appears_once(recorder):
    load.set_params(
        ["run ngpus 0\n", "run ncpus 2\n", "chisq ftol 1.0E-8\n"], ArgFlag()
    )
    assert [t for t in recorder.said if "set more than once" in t] == []


def test_set_params_ignores_repeats_in_comments_and_blank_lines(recorder):
    load.set_params(["run ngpus 0\n", "# run ngpus 4\n", "\n"], ArgFlag())
    assert [t for t in recorder.said if "set more than once" in t] == []


def test_set_params_does_not_warn_across_separate_calls(recorder):
    # Repeats *across* calls are the intended override mechanism: settings.alis
    # is read first, then the model file overrides it.
    cfg = load.set_params(["run ngpus 0\n"], ArgFlag())
    cfg = load.set_params(["run ngpus 2\n"], cfg)
    assert cfg["run"]["ngpus"] == 2
    assert [t for t in recorder.said if "set more than once" in t] == []


def test_the_shipped_default_settings_have_no_repeats(recorder):
    # settings.alis is read on every run; a repeat there would warn every time.
    path = Path(alis.__file__).parent / "data" / "settings.alis"
    load.set_params(path.read_text().splitlines(), ArgFlag(), setstr="Default ")
    assert [t for t in recorder.said if "set more than once" in t] == []
