"""The `.mod` model-block parser (Stage 5.5).

`load_model` is where a model file becomes a `ModelPass`: which parameters the
user gave and how (positionally or by name), which are tied to which, which are
fixed, and what `fix` / `lim` lines do on top. Heavy `load_model` parsing was
deferred out of the cross-cutting unit-test task
(`claude_prompts/refactor_code_unit_tests.md`) and into this stage; this is it.

No data and no fit: `load_model` needs only a specid list and a function
registry, so every test here is a few model lines and an assertion on the
parsed structure. `tests/test_writer_round_trip.py` covers the same parser from
the other end, on 40 real saved models; this covers the individual rules.

The `input` tri-state below deserves its own mention. `mkey[i]['input'][par]`
records whether the user gave a parameter *on that line* -- 0 not at all,
1 positionally, 2 by name -- and `parout` echoes only what it says was given.
Getting that record wrong is the whole of the Stage 5.4 `damping=` bug.

Generated by RJC and Claude.
"""

import numpy as np
import pytest

from alis import load
from alis.config import ArgFlag, ModelPass
from alis.main import build_funcarray

pytestmark = pytest.mark.unit


class _State:
    """The attributes `load_model` / `load_parinfo` read, and nothing else.

    A fresh registry per state: `load_model` writes `fix` and `lim` lines
    straight onto the shared function *instances* (`_fixpar`, `_limits`), so a
    registry reused between tests would carry one test's `fix` into the next.
    """

    def __init__(self, atomic, specid=("0",)):
        self._argflag = ArgFlag()
        self._argflag["out"]["verbose"] = -1
        self._atomic = atomic
        self._funcarray = build_funcarray(self._argflag, atomic)
        self._specid = np.array(list(specid))
        self._resn = []
        self._shft = []


# Two absorption lines of the same function, which is what the `input` record
# has to keep apart: the first names nothing but its ion, the second names both
# ColDens and damping.
MODEL = [
    "emission\n",
    "  legendre 1.0 0.01 specid=0\n",
    "absorption\n",
    "  voigt ion=16O_I 14.0 0.0 5.0da 8000.0TA specid=0\n",
    "  voigt ion=28Si_II ColDens=13.0 0.0 5.0da 8000.0TA damping=2.5 specid=0\n",
]


@pytest.fixture
def state(atomic_data):
    return _State(atomic_data)


def parse(state, lines):
    """(modpass, parinfo) for a model block."""
    state._modpass = load.load_model(state, lines)
    state._links = load.load_links(state, [])
    parinfo, _levadd = load.load_parinfo(state)
    return state._modpass, parinfo


def nfree(parinfo):
    return sum(1 for p in parinfo if not p.get("fixed", 0))


# -- structure ----------------------------------------------------------------


def test_the_model_block_is_split_into_components_and_tagged(state):
    mp, _ = parse(state, MODEL)
    assert mp["mtyp"] == ["legendre", "voigt", "voigt"]
    assert mp["emab"] == ["em", "ab", "ab"]


def test_a_zerolevel_section_is_tagged_separately(state):
    mp, _ = parse(
        state,
        ["emission\n", "  legendre 1.0 specid=0\n", "zerolevel\n", "  constant 0.0\n"],
    )
    assert mp["emab"] == ["em", "zl"]


def test_the_zero_level_may_only_be_given_once(state):
    with pytest.raises(SystemExit):
        parse(
            state,
            ["zerolevel\n", "  constant 0.0\n", "zerolevel\n", "  constant 0.1\n"],
        )


def test_every_parameter_remembers_which_model_line_it_came_from(state):
    mp, _ = parse(state, MODEL)
    # modpass['line'] is what the GUI and the error messages use to point back
    # at the file; entry j is the index into modlines of parameter j.
    assert mp["line"][:2] == [1, 1]  # the legendre line
    assert set(mp["line"][2:9]) == {3}  # the first voigt
    assert set(mp["line"][9:]) == {4}  # the second


def test_blank_and_commented_model_lines_are_skipped(state):
    mp, _ = parse(
        state,
        ["\n", "# a comment\n", "emission\n", "  legendre 1.0 specid=0\n"],
    )
    assert mp["mtyp"] == ["legendre"]


def test_an_unrecognised_function_is_rejected(state):
    with pytest.raises(SystemExit):
        parse(state, ["absorption\n", "  wibble 1.0 specid=0\n"])


def test_too_many_parameters_are_rejected(state):
    # voigt takes seven; this line gives eight.
    with pytest.raises(SystemExit):
        parse(state, ["absorption\n", "  voigt ion=1H_I 1 2 3 4 5 6 7 8\n"])


def test_a_component_cannot_name_a_specid_with_no_data(state):
    with pytest.raises(SystemExit):
        parse(
            state, ["absorption\n", "  voigt ion=1H_I 14.0 0.0 5.0 10000.0 specid=7\n"]
        )


# -- which parameters the user gave, and how (the Stage 5.4 record) ----------


def test_the_input_record_distinguishes_named_positional_and_absent(state):
    mp, _ = parse(state, MODEL)
    first, second = mp["mkey"][1]["input"], mp["mkey"][2]["input"]
    assert first["ColDens"] == 1, "given positionally on the first line"
    assert second["ColDens"] == 2, "given by name on the second"
    assert first["damping"] == 0, "not given at all on the first line"
    assert second["damping"] == 2, "given by name on the second"


def test_the_input_record_is_per_line_and_not_shared_between_lines(state):
    """The Stage 5.4 root cause, pinned directly.

    Since Stage 2 a function is instantiated once and reused for every line of
    its type. `load()` records the named parameters in the *instance's*
    `_keywd['input']` and then shallow-copies `_keywd` into `mkey`, so without
    `call_function_load` clearing it the record is never reset between lines
    *and* every line ends up sharing one dict -- and `parout` then echoes, on
    every line, the union of what any line named.
    """
    mp, _ = parse(state, MODEL)
    assert mp["mkey"][1]["input"] is not mp["mkey"][2]["input"]


def test_call_function_load_is_what_keeps_the_record_per_line(state):
    """Bypassing the guard reproduces the bug, so the guard is load-bearing."""
    inst = state._funcarray[2]["voigt"]
    cls = state._funcarray[1]["voigt"]
    named = "ion=1H_I 14.0 0.0 5.0 10000.0 damping=1.0 specid=0"
    plain = "ion=1H_I 14.0 0.0 5.0 10000.0 specid=0"

    leaky = ModelPass()
    leaky, _ = cls.load(inst, named, 0, leaky, state._specid)
    leaky, _ = cls.load(inst, plain, 1, leaky, state._specid)
    assert leaky["mkey"][0]["input"] is leaky["mkey"][1]["input"]
    assert leaky["mkey"][1]["input"]["damping"] == 2, (
        "the second line inherits a damping it never named -- exactly what the "
        "writer used to echo onto all 12 helium34 voigt lines"
    )

    guarded = ModelPass()
    guarded, _ = load.call_function_load(cls, inst, named, 0, guarded, state._specid)
    guarded, _ = load.call_function_load(cls, inst, plain, 1, guarded, state._specid)
    assert guarded["mkey"][0]["input"]["damping"] == 2
    assert guarded["mkey"][1]["input"]["damping"] == 0


def test_a_parameter_left_out_takes_its_default_and_is_fixed(state):
    """voigt's damping defaults to 0.0 *and* to fixed, which is why writing it
    back out without a fix marker changed the degrees of freedom (Stage 5.4)."""
    mp, parinfo = parse(
        state, ["absorption\n", "  voigt ion=1H_I 14.0 0.0 5.0 10000.0 specid=0\n"]
    )
    damping = state._funcarray[2]["voigt"]._parid.index("damping")
    assert mp["mfix"][0][damping] == 1
    assert mp["mpar"][0][damping] == 0.0


# -- ties ---------------------------------------------------------------------


def test_a_lower_case_tie_label_ties_the_parameter_and_leaves_it_free(state):
    mp, parinfo = parse(state, MODEL)
    labels = [t[0] for t in mp["tpar"]]
    assert "da" in labels
    bturb = state._funcarray[2]["voigt"]._parid.index("bturb")
    assert mp["mfix"][1][bturb] == 0


def test_an_upper_case_tie_label_ties_the_parameter_and_fixes_it(state):
    mp, _ = parse(state, MODEL)
    temperature = state._funcarray[2]["voigt"]._parid.index("temperature")
    assert mp["mfix"][1][temperature] == 1
    assert mp["mfix"][2][temperature] == 1


def test_two_lines_sharing_a_tie_label_share_one_free_parameter(state):
    tied = [
        "absorption\n",
        "  voigt ion=16O_I 14.0 0.0 5.0da 10000.0TA specid=0\n",
        "  voigt ion=28Si_II 13.0 0.0 5.0da 10000.0TA specid=0\n",
    ]
    untied = [line.replace("da", "").replace("TA", "") for line in tied]
    mp_t, parinfo_t = parse(state, tied)
    mp_u, parinfo_u = parse(_State(state._atomic), untied)
    # Tied: the two b's collapse to one entry and the two T's to one, so 12
    # parameters instead of 14; free are N and z on each line plus the shared
    # b (the shared T is upper case, hence fixed).
    assert (len(mp_t["p0"]), nfree(parinfo_t)) == (12, 5)
    # Untied: every parameter stands alone, and both T's are now free.
    assert (len(mp_u["p0"]), nfree(parinfo_u)) == (14, 8)


def test_a_tie_label_records_where_its_value_lives(state):
    mp, _ = parse(state, MODEL)
    for label, index in mp["tpar"]:
        assert 0 <= index < len(mp["p0"])
    lookup = dict(mp["tpar"])
    assert mp["p0"][lookup["da"]] == 5.0
    assert mp["p0"][lookup["TA"]] == 8000.0


# -- an unsigned exponent is not scientific notation -------------------------
#
# '<value><tie label>' in one word makes '1e4' ambiguous, and ALIS resolves it
# the way that surprises people: the value 1.0, tied to a label 'e4'. Two lines
# both written '1e4' then silently share one free parameter. Nothing downstream
# can tell -- 'e4' is a legal label -- so it is rejected at the parse.


@pytest.mark.parametrize("token", ["1e4", "1.0e345", "5.0E45", "2.0E5", "7E054"])
def test_an_unsigned_exponent_is_rejected(state, token, logmsgs):
    with pytest.raises(SystemExit):
        parse(
            state,
            [
                "absorption\n",
                "  voigt ion=1H_I 14.0 0.0 {0:s} 10000.0 specid=0\n".format(token),
            ],
        )
    said = "\n".join(logmsgs)
    assert token in said
    assert "E+" in said and "E-" in said, "the message must show the fix"


@pytest.mark.parametrize(
    "token,value", [("1.0E+04", 1.0e4), ("1.0e-03", 1.0e-3), ("3.0e+1", 30.0)]
)
def test_a_signed_exponent_is_still_a_number(state, token, value):
    mp, _ = parse(
        state,
        [
            "absorption\n",
            "  voigt ion=1H_I 14.0 0.0 {0:s} 10000.0 specid=0\n".format(token),
        ],
    )
    bturb = state._funcarray[2]["voigt"]._parid.index("bturb")
    assert mp["mpar"][0][bturb] == value
    assert mp["tpar"] == [], "a number is not a tie"


@pytest.mark.parametrize("label", ["E5t", "e345j", "e293e", "da", "TA"])
def test_a_label_that_is_not_only_digits_after_the_e_is_left_alone(state, label):
    """Only the genuinely ambiguous form is rejected. `E5t` cannot be a number,
    so it is an ordinary tie label and stays one."""
    mp, _ = parse(
        state,
        [
            "absorption\n",
            "  voigt ion=1H_I 14.0 0.0 5.0{0:s} 10000.0 specid=0\n".format(label),
        ],
    )
    assert [t[0] for t in mp["tpar"]] == [label]
    bturb = state._funcarray[2]["voigt"]._parid.index("bturb")
    assert mp["mpar"][0][bturb] == 5.0


def test_every_model_function_rejects_an_unsigned_exponent(atomic_data, logmsgs):
    """`check_tied_param` is copy-pasted into 20 places across 17 modules, so
    adding the check to one of them says nothing about the other 19. Rather
    than read the source, drive every function in the registry.

    The message is checked as well as the exit: several functions reject a bare
    parameter list for other reasons (a missing required keyword), and those
    would make an exit-only assertion pass without the check being reached.
    """
    registry = build_funcarray(ArgFlag(), atomic_data)
    specid = np.array(["0"])
    unprotected = []
    for name in registry[0]:
        before = len(logmsgs)
        try:
            load.call_function_load(
                registry[1][name], registry[2][name], "1e4", 0, ModelPass(), specid
            )
            unprotected.append(name)
        except SystemExit:
            if not any("Ambiguous" in m for m in logmsgs[before:]):
                unprotected.append(name)
    assert unprotected == [], unprotected
    assert len(registry[0]) > 25, "the registry looks unexpectedly small"


# -- fix ----------------------------------------------------------------------


def test_fix_names_a_parameter_of_a_whole_function(state):
    _mp, parinfo = parse(state, MODEL)
    before = nfree(parinfo)
    _mp2, parinfo2 = parse(_State(state._atomic), ["fix voigt redshift True\n"] + MODEL)
    assert nfree(parinfo2) == before - 2, "both voigt lines lose their redshift"


def test_fix_requires_exactly_three_arguments(state):
    with pytest.raises(SystemExit):
        parse(state, ["fix voigt redshift\n"] + MODEL)


def test_fix_rejects_a_function_or_parameter_it_does_not_know(state):
    with pytest.raises(SystemExit):
        parse(state, ["fix wibble redshift True\n"] + MODEL)
    with pytest.raises(SystemExit):
        parse(_State(state._atomic), ["fix voigt wibble True\n"] + MODEL)


def test_fix_param_fixes_everything_carrying_a_tie_label(state):
    _mp, parinfo = parse(state, MODEL)
    before = nfree(parinfo)
    _mp2, parinfo2 = parse(_State(state._atomic), ["fix param da True\n"] + MODEL)
    assert nfree(parinfo2) == before - 1


def test_fix_param_false_releases_a_parameter_the_label_had_fixed(state):
    # TA is upper case, so it arrives fixed; 'fix param TA False' frees it.
    _mp, parinfo = parse(state, MODEL)
    before = nfree(parinfo)
    _mp2, parinfo2 = parse(_State(state._atomic), ["fix param TA False\n"] + MODEL)
    assert nfree(parinfo2) == before + 1


def test_fix_param_with_a_number_sets_the_value_as_well(state):
    mp, _ = parse(state, ["fix param da 3.5\n"] + MODEL)
    lookup = dict(mp["tpar"])
    assert mp["p0"][lookup["da"]] == 3.5
    bturb = state._funcarray[2]["voigt"]._parid.index("bturb")
    assert mp["mpar"][1][bturb] == 3.5
    assert mp["mpar"][2][bturb] == 3.5


def test_fix_param_on_a_tie_label_that_does_not_exist_is_fatal(state):
    with pytest.raises(SystemExit):
        parse(state, ["fix param zz True\n"] + MODEL)


# -- lim ----------------------------------------------------------------------


def test_lim_bounds_a_parameter_of_a_whole_function(state):
    _mp, parinfo = parse(state, ["lim voigt ColDens [12.0,16.0]\n"] + MODEL)
    coldens = state._funcarray[2]["voigt"]._parid.index("ColDens")
    # parinfo runs over p0, whose first two entries are the legendre line.
    bounded = parinfo[2 + coldens]
    assert bounded["limited"] == [1, 1]
    assert bounded["limits"] == [12.0, 16.0]


def test_lim_accepts_none_for_a_one_sided_bound(state):
    _mp, parinfo = parse(state, ["lim voigt ColDens [12.0,None]\n"] + MODEL)
    coldens = state._funcarray[2]["voigt"]._parid.index("ColDens")
    assert parinfo[2 + coldens]["limited"] == [1, 0]
    assert parinfo[2 + coldens]["limits"][0] == 12.0


def test_lim_param_bounds_everything_carrying_a_tie_label(state):
    _mp, parinfo = parse(state, ["lim param da [1.0,9.0]\n"] + MODEL)
    bturb = state._funcarray[2]["voigt"]._parid.index("bturb")
    assert parinfo[2 + bturb]["limited"] == [1, 1]
    assert parinfo[2 + bturb]["limits"] == [1.0, 9.0]


def test_lim_requires_a_two_element_range(state):
    with pytest.raises(SystemExit):
        parse(state, ["lim voigt ColDens [12.0]\n"] + MODEL)


def test_lim_requires_three_arguments(state):
    with pytest.raises(SystemExit):
        parse(state, ["lim voigt ColDens\n"] + MODEL)


def test_lim_param_on_a_tie_label_that_does_not_exist_is_fatal(state):
    with pytest.raises(SystemExit):
        parse(state, ["lim param zz [1.0,9.0]\n"] + MODEL)


# -- the resolution and shift functions appended after the model -------------


def test_the_resolution_and_shift_are_parsed_as_extra_components(state):
    """They are not in the `model read` block, but they carry parameters that
    can be fitted and tied, so `load_model` appends them to the same structure
    with their own tags -- which is how the writer knows to print them under
    "Convolution Models" and "Shift Models" rather than inline."""
    state._resn = [np.array(["vfwhm(7.0)"])]
    state._shft = [np.array(["none"])]
    mp, _ = parse(state, MODEL)
    assert mp["mtyp"] == ["legendre", "voigt", "voigt", "vfwhm", "Ashift"]
    assert mp["emab"][-2:] == ["cv", "sh"]


def test_a_tied_resolution_shares_its_value_with_the_model(state):
    state._resn = [np.array(["vfwhm(7.0va)"])]
    state._shft = [np.array(["none"])]
    mp, _ = parse(state, MODEL)
    assert "va" in [t[0] for t in mp["tpar"]]
