"""The continuum: evaluated as ALIS does, first guess, order, knots, sharing.

Dashboard Stage 4.3 (S8, S9, S10, D17; Q4.6, Q4.7, Q4.8, Q4.13, Q4.16). The curve the
dashboard draws must equal ALIS's own evaluation, to 1e-12, for every emission line
of the ``examples/`` models. On synthetic data the first guess recovers a known
polynomial under absorption lines, and the BIC picks its order; a refit passes
through every knot; a shared continuum reads in ALIS with its ``min=``/``max=``.

Generated by RJC and Claude.
"""

from pathlib import Path

import numpy as np
import pytest

from alis.dashboard import continuum as CO
from alis.dashboard import history as H
from alis.dashboard import lines as L
from alis.dashboard import model as M
from alis.dashboard import modes
from alis.dashboard import project as P
from alis.dashboard import snips as S
from alis.dashboard import sources
from alis.dashboard import validate as V

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]
SPECTRUM = ROOT / "examples/metal_line_abs/data/OI_SiII.dat"
SII = ("28Si_II", 1260.4221)


@pytest.fixture(scope="module")
def registry(atomic_data):
    return M.Registry(atomic_data)


def errors(project):
    return [p.message for p in V.check(project) if p.severity == V.ERROR]


def _fit_models():
    out = []
    for path in sorted((ROOT / "examples").glob("*/model/*.mod")):
        text = path.read_text()
        if "generate" in path.name or "generate" in text.split("data read")[0]:
            continue
        if not any(f in text for f in CO.FUNCTIONS):
            continue
        out.append(path)
    return out


# -- ALIS's own evaluation --------------------------------------------------------


@pytest.mark.parametrize(
    "path", _fit_models(), ids=lambda p: p.parent.parent.name + "/" + p.name
)
def test_the_curve_is_alis_own(path, registry):
    project = P.Project.import_model(str(path), registry=registry)
    if project.paused:
        pytest.skip("the model does not read on its own")
    state = CO._load_with_alis(project)
    shind = np.where(np.array(state._modpass["emab"]) == "sh")[0][0]
    by_specid = {}
    for snip in project.snips:
        by_specid.setdefault(snip.specid, []).append(snip)
    checked = 0
    for sp in range(len(state._posnspx)):
        specid = str(state._specid[sp])
        for sn in range(len(state._posnspx[sp]) - 1):
            low, high = state._posnspx[sp][sn], state._posnspx[sp][sn + 1]
            mtyp = state._modpass["mtyp"][shind]
            inst, cls = state._funcarray[2][mtyp], state._funcarray[1][mtyp]
            inst._keywd = state._modpass["mkey"][shind]
            shpar = cls.set_vars(
                inst, state._modpass["p0"], state._levadd[shind], state._modpass, shind
            )
            wave = cls.call_CPU(inst, state._wavespx[sp][low:high], shpar)
            shind += 1
            snip = by_specid[specid][sn]
            for line in project.parsed.lines:
                if line.section != "emission" or line.function not in CO.FUNCTIONS:
                    continue
                if specid not in line.specids and line.specids:
                    continue
                i = line.index
                ftyp = state._modpass["mtyp"][i]
                finst, fcls = state._funcarray[2][ftyp], state._funcarray[1][ftyp]
                finst._keywd = state._modpass["mkey"][i]
                pars = fcls.set_vars(
                    finst,
                    state._modpass["p0"],
                    state._levadd[i],
                    state._modpass,
                    i,
                    spid=state._specid[sp],
                    levid=state._levadd,
                )
                theirs = fcls.call_CPU(
                    finst, wave, np.array([pars]), mkey=[state._modpass["mkey"][i]]
                )
                ours = CO.curve(
                    registry,
                    line.function,
                    CO.coefficients(project, line),
                    wave,
                    CO.xrange_of(project, snip, line),
                )
                assert np.allclose(ours, theirs, rtol=1e-12, atol=0), line.function
                checked += 1
    assert checked


# -- The first guess (S8, Q4.6) -------------------------------------------------------


TRUTH = [1.0, 0.08, -0.15]


def _legendre(coef, wave, low, high):
    t = 2.0 * (wave - low) / (high - low) - 1.0
    return np.polynomial.legendre.legval(t, coef)


@pytest.fixture
def synthetic(registry, tmp_path):
    """A snip of Si II 1260 on a known order-2 Legendre, with three absorption lines."""
    rng = np.random.default_rng(42)
    wave = np.arange(1250.0, 1270.0, 0.02)
    low, high = S.window(SII[1], 0.0, 0.0, 1500.0)
    edge = wave[(wave >= low) & (wave <= high)]
    cont = 1.0e3 * _legendre(TRUTH, wave, edge[0], edge[-1])
    absorb = np.ones_like(wave)
    for centre in (1258.9, 1260.4221, 1261.7):
        absorb *= 1.0 - 0.8 * np.exp(-0.5 * ((wave - centre) / 0.06) ** 2)
    error = np.full_like(wave, 5.0)
    flux = cont * absorb + rng.normal(0.0, 5.0, wave.size)
    path = tmp_path / "synthetic.dat"
    np.savetxt(str(path), np.column_stack([wave, flux, error]))
    project, _ = modes.get().empty_project([str(path)], "s", z=0.0, registry=registry)
    spec = {project.rows[0].id: sources.spectrum(project, project.rows[0])}
    atom = L.atomic(registry)
    line = next(ln for ln in atom.ion_lines(SII[0]) if abs(ln.rest - SII[1]) < 0.01)
    hist = H.History(project)
    hist.do(S.snip_step(project, project.systems[0], line, spec, half_width=1500.0))
    snip = project.snips[0]
    hist.do(S.add_region_step(project, snip, 1260.2, 1260.7))
    return project, hist, wave, (edge[0], edge[-1])


def test_the_first_guess_recovers_a_known_polynomial(synthetic):
    project, hist, _, span = synthetic
    snip = project.snips[0]
    guess = CO.guess(project, snip)
    # The BIC picks the order the continuum was made with
    assert guess.best == 2
    # And the curve is the continuum, under the absorption lines, to the noise
    truth = 1.0e3 * _legendre(TRUTH, snip.pixels.wave, *span)
    ours = CO.curve(
        project.registry,
        "legendre",
        guess.fit.coeffs,
        CO.model_wave(project, snip, snip.pixels.wave),
        guess.fit.xrange,
    )
    assert np.max(np.abs(ours - truth)) < 3.0
    # The line snipped, and the systems' line IDs, are left out (Q4.16)
    cores = CO.line_cores(project, snip)
    near = np.abs(snip.pixels.wave - 1260.4221) < 1260.4221 * 14.0 / CO.C_KMS
    assert cores[near].all()
    # The table of orders, on the same pixels
    table = guess.table()
    assert [row[0] for row in table] == [1, 2, 3]
    assert table[1][2] == 0.0 and table[1][3] == 0.0
    assert table[0][3] > 0 and table[2][3] > 0


def test_the_passes_keep_the_curved_ends_and_leave_out_the_lines(synthetic):
    """Q4.19: a straight line first, then one order higher twice, each pass judging
    every pixel again: the absorption is left out, and the ends of a curved
    continuum (which a straight line misses) are kept."""
    project, _, _, span = synthetic
    snip = project.snips[0]
    keep = CO.continuum_pixels(project, snip)
    truth = 1.0e3 * _legendre(TRUTH, snip.pixels.wave, *span)
    depth = 1.0 - (snip.pixels.flux / truth)
    # Every pixel absorbed by more than a tenth is left out
    assert not keep[depth > 0.1].any()
    # Far from the lines, nearly every continuum pixel is kept, at both ends too
    wave = snip.pixels.wave
    far = np.ones(wave.size, dtype=bool)
    for centre in (1258.9, 1260.4221, 1261.7):
        far &= np.abs(wave - centre) > 0.4
    assert keep[far].mean() > 0.97
    ends = far & ((wave < wave[0] + 1.0) | (wave > wave[-1] - 1.0))
    assert keep[ends].mean() > 0.95
    # A straight line alone would have lost the ends
    line = CO.fit(
        project.registry,
        "legendre",
        1,
        CO.model_wave(project, snip, wave),
        snip.pixels.flux,
        snip.pixels.error,
        CO.usable(project, snip),
        CO.xrange_of(project, snip),
    )
    assert line.keep[ends].mean() < 0.5


def test_snip_writes_the_first_guess(synthetic):
    project, _, _, _ = synthetic
    snip = project.snips[0]
    assert snip.continuum.function == "legendre"
    assert CO.order_of(snip.continuum) == 2
    # Coefficients near unity, with power-of-ten scales
    words = project.text.splitlines()[snip.continuum.line].split()
    scale = [w for w in words if w.startswith("scale=")][0][len("scale=") :]
    for value, factor in zip(words[1:4], scale.split(",")):
        assert 1.0 <= abs(float(value)) < 10.0
        assert np.log10(float(factor)) == round(np.log10(float(factor)))
    # Laid out alike: the values in columns, then the keywords
    assert project.text.splitlines()[snip.continuum.line] == CO.line_text(words)


def test_order_up_then_down_gives_back_the_same_text(synthetic):
    project, hist, _, _ = synthetic
    before = project.text
    assert CO.order_of(project.snips[0].continuum) == 2
    hist.do(CO.order_step(project, project.snips[0], 3))
    assert CO.order_of(project.snips[0].continuum) == 3
    hist.do(CO.order_step(project, project.snips[0], 2))
    assert project.text == before
    hist.do(CO.order_step(project, project.snips[0], 1))
    hist.do(CO.order_step(project, project.snips[0], 2))
    assert project.text == before
    with pytest.raises(CO.ContinuumError):
        CO.order_step(project, project.snips[0], 11)


def test_a_refit_passes_through_every_knot(synthetic):
    project, hist, _, _ = synthetic
    snip = project.snips[0]
    knots = [(1255.0, 900.0), (1262.0, 1100.0), (1266.0, 950.0), (1268.0, 1000.0)]
    hist.do(CO.knots_step(project, snip, knots))
    snip = project.snips[0]
    # Four knots raise the order to at least 3
    assert CO.order_of(snip.continuum) == 3
    assert project.ui["knots"][snip.specid][0] == [1255.0, 900.0]
    at = CO.evaluate(project, snip, np.array([k[0] for k in knots]))
    assert np.allclose(at, [k[1] for k in knots], rtol=1e-8)
    # The order cannot go below what the knots need
    with pytest.raises(CO.ContinuumError, match="knots"):
        CO.order_step(project, snip, 2)
    # Auto first guess honours them too
    guess = CO.guess(project, snip)
    assert guess.best >= 3
    # Removing them is one step, and undo restores them
    hist.do(CO.knots_step(project, snip, []))
    assert "knots" not in project.ui
    hist.undo()
    assert len(project.ui["knots"][snip.specid]) == 4


def test_the_function_can_change_and_change_back(synthetic):
    project, hist, wave, _ = synthetic
    before = project.text
    hist.do(CO.function_step(project, project.snips[0], "chebyshev"))
    snip = project.snips[0]
    assert snip.continuum.function == "chebyshev"
    assert snip.continuum.keyword("min") is None
    assert errors(project) == []
    hist.do(CO.function_step(project, snip, "constant"))
    assert project.snips[0].continuum.function == "constant"
    assert errors(project) == []
    hist.undo()
    hist.undo()
    assert project.text == before


def test_a_blinded_continuum_stays_hidden(synthetic):
    project, hist, _, _ = synthetic
    from alis.dashboard import edit as E

    line = project.snips[0].continuum
    hist.edit(E.set_blind(project.parsed, line))
    assert project.snips[0].continuum.blind
    hist.do(CO.order_step(project, project.snips[0], 3))
    cont = project.snips[0].continuum
    assert cont.blind and cont.line in project.hidden_lines()


# -- Sharing (S10, Q4.8) ----------------------------------------------------------------


def _two_rows(registry, tmp_path):
    other = tmp_path / "second.dat"
    other.write_bytes(SPECTRUM.read_bytes())
    project, _ = modes.get().empty_project(
        [str(SPECTRUM), str(other)], "t", z=0.0, registry=registry
    )
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    atom = L.atomic(registry)
    line = next(
        ln for ln in atom.ion_lines("16O_I") if abs(ln.rest - 1302.16849) < 0.01
    )
    hist = H.History(project)
    hist.do(S.snip_step(project, project.systems[0], line, spec))
    for snip in list(project.snips):
        hist.do(S.add_region_step(project, snip, 1301.5, 1302.8))
    return project, hist


def test_a_shared_continuum_reads_in_alis(registry, tmp_path):
    project, hist = _two_rows(registry, tmp_path)
    before = project.text
    assert CO.shareable(project, project.snips) == ""
    hist.do(CO.share_step(project, project.snips))
    legendre = project.parsed.function_lines("legendre")
    assert len(legendre) == 1
    shared = legendre[0]
    assert shared.specids == ["OI_1302_r1", "OI_1302_r2"]
    low = min(CO.new_range(project, s)[0] for s in project.snips)
    assert float(shared.keyword("min")) == pytest.approx(low)
    assert errors(project) == []
    # Both snips draw the one curve, each from its own pixels
    for snip in project.snips:
        assert snip.continuum is not None and snip.continuum.line == shared.line
        assert CO.evaluate(project, snip) is not None
    hist.do(CO.unshare_step(project, shared))
    assert len(project.parsed.function_lines("legendre")) == 2
    assert errors(project) == []
    hist.undo()
    hist.undo()
    assert project.text == before


def test_only_one_transition_in_different_rows_can_share(registry, tmp_path):
    project, hist = _two_rows(registry, tmp_path)
    assert "at least two" in CO.shareable(project, project.snips[:1])
    atom = L.atomic(registry)
    si = next(ln for ln in atom.ion_lines("28Si_II") if abs(ln.rest - 1304.3702) < 0.01)
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    hist.do(S.snip_step(project, project.systems[0], si, spec))
    first_row = [s for s in project.snips if s.row.id == "r1"]
    assert "one transition" in CO.shareable(project, first_row)
    hist.do(CO.function_step(project, project.snips[0], "chebyshev"))
    oi = [s for s in project.snips if s.specid.startswith("OI")]
    assert "Legendre" in CO.shareable(project, oi)


def test_reexpressing_keeps_the_curve(registry):
    coeffs = np.array([1.0, 0.2, -0.1, 0.05])
    x = np.linspace(1300.0, 1302.0, 50)
    new = CO.reexpress(
        registry, "legendre", coeffs, (1300.0, 1302.0), (1299.0, 1304.0), 3
    )
    assert np.allclose(
        CO.curve(registry, "legendre", new, x, (1299.0, 1304.0)),
        CO.curve(registry, "legendre", coeffs, x, (1300.0, 1302.0)),
        rtol=1e-12,
    )
