"""The Data tab (dashboard Stage 4.6; D35, S24, S25, D14–D16, F13, S3, Q4.14).

On a new project from ``OI_SiII.dat``, Identify a feature sets the primary z; on
Q1243p307, a tie between two rows reaches the model and one undo removes it; Confirm
clears the Data tab's "!" and the banner; on ``examples/blind``, no hidden value is in
the tab. Also: the datasets table, the reference, the zero level, Add file…,
renaming, removing with a preview, the coverage grid, and no design reference.

Generated by RJC and Claude.
"""

import shutil

import numpy as np
import pytest
from dashboard_qt_helpers import (
    BLIND,
    J1358,
    Q1243,
    SPECTRUM,
    design_references,
    make_window,
    ui_strings,
    wait_idle,
)

pytestmark = pytest.mark.gui

pytest.importorskip("qtpy.QtWidgets")
pytest.importorskip("pyqtgraph")

from alis.dashboard import blinding as BL  # noqa: E402
from alis.dashboard import lines as L  # noqa: E402
from alis.dashboard import session as S  # noqa: E402
from alis.dashboard import snips as SN  # noqa: E402
from alis.dashboard import sources  # noqa: E402
from alis.dashboard.qt import dialogs as D  # noqa: E402


@pytest.fixture
def home(tmp_path, monkeypatch):
    folder = tmp_path / "alis_home"
    monkeypatch.setenv("ALIS_HOME", str(folder))
    return folder


@pytest.fixture
def window(qtbot, home):
    win = make_window(qtbot, home)
    yield win
    if win.session is not None:
        win.session.discard_recovery()
        win.session = None


def need(path):
    if not path.exists():
        pytest.skip("{0} is not present".format(path.name))


def new_project(window, tmp_path, z=None, spectra=(SPECTRUM,)):
    session, _ = S.Session.new(
        str(tmp_path / "test.model"), [str(p) for p in spectra], z=z
    )
    window.set_session(session)
    return window.tab_widgets[0]


def table_text(tab):
    table = tab.table
    return [
        [table.item(r, c).text() for c in range(table.columnCount())]
        for r in range(table.rowCount())
    ]


# -- Systems and Identify a feature (S24, D35) ---------------------------------------


def test_identify_a_feature_sets_the_primary_z(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path)
    project = window.session.project
    assert project.systems == []
    tab.identify.click()
    assert tab.identify.isChecked() and tab.view.box.mode == "click"
    # A click on the O I 1302 line of the spectrum
    tab.view.clicked.emit(1302.16849 * (1.0 + 2.0e-5), 0.5)
    panel = tab.identify_panel
    assert panel.isVisible()
    panel.element.setCurrentText("O")
    panel.stage.setCurrentText("I")
    for num in range(panel.transition.count()):
        if panel.transition.itemData(num).name == "O I 1302.2":
            panel.transition.setCurrentIndex(num)
    assert panel.current().z == pytest.approx(2.0e-5, abs=1e-7)
    panel.primary.click()
    project = window.session.project
    assert len(project.systems) == 1 and project.systems[0].primary
    assert project.systems[0].z == pytest.approx(2.0e-5, abs=1e-7)
    assert not tab.identify.isChecked() and not panel.isVisible()
    assert float(tab.z_edit.text()) == pytest.approx(2.0e-5, abs=1e-7)
    # One step, which undo takes back
    window.do_edit_undo()
    assert window.session.project.systems == []


def test_the_primary_z_is_typed_and_a_new_system_added(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    tab.z_edit.setText("0.0001")
    tab.z_edit.returnPressed.emit()
    assert window.session.project.systems[0].z == pytest.approx(1e-4)
    # Identify, then "Add as a new system"
    tab.identify.click()
    tab.identify_at(1304.0)
    tab.identify_panel.new.click()
    systems = window.session.project.systems
    assert len(systems) == 2 and not systems[1].primary
    assert tab.others.count() == 1
    # The rows of the other systems: Rename… and Make primary
    other = systems[1]
    window.on_dialog = lambda dialog: (dialog.set("name", "interloper"), 1)[1]
    tab._act("rename", lambda: tab.rename_system(other))
    assert window.session.project.system(other.id).name == "interloper"
    assert tab.others.item(0).text().startswith("interloper")


def test_a_first_choice_near_a_known_system(window, qtbot, tmp_path):
    need(J1358)
    src = J1358.parent.parent / "data/J1358p6522_fluxcal.dat"
    tab = new_project(window, tmp_path, z=3.067258, spectra=(src,))
    tab.identify.click()
    tab.identify_at(1025.7223 * (1.0 + 3.067258))
    assert tab.identify_panel.current().name == "Lyβ 1025.7"


# -- The datasets table (S25, D14, D35) ---------------------------------------------


def test_the_table_of_a_new_project(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    rows = table_text(tab)
    assert len(rows) == 1
    ref, name, contents, fwhm, shift, zero, check = rows[0]
    assert ref == "◉" and name == "OI_SiII"
    assert contents.startswith("wave, flux, error") and "554 px" in contents
    assert shift == "0 · reference" and zero == "Off" and check == "✓ unchanged"
    assert tab.spectrum.title.text() == "Spectrum · OI_SiII.dat"
    assert tab.view._wave is not None and tab.view._wave.size == 554
    assert not tab.coverage.isVisible()


def test_add_file_reference_and_zero_level(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    other = tmp_path / "second.dat"
    shutil.copy(str(SPECTRUM), str(other))

    def add(dialog):
        dialog.set_file(str(other))
        return 1

    window.on_dialog = add
    tab.add_file.click()
    project = window.session.project
    assert [r.name for r in project.rows] == ["OI_SiII", "second"]
    assert tab.table.rowCount() == 2 and tab.coverage.isVisible()
    # SNIP O I in both rows, so the reference and the zero level have lines
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    atom = L.atomic(project.registry)
    line = next(
        ln for ln in atom.ion_lines("16O_I") if abs(ln.rest - 1302.16849) < 0.01
    )
    window.session.history.do(SN.snip_step(project, project.systems[0], line, spec))
    window.refresh()
    assert "■" in [tab.grid.item(0, c).text() for c in (1, 2)]
    # The reference moves with a click on the second row's ○
    tab._cell_clicked(1, 0)
    project = window.session.project
    assert project.rows[1].reference and not project.rows[0].reference
    assert table_text(tab)[1][4] == "0 · reference"
    # Zero level on, then off
    tab._cell_clicked(0, 5)
    assert window.session.project.rows[0].zero is not None
    assert table_text(tab)[0][5] == "On"
    tab._cell_clicked(0, 5)
    assert window.session.project.rows[0].zero is None


def test_remove_lists_the_lines_first(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    project = window.session.project
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    atom = L.atomic(project.registry)
    line = next(
        ln for ln in atom.ion_lines("16O_I") if abs(ln.rest - 1302.16849) < 0.01
    )
    window.session.history.do(SN.snip_step(project, project.systems[0], line, spec))
    window.refresh()
    seen = []

    def cancel(dialog):
        seen.append(dialog)
        return 0

    window.on_dialog = cancel
    tab.remove_row(window.session.project.rows[0])
    assert isinstance(seen[0], D.PlanDialog)
    reasons = [row[2] for row in seen[0].rows()]
    assert any("data line" in r for r in reasons)
    assert len(window.session.project.snips) == 1
    window.on_dialog = lambda dialog: 1
    tab.remove_row(window.session.project.rows[0])
    assert window.session.project.rows == []


def test_column_roles_are_fixed_once_a_row_has_snips(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    row = window.session.project.rows[0]
    seen = []

    def change(dialog):
        seen.append(dialog)
        dialog.columns.set_role(3, None)
        return 1

    window.on_dialog = change
    tab.column_roles(row)
    assert "continuum" not in window.session.project.rows[0].columns
    project = window.session.project
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    atom = L.atomic(project.registry)
    line = next(
        ln for ln in atom.ion_lines("16O_I") if abs(ln.rest - 1302.16849) < 0.01
    )
    window.session.history.do(SN.snip_step(project, project.systems[0], line, spec))
    tab.column_roles(window.session.project.rows[0])
    assert not seen[-1].columns.isEnabled()
    assert "CLEAR" in seen[-1].error.text()


# -- Q1243p307: three datasets, ties, Confirm (Q0.8, Q2.4) -----------------------------


def test_q1243_tie_reaches_the_model_and_undo_removes_it(window, qtbot):
    need(Q1243)
    window.import_path(str(Q1243))
    wait_idle(qtbot, window)
    tab = window.tab_widgets[0]
    rows = table_text(tab)
    assert [r[1] for r in rows] == ["HIRES", "PROCHASKA", "KIRKMAN"]
    assert all("no source spectrum" in r[2] for r in rows)
    assert tab.coverage.isVisible() and tab.grid.rowCount() == 16
    before = window.session.project.text
    kirkman = window.session.project.row("KIRKMAN")
    tab.badge_menu(kirkman, "resolution", "Tie to PROCHASKA")
    project = window.session.project
    label = project.row("PROCHASKA").snips[0].data.param("resolution").label
    assert project.row("KIRKMAN").snips[0].data.param("resolution").label == label
    assert "⛓" in table_text(tab)[2][3]
    window.do_edit_undo()
    assert window.session.project.text == before


def test_confirm_clears_the_mark_and_the_banner(window, qtbot):
    need(Q1243)
    window.import_path(str(Q1243))
    wait_idle(qtbot, window)
    tab = window.tab_widgets[0]
    assert window.markers["Data"].state == "attention"
    assert window.notice_banner.isVisible()
    assert tab.confirm.isVisible() and tab.systems_note.isVisible()
    tab.confirm.click()
    assert window.markers["Data"].state == "complete"
    assert not window.notice_banner.isVisible()
    assert not tab.confirm.isVisible()


# -- Blinding (D24, F8) ---------------------------------------------------------------


def test_no_hidden_value_in_the_tab(window, qtbot, tmp_path):
    # examples/blind, its hidden Si II line given values no other text holds
    folder = tmp_path / "blind"
    shutil.copytree(str(BLIND.parent.parent), str(folder))
    model = folder / "model" / BLIND.name
    text = model.read_text().replace(
        "13.0    0.0    1.0da   8000TA", "13.4729 0.000173 1.37da 8123TA"
    )
    model.write_text(text)
    window.import_path(str(model))
    wait_idle(qtbot, window)
    project = window.session.project
    hidden = BL.Gate(project).hidden_values()
    assert hidden
    texts = ui_strings(window)
    tab = window.tab_widgets[0]
    texts += [t for row in table_text(tab) for t in row]
    texts.append(tab.blinded.text())
    for value in hidden:
        for text in texts:
            assert value not in text, (value, text)
    assert tab.blinded.text() == "Blinded: Si II"


def test_no_design_reference_in_the_tab(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    tab.identify.click()
    tab.identify_at(1302.2)
    assert design_references(ui_strings(window)) == []


def test_the_spectrum_shows_line_ids_and_counts_the_rest(window, qtbot, tmp_path):
    tab = new_project(window, tmp_path, z=0.0)
    tab._draw_ids()
    assert any("O I" in text.toPlainText() for _, _, text in tab.view._ids)
    hidden = getattr(tab.view, "hidden_note", 0)
    tab.all_lines.setChecked(True)
    assert getattr(tab.view, "hidden_note", 0) == 0
    assert len(tab.view._ids) >= hidden
    tab.log_button.click()
    assert tab.view.log
    assert np.isfinite(tab.view.view_range()[0][0])


def test_cross_highlighting_both_ways(window, qtbot, tmp_path):
    other = tmp_path / "second.dat"
    shutil.copy(str(SPECTRUM), str(other))
    tab = new_project(window, tmp_path, z=0.0, spectra=(SPECTRUM, other))
    project = window.session.project
    spec = {r.id: sources.spectrum(project, r) for r in project.rows}
    atom = L.atomic(project.registry)
    line = next(
        ln for ln in atom.ion_lines("16O_I") if abs(ln.rest - 1302.16849) < 0.01
    )
    window.session.history.do(SN.snip_step(project, project.systems[0], line, spec))
    window.refresh()
    project = window.session.project
    # A row selected in the table highlights its lines in the .mod panel
    tab._cell_clicked(1, 1)
    second = project.rows[1]
    assert window.panel._selected == project.lines_of(second)
    # The cursor on the first row's data line selects that row
    tab.show_items(project.items_at(project.rows[0].snips[0].line))
    assert tab.selected == project.rows[0].id
    assert tab.table.currentRow() == 0


def test_an_edit_keeps_the_mark_until_confirm(window, qtbot):
    """An edit keeps an imported fit's rows apart, but the "!" and the banner stay
    until Confirm is pressed (RJC's review, Q4.18)."""
    need(Q1243)
    window.import_path(str(Q1243))
    wait_idle(qtbot, window)
    tab = window.tab_widgets[0]
    kirkman = window.session.project.row("KIRKMAN")
    tab.badge_menu(kirkman, "resolution", "Tie to PROCHASKA")
    project = window.session.project
    assert [r.name for r in project.rows] == ["HIRES", "PROCHASKA", "KIRKMAN"]
    assert project.inferred
    assert window.markers["Data"].state == "attention"
    assert "Confirm" in window.markers["Data"].tip
    assert window.notice_banner.isVisible() and tab.confirm.isVisible()
    tab.confirm.click()
    assert window.markers["Data"].state == "complete"
    assert not window.notice_banner.isVisible()
