"""The project: the dashboard's concepts (dashboard Stage 2.5).

On the two fits the mockups were drawn from (J1358p6522 and Q1243p307), the project
must find the systems, components, isotopes and datasets the mockups show. It must
list, and fix, the components of imported models that break D20 (untied ions) and
D22 (isotopes that do not share z, b and T). Regions are read and edited in a snip's
mask column, or in its ``fitrange`` (Q2.7, Q2.10).

Generated by RJC and Claude.
"""

import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from alis import bundle as B
from alis import load
from alis.config import ArgFlag
from alis.dashboard import edit as E
from alis.dashboard import model as M
from alis.dashboard import project as P
from alis.dashboard import text as T

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]
CTX = ROOT / "context/fitting_examples"
J1358 = CTX / "VMP_DLA/J1358p6522/model/J1358p6522.mod"
Q1243 = CTX / "DH/Q1243p307/model/Q1243p307_converge_newstart76.mod"
METAL = ROOT / "examples/metal_line_abs/model/fit_spectra.mod"
BLIND = ROOT / "examples/blind/model/fit_spectra.mod"


@pytest.fixture(scope="module")
def registry(atomic_data):
    return M.Registry(atomic_data)


def imported(path, registry):
    if not path.exists():
        pytest.skip("model not present: " + str(path.relative_to(ROOT)))
    project = P.Project.import_model(str(path), registry=registry)
    assert not project.paused, project.parsed.errors
    return project


def make_project(registry, text, files):
    """A project from a model text and its files, without anything on disk."""
    members = {"files/model/test.mod": text.encode("utf-8"), "atomic/atomic.ecsv": b""}
    members.update({"files/" + k: v for k, v in files.items()})
    manifest = {
        "format": B.FORMAT,
        "version": B.FORMAT_VERSION,
        "model": "files/model/test.mod",
        "atomic": "atomic/atomic.ecsv",
    }
    return P.Project(B.Bundle(members=members, manifest=manifest), registry)


def snip_bytes(wave, mask=None):
    """A four-column snip in prepfit's format (np.savetxt's default)."""
    flux = np.ones_like(wave)
    error = np.full_like(wave, 0.1)
    cols = [wave, flux, error] + ([] if mask is None else [mask.astype(float)])
    rows = np.column_stack(cols)
    return "".join(
        " ".join("{0:.18e}".format(v) for v in row) + "\n" for row in rows
    ).encode("utf-8")


# -- J1358p6522: one dataset, one system, isotopes ---------------------------------


def test_j1358_systems_and_components(registry):
    project = imported(J1358, registry)
    assert len(project.systems) == 1
    system = project.systems[0]
    assert system.primary and abs(system.z - 3.0672596274) < 1.0e-9
    assert [P.ion_name(i) for i in system.ions] == ["H I", "D I", "O I"]
    comps = system.components
    assert [round(c.velocity, 1) for c in comps] == [-7.2, 0.0]
    main = comps[1]
    assert main.label == "ra"
    assert [P.ion_name(i) for i in main.ions] == ["H I", "D I", "O I"]
    assert main.isotopes == {("H", "I"): ["1H_I", "2H_I"]}
    assert len(main.lines_of("16O_I")) == 6
    assert [P.ion_name(i) for i in comps[0].ions] == ["H I"]
    assert main.temperature_mode == ("preset", 0.0)
    assert len(project.absorbers) == 57


def test_j1358_has_one_dataset_of_twelve_snips(registry):
    project = imported(J1358, registry)
    assert [(r.name, len(r.snips), r.reference) for r in project.rows] == [
        ("J1358p6522_fluxcal", 12, True)
    ]
    row = project.rows[0]
    assert row.fwhm.label == "va" and row.shift.token is None
    snip = project.snip("H2")
    assert snip.row is row and snip.continuum.specids == ["H2"]
    assert snip.extent[0] == pytest.approx(3755.03, abs=0.01)
    assert len(snip.regions) > 1


def test_j1358_notices_and_their_fixes(registry):
    project = imported(J1358, registry)
    kinds = [n.kind for n in project.notices]
    assert kinds == ["inferred", "untied", "isotopes"]
    untied = project.notices[1]
    assert "O I" in untied.message and len(untied.lines) == 6
    assert "D I" in project.notices[2].message
    assert "b_turb" in project.notices[2].message
    # The untied fix ties every O I line to 'ra', and nothing else
    before = project.text
    project.apply(project.fix_notice(untied))
    assert [n.kind for n in project.notices] == ["inferred", "isotopes"]
    main = project.systems[0].components[1]
    assert {ln.param("redshift").label for ln in main.lines} == {"ra"}
    changed = {
        n
        for n, (a, b) in enumerate(zip(before.splitlines(), project.text.splitlines()))
        if a != b
    }
    assert changed == set(untied.lines)
    # The isotope fix gives H I's and D I's b_turb a label of the scheme
    project.apply(project.fix_notice(project.notices[1]))
    assert [n.kind for n in project.notices] == ["inferred"]
    main = project.systems[0].components[1]
    hyd, deut = main.lines_of("1H_I")[0], main.lines_of("2H_I")[0]
    assert hyd.param("bturb").label == deut.param("bturb").label == "ba1"
    assert deut.param("bturb").value == hyd.param("bturb").value


def test_cross_highlighting_maps_items_to_lines(registry):
    project = imported(J1358, registry)
    main = project.systems[0].components[1]
    lines = project.lines_of(main)
    assert set(lines) == {ln.line for ln in main.lines}
    snip = project.snip("O1")
    assert project.lines_of(snip) == sorted([snip.line, snip.continuum.line])
    found = project.items_at(snip.line)
    assert snip in found and snip.row in found
    assert main in project.items_at(main.lines[0].line)
    assert project.lines_of(project.systems[0]) == sorted(
        {n for c in project.systems[0].components for n in project.lines_of(c)}
    )


# -- Q1243p307: three datasets, several systems ------------------------------------


def test_q1243_three_datasets(registry):
    project = imported(Q1243, registry)
    assert [(r.name, len(r.snips)) for r in project.rows] == [
        ("HIRES", 23),
        ("PROCHASKA", 16),
        ("KIRKMAN", 12),
    ]
    assert [r.reference for r in project.rows] == [True, False, False]
    assert [r.fwhm.label for r in project.rows] == ["vh", "vp", "vk"]
    assert project.row("KIRKMAN").shift.label == "SHK"
    zero = project.row("KIRKMAN").zero
    assert zero is not None and "Lyak" in zero.specids


def test_q1243_systems(registry):
    project = imported(Q1243, registry)
    primary = project.systems[0]
    assert primary.primary and abs(primary.z - 2.5257) < 1.0e-3
    others = sorted(round(s.z, 2) for s in project.systems[1:])
    assert others == [2.05, 2.18, 2.40, 2.44]
    assert len(primary.components) == 18
    with_d = [c for c in primary.components if "2H_I" in c.ions]
    assert all(c.isotopes == {("H", "I"): ["1H_I", "2H_I"]} for c in with_d)
    notices = [n for n in project.notices if n.kind == "isotopes"]
    assert len(notices) == 5
    project.apply(project.fix_notice(notices[0]))
    assert len([n for n in project.notices if n.kind == "isotopes"]) == 4


# -- Small models that break D20 and D22 -------------------------------------------

SMALL = """data read
  ../data/a.dat  specid=A  fitrange=[1300.0,1306.0]  resolution=vfwhm(7.0VA)
data end
model read
 emission
  legendre 1.0  0.0  specid=A
 absorption
  voigt  ion=16O_I    14.0  0.00100  5.0   1.0E+03  specid=A
  voigt  ion=28Si_II  13.0  0.00100  5.0   1.0E+03  specid=A
  voigt  ion=3He_I    12.0  0.0300za  4.0ba  8000.0ta  specid=A
  voigt  ion=4He_I    14.0  0.0300za  6.0  8000.0ta  specid=A
model end
"""


@pytest.fixture
def small(registry):
    wave = np.linspace(1299.0, 1307.0, 81)
    return make_project(registry, SMALL, {"data/a.dat": snip_bytes(wave)})


def test_a_model_that_breaks_d20(small):
    untied = [n for n in small.notices if n.kind == "untied"]
    assert len(untied) == 1 and untied[0].lines == [7, 8]
    small.apply(small.fix_notice(untied[0]))
    assert not [n for n in small.notices if n.kind == "untied"]
    labels = {
        ln.param("redshift").label
        for c in small.components
        for ln in c.lines
        if ln.ion in ("16O_I", "28Si_II")
    }
    assert labels == {"za1"}


def test_a_model_that_breaks_d22(small):
    iso = [n for n in small.notices if n.kind == "isotopes"]
    assert len(iso) == 1
    assert "3He I" in iso[0].message and "b_turb" in iso[0].message
    assert iso[0].lines == [9]
    small.apply(small.fix_notice(iso[0]))
    assert not [n for n in small.notices if n.kind == "isotopes"]
    comp = [c for c in small.components if "4He_I" in c.ions][0]
    main = comp.lines_of("4He_I")[0].param("bturb")
    minor = comp.lines_of("3He_I")[0].param("bturb")
    # A fresh label of the scheme: the minor isotope's own 'ba' might be shared
    assert main.label == minor.label == "b{0}1".format(comp.system.id)
    assert minor.value == main.value == 6.0


# -- Regions (Q2.7, Q2.10) ---------------------------------------------------------


def test_regions_of_a_masked_snip_change_only_the_mask(registry):
    project = imported(J1358, registry)
    snip = project.snip("H2")
    old = project.files[snip.member]
    lo, hi = snip.extent
    wanted = [(lo + 1.0, lo + 3.0), (hi - 3.0, hi - 1.0)]
    step = project.set_regions(snip, wanted)
    assert step.text is None and list(step.files) == [snip.member]
    project.apply(step)
    new = project.files[snip.member]
    old_lines, new_lines = old.decode().splitlines(), new.decode().splitlines()
    assert len(old_lines) == len(new_lines)
    for a, b in zip(old_lines, new_lines):
        wa, wb = a.split(), b.split()
        assert wa[:3] == wb[:3] and wa[4:] == wb[4:]
        assert len(a) == len(b)
    got = project.snip("H2").regions
    assert len(got) == 2
    for (glo, ghi), (wlo, whi) in zip(got, wanted):
        assert wlo <= glo < wlo + 0.1 and whi - 0.1 < ghi <= whi
    project.revert(step)
    assert project.files[snip.member] == old


def test_one_region_on_a_fitrange_line_edits_the_token(registry):
    project = imported(METAL, registry)
    snip = project.snips[0]
    assert snip.regions == [(1301.0, 1305.0)]
    step = project.set_regions(snip, [(1301.5, 1304.5)])
    assert not step.files
    project.apply(step)
    assert project.snips[0].regions == [(1301.5, 1304.5)]
    assert project.snips[0].data.keyword("fitrange") == "[1301.5,1304.5]"


def test_two_regions_switch_a_fitrange_line_to_a_mask(registry):
    project = imported(METAL, registry)
    snip = project.snips[0]
    old = project.files[snip.member]
    step = project.set_regions(snip, [(1301.0, 1302.5), (1303.5, 1305.0)])
    project.apply(step)
    item = project.parsed.data[0]
    assert item.keyword("fitrange") == "columns"
    # The file already has four columns, so the mask is the fifth
    ncols = len(old.decode().splitlines()[0].split())
    assert item.keyword("columns") == "[wave,flux,error,fitrange:{0}]".format(ncols)
    new = project.files[snip.member]
    for a, b in zip(old.decode().splitlines(), new.decode().splitlines()):
        assert b.startswith(a) and len(b.split()) == len(a.split()) + 1
    assert len(project.snips[0].regions) == 2
    wave = project.snips[0].pixels.wave
    mask = project.snips[0].pixels.mask != 0
    want = ((wave >= 1301.0) & (wave <= 1302.5)) | ((wave >= 1303.5) & (wave <= 1305.0))
    assert np.array_equal(mask, want)
    # ALIS, reading the edited bundle from memory, fits exactly those pixels
    bundle = project.to_bundle()
    state = SimpleNamespace(_argflag=ArgFlag())
    state._argflag["out"]["verbose"] = -1
    with M.alis_quietly():
        _, datlines, _, _ = load.load_input(
            state, textstr=bundle.model_text(restore=True).splitlines(True)
        )
        state._atomic = registry.atomic
        state._funcarray = registry.instances()
        load.load_data(state, datlines, data=bundle.data_for_run())
    assert np.array_equal(state._wavefit[0], wave[want])
    project.revert(step)
    assert project.files[snip.member] == old
    assert project.parsed.data[0].keyword("fitrange") == "[1301.0,1305.0]"


def test_a_shared_file_is_copied_before_it_gets_a_mask(registry):
    text = SMALL.replace(
        "data end",
        "  ../data/a.dat  specid=B  fitrange=[1300.5,1301.0]  resolution=vfwhm(7.0VA)"
        "\ndata end",
    ).replace(
        "legendre 1.0  0.0  specid=A",
        "legendre 1.0  0.0  specid=A\n  constant 1.0 specid=B",
    )
    text = text.replace("specid=A\n model end", "specid=A\nmodel end")
    wave = np.linspace(1299.0, 1307.0, 81)
    project = make_project(registry, text, {"data/a.dat": snip_bytes(wave)})
    assert not project.paused, project.parsed.errors
    snip = project.snip("A")
    project.apply(project.set_regions(snip, [(1300.0, 1301.0), (1302.0, 1303.0)]))
    assert project.parsed.data[0].file.text == "../data/a_A.dat"
    assert project.parsed.data[1].file.text == "../data/a.dat"
    assert "files/data/a_A.dat" in project.files
    assert project.files["files/data/a.dat"] == snip_bytes(wave)


def test_snip_edges_move_inwards_only(registry):
    project = imported(J1358, registry)
    snip = project.snip("O1")
    lo, hi = snip.extent
    old = project.files[snip.member].decode().splitlines()
    project.apply(project.set_snip_edges(snip, lo + 0.5, hi - 0.5))
    new = project.files[snip.member].decode().splitlines()
    assert set(new) <= set(old) and len(new) < len(old)
    assert project.snip("O1").extent[0] >= lo + 0.5
    with pytest.raises(P.ProjectError):
        project.set_snip_edges(project.snip("O1"), lo - 1.0, hi)


# -- ui/project.json, saving and the latest run ------------------------------------


def test_confirming_the_structure_writes_project_json(registry, tmp_path):
    project = imported(Q1243, registry)
    assert project.inferred
    project.apply(project.confirm_structure())
    assert not project.inferred
    assert [n.kind for n in project.notices if n.kind == "inferred"] == []
    path = tmp_path / "q.model"
    project.save(str(path))
    again = P.Project.open(str(path), registry)
    data = json.loads(again.bundle.members[P.PROJECT_JSON])
    assert [r["name"] for r in data["rows"]] == ["HIRES", "PROCHASKA", "KIRKMAN"]
    assert [round(s.z, 4) for s in again.systems] == [
        round(s.z, 4) for s in project.systems
    ]
    assert not again.inferred
    assert again.text == project.text


def test_writing_back_hides_the_blind_line_again(registry):
    project = imported(BLIND, registry)
    packed = B.pack(str(BLIND))
    assert project.hidden_lines() == B.blind_line_numbers(project.text)
    data, store = project.model_bytes()
    assert data == packed.members[packed.model_member]
    assert store == packed.hidden_model_lines()
    assert "28Si_II" not in data.decode()


def test_the_model_changed_since_the_last_run(registry):
    project = imported(METAL, registry)
    assert project.model_changed_since_run() is None
    data = project.model_bytes()[0]
    info = {"model_sha256": B.sha256(data)}
    project.bundle.members[B.LATEST + "run.json"] = json.dumps(info).encode()
    assert project.model_changed_since_run() is False
    oxygen = project.parsed.function_lines("voigt")[0]
    project.edit(E.set_value(project.parsed, oxygen.param("ColDens"), 14.5))
    assert project.model_changed_since_run() is True


def test_a_text_that_does_not_read_pauses_the_panels(registry):
    project = imported(METAL, registry)
    rows = project.rows
    broken = T.Change((T.Patch(project.text.index("model end"), "model end", ""),))
    step = project.edit(broken)
    assert project.paused and project.rows is rows
    with pytest.raises(P.ProjectError):
        project.require_reading()
    with pytest.raises(P.ProjectError):
        project.set_regions(project.snips[0], [(1301.0, 1302.0)])
    project.revert(step)
    assert not project.paused


def test_hidden_lines_follow_the_edits(registry):
    project = imported(METAL, registry)
    num = project.parsed.function_lines("voigt")[0].line
    project.apply(project.mark_hidden(num))
    assert num in project.hidden_lines()
    pm = project.parsed
    step = project.edit(E.add_continuum(pm, "0", [1.0]))
    assert project.extra_hidden == {num + 1}
    project.revert(step)
    assert project.extra_hidden == {num}


def test_ion_names():
    assert P.ion_name("2H_I") == "D I"
    assert P.ion_name("16O_I") == "O I"
    assert P.ion_name("3He_I") == "3He I"
    assert P.split_ion("28Si_II") == (28, "Si", "II")
    assert P.split_ion("odd") == (None, "odd", "")


def test_saving_over_a_bundle_keeps_its_runs(registry, tmp_path):
    project = imported(METAL, registry)
    path = tmp_path / "metal.model"
    project.save(str(path))

    # A run, and a committed run, added to the bundle on disk meanwhile
    def add_runs(bundle):
        bundle.members[B.LATEST + "run.json"] = b'{"status": "completed"}'
        bundle.members["runs/0001/run.json"] = b'{"status": "completed"}'

    B.update(str(path), add_runs)
    oxygen = project.parsed.function_lines("voigt")[0]
    project.edit(E.set_value(project.parsed, oxygen.param("ColDens"), 14.25))
    project.save(str(path))
    again = B.read(str(path))
    assert B.LATEST + "run.json" in again.members
    assert "runs/0001/run.json" in again.members
    assert "14.25" in again.model_text()


def test_a_mask_written_as_integers_keeps_its_style(registry):
    wave = np.linspace(1299.0, 1307.0, 81)
    mask = (wave > 1301.0) & (wave < 1305.0)
    rows = ["{0:.6f} 1.0 0.1 {1:d}\n".format(w, int(m)) for w, m in zip(wave, mask)]
    text = SMALL.replace(
        "fitrange=[1300.0,1306.0]",
        "fitrange=columns  columns=[wave,flux,error,fitrange]",
    )
    project = make_project(registry, text, {"data/a.dat": "".join(rows).encode()})
    snip = project.snip("A")
    old = project.files[snip.member].decode().splitlines()
    project.apply(project.set_regions(snip, [(1300.0, 1302.0)]))
    new = project.files[snip.member].decode().splitlines()
    assert all(len(a) == len(b) for a, b in zip(old, new))
    assert {line.split()[3] for line in new} == {"0", "1"}
    assert len(project.snip("A").regions) == 1
