"""Atomic masses reach the line profiles intact (Stage 5.6).

`load_atomic` publishes ``Element`` and ``AtomicMass`` as a per-isotope
*mapping*: ``Element[i]`` is the isotope whose mass is ``AtomicMass[i]``. Every
line-profile function relies on it --

    m = np.where(atomic['Element'] == isotope); mass = atomic['AtomicMass'][m][0]

-- and the mass then sets the thermal width,
``b = sqrt(b_turb**2 + 0.01662892444*T/m)``.

Until Stage 5.6 the two arrays were de-duplicated *independently* -- ``Element``
by isotope string, ``AtomicMass`` by mass **value** -- so they had different
lengths (80 against 82, because ``1H``/``1Ly``/``1TL`` share a mass) and the
index found in one addressed the wrong slot in the other. 132 of the 167
isotope/ion combinations in ``atomic.xml`` were handed another isotope's mass:
``1H`` got deuterium's, ``16O`` got neon's, and the thermal width was wrong by
up to 63%.

The tests are in two layers, so that Stage 5.2's switch to ``atomic.ecsv``
breaks as little as possible:

* **format-specific** -- the mapping ``load_atomic`` publishes agrees with the
  raw data file. Reading the file directly means a VOTable parser here, so
  these are the tests 5.2 has to revisit.
* **format-agnostic** -- the mass that actually reaches the line profile is the
  one ``load_atomic`` published. This drives ALIS's own parser with a model line
  per isotope/ion, reads the broadening ``set_vars`` returns, and inverts
  ``b = sqrt(b_turb**2 + K*T/m)`` to recover the mass used. It never touches the
  file, so it carries over to ECSV unchanged -- and it is the layer that would
  have caught the Stage 5.6 bug.

Grown from `context/atomic/test_voigt_atomic.py` (RJC).

Generated by RJC and Claude.
"""

import os
from collections import defaultdict

import numpy as np
import pytest

from alis import load
from alis.config import ArgFlag
from alis.main import build_funcarray

pytestmark = pytest.mark.unit

# The fake model lines: 1 km/s of turbulence and 10000 K, so that
# b = sqrt(1 + 166.2892444/m) and the mass can be recovered from b.
BTURB = 1.0
TEMPERATURE = 10000.0
KCONST = 0.01662892444


class _State:
    """The attributes `load_model` / `load_parinfo` read, and nothing else."""

    def __init__(self, atomic_file="atomic.xml"):
        self._argflag = ArgFlag()
        self._argflag["run"]["atomic"] = atomic_file
        self._argflag["out"]["verbose"] = 0
        self._argflag["run"]["prognm"] = os.path.join(
            os.path.dirname(load.__file__), "alis.py"
        )
        self._specid = np.array(["0"])
        self._resn = []
        self._shft = []
        self._emab = []
        self._funcused = []


def _atomic_path(name="atomic.xml"):
    return os.path.join(os.path.dirname(load.__file__), "data", name)


def _file_masses(path):
    """isotope -> set of AtomicMass values the file records, read directly."""
    import warnings

    from astropy.io.votable import parse_single_table

    warnings.filterwarnings("ignore")
    arr = parse_single_table(path).array

    def text(v):
        return v.decode() if isinstance(v, bytes) else str(v)

    out = defaultdict(set)
    for row in arr:
        iso = f"{int(row['MassNumber'])}{text(row['Element']).strip()}"
        out[iso].add(float(row["AtomicMass"]))
    return out


@pytest.fixture(scope="module")
def atomic():
    state = _State()
    return load.load_atomic(state)


@pytest.fixture(scope="module")
def broadening():
    """isotope_ion -> the b that `set_vars` returns for it.

    One `voigt` line per isotope/ion in the atomic file, parsed by ALIS's own
    loader so the path exercised is the one a fit takes.
    """
    state = _State()
    state._atomic = load.load_atomic(state)
    state._funcarray = build_funcarray(state._argflag, state._atomic)
    ions = sorted(set(np.asarray(state._atomic["Ion"]).astype(str)))

    lines = ["emission", "  legendre 1.0   specid=0", "absorption"]
    lines += [
        f"  voigt   ion={ion}   12.0    0.0    {BTURB}    {TEMPERATURE}   specid=0"
        for ion in ions
    ]
    state._modpass = load.load_model(state, lines)
    state._links = load.load_links(state, [])
    _, levadd = load.load_parinfo(state)

    cls = state._funcarray[1]["voigt"]
    inst = state._funcarray[2]["voigt"]
    out = {}
    for ival, mtyp in enumerate(state._modpass["mtyp"]):
        if mtyp != "voigt":
            continue
        inst._keywd = state._modpass["mkey"][ival]
        try:
            params = cls.set_vars(
                inst,
                state._modpass["p0"],
                levadd[ival],
                state._modpass,
                ival,
                wvrng=[0.0, 1.0e9],
                spid="0",
                levid=levadd,
            )
        except SystemExit:  # msgs.error(); not what is under test
            continue
        if len(params) == 0:
            continue
        out[state._modpass["mkey"][ival]["ion"]] = np.asarray(params)[:, 2]
    return out


# -- format-specific: the mapping agrees with the data file ------------------


def test_element_and_atomic_mass_are_the_same_length(atomic):
    # The invariant every consumer depends on. It was 80 against 82, and a
    # single check like this would have caught that at every start-up.
    assert len(atomic["Element"]) == len(atomic["AtomicMass"])


def test_each_isotope_appears_once(atomic):
    # The consumers do `if np.size(m) != 1: msgs.error(...)`, so a repeated
    # isotope would abort the fit.
    elements = np.asarray(atomic["Element"]).astype(str)
    assert len(set(elements)) == len(elements)


def test_every_isotope_maps_to_its_own_mass(atomic):
    # Directly the bug: the index found in Element must address the right slot
    # in AtomicMass. Checked against the file rather than a hard-coded table so
    # this still holds when the data changes (e.g. atomic.ecsv, Stage 5.2).
    expected = _file_masses(_atomic_path())
    elements = np.asarray(atomic["Element"]).astype(str)
    masses = np.asarray(atomic["AtomicMass"]).astype(float)
    wrong = [
        (iso, got, sorted(expected[iso]))
        for iso, got in zip(elements, masses)
        if not any(abs(got - m) <= 1e-9 * max(m, 1.0) for m in expected[iso])
    ]
    assert not wrong, f"{len(wrong)} isotopes carry another isotope's mass: {wrong[:5]}"


@pytest.mark.parametrize(
    "isotope,mass",
    [
        ("1H", 1.00782503207),
        ("2H", 2.0141017778),
        ("3He", 3.0160293191),
        ("4He", 4.00260325415),
        ("12C", 12.0),
        ("16O", 15.9994),
        # The four that carried two masses until Stage 5.6; RJC chose the
        # isotopic value in each case.
        ("24Mg", 23.9850417),
        ("28Si", 27.9769265325),
        ("47Ti", 46.9517631),
        ("56Fe", 55.9349375),
    ],
)
def test_named_isotopes_have_the_expected_mass(atomic, isotope, mass):
    elements = np.asarray(atomic["Element"]).astype(str)
    found = np.where(elements == isotope)[0]
    assert found.size == 1, f"{isotope} appears {found.size} times"
    assert float(np.asarray(atomic["AtomicMass"])[found][0]) == pytest.approx(
        mass, rel=1e-12
    )


def test_no_isotope_carries_two_masses_in_the_shipped_file():
    # Stage 5.6 made atomic.xml self-consistent (24Mg/28Si/47Ti/56Fe each had
    # two). load_atomic warns and takes the first if this is ever untrue again,
    # but the shipped file should not need that.
    multi = {k: v for k, v in _file_masses(_atomic_path()).items() if len(v) > 1}
    assert not multi, f"isotopes with more than one AtomicMass: {multi}"


# -- format-agnostic: the mass that reaches the profile ----------------------


def test_every_isotope_ion_broadens_with_its_own_mass(broadening, atomic):
    """The whole point: recover the mass from the b `set_vars` returned.

    b = sqrt(b_turb^2 + K*T/m)  =>  m = K*T / (b^2 - b_turb^2)

    Compared against the mapping `load_atomic` published rather than against
    the file, so this survives the move to `atomic.ecsv` untouched. That the
    mapping itself matches the file is the job of the tests above.
    """
    elements = np.asarray(atomic["Element"]).astype(str)
    masses = np.asarray(atomic["AtomicMass"]).astype(float)
    published = dict(zip(elements, masses))
    wrong = []
    for ion, b_used in broadening.items():
        used = KCONST * TEMPERATURE / (b_used[0] ** 2 - BTURB**2)
        want = published[ion.split("_")[0]]
        if abs(used - want) > 1e-6 * want:
            wrong.append((ion, used, want))
    assert not wrong, (
        f"{len(wrong)} of {len(broadening)} isotope/ion combinations broaden "
        f"with a mass load_atomic did not publish for them, e.g. {wrong[:5]}"
    )


def test_all_transitions_of_one_ion_share_a_broadening(broadening):
    # b is computed once per component, before the transitions are selected,
    # so every transition of an ion must come out identical.
    for ion, b_used in broadening.items():
        assert np.allclose(b_used, b_used[0], rtol=0, atol=1e-12), ion


def test_the_check_covers_the_whole_atomic_file(broadening, atomic):
    # Guards the test itself: if the fixture silently stopped producing
    # profiles, every assertion above would pass vacuously.
    assert len(broadening) > 150
    assert len(broadening) >= len(set(np.asarray(atomic["Ion"]).astype(str))) - 5


@pytest.mark.parametrize(
    "ion,mass", [("1H_I", 1.00782503207), ("16O_I", 15.9994), ("12C_II", 12.0)]
)
def test_named_ions_broaden_with_the_right_mass(broadening, ion, mass):
    # The three that showed the bug most clearly: 1H was given deuterium's mass
    # (-29% in b) and 16O was given neon's (-11%).
    assert ion in broadening
    expected = np.sqrt(BTURB**2 + KCONST * TEMPERATURE / mass)
    assert broadening[ion][0] == pytest.approx(expected, rel=1e-10)
