"""The Data tab (dashboard Stage 4.6; D35, S24, S25, D14–D16, F13, S3, Q4.14).

At the left, **Systems**, **Coverage** (with several files) and **Blinding**; at the
right, the **Datasets** table and the **Spectrum** of the selected row.

- **Systems** (D15, D16, S24 as revised in D35): the primary z, typed (Enter makes it
  one step); ⌖ Identify a feature…, which arms the spectrum: a click there opens a
  panel with Element → Ion → Transition menus, each transition with the z it implies,
  then "Set as primary z" or "Add as a new system"; the other systems, each with its
  transitions, and a right-click menu (Rename…, Make primary, Set z…, Remove…); the
  generic absorbers; Add system…. An imported fit's systems were worked out from the
  model: the pane says so, and Confirm keeps them (Q2.4, Q4.14).
- **Coverage** (Q0.5): ■ a snip, □ covered by the source, · not covered; a
  double-click opens the transition on the Regions tab.
- **Blinding** (D24, Q3.9): Blind the whole fit, what is blinded (no values), Blind
  lines… and Unblind….
- **Datasets** (S25, D14, D35, Q0.8): one row per file: the reference (◉), the
  file, its contents, its FWHM and shift (each with a badge: ● free, ■ fixed, ⛓ tied;
  a click on the badge offers Free, Fixed and Tie to <row>; a double-click on the
  value types a new one), its zero level (Off/On) and its checksum (Relink…). Add
  file… opens Stage 3's spectrum dialog; a right-click offers Make reference,
  Rename…, Column roles… and Remove….
- **Spectrum** (D35, S5): the selected row's source spectrum, or its snips each
  scaled to its own peak; Flux | Log; the primary system's transitions (with the number
  left unlabelled, and All lines); the zoom bar.

Every action is a step of the history, made through the window (``window._run``),
and every value is shown through the blinding gate.

Generated by RJC and Claude.
"""

import numpy as np
from qtpy import QtCore, QtGui, QtWidgets

from alis.dashboard import blinding as BL
from alis.dashboard import datasets as DS
from alis.dashboard import lines as L
from alis.dashboard import remove as R
from alis.dashboard import sources as SR
from alis.dashboard.qt import dialogs as D
from alis.dashboard.qt import plots as PL
from alis.dashboard.qt import style as ST
from alis.dashboard.qt import widgets as W

INFERRED = "Worked out from the model's labels and redshifts: check them, then Confirm."
COLUMNS = (
    "Ref.",
    "Dataset (file)",
    "Contents",
    "FWHM (km/s)",
    "Shift (km/s)",
    "Zero level",
    "Checksum",
)
BADGES = {DS.FREE: "●", DS.FIXED: "■", DS.TIED: "⛓"}
BADGE_TIPS = {
    DS.FREE: "Free: the fit varies it",
    DS.FIXED: "Fixed: the fit keeps it",
    DS.TIED: "Tied: shared with another dataset",
}
CELLS = {L.SNIP: "■", L.COVERED: "□", L.NONE: "·"}


class IdentifyPanel(QtWidgets.QFrame):
    """
    The panel Identify a feature opens beside a clicked point (D35): Element → Ion →
    Transition, each transition with the z it implies; Set as primary z, Add as a new
    system, Cancel.

    Signals
    -------
    chosen(str, float)
        ``"primary"`` or ``"new"``, and the redshift.

    Generated by RJC and Claude.
    """

    chosen = QtCore.Signal(str, float)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("pane")
        self.setAutoFillBackground(True)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(10, 8, 10, 8)
        self.where = QtWidgets.QLabel("")
        layout.addWidget(self.where)
        row = QtWidgets.QHBoxLayout()
        self.element = QtWidgets.QComboBox()
        self.stage = QtWidgets.QComboBox()
        self.transition = QtWidgets.QComboBox()
        self.transition.setMinimumWidth(190)
        for label, box in (
            ("Element", self.element),
            ("Ion", self.stage),
            ("Transition", self.transition),
        ):
            row.addWidget(QtWidgets.QLabel(label))
            row.addWidget(box)
        layout.addLayout(row)
        self.z = QtWidgets.QLabel("")
        layout.addWidget(self.z)
        buttons = QtWidgets.QHBoxLayout()
        self.primary = QtWidgets.QPushButton("Set as primary z")
        self.new = QtWidgets.QPushButton("Add as a new system")
        self.cancel = QtWidgets.QPushButton("Cancel")
        for button in (self.primary, self.new, self.cancel):
            buttons.addWidget(button)
        layout.addLayout(buttons)
        self.menus = {}
        self.element.currentIndexChanged.connect(self._fill_stages)
        self.stage.currentIndexChanged.connect(self._fill_transitions)
        self.transition.currentIndexChanged.connect(self._show_z)
        self.primary.clicked.connect(lambda: self._choose("primary"))
        self.new.clicked.connect(lambda: self._choose("new"))
        self.cancel.clicked.connect(self.hide)
        self.hide()

    def show_for(self, wave, candidates, first):
        """
        Offer the transitions that could make a feature at ``wave``.

        Parameters
        ----------
        wave : float
        candidates : list of lines.Candidate
        first : int or None
            The first choice.

        Generated by RJC and Claude.
        """
        self.menus = L.candidate_menus(candidates)
        self.where.setText("Clicked at {0:.2f} Å. Choose the transition:".format(wave))
        pick = candidates[first] if first is not None else None
        self.element.blockSignals(True)
        self.element.clear()
        for elem in self.menus:
            self.element.addItem(elem)
        self.element.blockSignals(False)
        if pick is not None:
            self.element.setCurrentText(pick.line.element)
        self._fill_stages()
        if pick is not None:
            self.stage.setCurrentText(pick.line.stage)
            self._fill_transitions()
            for num in range(self.transition.count()):
                if self.transition.itemData(num) is pick:
                    self.transition.setCurrentIndex(num)
        self._show_z()
        self.show()
        self.raise_()

    def _fill_stages(self):
        self.stage.blockSignals(True)
        self.stage.clear()
        for stage in self.menus.get(self.element.currentText(), {}):
            self.stage.addItem(stage)
        self.stage.blockSignals(False)
        self._fill_transitions()

    def _fill_transitions(self):
        self.transition.blockSignals(True)
        self.transition.clear()
        stages = self.menus.get(self.element.currentText(), {})
        for cand in stages.get(self.stage.currentText(), []):
            self.transition.addItem(
                "{0}    z = {1:.5f}".format(cand.name, cand.z), cand
            )
        self.transition.blockSignals(False)
        self._show_z()

    def current(self):
        """The candidate chosen, or None."""
        return self.transition.currentData()

    def _show_z(self):
        cand = self.current()
        self.z.setText("→ z = {0:.6f}".format(cand.z) if cand is not None else "")
        self.primary.setEnabled(cand is not None)
        self.new.setEnabled(cand is not None)

    def _choose(self, what):
        cand = self.current()
        if cand is not None:
            self.hide()
            self.chosen.emit(what, cand.z)


class DataTab(W.Tab):
    """
    The Data tab (D35): Systems, Coverage (several files) and Blinding at the left;
    the Datasets table and the Spectrum at the right.

    Generated by RJC and Claude.
    """

    name = "Data"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.main = None
        self.session = None
        self.selected = None
        self._drawn = None
        self._candidates = []
        self._build_systems()
        self._build_coverage()
        self._build_blinding()
        self._build_files()
        self._build_spectrum()
        left = W.column(
            self.systems, self.coverage, self.blinding, stretch=[3, 2, 2], width=340
        )
        right = W.column(self.files, self.spectrum, stretch=[2, 5], width=1050)
        self.layout_.addWidget(W.row(left, right, stretch=[340, 1050]))
        self.coverage.hide()

    # -- building -----------------------------------------------------------------------

    def _build_systems(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        # The z and Identify share a row, one above the other when the pane is narrow
        # (the .mod panel open beside the tab)
        row = QtWidgets.QBoxLayout(QtWidgets.QBoxLayout.Direction.LeftToRight)
        self._z_row = row
        zline = QtWidgets.QHBoxLayout()
        zline.addWidget(QtWidgets.QLabel("<b>Primary</b> z ="))
        self.z_edit = QtWidgets.QLineEdit()
        self.z_edit.setPlaceholderText("type the redshift")
        self.z_edit.setToolTip("The primary system's redshift: Enter keeps it")
        self.z_edit.returnPressed.connect(self._z_typed)
        zline.addWidget(self.z_edit, 1)
        row.addLayout(zline, 1)
        self.identify = QtWidgets.QToolButton()
        self.identify.setText("⌖ Identify a feature…")
        self.identify.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.identify.setCheckable(True)
        self.identify.setToolTip(
            "Click a feature of the spectrum, then choose its transition"
        )
        self.identify.toggled.connect(self._arm)
        row.addWidget(self.identify)
        box.addLayout(row)
        self.others = QtWidgets.QListWidget()
        self.others.setObjectName("systems")
        self.others.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.others.customContextMenuRequested.connect(self._system_menu)
        self.others.itemClicked.connect(self._system_clicked)
        box.addWidget(self.others, 1)
        self.generic = W.muted("")
        box.addWidget(self.generic)
        self.systems_note = W.muted(INFERRED)
        self.systems_note.setWordWrap(True)
        box.addWidget(self.systems_note)
        buttons = QtWidgets.QHBoxLayout()
        self.add_system = QtWidgets.QPushButton("Add system…")
        self.add_system.clicked.connect(
            lambda: self._act("add_system", self._add_system)
        )
        self.confirm = QtWidgets.QPushButton("Confirm")
        self.confirm.setToolTip("Keep these systems and datasets as the project's own")
        self.confirm.clicked.connect(lambda: self._act("confirm", self._confirm))
        buttons.addWidget(self.add_system)
        buttons.addStretch(1)
        buttons.addWidget(self.confirm)
        box.addLayout(buttons)
        self.systems = W.Pane("Systems", body)
        self.systems.installEventFilter(self)

    def eventFilter(self, obj, event):
        """Stack the z and Identify when the Systems pane is narrow."""
        if obj is self.systems and event.type() == QtCore.QEvent.Type.Resize:
            narrow = obj.width() < 330
            self._z_row.setDirection(
                QtWidgets.QBoxLayout.Direction.TopToBottom
                if narrow
                else QtWidgets.QBoxLayout.Direction.LeftToRight
            )
        return super().eventFilter(obj, event)

    def _build_coverage(self):
        self.grid = QtWidgets.QTableWidget()
        self.grid.setObjectName("coverage")
        self.grid.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.grid.verticalHeader().setVisible(False)
        self.grid.cellDoubleClicked.connect(self._coverage_clicked)
        self.grid.setToolTip(
            "■ a snip · □ covered by the file, no snip yet · · not covered;"
            " double-click to open it on the Regions tab"
        )
        self.coverage = W.Pane("Coverage", self.grid)

    def _build_blinding(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        self.blind_all = QtWidgets.QCheckBox("Blind the whole fit (run blind True)")
        self.blind_all.clicked.connect(self._blind_all)
        box.addWidget(self.blind_all)
        hint = W.muted(
            "Hides every best-fit value. It can be switched on at any time; only"
            " Unblind… switches it off."
        )
        hint.setWordWrap(True)
        box.addWidget(hint)
        self.blinded = QtWidgets.QLabel("")
        self.blinded.setWordWrap(True)
        box.addWidget(self.blinded)
        buttons = QtWidgets.QHBoxLayout()
        self.blind_lines = QtWidgets.QPushButton("Blind lines…")
        self.unblind = QtWidgets.QPushButton("Unblind…")
        buttons.addWidget(self.blind_lines)
        buttons.addWidget(self.unblind)
        buttons.addStretch(1)
        box.addLayout(buttons)
        box.addStretch(1)
        self.blind_lines.clicked.connect(
            lambda: self.main.qactions["model.blind_lines"].trigger()
        )
        self.unblind.clicked.connect(
            lambda: self.main.qactions["model.unblind"].trigger()
        )
        self.blinding = W.Pane("Blinding", body)

    def _build_files(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        self.table = QtWidgets.QTableWidget(0, len(COLUMNS))
        self.table.setObjectName("datasets")
        self.table.setHorizontalHeaderLabels(COLUMNS)
        self.table.verticalHeader().setVisible(False)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.table.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.table.customContextMenuRequested.connect(self._row_menu)
        self.table.cellClicked.connect(self._cell_clicked)
        self.table.cellDoubleClicked.connect(self._cell_double_clicked)
        box.addWidget(self.table, 1)
        self.files_note = W.muted(
            "Click a badge to free, fix or tie a value to another dataset (for"
            " example two settings of one instrument sharing one FWHM); double-click"
            " a value to type it. Right-click a row for more."
        )
        self.files_note.setWordWrap(True)
        box.addWidget(self.files_note)
        self.add_file = QtWidgets.QPushButton("Add file…")
        self.add_file.clicked.connect(lambda: self._act("add_file", self._add_file))
        self.files = W.Pane("Datasets · one row per file", body, extra=[self.add_file])

    def _build_spectrum(self):
        self.view = PL.SpectrumView()
        self.view.clicked.connect(self._clicked)
        self.zoom = PL.ZoomBar()
        self.zoom.attach(self.view)
        self.flux_button = QtWidgets.QToolButton()
        self.flux_button.setText("Flux")
        self.log_button = QtWidgets.QToolButton()
        self.log_button.setText("Log")
        for button in (self.flux_button, self.log_button):
            button.setCheckable(True)
            button.setAutoRaise(True)
        self.flux_button.setChecked(True)
        group = QtWidgets.QButtonGroup(self)
        group.addButton(self.flux_button)
        group.addButton(self.log_button)
        self.log_button.toggled.connect(self.view.set_log)
        self.show_ids = QtWidgets.QCheckBox("Transitions of z")
        self.show_ids.setChecked(True)
        self.show_ids.toggled.connect(lambda _: self._draw_ids())
        self.all_lines = QtWidgets.QCheckBox("All lines")
        self.all_lines.setToolTip("Label every line, not only the strong ones")
        self.all_lines.toggled.connect(lambda _: self._draw_ids())
        self.view.box.sigXRangeChanged.connect(lambda *a: self._ids_timer.start())
        self._ids_timer = QtCore.QTimer(self)
        self._ids_timer.setSingleShot(True)
        self._ids_timer.setInterval(150)
        self._ids_timer.timeout.connect(self._draw_ids)
        holder = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(holder)
        box.setContentsMargins(0, 0, 0, 0)
        box.addWidget(self.view)
        self.identify_panel = IdentifyPanel(holder)
        self.identify_panel.chosen.connect(self._identified)
        self.spectrum = W.Pane(
            "Spectrum",
            holder,
            extra=[
                self.flux_button,
                self.log_button,
                self.show_ids,
                self.all_lines,
                self.zoom,
            ],
        )

    def attach(self, window):
        """The main window, whose actions, questions and history this tab uses."""
        self.main = window

    def bind_action(self, name, action):
        """
        The tab's own actions: Identify a feature… is its button.

        Generated by RJC and Claude.
        """
        self.tab_buttons = getattr(self, "tab_buttons", [])
        if name == "data.identify":
            action.setText("⌖ Identify a feature…")
            self.identify.setDefaultAction(action)
            self.tab_buttons.append(self.identify)

    def do_identify(self):
        """Identify a feature…: arming is done by the button's toggle."""

    # -- acting ---------------------------------------------------------------------------

    def _act(self, name, handler):
        """Run a handler through the window (typing read first, errors reported)."""
        if self.main is not None:
            self.main._run("data." + name, handler)
        else:
            handler()

    def _do(self, step):
        """Make a step through the history."""
        if step is not None and step:
            self.session.history.do(step)

    def _gate(self):
        return BL.Gate(self.session.project)

    def _pref(self, key, default):
        """A preference, or its default without a window (tests)."""
        prefs = getattr(self.main, "prefs", None)
        try:
            return prefs[key] if prefs is not None else default
        except KeyError:
            return default

    # -- refreshing ---------------------------------------------------------------------

    def refresh(self, session):
        """
        Redraw the tab from the project (after every step, undo and redo).

        Generated by RJC and Claude.
        """
        self.session = session
        if session is None:
            return
        project = session.project
        if project.paused:
            return
        gate = self._gate()
        self._refresh_systems(project, gate)
        self._refresh_files(project, gate)
        self._refresh_coverage(project)
        self._refresh_blinding(project)
        self._refresh_spectrum(project)

    def _primary(self, project):
        return next((s for s in project.systems if s.primary), None)

    def _refresh_systems(self, project, gate):
        primary = self._primary(project)
        if not self.z_edit.hasFocus():
            self.z_edit.setText(gate.system_z(primary) if primary else "")
        self.others.clear()
        snip_map = L.snip_transitions(project)
        for system in project.systems:
            if system.primary:
                continue
            names = DS.system_lines(project, system, snip_map)
            text = system.name + (" · " + ", ".join(names) if names else "")
            item = QtWidgets.QListWidgetItem(gate.message(text))
            item.setData(QtCore.Qt.ItemDataRole.UserRole, system.id)
            self.others.addItem(item)
        if not self.others.count():
            item = QtWidgets.QListWidgetItem("No other systems")
            item.setFlags(QtCore.Qt.ItemFlag.NoItemFlags)
            self.others.addItem(item)
        generic = DS.generic_summary(project)
        self.generic.setText("Generic absorbers · " + generic if generic else "")
        self.generic.setVisible(bool(generic))
        self.systems_note.setVisible(project.inferred)
        self.confirm.setVisible(project.inferred)
        self.files_note.setText(
            (INFERRED + " ") * project.inferred
            + "Click a badge to free, fix or tie a value to another dataset;"
            " double-click a value to type it. Right-click a row for more."
        )

    def _states(self, project):
        path = self.session.path
        out = {}
        for entry, state in SR.states(project.bundle, path):
            out[entry["id"]] = state
        return out

    def _spectrum_of(self, row):
        return SR.spectrum(self.session.project, row, self.session.path)

    def _refresh_files(self, project, gate):
        states = self._states(project)
        rows = project.rows
        keep = self.selected
        self.table.blockSignals(True)
        self.table.setRowCount(len(rows))
        for num, row in enumerate(rows):
            spec = self._spectrum_of(row) if row.source else None
            state = states.get(row.source["id"]) if row.source else None
            cells = [
                "◉" if row.reference else "○",
                row.name,
                DS.contents(row, spec),
                self._value_text(gate, row, "resolution"),
                self._shift_text(gate, row),
                "On" if row.zero is not None else "Off",
                DS.checksum(state) + (" · Relink…" if state == SR.MISSING else ""),
            ]
            for col, text in enumerate(cells):
                item = QtWidgets.QTableWidgetItem(text)
                item.setData(QtCore.Qt.ItemDataRole.UserRole, row.id)
                if col == 0:
                    item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    item.setToolTip(
                        "The reference: its shift is 0"
                        if row.reference
                        else "Click to make this the reference"
                    )
                if col in (3, 4):
                    what = "resolution" if col == 3 else "shift"
                    item.setToolTip(self._badge_tip(project, row, what))
                if col == 5:
                    item.setToolTip("Click to switch the zero level on or off")
                if col == 6 and state == SR.MISSING:
                    item.setToolTip("The file has moved: click to relink it")
                self.table.setItem(num, col, item)
        self.table.blockSignals(False)
        self.table.resizeColumnsToContents()
        ids = [r.id for r in rows]
        if keep not in ids:
            keep = ids[0] if ids else None
        self.selected = keep
        if keep is not None:
            self.table.selectRow(ids.index(keep))

    def _badge(self, project, row, what):
        state = DS.state_of(row, what)
        if state is None:
            return ""
        if DS.tied_to(project, row, what):
            state = DS.TIED
        return BADGES[state]

    def _badge_tip(self, project, row, what):
        state = DS.state_of(row, what)
        if state is None:
            return ""
        others = DS.tied_to(project, row, what)
        if others:
            return BADGE_TIPS[DS.TIED] + " (" + ", ".join(r.name for r in others) + ")"
        return BADGE_TIPS[state] + "; click the badge to change it"

    def _value_text(self, gate, row, what):
        if not row.snips:
            entry = next(
                (
                    e
                    for e in self.session.project.ui.get("rows", [])
                    if e.get("id") == row.id
                ),
                {},
            )
            return "{0:g}".format(entry["fwhm"]) if "fwhm" in entry else "—"
        par = row.snips[0].data.param(what)
        if par is None:
            return "—"
        return gate.value(par) + " " + self._badge(self.session.project, row, what)

    def _shift_text(self, gate, row):
        if row.reference:
            return "0 · reference"
        if not row.snips:
            return "free, once it has a snip"
        par = row.snips[0].data.param("shift")
        if par is None or "shift" not in row.snips[0].data.keywords:
            return "0"
        return gate.value(par) + " " + self._badge(self.session.project, row, "shift")

    def _refresh_coverage(self, project):
        rows = project.rows
        self.coverage.setVisible(len(rows) > 1)
        if len(rows) < 2:
            return
        primary = self._primary(project)
        if primary is None:
            self.grid.setRowCount(0)
            return
        covs = []
        for row in rows:
            spec = self._spectrum_of(row) if row.source else None
            if spec is not None:
                covs.append(L.coverage_of_spectrum(row.id, row.name, spec))
            else:
                covs.append(L.coverage_of_snips(row))
        grid = L.coverage_grid(project, primary, covs)
        self.grid.setColumnCount(1 + len(rows))
        self.grid.setHorizontalHeaderLabels(["Transition"] + [r.name for r in rows])
        self.grid.setRowCount(len(grid))
        self._grid = grid
        for num, entry in enumerate(grid):
            self.grid.setItem(num, 0, QtWidgets.QTableWidgetItem(entry.name))
            for col, cov in enumerate(covs, 1):
                item = QtWidgets.QTableWidgetItem(CELLS[entry.cells[cov.row]])
                item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.grid.setItem(num, col, item)
        self.grid.resizeColumnsToContents()

    def _refresh_blinding(self, project):
        self.blind_all.blockSignals(True)
        self.blind_all.setChecked(project.parsed.blind)
        self.blind_all.setEnabled(not project.parsed.blind)
        self.blind_all.blockSignals(False)
        items = BL.blinded_items(project)
        if items:
            self.blinded.setText("Blinded: " + ", ".join(items))
        elif project.parsed.blind:
            self.blinded.setText("Every best-fit value is hidden.")
        else:
            self.blinded.setText("Nothing is blinded in this project.")

    def _row(self, ident=None):
        project = self.session.project
        ident = self.selected if ident is None else ident
        for row in project.rows:
            if row.id == ident:
                return row
        return None

    def _refresh_spectrum(self, project):
        row = self._row()
        title = "Spectrum"
        if row is None:
            self.spectrum.title.setText(title)
            self.view.set_pieces([])
            self._drawn = None
            return
        spec = self._spectrum_of(row) if row.source else None
        if row.source:
            name = row.source["path"].replace("\\", "/").split("/")[-1]
            title += " · " + name
        else:
            title += " · " + row.name
        if spec is None and row.snips:
            title += " · its snips, each scaled to its peak"
        self.spectrum.title.setText(title)
        key = (
            row.id,
            row.source["sha256"] if row.source and spec is not None else None,
            tuple((s.member, id(s.pixels)) for s in row.snips) if spec is None else (),
        )
        if key != self._drawn:
            if spec is not None:
                self.view.set_data(spec.wave, spec.flux, spec.error, spec.mask)
            else:
                pieces = []
                for snip in row.snips:
                    pix = snip.pixels
                    if pix is None or not pix.wave.size:
                        continue
                    peak = np.nanpercentile(pix.flux, 98)
                    pieces.append((pix.wave, pix.flux / peak if peak else pix.flux))
                self.view.set_pieces(pieces)
            self.view.home()
            self.zoom.attach(self.view)
            self.zoom.remember()
            self._drawn = key
        self._draw_ids()

    def _draw_ids(self):
        if self.session is None or self.session.project.paused:
            return
        project = self.session.project
        primary = self._primary(project)
        on = self.show_ids.isChecked() and primary is not None
        self.all_lines.setEnabled(on)
        if primary is not None:
            self.show_ids.setText("Transitions of " + primary.name)
        if not on or self.view._wave is None:
            self.view.set_line_ids([])
            return
        (x0, x1), _ = self.view.view_range()
        ids, hidden = L.line_ids(
            project,
            x0,
            x1,
            reference=primary.id,
            show_all=self.all_lines.isChecked(),
            strong=self._pref("lines.strength", L.STRONG),
            systems=[primary],
        )
        self.view.set_line_ids([(i.observed, i.label, i.kind) for i in ids], hidden)

    # -- cross-highlighting (S16) -------------------------------------------------------

    def show_items(self, items):
        """
        Select what a line of the .mod panel describes: its row (S16).

        Generated by RJC and Claude.
        """
        if self.session is None:
            return
        for item in items:
            row = getattr(item, "row", None) if not hasattr(item, "snips") else item
            if row is not None and hasattr(row, "snips"):
                ids = [r.id for r in self.session.project.rows]
                if row.id in ids:
                    self.selected = row.id
                    self.table.selectRow(ids.index(row.id))
                    self._refresh_spectrum(self.session.project)
                return

    def _highlight(self, item):
        if self.main is not None and item is not None:
            self.main.panel.select_items([item])

    # -- systems ------------------------------------------------------------------------

    def _z_typed(self):
        text = self.z_edit.text().strip()
        self._act("z", lambda: self._set_primary_z(text))

    def _set_primary_z(self, text):
        try:
            z = float(text)
        except ValueError:
            self.main.tell("Primary z", "Type a redshift, such as 2.5257.", "warning")
            return
        project = self.session.project
        primary = self._primary(project)
        if primary is None:
            self._do(DS.add_system_step(project, z, primary=True))
        else:
            if abs(z - primary.z) < 1e-12:
                return
            self._do(DS.set_z_step(project, primary, z))
        self.z_edit.clearFocus()

    def _arm(self, on):
        """⌖ Identify a feature…: the next click on the spectrum identifies it."""
        self.view.set_mode(PL.CLICK if on else PL.PAN)
        if on:
            self.zoom.buttons["pan"].setChecked(False)
            self.zoom.buttons["zoom"].setChecked(False)
        else:
            self.zoom.set_mode(PL.PAN)

    def _clicked(self, x, y):
        if not self.identify.isChecked() or self.session is None:
            return
        self.identify_at(x)

    def identify_at(self, wave):
        """
        Open the Identify panel for a wavelength (the click, or a test).

        Generated by RJC and Claude.
        """
        project = self.session.project
        atom = L.atomic(project.registry)
        data_max = (
            float(np.nanmax(self.view._wave)) if self.view._wave is not None else None
        )
        cands, first = L.identify(atom, wave, data_max, [s.z for s in project.systems])
        self._candidates = cands
        self.view.set_marker(wave)
        self.identify_panel.show_for(wave, cands, first)
        holder = self.identify_panel.parentWidget()
        self.identify_panel.adjustSize()
        pos = self.view.box.mapViewToDevice(QtCore.QPointF(wave, 0.0))
        x = 20 if pos is None else int(pos.x()) + 12
        x = max(0, min(x, holder.width() - self.identify_panel.width()))
        self.identify_panel.move(x, 10)

    def _identified(self, what, z):
        self.identify.setChecked(False)
        self.view.set_marker(None)
        project = self.session.project
        if what == "primary":
            primary = self._primary(project)
            if primary is None:
                self._act(
                    "identify",
                    lambda: self._do(DS.add_system_step(project, z, primary=True)),
                )
            else:
                self._act(
                    "identify", lambda: self._do(DS.set_z_step(project, primary, z))
                )
        else:
            self._act("identify", lambda: self._do(DS.add_system_step(project, z)))

    def _system_clicked(self, item):
        ident = item.data(QtCore.Qt.ItemDataRole.UserRole)
        if ident is not None and self.session is not None:
            self._highlight(self.session.project.system(ident))

    def _system_menu(self, pos):
        item = self.others.itemAt(pos)
        if item is None or item.data(QtCore.Qt.ItemDataRole.UserRole) is None:
            return
        system = self.session.project.system(item.data(QtCore.Qt.ItemDataRole.UserRole))
        menu = QtWidgets.QMenu(self)
        for text, handler in (
            ("Rename…", lambda: self.rename_system(system)),
            (
                "Make primary",
                lambda: self._do(DS.make_primary_step(self.session.project, system)),
            ),
            ("Set z…", lambda: self.set_system_z(system)),
            ("Remove…", lambda: self.remove_system(system)),
        ):
            menu.addAction(text, lambda h=handler, t=text: self._act(t, h))
        menu.exec(self.others.mapToGlobal(pos))

    def rename_system(self, system):
        """Rename… a system."""
        dialog = D.AskDialog(
            "Rename the system", [("name", "Name", system.name, "text")], "Rename"
        )
        if self.main.run_dialog(dialog):
            self._do(
                DS.rename_system_step(
                    self.session.project, system, dialog.values()["name"]
                )
            )

    def set_system_z(self, system):
        """Set z… of a system (D16: it moves nothing)."""
        gate = self._gate()
        dialog = D.AskDialog(
            "Set the redshift",
            [("z", "z", gate.system_z(system), "number")],
            "Set",
            "The redshift sets the velocity axes and where transitions are looked"
            " for; it moves no snip and no component.",
        )
        if self.main.run_dialog(dialog):
            self._do(DS.set_z_step(self.session.project, system, dialog.values()["z"]))

    def remove_system(self, system):
        """Remove… a system, after listing the lines it changes (S27)."""
        project = self.session.project
        plan = R.plan_system(project, system)
        dialog = D.PlanDialog("Remove a system", plan, self._gate(), "Remove")
        if self.main.run_dialog(dialog):
            self._do(plan.step(project))

    def _add_system(self):
        dialog = D.AskDialog(
            "Add a system",
            [("z", "z", "", "number"), ("name", "Name (optional)", "", "text")],
            "Add",
        )
        if self.main.run_dialog(dialog):
            values = dialog.values()
            self._do(
                DS.add_system_step(self.session.project, values["z"], values["name"])
            )

    def _confirm(self):
        """
        Confirm: keep the systems and datasets, then check the model again, so that
        each tab's marker says what still needs attention (Q4.18).

        Generated by RJC and Claude.
        """
        project = self.session.project
        self._do(project.confirm_structure())
        if self.main is not None:
            self.main.notice_banner.clear()
            self.main.panel.check_now()

    def _coverage_clicked(self, num, col):
        """Open a transition of the coverage grid on the Regions tab."""
        grid = getattr(self, "_grid", [])
        if not 0 <= num < len(grid) or self.session is None:
            return
        entry = grid[num]
        rows = self.session.project.rows
        row = rows[col - 1].id if 1 <= col <= len(rows) else None
        primary = self._primary(self.session.project)
        self.session.set_view(
            "regions",
            {"system": primary.id, "ion": entry.ion, "rest": entry.rest, "row": row},
        )
        if self.main is not None:
            self.main.tabs.setCurrentIndex(1)

    # -- blinding -----------------------------------------------------------------------

    def _blind_all(self, checked):
        if checked and self.main is not None:
            self.main.qactions["model.blind"].trigger()
        self.refresh(self.session)

    # -- datasets -----------------------------------------------------------------------

    def _cell_clicked(self, num, col):
        rows = self.session.project.rows if self.session else []
        if not 0 <= num < len(rows):
            return
        row = rows[num]
        if row.id != self.selected:
            self.selected = row.id
            self._refresh_spectrum(self.session.project)
            self._highlight(row)
        if col == 0 and not row.reference:
            self._act(
                "reference",
                lambda: self._do(DS.set_reference_step(self.session.project, row)),
            )
        elif col in (3, 4) and row.snips:
            what = "resolution" if col == 3 else "shift"
            if what == "shift" and row.reference:
                return
            self.badge_menu(row, what)
        elif col == 5:
            self.toggle_zero(row)
        elif col == 6:
            if (
                self.main is not None
                and row.source
                and "Relink" in self.table.item(num, 6).text()
            ):
                self.main.qactions["file.relink"].trigger()

    def badge_menu(self, row, what, choice=None):
        """
        The badge's menu: Free, Fixed, or Tie to <row> (D35, Q0.8). ``choice`` makes
        the choice without the menu (tests).

        Generated by RJC and Claude.
        """
        project = self.session.project
        options = [("Free", DS.FREE, None), ("Fixed", DS.FIXED, None)]
        for other in project.rows:
            if other.id != row.id and other.snips:
                options.append(("Tie to " + other.name, DS.TIED, other))
        if choice is None:
            menu = QtWidgets.QMenu(self)
            actions = {
                menu.addAction(text): (state, other) for text, state, other in options
            }
            picked = menu.exec(QtGui.QCursor.pos())
            if picked is None:
                return
            state, other = actions[picked]
        else:
            state, other = next((s, o) for t, s, o in options if t == choice)
        self._act(
            "badge",
            lambda: self._do(DS.set_state_step(project, row, what, state, other)),
        )

    def toggle_zero(self, row):
        """Zero level Off/On (D14)."""
        project = self.session.project
        on = row.zero is None
        if not on:
            shared = DS.zero_level_shared(project, row)
            if shared:
                choice = self.main.ask(
                    "zero_off",
                    "Zero level",
                    "{0} shares its zero level with {1}. Switching it off removes"
                    " {0}'s snips from that zero level; the others keep it.".format(
                        row.name, ", ".join(r.name for r in shared)
                    ),
                    ["Switch off", "Cancel"],
                )
                if choice != "Switch off":
                    return
        self._act("zero", lambda: self._do(DS.zero_level_step(project, row, on)))

    def _cell_double_clicked(self, num, col):
        rows = self.session.project.rows if self.session else []
        if col not in (3, 4) or not 0 <= num < len(rows):
            return
        row = rows[num]
        what = "resolution" if col == 3 else "shift"
        if what == "shift" and (row.reference or not row.snips):
            return
        self.type_value(row, what)

    def type_value(self, row, what, value=None):
        """
        Type a row's FWHM or shift (``value`` gives it without the dialog: tests).

        Generated by RJC and Claude.
        """
        project = self.session.project
        if value is None:
            gate = self._gate()
            par = row.snips[0].data.param(what) if row.snips else None
            start = gate.value(par) if par is not None else ""
            name = "FWHM (km/s)" if what == "resolution" else "Shift (km/s)"
            dialog = D.AskDialog(
                "{0} of {1}".format(name.split(" ")[0], row.name),
                [("value", name, start, "number")],
                "Set",
            )
            if not self.main.run_dialog(dialog):
                return
            value = dialog.values()["value"]
        self._act(
            "value", lambda: self._do(DS.set_value_step(project, row, what, value))
        )

    def _row_menu(self, pos):
        item = self.table.itemAt(pos)
        if item is None:
            return
        row = self._row(item.data(QtCore.Qt.ItemDataRole.UserRole))
        menu = QtWidgets.QMenu(self)
        entries = []
        if not row.reference:
            entries.append(
                (
                    "Make reference",
                    lambda: self._do(DS.set_reference_step(self.session.project, row)),
                )
            )
        entries += [
            ("Rename…", lambda: self.rename_row(row)),
            ("Column roles…", lambda: self.column_roles(row)),
            ("Remove…", lambda: self.remove_row(row)),
        ]
        for text, handler in entries:
            menu.addAction(text, lambda h=handler, t=text: self._act(t, h))
        menu.exec(self.table.viewport().mapToGlobal(pos))

    def rename_row(self, row):
        """Rename… a dataset."""
        dialog = D.AskDialog(
            "Rename the dataset", [("name", "Name", row.name, "text")], "Rename"
        )
        if self.main.run_dialog(dialog):
            self._do(
                DS.rename_row_step(self.session.project, row, dialog.values()["name"])
            )

    def column_roles(self, row):
        """
        Column roles… (Q4.14): Stage 3's dialog for the row's source; the roles change
        only while the row has no snips.

        Generated by RJC and Claude.
        """
        project = self.session.project
        if row.source is None:
            self.main.tell(
                "Column roles", "{0} has no source spectrum.".format(row.name)
            )
            return
        where = SR.location(row.source, self.session.path)
        dialog = D.SpectrumDialog(
            "",
            entry={"path": where, "fwhm": 7.0, "roles": row.columns},
            parent=self,
        )
        dialog.setWindowTitle("Column roles · " + row.name)
        dialog.fwhm.setEnabled(False)
        if row.snips:
            dialog.columns.setEnabled(False)
            dialog.error.setText(
                "Its snips were cut with these roles; CLEAR them on the Regions tab"
                " before changing the roles."
            )
        if not self.main.run_dialog(dialog) or row.snips:
            return
        self._do(DS.columns_step(project, row, dialog.entry()["roles"]))

    def remove_row(self, row):
        """Remove… a dataset, after listing the lines it changes (S27)."""
        project = self.session.project
        plan = R.plan_dataset(project, row)
        dialog = D.PlanDialog("Remove a dataset", plan, self._gate(), "Remove")
        if self.main.run_dialog(dialog):
            self._do(plan.step(project))

    def _add_file(self):
        """Add file… (S3): Stage 3's spectrum dialog, then a new row."""
        dialog = D.SpectrumDialog("", self.main.prefs["new_project.fwhm"], parent=self)
        if not self.main.run_dialog(dialog):
            return
        entry = dialog.entry()
        self._do(
            DS.add_file_step(
                self.session.project,
                entry["path"],
                entry["roles"],
                entry["fwhm"],
                self.session.path,
            )
        )


__all__ = ["DataTab", "IdentifyPanel"]
