"""The ``.mod`` panel: the model text, as the blinding gate shows it, and typed in.

Dashboard Stage 3.6 (D5, D7, F2, F5, F8, S16; Q3.5). The panel is on every tab, and
collapses to a strip at the right.

- **What it shows.** ``Gate.view()``: hidden values are masked (``▒▒▒▒``). Each line has
  its number and is coloured by its kind (comments, block markers, settings, data
  lines, functions, labels). The current line is highlighted, and so are the lines of
  the item selected in a tab (``project.lines_of``).
- **Typing.** The editor's own undo is off. Each key becomes a patch of the real text
  (:class:`~alis.dashboard.livetext.LiveText`); after a pause (0.3 s) the patches go to
  the history as typing, grouped by pause (F2), the project reads the text again, and
  the panel is redrawn from the gate, keeping the cursor's line and column. An edit
  inside a mask asks for the new value in a small box; it stays hidden. An edit that
  would show a hidden value is refused (Q3.14).
- **Problems** (F5). ``validate.quick`` runs after each reading, ``validate.full``
  after a longer pause (2 s) in a worker thread; a full check made stale by more
  typing is dropped. Problems are marked beside their lines and listed below, through
  the gate.
- **Cross-highlighting** (S16). Moving the cursor to a line says what it describes
  (``project.items_at``).
- **The text is authoritative** (D7): the panel always works, even while the text does
  not read (QF.3).

Generated by RJC and Claude.
"""

import re

from qtpy import QtCore, QtGui, QtWidgets

from alis.dashboard import blinding as BL
from alis.dashboard import livetext as L
from alis.dashboard import project as P
from alis.dashboard import text as T
from alis.dashboard import validate as V
from alis.dashboard.qt import style as S
from alis.dashboard.qt import widgets as W

# A value with its label, or a mask with its label
_LABEL = re.compile(
    r"(?<![\w.])(?<!ion=)(?:[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]\d+)?|▒+)([A-Za-z_]\w*)"
)
_MASK = re.compile("▒+")
_FIRST_WORD = re.compile(r"\S+")


def describe_items(items):
    """
    What a line describes, in words with no values (for the panel's footer).

    Generated by RJC and Claude.
    """
    words = []
    for item in items:
        if isinstance(item, P.Snip):
            words.append("snip " + item.specid)
        elif isinstance(item, P.Row):
            words.append("file row " + item.name)
        elif isinstance(item, P.Component):
            ions = ", ".join(P.ion_name(i) for i in item.ions[:3])
            words.append("component {0} ({1})".format(item.id, ions))
        elif isinstance(item, P.System):
            words.append("system " + item.id)
    return "; ".join(words)


# -- Colours -------------------------------------------------------------------------


def _format(colour, bold=False, italic=False):
    fmt = QtGui.QTextCharFormat()
    fmt.setForeground(QtGui.QColor(colour))
    if bold:
        fmt.setFontWeight(QtGui.QFont.Weight.Bold)
    if italic:
        fmt.setFontItalic(True)
    return fmt


class ModHighlighter(QtGui.QSyntaxHighlighter):
    """
    Colours each line of the ``.mod`` panel by its kind, and labels and masks.

    Generated by RJC and Claude.
    """

    def __init__(self, document):
        super().__init__(document)
        self.kinds = []
        colours = S.TEXT_COLOURS
        self.formats = {
            T.COMMENT: _format(colours["comment"], italic=True),
            T.LONG: _format(colours["comment"], italic=True),
            T.HIDDEN: _format(colours["comment"], italic=True),
            T.BLOCK: _format(colours["block"], bold=True),
            T.SECTION: _format(colours["block"], bold=True),
            T.SETTING: _format(colours["setting"]),
            T.DATA: _format(colours["data"]),
            T.FIX: _format(colours["label"]),
            T.LIM: _format(colours["label"]),
        }
        self.function = _format(colours["function"], bold=True)
        self.label = _format(colours["label"])
        self.mask = _format(colours["mask"])

    def set_kinds(self, kinds):
        """The kind of each line, from the text as last read."""
        self.kinds = list(kinds)
        self.rehighlight()

    def highlightBlock(self, text):
        """Colour one line."""
        num = self.currentBlock().blockNumber()
        kind = self.kinds[num] if num < len(self.kinds) else None
        if kind in self.formats:
            self.setFormat(0, len(text), self.formats[kind])
        if kind == T.FUNCTION:
            first = _FIRST_WORD.search(text)
            if first is not None:
                self.setFormat(
                    first.start(), first.end() - first.start(), self.function
                )
        if kind in (T.FUNCTION, T.DATA, T.LIM, T.FIX):
            for match in _LABEL.finditer(text):
                self.setFormat(
                    match.start(1), match.end(1) - match.start(1), self.label
                )
        for match in _MASK.finditer(text):
            self.setFormat(match.start(), match.end() - match.start(), self.mask)


# -- The editor ----------------------------------------------------------------------


class _Gutter(QtWidgets.QWidget):
    """The line numbers, and the problems' marks, beside the text."""

    def __init__(self, editor):
        super().__init__(editor)
        self.editor = editor

    def sizeHint(self):
        return QtCore.QSize(self.editor.gutter_width(), 0)

    def paintEvent(self, event):
        self.editor.paint_gutter(event)


class ModEditor(QtWidgets.QPlainTextEdit):
    """
    The text of the ``.mod`` panel, with a gutter of line numbers and problem marks.

    Its own undo is off: undo and redo are the history's (F2), so their shortcuts
    are left to the window's actions.

    Generated by RJC and Claude.
    """

    blindLineRequested = QtCore.Signal(int)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("modText")
        self.setUndoRedoEnabled(False)
        self.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.setFont(S.mono_font())
        self.setTabChangesFocus(False)
        self.marks = {}
        self.panel_actions = []
        self.icons = {sev: S.problem_icon(sev) for sev in S.SEVERITY_ICONS}
        self.can_blind = lambda line: False
        self.gutter = _Gutter(self)
        self.blockCountChanged.connect(self._update_width)
        self.updateRequest.connect(self._update_gutter)
        self._update_width()

    def event(self, event):
        """Leave undo and redo to the window (the history's)."""
        if event.type() == QtCore.QEvent.Type.ShortcutOverride and (
            event.matches(QtGui.QKeySequence.StandardKey.Undo)
            or event.matches(QtGui.QKeySequence.StandardKey.Redo)
        ):
            event.ignore()
            return False
        return super().event(event)

    def keyPressEvent(self, event):
        """Undo and redo keys are not the editor's (its own undo is off)."""
        if event.matches(QtGui.QKeySequence.StandardKey.Undo) or event.matches(
            QtGui.QKeySequence.StandardKey.Redo
        ):
            event.ignore()
            return
        super().keyPressEvent(event)

    # -- the gutter ---------------------------------------------------------------

    def gutter_width(self):
        """Room for the line numbers and a mark."""
        digits = max(3, len(str(self.blockCount())))
        return 22 + self.fontMetrics().horizontalAdvance("9") * digits

    def _update_width(self, *args):
        self.setViewportMargins(self.gutter_width(), 0, 0, 0)

    def _update_gutter(self, rect, dy):
        if dy:
            self.gutter.scroll(0, dy)
        else:
            self.gutter.update(0, rect.y(), self.gutter.width(), rect.height())

    def resizeEvent(self, event):
        super().resizeEvent(event)
        rect = self.contentsRect()
        self.gutter.setGeometry(
            QtCore.QRect(rect.left(), rect.top(), self.gutter_width(), rect.height())
        )

    def paint_gutter(self, event):
        """Draw the line numbers, and a mark beside each line with a problem."""
        painter = QtGui.QPainter(self.gutter)
        painter.fillRect(event.rect(), QtGui.QColor("#f3f3f3"))
        block = self.firstVisibleBlock()
        num = block.blockNumber()
        top = round(
            self.blockBoundingGeometry(block).translated(self.contentOffset()).top()
        )
        height = round(self.blockBoundingRect(block).height())
        width = self.gutter.width()
        painter.setPen(QtGui.QColor("#8a8a8a"))
        while block.isValid() and top <= event.rect().bottom():
            if block.isVisible() and top + height >= event.rect().top():
                painter.drawText(
                    0,
                    top,
                    width - 18,
                    height,
                    QtCore.Qt.AlignmentFlag.AlignRight,
                    str(num + 1),
                )
                severity = self.marks.get(num)
                if severity is not None:
                    side = min(12, height - 2)
                    self.icons[severity].paint(
                        painter,
                        QtCore.QRect(
                            width - 15, top + (height - side) // 2, side, side
                        ),
                    )
            block = block.next()
            top += height
            height = round(self.blockBoundingRect(block).height())
            num += 1
        painter.end()

    def set_marks(self, marks):
        """The problems' marks: line to ``"error"`` or ``"warning"``."""
        self.marks = dict(marks)
        self.gutter.update()

    # -- the context menu ---------------------------------------------------------

    def contextMenuEvent(self, event):
        """The editor's menu, with "Blind this line" for a model line (Q3.13)."""
        menu = self.createStandardContextMenu()
        for action in list(menu.actions()):
            if action.text().replace("&", "").startswith(("Undo", "Redo")):
                menu.removeAction(action)
        line = self.cursorForPosition(event.pos()).blockNumber()
        menu.addSeparator()
        for action in self.panel_actions:
            menu.addAction(action)
        blind = menu.addAction("Blind this line")
        blind.setEnabled(bool(self.can_blind(line)))
        blind.triggered.connect(lambda: self.blindLineRequested.emit(line))
        menu.exec(event.globalPos())


# -- The full check, in a worker thread ----------------------------------------------


class _Relay(QtCore.QObject):
    """Carries a full check's result back to the panel's thread."""

    done = QtCore.Signal(int, object)


class _FullCheck(QtCore.QRunnable):
    """ALIS's own check of the model (``validate.full``), off the window's thread."""

    def __init__(self, generation, text, data, registry, parsed, relay):
        super().__init__()
        self.args = (text, data, registry, parsed)
        self.generation = generation
        self.relay = relay

    def run(self):
        try:
            problems = V.full(*self.args)
        except Exception as error:  # an error of the dashboard itself
            problems = [V.unexpected(error)]
        self.relay.done.emit(self.generation, problems)


# -- The panel -----------------------------------------------------------------------


class ModPanel(QtWidgets.QWidget):
    """
    The ``.mod`` panel of a session.

    Signals
    -------
    changed : the project changed (a reading after typing, or a value typed in the
        box); the window refreshes the tabs, the markers and the status bar.
    typing : the first key since the last reading (Undo applies to it).
    itemsAtCursor(list) : what the cursor's line describes (S16).
    hideRequested : "◂ Hide" was pressed.
    windowRequested : "⧉ Own window" (or "↩ Back to the dashboard") was pressed.
    blindLineRequested(int) : "Blind this line" was chosen.
    refused(str) : an edit was refused (it would show a hidden value).

    Generated by RJC and Claude.
    """

    changed = QtCore.Signal()
    typing = QtCore.Signal()
    itemsAtCursor = QtCore.Signal(list)
    hideRequested = QtCore.Signal()
    windowRequested = QtCore.Signal()
    blindLineRequested = QtCore.Signal(int)
    refused = QtCore.Signal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.session = None
        self.live = None
        self.problems = []
        self.quick = []
        self._updating = False
        self._generation = 0
        self._selected = []
        self._cursor_line = -1
        self._drawn = None
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        header = QtWidgets.QFrame()
        header.setObjectName("modHeader")
        row = QtWidgets.QHBoxLayout(header)
        row.setContentsMargins(8, 4, 6, 4)
        self.name = QtWidgets.QLabel("")
        self.name.setObjectName("paneTitle")

        self.state = W.ElidedLabel("")
        self.state.setObjectName("muted")
        # The state may be cut short (the status bar also gives it), so that the
        # panel can be made narrow
        self.state.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred
        )
        self.state.setMinimumWidth(20)
        self.hide_button = QtWidgets.QToolButton()
        self.hide_button.setText("◂ Hide")
        self.hide_button.setToolTip("Hide the .mod panel")
        self.hide_button.clicked.connect(self.hideRequested.emit)
        self.window_button = QtWidgets.QToolButton()
        self.window_button.clicked.connect(self.windowRequested.emit)
        self.set_window_mode(False)
        row.addWidget(self.name)
        row.addWidget(self.state, 1)
        # The panel's own actions (Align columns) go here, before the window's
        self.header_row = row
        self.panel_buttons = []
        row.addWidget(self.window_button)
        row.addWidget(self.hide_button)
        layout.addWidget(header)
        self.editor = ModEditor()
        self.editor.can_blind = self._can_blind
        self.editor.blindLineRequested.connect(self.blindLineRequested.emit)
        self.highlighter = ModHighlighter(self.editor.document())
        layout.addWidget(self.editor, 1)
        self.list = QtWidgets.QListWidget()
        self.list.setObjectName("problems")
        self.list.setMaximumHeight(110)
        self.list.itemActivated.connect(self._go_to_problem)
        self.list.itemClicked.connect(self._go_to_problem)
        layout.addWidget(self.list)
        self.footer = QtWidgets.QLabel("")
        self.footer.setObjectName("muted")
        self.footer.setContentsMargins(8, 2, 8, 3)
        layout.addWidget(self.footer)
        self.read_timer = QtCore.QTimer(self)
        self.read_timer.setSingleShot(True)
        self.read_timer.timeout.connect(self.flush)
        self.check_timer = QtCore.QTimer(self)
        self.check_timer.setSingleShot(True)
        self.check_timer.timeout.connect(self.start_full_check)
        self.relay = _Relay()
        self.relay.done.connect(self._full_done)
        self.editor.textChanged.connect(self._typed)
        self.editor.cursorPositionChanged.connect(self._cursor_moved)

    def set_panel_actions(self, actions):
        """
        The panel's own actions (Align columns): a button each in its header, and an
        entry each in its right-click menu.

        Generated by RJC and Claude.
        """
        for action in actions:
            button = QtWidgets.QToolButton()
            button.setDefaultAction(action)
            self.header_row.insertWidget(
                self.header_row.indexOf(self.window_button), button
            )
            self.panel_buttons.append(button)
        self.editor.panel_actions = list(actions)

    def set_window_mode(self, own):
        """The header's button, for a panel in its own window or in the dashboard."""
        if own:
            self.window_button.setText("↩ Back to the dashboard")
            self.window_button.setToolTip("Put the .mod panel back into the dashboard")
        else:
            self.window_button.setText("⧉ Own window")
            self.window_button.setToolTip(
                "Move the .mod panel to a window of its own; it keeps working with"
                " the dashboard"
            )
        self.hide_button.setVisible(not own)

    # -- the session --------------------------------------------------------------

    def set_session(self, session, prefs=None):
        """
        Show a session's model.

        Generated by RJC and Claude.
        """
        self.session = session
        if prefs is not None:
            self.read_timer.setInterval(int(prefs["editor.read_delay"] * 1000))
            self.check_timer.setInterval(int(prefs["editor.check_delay"] * 1000))
        else:
            self.read_timer.setInterval(300)
            self.check_timer.setInterval(2000)
        self._generation += 1
        self.problems, self.quick = [], []
        self._selected = []
        self._cursor_line = -1
        self.footer.setText("")
        if session is None:
            self.live = None
            self._set_text("")
            self.name.setText("")
            return
        self.name.setText(session.project.bundle.model_name)
        self.redraw(keep_cursor=False)
        self.check_now()

    @property
    def project(self):
        return self.session.project if self.session is not None else None

    def gate(self):
        """The project's blinding gate."""
        return BL.Gate(self.project)

    # -- drawing ------------------------------------------------------------------

    def _set_text(self, text, line=0, column=0, scroll=None):
        """Put text in the editor without it counting as typing."""
        self._updating = True
        try:
            if self.editor.toPlainText() != text:
                self.editor.setPlainText(text)
            cursor = self.editor.textCursor()
            cursor.setPosition(L.offset(text, line, column))
            self.editor.setTextCursor(cursor)
            if scroll is not None:
                self.editor.verticalScrollBar().setValue(scroll)
        finally:
            self._updating = False

    def redraw(self, keep_cursor=True):
        """
        Draw the text again from the gate, keeping the cursor's line and column.

        Generated by RJC and Claude.
        """
        if self.session is None:
            return
        line = column = 0
        scroll = None
        if keep_cursor and self.live is not None:
            cursor = self.editor.textCursor()
            line, column = cursor.blockNumber(), cursor.positionInBlock()
            scroll = self.editor.verticalScrollBar().value()
        self.live = L.LiveText(self.gate().view())
        self._drawn = self._key()
        kinds = [ln.kind for ln in self.project.parsed.text.lines]
        self.highlighter.kinds = kinds
        self._set_text(self.live.shown, line, column, scroll)
        self.highlighter.rehighlight()
        self._show_problems()
        self._highlight_lines()

    def _key(self):
        """What the panel's text is drawn from: the text and its hidden lines."""
        project = self.project
        return project.text, tuple(project.hidden_lines())

    def sync(self):
        """
        Redraw when the project has changed since the panel was drawn: a step made by
        a panel, undo or redo (not while there is typing to read).

        Returns
        -------
        bool
            Whether the panel was redrawn.

        Generated by RJC and Claude.
        """
        if self.session is None or (self.live is not None and self.live.dirty):
            return False
        if self._key() == self._drawn:
            return False
        self.redraw()
        self.check_now(full_later=True)
        return True

    # -- typing -------------------------------------------------------------------

    def _typed(self):
        """A key in the editor: follow it in the real text."""
        if self._updating or self.live is None:
            return
        cursor = self.editor.textCursor().position()
        result = self.live.edit(self.editor.toPlainText(), cursor)
        if result is None:
            return
        if isinstance(result, L.MaskEdit):
            # Put the panel's text back, and ask for the value
            self._set_text(self.live.shown, *L.position(self.live.shown, result.start))
            value = self.ask_hidden_value(result.typed)
            if value is None:
                return
            self.live.replace_masked(result.start, result.end, value)
            self.flush()
            return
        self.state.setText("Typing…")
        self._generation += 1
        self.read_timer.start()
        self.check_timer.stop()
        if len(self.live.patches) == 1:
            self.typing.emit()

    def ask_hidden_value(self, typed):
        """
        Ask for the new value of a hidden parameter (QF.20(c)). The user sees only
        what they type, and it is hidden once entered.

        Returns
        -------
        str or None
            None when cancelled.

        Generated by RJC and Claude.
        """
        value, ok = QtWidgets.QInputDialog.getText(
            self,
            "A hidden value",
            "The new value of this hidden parameter.\n"
            "It stays hidden once it is entered.",
            QtWidgets.QLineEdit.EchoMode.Normal,
            typed,
        )
        value = value.strip()
        return value if ok and value else None

    def flush(self):
        """
        Give the history what was typed since the last reading, as typing; the
        project reads the text again, and the panel is redrawn from the gate.

        Returns
        -------
        bool
            Whether anything was given.

        Generated by RJC and Claude.
        """
        self.read_timer.stop()
        if self.live is None or not self.live.dirty:
            return False
        change = self.live.pending()
        try:
            self.session.history.type(change)
        except BL.RevealError as error:
            self.redraw()
            self.refused.emit(str(error))
            self.check_now()
            return False
        self.redraw()
        self.check_now(full_later=True)
        self.changed.emit()
        return True

    # -- problems -----------------------------------------------------------------

    def check_now(self, full_later=False):
        """
        The quick check now, and the full check after the pause (or now).

        Generated by RJC and Claude.
        """
        if self.session is None:
            return
        project = self.project
        try:
            self.quick = V.quick(project.parsed, project.data_for_run())
        except Exception as error:
            self.quick = [V.unexpected(error)]
        self._generation += 1
        self.problems = list(self.quick)
        self._show_problems()
        if full_later:
            self.check_timer.start()
        else:
            self.start_full_check()

    def start_full_check(self):
        """
        Start ALIS's own check of the model in a worker thread (F5). Its result is
        dropped if the text changes meanwhile.

        Generated by RJC and Claude.
        """
        if self.session is None or self.live is None or self.live.dirty:
            return
        project = self.project
        if project.paused or any(p.severity == V.ERROR for p in self.quick):
            return
        job = _FullCheck(
            self._generation,
            project.text,
            project.data_for_run(),
            project.registry,
            project.parsed,
            self.relay,
        )
        self.state.setText("Checking…")
        QtCore.QThreadPool.globalInstance().start(job)

    def _full_done(self, generation, problems):
        """A full check's result: dropped if the text has changed since it began."""
        if generation != self._generation or self.session is None:
            return
        self.problems = V.order(list(self.quick) + list(problems))
        self._show_problems()
        self.changed.emit()

    def _show_problems(self):
        """Mark the problems beside their lines, and list them, through the gate."""
        if self.session is None:
            return
        gate = self.gate()
        shown = [gate.problem(p) for p in self.problems]
        marks = {}
        for prob in shown:
            if prob.line is not None and marks.get(prob.line) != V.ERROR:
                marks[prob.line] = prob.severity
        self.editor.set_marks(marks)
        self.list.clear()
        for prob in shown:
            where = "Line {0}: ".format(prob.line + 1) if prob.line is not None else ""
            item = QtWidgets.QListWidgetItem(
                S.problem_icon(prob.severity), where + prob.message
            )
            item.setData(QtCore.Qt.ItemDataRole.UserRole, prob.line)
            item.setToolTip(prob.message)
            self.list.addItem(item)
        self.list.setVisible(bool(shown))
        self.state.setText(self.state_text())

    def state_text(self):
        """
        The state of the model, for the panel's header and the status bar.

        Generated by RJC and Claude.
        """
        if self.session is None:
            return ""
        if self.project.paused:
            return "The model does not read: the panels are paused"
        if not self.problems:
            return "✓ The model reads"
        errors = sum(p.severity == V.ERROR for p in self.problems)
        count = len(self.problems)
        text = "! {0} problem{1}".format(count, "" if count == 1 else "s")
        if errors:
            text += " ({0} error{1})".format(errors, "" if errors == 1 else "s")
        return text

    def _go_to_problem(self, item):
        line = item.data(QtCore.Qt.ItemDataRole.UserRole)
        if line is not None:
            self.go_to_line(line)

    def go_to_line(self, line):
        """Put the cursor at the start of a line, and show it."""
        block = self.editor.document().findBlockByNumber(line)
        if block.isValid():
            cursor = self.editor.textCursor()
            cursor.setPosition(block.position())
            self.editor.setTextCursor(cursor)
            self.editor.centerCursor()
            self.editor.setFocus()

    # -- highlighting -------------------------------------------------------------

    def _cursor_moved(self):
        """The current line, and what it describes (S16)."""
        self._highlight_lines()
        if self._updating or self.session is None:
            return
        line = self.editor.textCursor().blockNumber()
        if line == self._cursor_line:
            return
        self._cursor_line = line
        items = [] if self.project.paused else self.project.items_at(line)
        text = describe_items(items)
        self.footer.setText("Line {0}".format(line + 1) + (": " + text if text else ""))
        self.itemsAtCursor.emit(items)

    def select_items(self, items):
        """
        Highlight the lines of the items selected in a tab (S16).

        Generated by RJC and Claude.
        """
        lines = set()
        for item in items:
            lines.update(self.project.lines_of(item))
        self._selected = sorted(lines)
        self._highlight_lines()
        if self._selected:
            self.go_to_line(self._selected[0])

    def _highlight_lines(self):
        """The current line, and the selected item's lines."""
        selections = []
        doc = self.editor.document()
        for line in self._selected:
            block = doc.findBlockByNumber(line)
            if block.isValid():
                sel = QtWidgets.QTextEdit.ExtraSelection()
                sel.format.setBackground(QtGui.QColor(S.SELECTED_LINES))
                sel.format.setProperty(
                    QtGui.QTextFormat.Property.FullWidthSelection, True
                )
                sel.cursor = QtGui.QTextCursor(block)
                selections.append(sel)
        sel = QtWidgets.QTextEdit.ExtraSelection()
        sel.format.setBackground(QtGui.QColor(S.CURRENT_LINE))
        sel.format.setProperty(QtGui.QTextFormat.Property.FullWidthSelection, True)
        sel.cursor = self.editor.textCursor()
        sel.cursor.clearSelection()
        selections.append(sel)
        self.editor.setExtraSelections(selections)

    # -- blinding a line ----------------------------------------------------------

    def _can_blind(self, line):
        """Whether "Blind this line" applies: a model line not yet blind."""
        if self.session is None or self.project.paused:
            return False
        item = self.project.parsed.item_at(line)
        return (
            item is not None
            and hasattr(item, "function")
            and line not in self.project.hidden_lines()
        )


__all__ = ["ModPanel", "ModEditor", "ModHighlighter", "describe_items"]
