"""The spectrum view: one pyqtgraph widget for every spectrum of the dashboard.

Dashboard Stage 4.5 (D38, D43). The Data and Regions tabs (and the Fit tab later)
draw their spectra with :class:`SpectrumView`, controlled by a :class:`ZoomBar`:

- **The zoom bar** (D38, Stage 0's draft 6): ⌂ home, ← back, → forward, ✥ pan, ⬚ zoom
  box, and + / − (zoom along the wavelength axis only). The wheel zooms the wavelength
  axis. Each bar keeps its own history of zooms for ← and →; the views it controls
  share their wavelength axis.
- **Drawing:** the data as steps centred on the pixels, broken where the data have a
  gap; the error, thin and grey; the continuum, dashed; the zero line, dashed grey;
  bad pixels as grey crosses. Large spectra are downsampled (peak) and clipped to the
  view.
- **Overlays:** fit regions, regions fitted by another snip, pixels fitted twice
  (hatched), the snip's edges (orange handles), the continuum's knots, line IDs (ticks
  and labels, each kind with its colour and its line style), and a marker for a
  clicked point.
- **Modes:** pan, zoom box, draw (a drag gives a span), mask (a click or a drag gives a
  span), click (a click gives a point: Identify a feature).
- **Axes:** wavelength in Å below; above, when a centre is set, velocity in km/s,
  signed (+100, −100, 0; D43).

The view draws what it is given and reports what the user does with signals; it
changes nothing in the project. It shows no parameter value: the line IDs name
transitions, and a hidden value never reaches it.

Generated by RJC and Claude.
"""

import numpy as np
import pyqtgraph as pg
from qtpy import QtCore, QtGui, QtWidgets

from alis.dashboard.qt import style as ST

C_KMS = 299792.458
# A step between pixels of this many times the median step is a gap in the data
SPLIT = 5.0
# How much + and − zoom the wavelength axis, and the wheel's factor per notch
ZOOM_STEP = 2.0
PAN, ZOOM, DRAW, MASK, CLICK = "pan", "zoom", "draw", "mask", "click"

COLOURS = {
    "data": "#1b1b1b",
    "error": "#9a9a9a",
    "continuum": ST.OKABE_ITO["blue"],
    "zero": "#8a8a8a",
    "fit": (0, 158, 115, 90),
    "other": (86, 180, 233, 90),
    "shared": "#a8457f",
    "edge": ST.OKABE_ITO["orange"],
    "marker": ST.OKABE_ITO["blue"],
    "bad": "#8a8a8a",
    "selected": ST.OKABE_ITO["blue"],
    "knot": ST.OKABE_ITO["blue"],
    "drawing": (0, 114, 178, 60),
    "masking": (90, 90, 90, 70),
}
# The line IDs' colours and line styles, by kind (the key): every kind is told by
# its colour and by its line, so that no state rests on colour alone (D43)
LINE_ID_STYLE = {
    "hydrogen": ("#D55E00", "#b34e00", QtCore.Qt.PenStyle.SolidLine),
    "metal": ("#CC79A7", "#9c4a7c", QtCore.Qt.PenStyle.DashLine),
    "other": ("#8c8c8c", "#6f6f6f", QtCore.Qt.PenStyle.DotLine),
}


# -- What is drawn ----------------------------------------------------------------------


def gaps(wave, split=SPLIT):
    """
    The indices after which the data have a gap: a step of more than ``split`` times
    the median step.

    Generated by RJC and Claude.
    """
    wave = np.asarray(wave, dtype=float)
    if wave.size < 3:
        return np.zeros(0, dtype=int)
    step = np.diff(wave)
    median = np.median(step[step > 0]) if np.any(step > 0) else 0.0
    if median <= 0:
        return np.zeros(0, dtype=int)
    return np.flatnonzero(step > split * median)


def step_curve(wave, flux, split=SPLIT):
    """
    The data as steps centred on the pixels: two points per pixel, at the edges
    half way to its neighbours, with a break (NaN) at each gap.

    Returns
    -------
    tuple
        ``(x, y)``.

    Generated by RJC and Claude.
    """
    wave = np.asarray(wave, dtype=float)
    flux = np.asarray(flux, dtype=float)
    if wave.size == 0:
        return np.zeros(0), np.zeros(0)
    if wave.size == 1:
        return np.array([wave[0], wave[0]]), np.array([flux[0], flux[0]])
    step = np.diff(wave)
    breaks = gaps(wave, split)
    mid = 0.5 * (wave[1:] + wave[:-1])
    left = np.concatenate(([wave[0] - 0.5 * step[0]], mid))
    right = np.concatenate((mid, [wave[-1] + 0.5 * step[-1]]))
    # Either side of a gap, a pixel's edge is as far from it as its other edge
    for k in breaks:
        right[k] = wave[k] + (wave[k] - left[k])
        left[k + 1] = wave[k + 1] - (right[k + 1] - wave[k + 1])
    x = np.empty(2 * wave.size)
    y = np.empty(2 * wave.size)
    x[0::2], x[1::2] = left, right
    y[0::2], y[1::2] = flux, flux
    if breaks.size:
        at = 2 * breaks + 2
        x = np.insert(x, at, np.nan)
        y = np.insert(y, at, np.nan)
    return x, y


def broken_line(wave, values, split=SPLIT):
    """
    A line through the pixels, with a break (NaN) at each gap of the data.

    Generated by RJC and Claude.
    """
    wave = np.asarray(wave, dtype=float)
    values = np.asarray(values, dtype=float)
    breaks = gaps(wave, split)
    if not breaks.size:
        return wave, values
    return np.insert(wave, breaks + 1, np.nan), np.insert(values, breaks + 1, np.nan)


def nice_step(span, target=6):
    """A round step that gives about ``target`` ticks over ``span``."""
    if span <= 0:
        return 1.0
    raw = span / target
    power = 10.0 ** np.floor(np.log10(raw))
    for factor in (1.0, 2.0, 2.5, 5.0, 10.0):
        if raw <= factor * power:
            return factor * power
    return 10.0 * power


def signed(value):
    """
    A velocity tick, signed (D43): ``+100``, ``−100``, ``0``.

    Generated by RJC and Claude.
    """
    if abs(value) < 1e-9:
        return "0"
    text = "{0:g}".format(abs(value))
    return ("+" if value > 0 else "−") + text


# -- The axes and the view box --------------------------------------------------------


class VelocityAxis(pg.AxisItem):
    """
    The top axis: velocity relative to a centre wavelength, in km/s, signed.

    Generated by RJC and Claude.
    """

    def __init__(self, *args, **kwargs):
        super().__init__("top", *args, **kwargs)
        self.centre = None

    def tickValues(self, minVal, maxVal, size):
        """Round velocities, placed at their wavelengths."""
        if self.centre is None or not np.isfinite(minVal) or not np.isfinite(maxVal):
            return []
        vlo = C_KMS * (minVal / self.centre - 1.0)
        vhi = C_KMS * (maxVal / self.centre - 1.0)
        step = nice_step(vhi - vlo, max(int(size / 90), 2))
        first = np.ceil(vlo / step) * step
        vels = np.arange(first, vhi + 0.5 * step, step)
        return [(step, list(self.centre * (1.0 + vels / C_KMS)))]

    def tickStrings(self, values, scale, spacing):
        """Each tick's velocity, signed."""
        if self.centre is None:
            return ["" for _ in values]
        return [signed(round(C_KMS * (v / self.centre - 1.0), 6)) for v in values]


class SpectrumBox(pg.ViewBox):
    """
    The view box: the wheel zooms the wavelength axis only; a drag pans, zooms to a
    box, or gives a span (draw, mask); a click gives a point.

    Generated by RJC and Claude.
    """

    clicked = QtCore.Signal(float, float)
    rightClicked = QtCore.Signal(float, float, object)
    spanned = QtCore.Signal(str, float, float, bool)
    userChanged = QtCore.Signal()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.mode = PAN
        self._span = None
        self.setMouseMode(pg.ViewBox.PanMode)

    def set_mode(self, mode):
        """Pan, zoom box, draw, mask or click."""
        self.mode = mode
        self.setMouseMode(pg.ViewBox.RectMode if mode == ZOOM else pg.ViewBox.PanMode)

    def wheelEvent(self, ev, axis=None):
        """Zoom the wavelength axis only (D38)."""
        super().wheelEvent(ev, axis=0)
        self.userChanged.emit()

    def mouseClickEvent(self, ev):
        """A left click gives its point; other clicks as pyqtgraph has them."""
        if ev.button() == QtCore.Qt.MouseButton.LeftButton:
            pos = self.mapSceneToView(ev.scenePos())
            ev.accept()
            if self.mode == MASK:
                self.spanned.emit(MASK, pos.x(), pos.x(), True)
            self.clicked.emit(pos.x(), pos.y())
            return
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            pos = self.mapSceneToView(ev.scenePos())
            ev.accept()
            self.rightClicked.emit(pos.x(), pos.y(), ev.screenPos())
            return
        super().mouseClickEvent(ev)

    def mouseDragEvent(self, ev, axis=None):
        """
        Draw and mask take a span: in draw mode a left drag draws and a right drag
        masks (as ``prepfit`` does), in mask mode a left drag masks; pan and zoom box
        as pyqtgraph does them.

        Generated by RJC and Claude.
        """
        button = ev.button()
        kind = None
        if self.mode == DRAW and button == QtCore.Qt.MouseButton.LeftButton:
            kind = DRAW
        elif self.mode == DRAW and button == QtCore.Qt.MouseButton.RightButton:
            kind = MASK
        elif self.mode == MASK and button == QtCore.Qt.MouseButton.LeftButton:
            kind = MASK
        if kind is not None:
            ev.accept()
            start = self.mapSceneToView(ev.buttonDownScenePos()).x()
            here = self.mapSceneToView(ev.scenePos()).x()
            low, high = sorted((start, here))
            if self._span is None:
                colour = COLOURS["drawing" if kind == DRAW else "masking"]
                self._span = pg.LinearRegionItem(
                    (low, high), movable=False, brush=pg.mkBrush(*colour)
                )
                self.addItem(self._span, ignoreBounds=True)
            self._span.setRegion((low, high))
            if ev.isFinish():
                self.removeItem(self._span)
                self._span = None
                self.spanned.emit(kind, low, high, True)
            return
        super().mouseDragEvent(ev, axis)
        if ev.isFinish():
            self.userChanged.emit()


# -- The view -----------------------------------------------------------------------------


class SpectrumView(pg.PlotWidget):
    """
    One spectrum, with its overlays.

    Signals
    -------
    clicked(x, y)
        A click, in data coordinates (Identify a feature).
    spanned(mode, low, high)
        A span drawn in draw or mask mode (a click in mask mode is a span of one
        point).
    edgeMoved(side, x, finished)
        A snip edge dragged: ``"low"`` or ``"high"``.
    regionMoved(index, low, high)
        A fit region's edges dragged (when they are movable).
    knotMoved(index, x, y)
        A knot dragged, when the drag ends.

    Generated by RJC and Claude.
    """

    clicked = QtCore.Signal(float, float)
    contextRequested = QtCore.Signal(float, float, object)
    spanned = QtCore.Signal(str, float, float)
    edgeMoved = QtCore.Signal(str, float, bool)
    regionMoved = QtCore.Signal(int, float, float)
    knotMoved = QtCore.Signal(int, float, float)

    def __init__(self, parent=None):
        self.box = SpectrumBox()
        self.top = VelocityAxis()
        super().__init__(parent, viewBox=self.box, axisItems={"top": self.top})
        self.setBackground(ST.GREY["base"])
        item = self.getPlotItem()
        item.showAxis("top", False)
        item.setLabel("bottom", "Wavelength (Å)")
        item.setLabel("left", "Flux")
        item.hideButtons()
        item.setMenuEnabled(False)
        for name in ("left", "bottom", "top"):
            axis = item.getAxis(name)
            axis.setPen(pg.mkPen("#7a7a7a"))
            axis.setTextPen(pg.mkPen(ST.GREY["text"]))
            # The values as they are: no "(x0.001)" in the axis's title
            axis.enableAutoSIPrefix(False)
        self.box.setAutoVisible(y=True)
        self.box.clicked.connect(self.clicked)
        self.box.rightClicked.connect(self.contextRequested)
        self.box.spanned.connect(lambda mode, a, b, _f: self.spanned.emit(mode, a, b))
        self._items = {}
        self._lists = {}
        self._ids = []
        self._wave = None
        self._home = None
        self.log = False
        self.zero = pg.InfiniteLine(
            0.0,
            angle=0,
            pen=pg.mkPen(COLOURS["zero"], width=1, style=QtCore.Qt.PenStyle.DashLine),
        )
        self.addItem(self.zero, ignoreBounds=True)
        self.box.sigYRangeChanged.connect(self._place_ids)
        self.box.sigXRangeChanged.connect(self._place_ids)

    # -- the data -----------------------------------------------------------------------

    def _curve(self, key, x, y, pen, connect="finite"):
        old = self._items.pop(key, None)
        if old is not None:
            self.removeItem(old)
        if x is None:
            return None
        item = pg.PlotDataItem(x, y, pen=pen, connect=connect)
        self.addItem(item)
        item.setDownsampling(auto=True, method="peak")
        item.setClipToView(True)
        self._items[key] = item
        return item

    def set_data(self, wave, flux, error=None, bad=None):
        """
        Draw a spectrum: the data as steps, the error thin and grey, and its bad
        pixels as grey crosses.

        Parameters
        ----------
        wave, flux : array
        error : array, optional
        bad : array of bool, optional

        Generated by RJC and Claude.
        """
        for key in [k for k in self._items if k.startswith("piece")]:
            self.removeItem(self._items.pop(key))
        wave = np.asarray(wave, dtype=float)
        flux = np.asarray(flux, dtype=float)
        self._wave = wave
        self._flux = flux
        self._error = None if error is None else np.asarray(error, dtype=float)
        self._bad = None if bad is None else np.asarray(bad, dtype=bool)
        self._redraw_data()

    def _redraw_data(self):
        wave, flux = self._wave, getattr(self, "_flux", None)
        if wave is None or flux is None:
            return
        scale = self._norm if getattr(self, "_norm", None) is not None else None
        shown = flux / scale if scale is not None else flux
        x, y = step_curve(wave, shown)
        self._curve("data", x, y, pg.mkPen(COLOURS["data"], width=1))
        if self._error is not None:
            err = self._error / scale if scale is not None else self._error
            # An error of 0 or less marks a pixel that cannot be fitted (often a
            # huge negative sentinel): it is not drawn
            with np.errstate(invalid="ignore"):
                err = np.where(self._error > 0, err, np.nan)
            ex, ey = broken_line(wave, err)
            self._curve("error", ex, ey, pg.mkPen(COLOURS["error"], width=1))
        else:
            self._curve("error", None, None, None)
        old = self._items.pop("bad", None)
        if old is not None:
            self.removeItem(old)
        if self._bad is not None and self._bad.any():
            sel = self._bad & np.isfinite(shown)
            item = pg.ScatterPlotItem(
                wave[sel],
                shown[sel],
                symbol="x",
                size=7,
                pen=pg.mkPen(COLOURS["bad"]),
                brush=None,
            )
            self.addItem(item)
            self._items["bad"] = item

    def set_context(self, wave=None, flux=None):
        """
        Draw the data around a snip faintly (its source beyond its edges), so that an
        edge can be dragged out over real data; None removes it.

        Generated by RJC and Claude.
        """
        if wave is None:
            self._curve("context", None, None, None)
            return
        x, y = step_curve(wave, flux)
        item = self._curve("context", x, y, pg.mkPen("#b9b9b9", width=1))
        item.setZValue(-5)

    def set_pieces(self, pieces):
        """
        Draw separate pieces of data, each as steps (a dataset's snips, when it has
        no source spectrum, each scaled to its own peak: D35).

        Parameters
        ----------
        pieces : list of (wave, flux)

        Generated by RJC and Claude.
        """
        for key in [k for k in self._items if k.startswith("piece")]:
            self.removeItem(self._items.pop(key))
        self._curve("data", None, None, None)
        self._curve("error", None, None, None)
        waves = []
        for num, (wave, flux) in enumerate(pieces):
            x, y = step_curve(wave, flux)
            self._curve(
                "piece{0}".format(num), x, y, pg.mkPen(COLOURS["data"], width=1)
            )
            waves.append(np.asarray(wave, dtype=float))
        self._wave = np.concatenate(waves) if waves else None
        self._flux, self._error, self._bad = None, None, None
        self._pieces_flux = (
            np.concatenate([np.asarray(f, dtype=float) for _, f in pieces])
            if pieces
            else None
        )

    def set_normalised(self, curve):
        """
        Draw the data divided by a continuum (S9), or as they are (None).

        Generated by RJC and Claude.
        """
        self._norm = None if curve is None else np.asarray(curve, dtype=float)
        self._redraw_data()
        cont = self._items.get("continuum")
        if cont is not None and getattr(self, "_cont", None) is not None:
            self.set_continuum(*self._cont)

    def set_continuum(self, wave, curve, style=QtCore.Qt.PenStyle.DashLine):
        """
        Draw a continuum, dashed, or remove it (``wave`` None).

        Generated by RJC and Claude.
        """
        if wave is None:
            self._cont = None
            self._curve("continuum", None, None, None)
            return
        self._cont = (wave, curve)
        curve = np.asarray(curve, dtype=float)
        norm = getattr(self, "_norm", None)
        if norm is not None and norm.size == curve.size:
            curve = curve / norm
        x, y = broken_line(wave, curve)
        self._curve(
            "continuum",
            x,
            y,
            pg.mkPen(COLOURS["continuum"], width=1.6, style=style),
        )

    def set_log(self, on):
        """Flux | Log: the flux axis linear or logarithmic."""
        self.log = bool(on)
        self.getPlotItem().setLogMode(y=self.log)
        self.zero.setVisible(not self.log)

    # -- overlays -----------------------------------------------------------------------

    def _clear_list(self, key):
        for item in self._lists.pop(key, []):
            self.removeItem(item)

    def set_regions(self, kind, spans, movable=False):
        """
        Shade wavelength spans: ``"fit"`` regions (green), ``"other"`` (fitted by
        another snip, light blue) or ``"shared"`` (fitted twice, hatched).

        Parameters
        ----------
        kind : str
        spans : list of (low, high)
        movable : bool
            Whether a fit region's edges can be dragged (``regionMoved``).

        Generated by RJC and Claude.
        """
        self._clear_list(kind)
        items = []
        for num, (low, high) in enumerate(spans):
            if kind == "shared":
                brush = QtGui.QBrush(
                    QtGui.QColor(COLOURS["shared"]), QtCore.Qt.BrushStyle.BDiagPattern
                )
            else:
                brush = pg.mkBrush(*COLOURS[kind])
            item = pg.LinearRegionItem(
                (low, high), movable=movable and kind == "fit", brush=brush
            )
            item.setZValue(-10)
            for line in item.lines:
                line.setPen(pg.mkPen(None) if not movable else pg.mkPen("#2f8f6f"))
            if movable and kind == "fit":
                item.sigRegionChangeFinished.connect(
                    lambda reg, n=num: self.regionMoved.emit(
                        n, *sorted(reg.getRegion())
                    )
                )
            self.addItem(item, ignoreBounds=True)
            items.append(item)
        self._lists[kind] = items

    def set_edges(self, low=None, high=None, movable=True):
        """
        The snip's edges, as orange handles (S6); None hides them.

        Generated by RJC and Claude.
        """
        self._clear_list("edges")
        if low is None or high is None:
            return
        items = []
        for side, pos in (("low", low), ("high", high)):
            line = pg.InfiniteLine(
                pos,
                angle=90,
                movable=movable,
                pen=pg.mkPen(COLOURS["edge"], width=3),
                hoverPen=pg.mkPen(COLOURS["edge"], width=5),
            )
            line.addMarker("<|>", position=0.5, size=12)
            line.sigPositionChanged.connect(
                lambda ln, s=side: self.edgeMoved.emit(s, ln.value(), False)
            )
            line.sigPositionChangeFinished.connect(
                lambda ln, s=side: self.edgeMoved.emit(s, ln.value(), True)
            )
            self.addItem(line, ignoreBounds=True)
            items.append(line)
        self._lists["edges"] = items

    def set_marker(self, x=None):
        """A marker at a clicked wavelength (Identify a feature), or none."""
        self._clear_list("marker")
        if x is None:
            return
        line = pg.InfiniteLine(
            x,
            angle=90,
            pen=pg.mkPen(
                COLOURS["marker"], width=1.4, style=QtCore.Qt.PenStyle.DashLine
            ),
        )
        self.addItem(line, ignoreBounds=True)
        self._lists["marker"] = [line]

    def set_knots(self, points, movable=True):
        """
        The continuum's knots (Q4.13), draggable when ``movable``.

        Generated by RJC and Claude.
        """
        self._clear_list("knots")
        items = []
        for num, (x, y) in enumerate(points):
            item = pg.TargetItem(
                (x, y),
                size=11,
                symbol="s",
                movable=movable,
                pen=pg.mkPen(COLOURS["knot"], width=2),
                brush=pg.mkBrush(255, 255, 255, 200),
            )
            item.sigPositionChangeFinished.connect(
                lambda it, n=num: self.knotMoved.emit(n, it.pos().x(), it.pos().y())
            )
            self.addItem(item, ignoreBounds=True)
            items.append(item)
        self._lists["knots"] = items

    def set_line_ids(self, ids, hidden=0):
        """
        The line IDs: a tick and a label for each, coloured and styled by kind; labels
        that would overlap go to a lower row, or are left out.

        Parameters
        ----------
        ids : list of (wavelength, label, kind)
        hidden : int
            The number of lines in the view not labelled (shown in the corner).

        Generated by RJC and Claude.
        """
        self._clear_list("ids")
        items = []
        self._ids = []
        for wave, label, kind in ids:
            colour, text_colour, style = LINE_ID_STYLE.get(kind, LINE_ID_STYLE["other"])
            tick = pg.PlotCurveItem(
                [wave, wave], [0.0, 1.0], pen=pg.mkPen(colour, width=1.2, style=style)
            )
            text = pg.TextItem(label, color=text_colour, anchor=(0.5, 1.0))
            font = QtGui.QFont(ST.ui_font())
            font.setPixelSize(10)
            text.setFont(font)
            self.addItem(tick, ignoreBounds=True)
            self.addItem(text, ignoreBounds=True)
            items += [tick, text]
            self._ids.append((wave, tick, text))
        self.hidden_note = hidden
        note = self._lists.get("note")
        if note:
            for item in note:
                self.removeItem(item)
        self._lists["ids"] = items
        if hidden:
            label = pg.TextItem(
                "+ {0} line{1} not labelled".format(hidden, "" if hidden == 1 else "s"),
                color=ST.GREY["muted"],
                anchor=(1.0, 0.0),
            )
            self.addItem(label, ignoreBounds=True)
            self._lists["note"] = [label]
        self._place_ids()

    def _place_ids(self, *args):
        """Put the line IDs at the top of the view, three rows, no overlaps."""
        if not self._ids and not self._lists.get("note"):
            return
        (x0, x1), (y0, y1) = self.box.viewRange()
        if self.log:
            y0, y1 = 10.0**y0, 10.0**y1
        height = y1 - y0
        width = max(self.box.width(), 1.0)
        per_pixel = (x1 - x0) / width
        ends = [-np.inf, -np.inf, -np.inf]
        for wave, tick, text in sorted(self._ids, key=lambda t: t[0]):
            top = y1 - 0.02 * height
            tick.setData([wave, wave], [top - 0.10 * height, top - 0.04 * height])
            half = 3.2 * len(text.toPlainText()) * per_pixel
            placed = False
            for row, end in enumerate(ends):
                if wave - half > end:
                    ends[row] = wave + half
                    text.setPos(wave, top - 0.11 * height - row * 0.07 * height)
                    text.setVisible(x0 <= wave <= x1)
                    placed = True
                    break
            if not placed:
                text.setVisible(False)
        for note in self._lists.get("note", []):
            note.setPos(x1, y1)

    def set_velocity_centre(self, wave=None):
        """
        Show the velocity axis above, relative to an observed wavelength (D43), or
        hide it (None).

        Generated by RJC and Claude.
        """
        self.top.centre = wave
        self.getPlotItem().showAxis("top", wave is not None)
        if wave is not None:
            self.getPlotItem().setLabel("top", "Velocity (km/s)")
        self.top.picture = None
        self.top.update()

    def set_labels(self, top=True, bottom=True):
        """
        Show or hide the axes' titles (their ticks stay): spectra stacked one above
        another name the velocity once at the top and the wavelength once below.

        Generated by RJC and Claude.
        """
        item = self.getPlotItem()
        item.setLabel("bottom", "Wavelength (Å)" if bottom else None)
        if self.top.centre is not None:
            item.setLabel("top", "Velocity (km/s)" if top else None)

    # -- the view range -----------------------------------------------------------------

    def set_home(self, xrange=None, yrange=None):
        """
        Where ⌂ returns: a wavelength range (and a flux range), or the whole data.

        Generated by RJC and Claude.
        """
        self._home = (xrange, yrange)

    def home(self):
        """Show the home range."""
        xrange, yrange = self._home if self._home else (None, None)
        if xrange is None and self._wave is not None and self._wave.size:
            xrange = (float(np.nanmin(self._wave)), float(np.nanmax(self._wave)))
        if xrange is not None:
            self.box.setXRange(*xrange, padding=0.01)
        if yrange is None:
            yrange = self.robust_yrange(xrange)
        if yrange is not None:
            self.box.setYRange(*yrange, padding=0.02)
        else:
            self.box.enableAutoRange(y=True)

    def robust_yrange(self, xrange=None):
        """
        A flux range that a few wild pixels do not stretch: from zero (or the 0.5th
        percentile, if lower) to 1.25 times the 99.7th percentile of the flux shown.

        Generated by RJC and Claude.
        """
        flux = getattr(self, "_flux", None)
        if flux is None:
            flux = getattr(self, "_pieces_flux", None)
        wave = self._wave
        if flux is None or wave is None or flux.size != wave.size:
            return None
        norm = getattr(self, "_norm", None)
        shown = flux / norm if norm is not None and norm.size == flux.size else flux
        sel = np.isfinite(shown)
        if xrange is not None:
            sel &= (wave >= xrange[0]) & (wave <= xrange[1])
        if np.count_nonzero(sel) < 2:
            return None
        low = min(0.0, float(np.percentile(shown[sel], 0.5)))
        high = 1.25 * float(np.percentile(shown[sel], 99.7))
        if self.log:
            return None
        if high <= low:
            return None
        return low - 0.05 * (high - low), high

    def view_range(self):
        """``(xrange, yrange)`` as shown now."""
        (x0, x1), (y0, y1) = self.box.viewRange()
        return (x0, x1), (y0, y1)

    def set_mode(self, mode):
        """Pan, zoom box, draw, mask or click."""
        self.box.set_mode(mode)


# -- The zoom bar -------------------------------------------------------------------------


class ZoomBar(QtWidgets.QWidget):
    """
    ⌂ home, ← back, → forward, ✥ pan, ⬚ zoom box, + and − (D38): for one view, or for
    several whose wavelength axes are linked (the Regions tab's datasets). It keeps
    a history of the zooms for ← and →.

    Generated by RJC and Claude.
    """

    MAX_HISTORY = 100

    def __init__(self, parent=None):
        super().__init__(parent)
        row = QtWidgets.QHBoxLayout(self)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(2)
        self.views = []
        self.history = []
        self.at = -1
        self.buttons = {}
        group = QtWidgets.QButtonGroup(self)
        group.setExclusive(True)
        for key, glyph, tip, checkable in (
            ("home", "⌂", "Home: the whole spectrum, or the transition", False),
            ("back", "←", "Back to the previous view", False),
            ("forward", "→", "Forward to the next view", False),
            ("pan", "✥", "Pan: drag to move the view", True),
            ("zoom", "⬚", "Zoom box: drag a box to zoom to it", True),
            ("in", "+", "Zoom in along the wavelength axis", False),
            ("out", "−", "Zoom out along the wavelength axis", False),
        ):
            button = QtWidgets.QToolButton()
            button.setText(glyph)
            button.setToolTip(tip)
            button.setObjectName("zoom_" + key)
            button.setAutoRaise(True)
            button.setCheckable(checkable)
            if checkable:
                group.addButton(button)
            row.addWidget(button)
            self.buttons[key] = button
        self.buttons["pan"].setChecked(True)
        self.buttons["home"].clicked.connect(self.home)
        self.buttons["back"].clicked.connect(self.back)
        self.buttons["forward"].clicked.connect(self.forward)
        self.buttons["pan"].clicked.connect(lambda: self.set_mode(PAN))
        self.buttons["zoom"].clicked.connect(lambda: self.set_mode(ZOOM))
        self.buttons["in"].clicked.connect(lambda: self.zoom(1.0 / ZOOM_STEP))
        self.buttons["out"].clicked.connect(lambda: self.zoom(ZOOM_STEP))
        self._timer = QtCore.QTimer(self)
        self._timer.setSingleShot(True)
        self._timer.setInterval(300)
        self._timer.timeout.connect(self.remember)
        self._update_buttons()

    def attach(self, *views):
        """
        Control these views; their wavelength axes are linked to the first's.

        Generated by RJC and Claude.
        """
        for view in self.views:
            try:
                view.box.userChanged.disconnect(self._timer.start)
            except (TypeError, RuntimeError):
                pass
        self.views = list(views)
        for num, view in enumerate(self.views):
            view.box.userChanged.connect(self._timer.start)
            if num:
                view.setXLink(self.views[0])
        self.history, self.at = [], -1

    @property
    def main(self):
        return self.views[0] if self.views else None

    def set_mode(self, mode):
        """Pan or zoom box, for every view (draw, mask and click are the tabs')."""
        for view in self.views:
            view.set_mode(mode)
        self.buttons["pan"].setChecked(mode == PAN)
        self.buttons["zoom"].setChecked(mode == ZOOM)

    def remember(self):
        """Keep the view as it is now, for ← and →."""
        if self.main is None:
            return
        state = self.main.view_range()
        if self.at >= 0 and np.allclose(
            np.ravel(state), np.ravel(self.history[self.at]), rtol=1e-12, atol=0
        ):
            return
        del self.history[self.at + 1 :]
        self.history.append(state)
        if len(self.history) > self.MAX_HISTORY:
            del self.history[0]
        self.at = len(self.history) - 1
        self._update_buttons()

    def _show(self, state):
        (x0, x1), (y0, y1) = state
        for view in self.views:
            view.box.setXRange(x0, x1, padding=0)
        self.main.box.setYRange(y0, y1, padding=0)

    def home(self):
        """⌂: every view to its home range."""
        for view in self.views:
            view.home()
        self.remember()

    def back(self):
        """←: the previous view."""
        self._timer.stop()
        if self.at > 0:
            self.at -= 1
            self._show(self.history[self.at])
        self._update_buttons()

    def forward(self):
        """→: the next view."""
        self._timer.stop()
        if self.at < len(self.history) - 1:
            self.at += 1
            self._show(self.history[self.at])
        self._update_buttons()

    def zoom(self, factor):
        """+ and −: zoom along the wavelength axis only, about the middle."""
        if self.main is None:
            return
        if self.at < 0:
            self.remember()
        (x0, x1), _ = self.main.view_range()
        middle, half = 0.5 * (x0 + x1), 0.5 * (x1 - x0) * factor
        for view in self.views:
            view.box.setXRange(middle - half, middle + half, padding=0)
            view.box.enableAutoRange(y=True)
        self.remember()

    def _update_buttons(self):
        self.buttons["back"].setEnabled(self.at > 0)
        self.buttons["forward"].setEnabled(0 <= self.at < len(self.history) - 1)


__all__ = [
    "SpectrumView",
    "SpectrumBox",
    "ZoomBar",
    "VelocityAxis",
    "step_curve",
    "broken_line",
    "gaps",
    "signed",
    "nice_step",
    "PAN",
    "ZOOM",
    "DRAW",
    "MASK",
    "CLICK",
    "COLOURS",
    "LINE_ID_STYLE",
]
