"""The Regions tab (dashboard Stages 4.8–4.11; D36, S2, S5–S10, S26, D17–D19).

At the left, the **Transitions** of one ion and the **Key**; in the centre, one
spectrum per dataset that covers the transition, with the tools above, and the
**Continuum** and **Snip** boxes of the selected dataset below.

- **Transitions** (S2, D36): System ▾ (the primary by default), Element ▾ and Ion ▾,
  each with ‹ ›; the ion's transitions on the data, strongest first, each with its
  observed wavelength, fλ and flags (gap, edge), ● for one with a snip. Without a
  source spectrum only the transitions with a snip are listed, and SNIP needs one.
  Keys, while the tab has the focus: ↑ ↓ the transition, [ ] the element, − + the
  continuum's order, Delete the region last clicked.
- **The spectra** (D36): one per dataset, stacked, scrolling beyond a number (a
  preference), with a velocity axis above (D43). Clicking one selects its dataset.
  Above them, what acts on the spectra (Q4.19): SNIP, CLEAR, and the fit regions'
  two tools, Add regions to all and Tweak dataset regions: in both, as in prepfit, a
  drag adds a region and a right-drag leaves pixels out, in every dataset of the
  transition or in the selected dataset alone (on a transition with no snip, a drag
  SNIPs first, Q4.2(c)); then the zoom bar. The snip's edges are orange handles; a
  fit region's edges move while either tool is on; a right-click removes a region
  (from every dataset, or from this one alone).
- **Continuum** (S8, D17, S10): the function, the order (− n +), and what acts on the
  continuum: Auto first guess, Add knot (a click adds a knot, a click on one removes
  it; a knot can be dragged), Clear knots, and Normalised (S9); the table of orders,
  and sharing with the same transition in other datasets.
- **Snip** (S6, S26, D19): its extent, fitted pixels and buffers; the pixels it shares
  with other snips and the two fixes (for every dataset with the same overlap at
  once); and, with several datasets, where each one's regions came from.

Every action is a step of the history, made through the window; the spectra show no
parameter value, and every number shown passes the blinding gate.

Generated by RJC and Claude.
"""

import numpy as np
from qtpy import QtCore, QtGui, QtWidgets

from alis.dashboard import actions as A
from alis.dashboard import blinding as BL
from alis.dashboard import continuum as CO
from alis.dashboard import lines as L
from alis.dashboard import project as P
from alis.dashboard import snips as SN
from alis.dashboard import sources as SR
from alis.dashboard.qt import dialogs as D
from alis.dashboard.qt import plots as PL
from alis.dashboard.qt import widgets as W

C_KMS = 299792.458
FUNCTION_TITLES = {
    "legendre": "Legendre",
    "chebyshev": "Chebyshev",
    "polynomial": "Polynomial",
    "constant": "Constant",
}
KEY_ITEMS = (
    ("fit", "fitted pixels"),
    ("other", "fitted by another snip"),
    ("shared", "fitted twice"),
    ("edge", "snip edges: drag the handles"),
    ("continuum", "continuum"),
    ("knot", "continuum knots"),
    ("hydrogen", "line IDs: H I and D I"),
    ("metal", "line IDs: metals"),
    ("ids_other", "line IDs: other systems"),
)
TOOLS = ("regions.draw", "regions.tweak", "regions.knot")
# What acts on the spectra (above them), and on the continuum (in its box): RJC's
# review, Q4.19
# The two ways of editing the fit regions (RJC's review of draft 2): in every dataset
# at once, or in the selected dataset alone; in both a drag adds a region and a
# right-drag leaves pixels out, as in prepfit
REGION_TOOLS = ("regions.draw", "regions.tweak")
TOOL_BUTTONS = ("regions.snip", "regions.clear", "regions.draw", "regions.tweak")
CONTINUUM_BUTTONS = ("regions.auto", "regions.knot", "regions.normalised")
NORMALISED_Y = (-0.1, 1.35)
BAR_WIDTH = 40
NO_SOURCE = (
    "No source spectrum: only the transitions with a snip are listed, and SNIP needs"
    " the source."
)
NO_REDSHIFT = "Set the redshift on the Data tab first."


def swatch(kind, size=14):
    """
    A small picture of one item of the key, drawn as the spectrum draws it.

    Generated by RJC and Claude.
    """
    pix = QtGui.QPixmap(size * 2, size)
    pix.fill(QtCore.Qt.GlobalColor.transparent)
    paint = QtGui.QPainter(pix)
    paint.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
    rect = QtCore.QRectF(1, 2, size * 2 - 2, size - 4)
    middle = QtCore.QPointF(size, 1), QtCore.QPointF(size, size - 1)
    if kind in ("fit", "other"):
        paint.fillRect(rect, QtGui.QColor(*PL.COLOURS[kind]))
    elif kind == "shared":
        brush = QtGui.QBrush(
            QtGui.QColor(PL.COLOURS["shared"]), QtCore.Qt.BrushStyle.BDiagPattern
        )
        paint.fillRect(rect, brush)
    elif kind == "edge":
        paint.setPen(QtGui.QPen(QtGui.QColor(PL.COLOURS["edge"]), 4))
        paint.drawLine(*middle)
    elif kind == "continuum":
        pen = QtGui.QPen(QtGui.QColor(PL.COLOURS["continuum"]), 2)
        pen.setStyle(QtCore.Qt.PenStyle.DashLine)
        paint.setPen(pen)
        paint.drawLine(
            QtCore.QPointF(1, size / 2), QtCore.QPointF(size * 2 - 1, size / 2)
        )
    elif kind == "knot":
        paint.setPen(QtGui.QPen(QtGui.QColor(PL.COLOURS["knot"]), 2))
        paint.drawRect(QtCore.QRectF(size - 4, size / 2 - 4, 8, 8))
    else:
        colour, _, style = PL.LINE_ID_STYLE[{"ids_other": "other"}.get(kind, kind)]
        pen = QtGui.QPen(QtGui.QColor(colour), 2)
        pen.setStyle(style)
        paint.setPen(pen)
        paint.drawLine(*middle)
    paint.end()
    return pix


def compact(table, rows):
    """A table with short rows, as high as its header and ``rows`` rows."""
    table.verticalHeader().setDefaultSectionSize(22)
    table.verticalHeader().setMinimumSectionSize(18)
    table.setMaximumHeight(26 + 22 * rows)


def flam_bar(below):
    """
    The fλ column's bar: full for the strongest transition, a fifth shorter for
    each factor of ten below it.

    Generated by RJC and Claude.
    """
    pix = QtGui.QPixmap(BAR_WIDTH, 10)
    pix.fill(QtCore.Qt.GlobalColor.transparent)
    paint = QtGui.QPainter(pix)
    width = max(2, int(round(BAR_WIDTH * max(0.0, 1.0 - 0.2 * below))))
    paint.fillRect(QtCore.QRectF(0, 1, width, 8), QtGui.QColor(PL.COLOURS["data"]))
    paint.end()
    return QtGui.QIcon(pix)


class KeyHolder:
    """
    Where a key's action is placed on the tab: a widget that also does it when
    clicked (tests and the shortcut sheet find the action through it).

    Generated by RJC and Claude.
    """

    def __init__(self, widget, action):
        self.widget = widget
        self.action = action

    def defaultAction(self):
        """The action placed here."""
        return self.action


class Strip(QtWidgets.QFrame):
    """
    One dataset's spectrum of the transition shown, with its title.

    Generated by RJC and Claude.
    """

    def __init__(self, row_id, parent=None):
        super().__init__(parent)
        self.row_id = row_id
        self.snip = None
        self.curve = None
        self.setObjectName("spectrumStrip")
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(4, 2, 4, 2)
        layout.setSpacing(0)
        self.title = QtWidgets.QLabel("")
        layout.addWidget(self.title)
        self.view = PL.SpectrumView()
        self.view.setMinimumHeight(110)
        layout.addWidget(self.view, 1)
        self.set_selected(False)

    def set_selected(self, on):
        """Frame the selected dataset's spectrum."""
        colour = PL.COLOURS["selected"] if on else "transparent"
        self.setStyleSheet(
            "QFrame#spectrumStrip {{ border: 2px solid {0}; border-radius: 4px; }}"
            "".format(colour)
        )
        font = self.title.font()
        font.setBold(on)
        self.title.setFont(font)

    def continuum_at(self, x):
        """The continuum drawn at a wavelength, or None."""
        if self.curve is None or self.snip is None or self.snip.pixels is None:
            return None
        return float(np.interp(x, self.snip.pixels.wave, self.curve))


class RegionsTab(W.Tab):
    """
    The Regions tab (D36): the transition list and the key at the left; one spectrum
    per dataset, with the Continuum and Snip boxes below.

    Generated by RJC and Claude.
    """

    name = "Regions"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.main = None
        self.session = None
        self.actions_ = {}
        self.tab_buttons = []
        self.strips = []
        self.state = {}
        self.selected = None
        self._mode = None
        self._rows = []
        self._list = []
        self._spectra = {}
        self._snip_map = {}
        self._elements = {}
        self._seen_view = None
        self._shown_key = None
        self._last_click = None
        self._stale = False
        self._filling = False
        self._build_transitions()
        self._build_key()
        self._build_plot()
        self._build_continuum()
        self._build_snip()
        left = W.column(self.transitions, self.key, stretch=[3, 1], width=300)
        below = QtWidgets.QWidget()
        boxes = QtWidgets.QHBoxLayout(below)
        boxes.setContentsMargins(0, 0, 0, 0)
        boxes.setSpacing(8)
        boxes.addWidget(self.continuum, 1)
        boxes.addWidget(self.snip, 1)
        centre = W.column(self.plot, below, stretch=[5, 3], width=1080)
        self.layout_.addWidget(W.row(left, centre, stretch=[300, 1080]))
        self._ids_timer = QtCore.QTimer(self)
        self._ids_timer.setSingleShot(True)
        self._ids_timer.setInterval(150)
        self._ids_timer.timeout.connect(self._draw_ids)
        # "=" raises the order too, for keyboards where + needs the shift key
        self._equals = QtGui.QShortcut(QtGui.QKeySequence("="), self)
        self._equals.setContext(QtCore.Qt.ShortcutContext.WidgetWithChildrenShortcut)
        self._equals.activated.connect(
            lambda: self._act("regions.order_up", self.do_order_up)
        )

    # -- building -----------------------------------------------------------------------

    def _build_transitions(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        form = QtWidgets.QGridLayout()
        form.addWidget(QtWidgets.QLabel("System"), 0, 0)
        self.system_box = QtWidgets.QComboBox()
        self.system_box.setObjectName("regions_system")
        self.system_box.currentIndexChanged.connect(self._system_chosen)
        form.addWidget(self.system_box, 0, 1, 1, 3)
        form.addWidget(QtWidgets.QLabel("Element"), 1, 0)
        self.element_box = QtWidgets.QComboBox()
        self.element_box.setObjectName("regions_element")
        self.element_box.currentIndexChanged.connect(self._element_chosen)
        form.addWidget(self.element_box, 1, 1)
        self.prev_element = QtWidgets.QToolButton()
        self.prev_element.setText("‹")
        self.prev_element.clicked.connect(lambda: self._step_element(-1))
        self.next_element = QtWidgets.QToolButton()
        self.next_element.setText("›")
        self.next_element.clicked.connect(lambda: self._step_element(1))
        form.addWidget(self.prev_element, 1, 2)
        form.addWidget(self.next_element, 1, 3)
        form.addWidget(QtWidgets.QLabel("Ion"), 2, 0)
        self.ion_box = QtWidgets.QComboBox()
        self.ion_box.setObjectName("regions_ion")
        self.ion_box.currentIndexChanged.connect(self._ion_chosen)
        form.addWidget(self.ion_box, 2, 1)
        self.prev_ion = QtWidgets.QToolButton()
        self.prev_ion.setText("‹")
        self.prev_ion.setToolTip("The ion stage below")
        self.prev_ion.clicked.connect(lambda: self._step_ion(-1))
        self.next_ion = QtWidgets.QToolButton()
        self.next_ion.setText("›")
        self.next_ion.setToolTip("The ion stage above")
        self.next_ion.clicked.connect(lambda: self._step_ion(1))
        form.addWidget(self.prev_ion, 2, 2)
        form.addWidget(self.next_ion, 2, 3)
        form.setColumnStretch(1, 1)
        box.addLayout(form)
        self.listing = QtWidgets.QTreeWidget()
        self.listing.setObjectName("transitions")
        self.listing.setHeaderLabels(["", "Transition", "λobs", "fλ", "Flags"])
        self.listing.setRootIsDecorated(False)
        self.listing.setUniformRowHeights(True)
        self.listing.setAlternatingRowColors(True)
        self.listing.setIconSize(QtCore.QSize(BAR_WIDTH, 10))
        self.listing.currentItemChanged.connect(self._transition_chosen)
        header = self.listing.header()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        header.setStretchLastSection(True)
        box.addWidget(self.listing, 1)
        self.list_note = W.muted("")
        self.list_note.setWordWrap(True)
        box.addWidget(self.list_note)
        self.transitions = W.Pane("Transitions", body)

    def _build_key(self):
        body = QtWidgets.QWidget()
        grid = QtWidgets.QGridLayout(body)
        grid.setContentsMargins(0, 0, 0, 0)
        grid.setVerticalSpacing(2)
        for num, (kind, text) in enumerate(KEY_ITEMS):
            icon = QtWidgets.QLabel()
            icon.setPixmap(swatch(kind))
            grid.addWidget(icon, num, 0)
            label = QtWidgets.QLabel(text)
            label.setWordWrap(True)
            grid.addWidget(label, num, 1)
        grid.setColumnStretch(1, 1)
        self.key = W.Pane("Key", body)

    def _build_plot(self):
        self.zoom = PL.ZoomBar()
        self.tool_row = QtWidgets.QWidget()
        self.tool_layout = QtWidgets.QHBoxLayout(self.tool_row)
        self.tool_layout.setContentsMargins(0, 0, 0, 0)
        self.tool_layout.setSpacing(2)
        self.scroll = QtWidgets.QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.holder = QtWidgets.QWidget()
        self.stack = QtWidgets.QVBoxLayout(self.holder)
        self.stack.setContentsMargins(0, 0, 0, 0)
        self.stack.setSpacing(4)
        self.scroll.setWidget(self.holder)
        self.empty = W.muted("Choose a transition at the left.")
        self.empty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stack.addWidget(self.empty)
        body = QtWidgets.QWidget()
        column = QtWidgets.QVBoxLayout(body)
        column.setContentsMargins(0, 0, 0, 0)
        column.setSpacing(4)
        tools = QtWidgets.QHBoxLayout()
        tools.addWidget(self.tool_row)
        tools.addStretch(1)
        tools.addWidget(self.zoom)
        column.addLayout(tools)
        column.addWidget(self.scroll, 1)
        self.plot = W.Pane("Transition", body)
        self.plot.title.setTextFormat(QtCore.Qt.TextFormat.PlainText)

    def _build_continuum(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        row = QtWidgets.QHBoxLayout()
        self.function_box = QtWidgets.QComboBox()
        self.function_box.setObjectName("continuum_function")
        for name in CO.FUNCTIONS:
            self.function_box.addItem(FUNCTION_TITLES[name], name)
        self.function_box.activated.connect(self._function_chosen)
        row.addWidget(self.function_box)
        row.addWidget(QtWidgets.QLabel("order"))
        self.order_down = QtWidgets.QToolButton()
        self.order_down.setText("−")
        self.order_down.setObjectName("order_down")
        self.order_label = QtWidgets.QLabel("")
        self.order_label.setObjectName("paneTitle")
        self.order_up = QtWidgets.QToolButton()
        self.order_up.setText("+")
        self.order_up.setObjectName("order_up")
        self.order_down.clicked.connect(
            lambda: self._act("regions.order_down", self.do_order_down)
        )
        self.order_up.clicked.connect(
            lambda: self._act("regions.order_up", self.do_order_up)
        )
        row.addWidget(self.order_down)
        row.addWidget(self.order_label)
        row.addWidget(self.order_up)
        row.addStretch(1)
        box.addLayout(row)
        self.continuum_tools = QtWidgets.QHBoxLayout()
        self.continuum_tools.setSpacing(2)
        self.clear_knots = QtWidgets.QToolButton()
        self.clear_knots.setText("Clear knots")
        self.clear_knots.setObjectName("clear_knots")
        self.clear_knots.clicked.connect(
            lambda: self._act("regions.knots", self.remove_knots)
        )
        self._continuum_buttons = {}
        self._order_continuum_tools()
        box.addLayout(self.continuum_tools)
        self.orders = QtWidgets.QTableWidget(0, 4)
        self.orders.setObjectName("orders")
        self.orders.setHorizontalHeaderLabels(["Order", "χ²", "Δχ²", "ΔBIC"])
        self.orders.verticalHeader().setVisible(False)
        self.orders.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.orders.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.ResizeMode.Stretch
        )
        compact(self.orders, 4)
        box.addWidget(self.orders)
        self.knots_label = W.muted("")
        self.knots_label.setWordWrap(True)
        box.addWidget(self.knots_label)
        self.share_label = W.muted("")
        self.share_label.setWordWrap(True)
        box.addWidget(self.share_label)
        self.share_row = QtWidgets.QHBoxLayout()
        box.addLayout(self.share_row)
        box.addStretch(1)
        self.continuum = W.Pane("Continuum", body)

    def _build_snip(self):
        body = QtWidgets.QWidget()
        box = QtWidgets.QVBoxLayout(body)
        box.setContentsMargins(0, 0, 0, 0)
        self.extent_label = QtWidgets.QLabel("")
        self.fitted_label = QtWidgets.QLabel("")
        self.buffer_label = QtWidgets.QLabel("")
        for label in (self.extent_label, self.fitted_label, self.buffer_label):
            label.setWordWrap(True)
            box.addWidget(label)
        self.shared_box = QtWidgets.QFrame()
        self.shared_box.setObjectName("banner")
        self.shared_box.setProperty("kind", "warning")
        shared = QtWidgets.QVBoxLayout(self.shared_box)
        shared.setContentsMargins(8, 6, 8, 6)
        self.shared_label = QtWidgets.QLabel("")
        self.shared_label.setWordWrap(True)
        shared.addWidget(self.shared_label)
        self.fix_buttons = QtWidgets.QHBoxLayout()
        self.keep_button = QtWidgets.QPushButton("Keep them in this snip only")
        self.keep_button.setObjectName("keep_shared")
        self.merge_button = QtWidgets.QPushButton("Merge the snips…")
        self.merge_button.setObjectName("merge_shared")
        self.keep_button.clicked.connect(
            lambda: self._act("regions.keep", self.keep_shared)
        )
        self.merge_button.clicked.connect(
            lambda: self._act("regions.merge", self.merge_shared)
        )
        self.fix_buttons.addWidget(self.keep_button)
        self.fix_buttons.addWidget(self.merge_button)
        self.fix_buttons.addStretch(1)
        shared.addLayout(self.fix_buttons)
        self.fix_all = QtWidgets.QCheckBox("Apply the fix to all datasets")
        self.fix_all.setChecked(True)
        shared.addWidget(self.fix_all)
        self.shared_box.hide()
        box.addWidget(self.shared_box)
        self.datasets = QtWidgets.QTableWidget(0, 4)
        self.datasets.setObjectName("snip_datasets")
        self.datasets.setHorizontalHeaderLabels(
            ["Dataset", "Fitted px", "Shared px", "Regions"]
        )
        self.datasets.verticalHeader().setVisible(False)
        self.datasets.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.datasets.horizontalHeader().setStretchLastSection(True)
        compact(self.datasets, 4)
        box.addWidget(self.datasets)
        self.copy_button = QtWidgets.QPushButton("Use these regions in every dataset")
        self.copy_button.setObjectName("copy_regions")
        self.copy_button.clicked.connect(
            lambda: self._act("regions.copy", lambda: self.copy_regions(False))
        )
        box.addWidget(self.copy_button)
        box.addStretch(1)
        self.snip = W.Pane("Snip", body)

    def attach(self, window):
        """The main window; the tab draws itself when it is shown."""
        super().attach(window)
        window.tabs.currentChanged.connect(self._tab_shown)

    def bind_action(self, name, action):
        """
        The tab's own actions: what acts on the spectra above them (SNIP, CLEAR, Add
        region, Exclude pixels), what acts on the continuum in its box (Auto first
        guess, Add knot, Normalised), and the keys.

        Generated by RJC and Claude.
        """
        self.actions_[name] = action
        if name in TOOL_BUTTONS:
            button = QtWidgets.QToolButton()
            button.setDefaultAction(action)
            button.setObjectName(name.replace(".", "_"))
            if name == "regions.snip":
                button.setStyleSheet("font-weight: 600;")
            if name == "regions.draw":
                line = QtWidgets.QFrame()
                line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
                line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.tool_layout.addWidget(line)
                self.tool_layout.addWidget(QtWidgets.QLabel("Fit regions:"))
            self.tool_layout.addWidget(button)
            self.tab_buttons.append(button)
        elif name in CONTINUUM_BUTTONS:
            button = QtWidgets.QToolButton()
            button.setDefaultAction(action)
            button.setObjectName(name.replace(".", "_"))
            self._continuum_buttons[name] = button
            self._order_continuum_tools()
            self.tab_buttons.append(button)
        else:
            holder = {
                "regions.remove_region": self.holder,
                "regions.order_down": self.order_down,
                "regions.order_up": self.order_up,
                "regions.previous_element": self.prev_element,
                "regions.next_element": self.next_element,
            }.get(name, self.listing)
            if isinstance(holder, QtWidgets.QToolButton):
                holder.setToolTip(action.toolTip())
            self.tab_buttons.append(KeyHolder(holder, action))

    def _order_continuum_tools(self):
        """Auto first guess, Add knot and Clear knots, then Normalised at the right."""
        while self.continuum_tools.count():
            self.continuum_tools.takeAt(0)
        names = ("regions.auto", "regions.knot")
        for name in names:
            if name in self._continuum_buttons:
                self.continuum_tools.addWidget(self._continuum_buttons[name])
        self.continuum_tools.addWidget(self.clear_knots)
        self.continuum_tools.addStretch(1)
        if "regions.normalised" in self._continuum_buttons:
            self.continuum_tools.addWidget(
                self._continuum_buttons["regions.normalised"]
            )

    # -- acting ---------------------------------------------------------------------------

    def _act(self, name, handler):
        """Run a handler through the window (typing read first, errors reported)."""
        if self.main is not None:
            self.main._run(name, handler)
        else:
            handler()

    def _do(self, step):
        """Make a step through the history."""
        if step is not None and step:
            self.session.history.do(step)

    def _warn(self, title, text):
        if self.main is not None:
            self.main.tell(title, text, "warning")

    def _pref(self, key, default):
        prefs = getattr(self.main, "prefs", None)
        try:
            return prefs[key] if prefs is not None else default
        except KeyError:
            return default

    def _options(self):
        """The continuum's fitting preferences."""
        return {
            "clip": (
                self._pref("continuum.clip_below", CO.CLIP[0]),
                self._pref("continuum.clip_above", CO.CLIP[1]),
            ),
            "line_kms": self._pref("continuum.line_width", CO.LINE_KMS),
        }

    def _max_order(self):
        return self._pref("continuum.max_order", CO.AUTO_MAX)

    # -- the state ----------------------------------------------------------------------

    def _system(self):
        if self.session is None:
            return None
        systems = self.session.project.systems
        ident = self.state.get("system")
        for system in systems:
            if system.id == ident:
                return system
        return next((s for s in systems if s.primary), systems[0] if systems else None)

    def _remember(self):
        """Keep where the tab is in the view state (saved with the project)."""
        if self.session is not None:
            data = {
                k: self.state[k] for k in ("system", "ion", "rest") if k in self.state
            }
            data["row"] = self.selected
            self._seen_view = data
            self.session.set_view("regions", data)

    def current_line(self):
        """The transition shown, as a ``lines.Line``, or None."""
        ion, rest = self.state.get("ion"), self.state.get("rest")
        if ion is None or rest is None or self.session is None:
            return None
        atom = L.atomic(self.session.project.registry)
        for line in atom.ion_lines(ion):
            if abs(line.rest - rest) < 0.01:
                return line
        return None

    def current_strip(self):
        """The selected dataset's spectrum, or None."""
        for strip in self.strips:
            if strip.row_id == self.selected:
                return strip
        return None

    def current_snip(self):
        """The selected dataset's snip of the transition shown, or None."""
        strip = self.current_strip()
        if strip is None or strip.snip is None:
            return None
        return self._snip(strip.snip.specid)

    def _snip(self, specid):
        """The project's snip of a specid now, or None (merged or cleared)."""
        try:
            return self.session.project.snip(specid)
        except P.ProjectError:
            return None

    def _row_name(self, row_id):
        for row in self.session.project.rows:
            if row.id == row_id:
                return row.name
        return ""

    # -- refreshing ---------------------------------------------------------------------

    def refresh(self, session):
        """
        Redraw the tab from the project (after every step, undo and redo); while
        another tab is shown, only once it is shown again.

        Generated by RJC and Claude.
        """
        if session is not self.session:
            self.state, self.selected, self._seen_view = {}, None, None
            self._shown_key = None
        self.session = session
        if session is None or session.project.paused:
            return
        if self.main is not None and self.main.tabs.currentWidget() is not self:
            self._stale = True
            return
        self._stale = False
        stored = session.view.get("regions") or {}
        if stored != self._seen_view:
            # Set elsewhere (the Data tab's coverage grid, a project opened)
            self.state = {
                k: stored[k] for k in ("system", "ion", "rest") if k in stored
            }
            self.selected = stored.get("row")
            self._seen_view = dict(stored)
        project = session.project
        self._spectra = {}
        for row in project.rows:
            spec = SR.spectrum(project, row, session.path)
            if spec is not None:
                self._spectra[row.id] = spec
        self._snip_map = L.snip_transitions(project)
        self._filling = True
        try:
            self._fill_systems()
            self._fill_elements()
            self._fill_list()
        finally:
            self._filling = False
        self._fill_strips()
        self._fill_boxes()

    def _tab_shown(self, index):
        if self.main.tabs.widget(index) is self and self._stale:
            self.refresh(self.session)

    def _coverages(self):
        """Where each row has data: its source, or else its snips (D12)."""
        out = []
        for row in self.session.project.rows:
            spec = self._spectra.get(row.id)
            if spec is not None:
                out.append(L.coverage_of_spectrum(row.id, row.name, spec))
            else:
                out.append(L.coverage_of_snips(row))
        return out

    def _fill_systems(self):
        project = self.session.project
        gate = BL.Gate(project)
        self.system_box.clear()
        for system in project.systems:
            text = gate.message(system.name)
            if not text.startswith("z ="):
                text += " · z = {0}".format(gate.system_z(system, 6))
            if system.primary:
                text += " · primary"
            self.system_box.addItem(text, system.id)
        system = self._system()
        if system is not None:
            self.state["system"] = system.id
            self.system_box.setCurrentIndex(self.system_box.findData(system.id))

    def _fill_elements(self):
        system = self._system()
        self.element_box.clear()
        self.ion_box.clear()
        self._elements = {}
        if system is None:
            return
        atom = L.atomic(self.session.project.registry)
        snipped = L.snipped_by_ion(self._snip_map, system.id)
        found = L.elements_on_data(
            atom,
            system.z,
            self._coverages(),
            snipped,
            half_width=self._pref("regions.half_width", L.HALF_WIDTH),
        )
        if not self._spectra:
            # Without a source only the snipped transitions are listed: offer only
            # the elements and stages that have one
            found = {
                elem: [
                    st for st in stages if snipped.get(atom.main_ion.get((elem, st)))
                ]
                for elem, stages in found.items()
            }
            found = {elem: stages for elem, stages in found.items() if stages}
        self._elements = found
        for element in found:
            self.element_box.addItem(element)
        ion = self.state.get("ion")
        if ion is not None:
            for (elem, stage), main in atom.main_ion.items():
                if main == ion and stage in found.get(elem, ()):
                    self.state["element"], self.state["stage"] = elem, stage
        element = self.state.get("element")
        if element not in found:
            element = next(iter(found), None)
        if element is None:
            self.state.pop("element", None)
            return
        self.state["element"] = element
        self.element_box.setCurrentIndex(self.element_box.findText(element))
        stages = found[element]
        stage = self.state.get("stage")
        if stage not in stages:
            stage = stages[0]
        self.state["stage"] = stage
        for name in stages:
            self.ion_box.addItem(name)
        self.ion_box.setCurrentIndex(stages.index(stage))

    def _fill_list(self):
        system = self._system()
        self.listing.clear()
        self._list = []
        if system is None or "element" not in self.state:
            self.list_note.setText(NO_REDSHIFT if system is None else NO_SOURCE)
            self.state.pop("ion", None)
            return
        project = self.session.project
        atom = L.atomic(project.registry)
        snipped = L.snipped_by_ion(self._snip_map, system.id)
        ion = atom.main_ion.get((self.state["element"], self.state["stage"]))
        rows = L.ion_transitions(
            atom,
            self.state["element"],
            self.state["stage"],
            system.z,
            self._coverages(),
            snipped.get(ion, []),
            system.id,
            half_width=self._pref("regions.half_width", L.HALF_WIDTH),
        )
        if self._spectra:
            self.list_note.setText(
                "The transitions on the data, strongest first. ● has a snip."
            )
        else:
            rows = [t for t in rows if t.snipped]
            self.list_note.setText(NO_SOURCE)
        self._list = rows
        masked = BL.Gate(project).system_z(system) == BL.MASK
        top = max((t.flam for t in rows), default=1.0)
        current = None
        for trans in rows:
            item = QtWidgets.QTreeWidgetItem(
                [
                    "●" if trans.snipped else "",
                    trans.name,
                    BL.MASK if masked else "{0:.1f}".format(trans.observed),
                    "",
                    " ".join(trans.flags),
                ]
            )
            item.setIcon(3, flam_bar(np.log10(top / trans.flam)))
            item.setData(0, QtCore.Qt.ItemDataRole.UserRole, (trans.ion, trans.rest))
            item.setToolTip(3, "fλ = {0:.4g}".format(trans.flam))
            self.listing.addTopLevelItem(item)
            if trans.ion == self.state.get("ion") and trans.has(
                self.state.get("rest", -1.0)
            ):
                current = item
        if current is None and rows:
            current = self.listing.topLevelItem(0)
        if current is not None:
            ion, rest = current.data(0, QtCore.Qt.ItemDataRole.UserRole)
            if not (
                ion == self.state.get("ion")
                and abs(rest - self.state.get("rest", -1.0)) < 0.01
            ):
                self.state["ion"], self.state["rest"] = ion, rest
            self.listing.setCurrentItem(current)
        else:
            self.state.pop("ion", None)
            self.state.pop("rest", None)

    def _clear_strips(self):
        for strip in self.strips:
            self.stack.removeWidget(strip)
            strip.hide()
            strip.setParent(None)
            strip.deleteLater()
        self.strips = []
        self._rows = []

    def _key(self):
        """What the spectra show: the zoom is kept while it stays the same."""
        return (
            self.state.get("system"),
            self.state.get("ion"),
            round(self.state.get("rest", 0.0), 3),
            self._normalised(),
        )

    def _normalised(self):
        action = self.actions_.get("regions.normalised")
        return action is not None and action.isChecked()

    def _fill_strips(self):
        kept = None
        if self.strips and self._shown_key == self._key():
            kept = self.strips[0].view.view_range()
        self._clear_strips()
        project = self.session.project
        line = self.current_line()
        system = self._system()
        self.empty.setVisible(line is None)
        if line is None or system is None:
            self.plot.title.setText("Transition")
            self._shown_key = None
            self._update_tools()
            self._update_snip()
            return
        found = SN.strips(project, system, line, self._spectra, self._snip_map)
        self._rows = found
        ids = [row.id for row, _ in found]
        if self.selected not in ids:
            self.selected = ids[0] if ids else None
        if len(found) == 1:
            title = "{0} · {1}".format(line.name, found[0][0].name)
        elif found:
            title = "{0} · {1} datasets · click a spectrum to select it".format(
                line.name, len(found)
            )
        else:
            title = "{0} · no dataset covers it".format(line.name)
        self.plot.title.setText(title)
        shown = max(1, min(len(found), self._pref("regions.spectra", 3)))
        height = max(150, (self.scroll.viewport().height() - 4) // shown)
        for row, snip in found:
            strip = Strip(row.id)
            strip.snip = snip
            strip.title.setText(row.name + ("" if snip is not None else " · no snip"))
            if len(found) > shown:
                strip.setFixedHeight(height)
            self._draw_strip(strip, row, snip, line, system)
            self._connect(strip)
            strip.set_selected(row.id == self.selected)
            strip.view.set_labels(
                top=not self.strips, bottom=len(self.strips) == len(found) - 1
            )
            self.stack.addWidget(strip, 1)
            self.strips.append(strip)
        if self.strips:
            self.zoom.attach(*[s.view for s in self.strips])
            if kept is not None:
                (x0, x1), (y0, y1) = kept
                for strip in self.strips:
                    strip.view.box.setXRange(x0, x1, padding=0)
                    if len(self.strips) == 1:
                        strip.view.box.setYRange(y0, y1, padding=0)
            self.zoom.remember()
        self._shown_key = self._key()
        self._apply_mode()
        self._update_tools()
        self._update_snip(found)
        self._remember()
        self._draw_ids()

    def _draw_strip(self, strip, row, snip, line, system):
        project = self.session.project
        view = strip.view
        shift = SN.row_shift(row)
        view.set_velocity_centre(line.rest * (1.0 + system.z) * (1.0 + shift / C_KMS))
        spec = self._spectra.get(row.id)
        if snip is not None and snip.pixels is not None:
            pix = snip.pixels
            view.set_data(pix.wave, pix.flux, pix.error, pix.bad)
            curve = CO.evaluate(project, snip)
            strip.curve = curve
            normalised = self._normalised() and curve is not None
            view.set_normalised(curve if normalised else None)
            if curve is not None:
                view.set_continuum(pix.wave, curve)
            low, high = snip.extent
            if spec is not None and not normalised:
                width = high - low
                sel = (spec.wave >= low - 0.6 * width) & (
                    spec.wave <= high + 0.6 * width
                )
                view.set_context(spec.wave[sel], spec.flux[sel])
            view.set_regions(
                "fit", SN.regions_of(snip), movable=self._mode in REGION_TOOLS
            )
            view.set_regions("other", self._other_regions(row, snip, low, high))
            view.set_regions("shared", self._shared_spans(snip))
            view.set_edges(low, high)
            knots = CO.knots_of(project, snip)
            if normalised:
                knots = [(x, y / strip.continuum_at(x)) for x, y in knots]
            view.set_knots(knots)
            pad = 0.04 * (high - low)
            view.set_home((low - pad, high + pad), NORMALISED_Y if normalised else None)
        elif spec is not None:
            low, high = SN.window(
                line.rest,
                system.z,
                shift,
                self._pref("regions.half_width", L.HALF_WIDTH),
            )
            width = high - low
            sel = (spec.wave >= low - 0.5 * width) & (spec.wave <= high + 0.5 * width)
            view.set_data(spec.wave[sel], spec.flux[sel], spec.error[sel])
            view.set_home((low, high))
        view.home()

    def _other_regions(self, row, snip, low, high):
        """The regions other snips of the row fit within this snip's extent."""
        out = []
        for other in row.snips:
            if other.specid == snip.specid or other.pixels is None:
                continue
            for a, b in SN.regions_of(other):
                if b >= low and a <= high:
                    out.append((max(a, low), min(b, high)))
        return out

    def _shared_spans(self, snip):
        """The pixels the snip shares with another, as wavelength spans."""
        spans = []
        wave = snip.pixels.wave
        for pair in SN.shared_pixels(self.session.project, snip):
            mask = np.zeros(wave.size, dtype=bool)
            mask[pair.pixels_of(snip)] = True
            spans += P.mask_regions(wave, mask)
        return spans

    def _connect(self, strip):
        view = strip.view
        view.clicked.connect(lambda x, y, s=strip: self._clicked(s, x, y))
        view.spanned.connect(lambda m, a, b, s=strip: self._spanned(s, m, a, b))
        view.edgeMoved.connect(
            lambda side, x, done, s=strip: self._edge(s, side, x, done)
        )
        view.regionMoved.connect(
            lambda n, a, b, s=strip: self._region_moved(s, n, a, b)
        )
        view.knotMoved.connect(lambda n, x, y, s=strip: self._knot_moved(s, n, x, y))
        view.contextRequested.connect(lambda x, y, pos, s=strip: self._menu(s, x, pos))
        view.box.sigXRangeChanged.connect(lambda *a: self._ids_timer.start())

    def _draw_ids(self):
        """The line IDs in each spectrum's view (S5, Q4.4)."""
        if self.session is None or self.session.project.paused:
            return
        system = self._system()
        if system is None:
            return
        strong = self._pref("lines.strength", L.STRONG)
        for strip in self.strips:
            (x0, x1), _ = strip.view.view_range()
            ids, hidden = L.line_ids(
                self.session.project, x0, x1, reference=system.id, strong=strong
            )
            strip.view.set_line_ids(
                [(i.observed, i.label, i.kind) for i in ids], hidden
            )

    def _fill_boxes(self):
        self._fill_continuum()
        self._fill_snip()

    @staticmethod
    def _clear_layout(layout):
        while layout.count():
            widget = layout.takeAt(0).widget()
            if widget is not None:
                widget.hide()
                widget.setParent(None)
                widget.deleteLater()

    def _fill_continuum(self):
        snip = self.current_snip()
        name = self._row_name(self.selected) if self.selected else ""
        self.continuum.title.setText("Continuum" + (" · " + name if name else ""))
        has = snip is not None and snip.continuum is not None
        for widget in (self.function_box, self.order_down, self.order_up):
            widget.setEnabled(has)
        self.orders.setRowCount(0)
        self._clear_layout(self.share_row)
        self.share_label.setText("")
        if not has:
            self.order_label.setText("")
            self.clear_knots.setEnabled(False)
            self.knots_label.setText(
                "Select a dataset whose transition is a snip."
                if snip is None
                else "No continuum yet: Auto first guess makes one."
            )
            return
        project = self.session.project
        function, order = CO.current(snip)
        self.function_box.setCurrentIndex(self.function_box.findData(function))
        self.order_label.setText(str(order))
        knots = CO.knots_of(project, snip)
        self.clear_knots.setEnabled(bool(knots))
        if knots:
            self.knots_label.setText(
                "{0} knot{1}: the starting continuum passes through {2}.".format(
                    len(knots),
                    "" if len(knots) == 1 else "s",
                    "it" if len(knots) == 1 else "them",
                )
            )
        else:
            self.knots_label.setText(
                "No knots. Add knot sets a point the starting continuum passes"
                " through."
            )
        self._fill_orders(project, snip, function, order)
        self._fill_sharing(project, snip)

    def _fill_orders(self, project, snip, function, order):
        """The table of orders (S8): χ², Δχ² and ΔBIC against the order chosen."""
        try:
            guess = CO.guess(
                project,
                snip,
                function,
                self._max_order(),
                orders=[o for o in (order - 1, order, order + 1) if o >= 0],
                **self._options(),
            )
            table = guess.table(order) if order in guess.fits else []
        except CO.ContinuumError:
            table = []
        self.orders.setRowCount(len(table))
        for num, (n, chi2, dchi2, dbic) in enumerate(table):
            cells = (
                str(n),
                "{0:.1f}".format(chi2),
                "{0:+.1f}".format(dchi2) if n != order else "—",
                "{0:+.1f}".format(dbic) if n != order else "—",
            )
            for col, text in enumerate(cells):
                item = QtWidgets.QTableWidgetItem(text)
                if n == order:
                    font = item.font()
                    font.setBold(True)
                    item.setFont(font)
                self.orders.setItem(num, col, item)

    def _fill_sharing(self, project, snip):
        """Sharing the continuum with the same transition in other datasets (S10)."""
        line = snip.continuum
        notes = []
        if line.line in project.hidden_lines():
            notes.append(
                "This continuum is hidden: it is drawn, and its coefficients are not"
                " shown."
            )
        others = [s for s in project.snips if s.specid in line.specids]
        others = [s for s in others if s.specid != snip.specid]
        if others:
            names = [s.row.name if s.row is not None else s.specid for s in others]
            notes.append("Shared with {0}.".format(", ".join(names)))
            button = QtWidgets.QPushButton("Unshare")
            button.setObjectName("unshare")
            button.clicked.connect(lambda: self._act("regions.unshare", self.unshare))
            self.share_row.addWidget(button)
        else:
            trans = self._snip_map.get(snip.specid)
            same = {}
            if trans is not None:
                same = SN.snips_of(
                    project, trans.system, trans.ion, trans.rest, self._snip_map
                )
            for row_id, other in same.items():
                if other.specid == snip.specid:
                    continue
                button = QtWidgets.QPushButton("Share with " + self._row_name(row_id))
                button.setObjectName("share_" + row_id)
                why = CO.shareable(project, [snip, other])
                button.setEnabled(not why)
                button.setToolTip(
                    why or "One continuum for this transition in both datasets"
                )
                button.clicked.connect(
                    lambda _=False, o=other.specid: self._act(
                        "regions.share", lambda: self.share_with(o)
                    )
                )
                self.share_row.addWidget(button)
        self.share_row.addStretch(1)
        self.share_label.setText(" ".join(notes))

    def _fill_snip(self):
        project = self.session.project
        snip = self.current_snip()
        line = self.current_line()
        name = self._row_name(self.selected) if self.selected else ""
        parts = ["Snip"] + ([line.name] if line else []) + ([name] if name else [])
        self.snip.title.setText(" · ".join(parts))
        self.shared_box.hide()
        several = len(self._rows) > 1
        self.datasets.setVisible(several)
        self.copy_button.setVisible(several)
        self.datasets.setRowCount(0)
        if snip is None or snip.pixels is None:
            self.extent_label.setText(
                "Not a snip yet: SNIP cuts it, or add a region on it."
                if line is not None and snip is None
                else ""
            )
            self.fitted_label.setText("")
            self.buffer_label.setText("")
        else:
            self._fill_snip_facts(project, snip)
        if several:
            self._fill_datasets(project)
        self.copy_button.setText(
            "Use {0}'s regions in every dataset".format(name)
            if name
            else "Use these regions in every dataset"
        )
        self.copy_button.setEnabled(
            snip is not None and snip.pixels is not None and bool(SN.fitted(snip).any())
        )

    def _fill_snip_facts(self, project, snip):
        facts = SN.summary(project, snip)
        low, high = facts["extent"]
        self.extent_label.setText(
            "Extent {0:.2f}–{1:.2f} Å · {2:,} pixels".format(low, high, facts["npix"])
        )
        if facts["nfit"]:
            self.fitted_label.setText(
                "Fitted: {0:,} pixels in {1} region{2}".format(
                    facts["nfit"],
                    facts["nregions"],
                    "" if facts["nregions"] == 1 else "s",
                )
            )
        else:
            self.fitted_label.setText(
                "No fit region yet: Add regions to all draws one."
            )
        self.buffer_label.setText(self._buffer_text(snip, facts["buffers"]))
        pairs = SN.shared_pixels(project, snip)
        if not pairs:
            return
        self.shared_box.show()
        self.shared_label.setText(SN.shared_text(pairs, snip, self._snip_map))
        first = SN.merge_first(pairs, self._pref("regions.merge_overlap", 25.0) / 100.0)
        # The fix offered first comes first (D19)
        order = (self.merge_button, self.keep_button)
        if not first:
            order = order[::-1]
        for num, button in enumerate(order):
            self.fix_buttons.removeWidget(button)
            self.fix_buttons.insertWidget(num, button)
            button.setDefault(num == 0)
            font = button.font()
            font.setBold(num == 0)
            button.setFont(font)
        also = SN.same_pairs(project, snip, pairs[0], self._snip_map)
        self.fix_all.setVisible(bool(also))
        self.fix_all.setText(
            "Apply the fix to all {0} datasets".format(len(also) + 1)
            if also
            else "Apply the fix to all datasets"
        )

    @staticmethod
    def _buffer_text(snip, buffers):
        """
        The buffers in Å, as the mockup gives them: "Buffer 1.57 Å blue, 2.84 Å red
        · needs ≥ 0.26 Å ✓".

        Generated by RJC and Claude.
        """
        if not buffers:
            return ""
        wave = snip.pixels.wave[SN.fitted(snip)]
        edge = {"blue": float(wave.min()), "red": float(wave.max())}
        have = [
            "{0:.2f} Å {1}".format(b.have * edge[b.side] / C_KMS, b.side)
            for b in buffers
        ]
        need = max(b.need * edge[b.side] / C_KMS for b in buffers)
        short = [b.side for b in buffers if not b.ok]
        return "Buffer {0} · needs ≥ {1:.2f} Å {2}".format(
            ", ".join(have),
            need,
            (
                "✓"
                if not short
                else "! (too narrow on the {0})".format(" and ".join(short))
            ),
        )

    def _fill_datasets(self, project):
        """Each dataset's snip of the transition: fitted, shared, regions' origin."""
        self.datasets.setRowCount(len(self._rows))
        for num, (row, one) in enumerate(self._rows):
            one = project.snip(one.specid) if one is not None else None
            if one is None or one.pixels is None:
                cells = [row.name, "—", "—", "no snip"]
            else:
                shared = sum(p.count for p in SN.shared_pixels(project, one))
                cells = [
                    row.name,
                    str(int(SN.fitted(one).sum())),
                    str(shared),
                    SN.origin(project, one),
                ]
            for col, text in enumerate(cells):
                self.datasets.setItem(num, col, QtWidgets.QTableWidgetItem(text))
            if row.id == self.selected:
                self.datasets.selectRow(num)

    def _update_snip(self, found=()):
        """SNIP: while a dataset whose source covers the transition has no snip."""
        action = self.actions_.get("regions.snip")
        if action is None:
            return
        spec = A.get("regions.snip")
        if not self._spectra:
            action.setEnabled(False)
            action.setToolTip(
                "SNIP needs a source spectrum, which this project does not have"
            )
            return
        action.setToolTip(spec.tip)
        action.setEnabled(any(snip is None for _, snip in found))

    def _update_tools(self):
        line = self.current_line()
        snip = self.current_snip()
        for name, on in (
            ("regions.clear", snip is not None),
            ("regions.auto", snip is not None and snip.pixels is not None),
            ("regions.draw", line is not None and bool(self.strips)),
            ("regions.tweak", snip is not None),
            ("regions.remove_region", snip is not None),
            ("regions.knot", snip is not None and snip.continuum is not None),
            ("regions.normalised", line is not None),
        ):
            action = self.actions_.get(name)
            if action is not None:
                action.setEnabled(on)

    # -- cross-highlighting (S16) -------------------------------------------------------

    def show_items(self, items):
        """
        Select what a line of the .mod panel describes: its snip's transition and
        dataset, or the snip of a continuum (S16).

        Generated by RJC and Claude.
        """
        if self.session is None or self.session.project.paused:
            return
        snip_map = L.snip_transitions(self.session.project)
        for item in items:
            specid = getattr(item, "specid", None)
            if specid is None and hasattr(item, "specids"):
                specids = item.specids
                specid = specids[0] if specids else None
            trans = snip_map.get(specid) if specid else None
            if trans is None or not trans.system:
                continue
            snip = self.session.project.snip(specid)
            row = snip.row.id if snip is not None and snip.row is not None else None
            self.show_transition(trans.system, trans.ion, trans.rest, row)
            return

    def show_transition(self, system, ion, rest, row=None):
        """
        Show a transition of a system (an id), and select a dataset.

        Generated by RJC and Claude.
        """
        same = (
            self.state.get("system") == system
            and self.state.get("ion") == ion
            and abs(self.state.get("rest", -1.0) - rest) < 0.01
        )
        if same and (row is None or row == self.selected):
            return
        self.state = {"system": system, "ion": ion, "rest": rest}
        if row is not None:
            self.selected = row
        self._remember()
        self.refresh(self.session)

    # -- the list -----------------------------------------------------------------------

    def _system_chosen(self, index):
        if self._filling or index < 0:
            return
        self.state = {"system": self.system_box.itemData(index)}
        self._remember()
        self.refresh(self.session)

    def _element_chosen(self, index):
        if self._filling or index < 0:
            return
        self.state["element"] = self.element_box.itemText(index)
        for key in ("stage", "ion", "rest"):
            self.state.pop(key, None)
        self._remember()
        self.refresh(self.session)

    def _ion_chosen(self, index):
        if self._filling or index < 0:
            return
        self.state["stage"] = self.ion_box.itemText(index)
        self.state.pop("ion", None)
        self.state.pop("rest", None)
        self._remember()
        self.refresh(self.session)

    def _transition_chosen(self, current, previous=None):
        if self._filling or current is None:
            return
        ion, rest = current.data(0, QtCore.Qt.ItemDataRole.UserRole)
        if ion == self.state.get("ion") and rest == self.state.get("rest"):
            return
        self.state["ion"], self.state["rest"] = ion, rest
        self._fill_strips()
        self._fill_boxes()

    def _step_ion(self, by):
        """‹ ›: the ion stage below or above (no further than the first or last)."""
        count = self.ion_box.count()
        index = min(max(self.ion_box.currentIndex() + by, 0), count - 1)
        if count and index != self.ion_box.currentIndex():
            self.ion_box.setCurrentIndex(index)

    def _step_element(self, by):
        count = self.element_box.count()
        if count:
            self.element_box.setCurrentIndex(
                (self.element_box.currentIndex() + by) % count
            )

    def _step_transition(self, by):
        count = self.listing.topLevelItemCount()
        if not count:
            return
        index = self.listing.indexOfTopLevelItem(self.listing.currentItem())
        index = min(max(index + by, 0), count - 1)
        self.listing.setCurrentItem(self.listing.topLevelItem(index))

    def do_previous(self):
        """↑: the transition above in the list."""
        self._step_transition(-1)

    def do_next(self):
        """↓: the transition below in the list."""
        self._step_transition(1)

    def do_previous_element(self):
        """[: the previous element."""
        self._step_element(-1)

    def do_next_element(self):
        """]: the next element."""
        self._step_element(1)

    # -- the tools ----------------------------------------------------------------------

    def _apply_mode(self):
        mode = {
            "regions.draw": PL.DRAW,
            "regions.tweak": PL.DRAW,
            "regions.knot": PL.CLICK,
        }.get(self._mode, PL.PAN)
        for strip in self.strips:
            strip.view.set_mode(mode)
            if strip.snip is not None and strip.snip.pixels is not None:
                strip.view.set_regions(
                    "fit",
                    SN.regions_of(strip.snip),
                    movable=self._mode in REGION_TOOLS,
                )

    def _linked(self):
        """Whether an edit of the regions reaches every dataset (not while tweaking)."""
        return self._mode != "regions.tweak"

    def _tool(self, name):
        action = self.actions_.get(name)
        on = action is not None and action.isChecked()
        for other in TOOLS:
            if other != name and other in self.actions_:
                self.actions_[other].setChecked(False)
        self._mode = name if on else None
        if not on:
            self.zoom.set_mode(PL.PAN)
            self.zoom.buttons["pan"].setChecked(True)
        self._apply_mode()

    def do_draw(self):
        """
        Add regions to all: a drag adds a fit region, and a right-drag leaves pixels
        out, in every dataset of the transition.
        """
        self._tool("regions.draw")

    def do_tweak(self):
        """
        Tweak dataset regions: a drag adds a fit region, and a right-drag leaves
        pixels out, in the selected dataset alone (as in prepfit).
        """
        self._tool("regions.tweak")

    def do_knot(self):
        """Add knot: a click adds a knot; a click on a knot removes it."""
        self._tool("regions.knot")

    def do_normalised(self):
        """Flux | Normalised (S9): the data divided by the continuum."""
        if self.session is not None:
            self._fill_strips()

    def do_snip(self):
        """
        SNIP: cut the transition from every dataset whose source covers it (Q4.2).

        Generated by RJC and Claude.
        """
        line = self.current_line()
        system = self._system()
        if line is None or system is None:
            return
        try:
            step = SN.snip_step(
                self.session.project,
                system,
                line,
                self._spectra,
                half_width=self._pref("regions.half_width", L.HALF_WIDTH),
                max_order=self._max_order(),
                **self._options(),
            )
        except SN.SnipError as error:
            self._warn("SNIP", str(error))
            return
        self._do(step)

    def do_clear(self):
        """
        CLEAR: remove the selected dataset's snip of the transition and its regions,
        after listing what changes (Q0.6, S27).

        Generated by RJC and Claude.
        """
        snip = self.current_snip()
        if snip is None:
            return
        project = self.session.project
        plan = SN.clear_plan(project, snip)
        dialog = D.PlanDialog("CLEAR " + snip.specid, plan, BL.Gate(project), "CLEAR")
        if self.main.run_dialog(dialog):
            self._do(plan.step(project))

    def do_auto(self):
        """Auto first guess (S8): the continuum fitted again, its order by BIC."""
        snip = self.current_snip()
        if snip is None or snip.pixels is None:
            return
        try:
            step = CO.auto_step(
                self.session.project, snip, self._max_order(), **self._options()
            )
        except CO.ContinuumError as error:
            self._warn("Auto first guess", str(error))
            return
        self._do(step)

    def _order(self, by):
        snip = self.current_snip()
        if snip is None or snip.continuum is None:
            return
        _, order = CO.current(snip)
        try:
            step = CO.order_step(
                self.session.project,
                snip,
                order + by,
                max_order=self._max_order(),
                **self._options(),
            )
        except CO.ContinuumError as error:
            if self.main is not None:
                self.main.statusBar().showMessage(str(error), 6000)
            return
        self._do(step)

    def do_order_down(self):
        """−: the continuum's order down by one, refitted."""
        self._order(-1)

    def do_order_up(self):
        """+: the continuum's order up by one, refitted."""
        self._order(1)

    def _function_chosen(self, index):
        snip = self.current_snip()
        function = self.function_box.itemData(index)
        if snip is None or function == CO.current(snip)[0]:
            return
        self._act("regions.function", lambda: self.set_function(function))

    def set_function(self, function):
        """The continuum's function (S8), refitted."""
        snip = self.current_snip()
        try:
            step = CO.function_step(
                self.session.project,
                snip,
                function,
                max_order=self._max_order(),
                **self._options(),
            )
        except CO.ContinuumError as error:
            self._warn("Continuum", str(error))
            return
        self._do(step)

    def set_knots(self, snip, knots):
        """
        The continuum's knots, its starting coefficients refitted through them
        (Q4.13).

        Generated by RJC and Claude.
        """
        try:
            step = CO.knots_step(
                self.session.project,
                snip,
                knots,
                max_order=self._max_order(),
                **self._options(),
            )
        except CO.ContinuumError as error:
            self._warn("Knots", str(error))
            return
        self._do(step)

    def remove_knots(self):
        """Clear knots."""
        snip = self.current_snip()
        if snip is not None:
            self.set_knots(snip, [])

    def share_with(self, specid):
        """One continuum for this transition here and in another dataset (S10)."""
        snip = self.current_snip()
        other = self.session.project.snip(specid)
        try:
            step = CO.share_step(self.session.project, [snip, other], **self._options())
        except CO.ContinuumError as error:
            self._warn("Share the continuum", str(error))
            return
        self._do(step)

    def unshare(self):
        """Each dataset its own continuum again, refitted (S10)."""
        snip = self.current_snip()
        if snip is not None and snip.continuum is not None:
            self._do(
                CO.unshare_step(self.session.project, snip.continuum, **self._options())
            )

    # -- the spectra ---------------------------------------------------------------------

    def select_row(self, row_id):
        """
        Select a dataset: its spectrum framed, its continuum and snip below, and its
        snip's line selected in the .mod panel (S16).

        Generated by RJC and Claude.
        """
        if row_id == self.selected:
            return
        self.selected = row_id
        for one in self.strips:
            one.set_selected(one.row_id == row_id)
        self._remember()
        self._fill_boxes()
        self._update_tools()
        snip = self.current_snip()
        if snip is not None and self.main is not None:
            self.main.panel.select_items([snip])

    def _clicked(self, strip, x, y):
        self.select_row(strip.row_id)
        self._last_click = (strip.row_id, x)
        if self._mode == "regions.knot" and strip.snip is not None:
            self._act("regions.knot", lambda: self.knot_at(strip, x, y))

    def knot_at(self, strip, x, y):
        """
        A click with Add knot: a knot there, or the knot clicked removed (Q4.13).

        Generated by RJC and Claude.
        """
        project = self.session.project
        snip = self._snip(strip.snip.specid)
        if snip.continuum is None:
            return
        knots = CO.knots_of(project, snip)
        normalised = self._normalised() and strip.curve is not None
        scale = strip.continuum_at(x) if normalised else 1.0
        y = y * scale
        (x0, x1), (y0, y1) = strip.view.view_range()
        near = [
            k
            for k in knots
            if abs(k[0] - x) < 0.015 * (x1 - x0)
            and abs(k[1] - y) < 0.05 * (y1 - y0) * scale
        ]
        knots = [k for k in knots if k not in near] if near else knots + [(x, y)]
        self.set_knots(snip, knots)

    def _knot_moved(self, strip, index, x, y):
        project = self.session.project
        snip = self._snip(strip.snip.specid)
        knots = list(CO.knots_of(project, snip))
        if not 0 <= index < len(knots):
            return
        if self._normalised() and strip.curve is not None:
            y = y * strip.continuum_at(x)
        knots[index] = (x, y)
        self._act("regions.knot", lambda: self.set_knots(snip, knots))

    def _spanned(self, strip, mode, low, high):
        self.select_row(strip.row_id)
        linked = self._linked()
        row = strip.row_id
        if mode == PL.DRAW and high > low:
            self._act("regions.draw", lambda: self.draw(row, low, high, linked))
        elif mode == PL.MASK and strip.snip is not None:
            self._act("regions.exclude", lambda: self.exclude(row, low, high, linked))

    def _snip_of_row(self, row_id):
        line = self.current_line()
        system = self._system()
        if line is None or system is None:
            return None
        found = SN.snips_of(self.session.project, system.id, line.ion, line.rest)
        return found.get(row_id)

    def draw(self, row_id, low, high, linked=True):
        """
        A region added on a dataset's spectrum, as one step: on a transition that is
        not a snip there yet, SNIP first (Q4.2(c)); the region is then added in every
        dataset of the transition (Q4.19), or in this one alone (``linked`` False:
        Tweak dataset regions).

        Generated by RJC and Claude.
        """
        line = self.current_line()
        if line is None:
            return
        history = self.session.history
        with history.group("Add a fit region to {0}".format(line.name)):
            if self._snip_of_row(row_id) is None:
                try:
                    step = SN.snip_step(
                        self.session.project,
                        self._system(),
                        line,
                        self._spectra,
                        half_width=self._pref("regions.half_width", L.HALF_WIDTH),
                        max_order=self._max_order(),
                        **self._options(),
                    )
                except SN.SnipError as error:
                    self._warn("Add region", str(error))
                    return
                history.do(step)
            snip = self._snip_of_row(row_id)
            if snip is None:
                return
            self.edit_regions(snip, [("add", low, high)], "Add a fit region to", linked)

    def edit_regions(self, snip, edits, what, linked=True):
        """
        Add or take out wavelength spans of the fit, the same in every dataset of the
        transition (Q4.19), or in the snip's dataset alone (``linked`` False):
        ``edits`` as :func:`snips.linked_step` takes them.

        Generated by RJC and Claude.
        """
        project = self.session.project
        snip_map = L.snip_transitions(project)
        if linked:
            name = SN.linked_name(project, snip, what, snip_map)
        else:
            trans = SN.transition_name(snip_map.get(snip.specid)) or snip.specid
            row = snip.row.name if snip.row is not None else snip.specid
            name = "{0} {1} in {2}".format(what, trans, row)
        self._do(SN.linked_step(project, snip, edits, name, snip_map, linked=linked))

    def exclude(self, row_id, low, high, linked=False):
        """
        Leave the pixels between two wavelengths out of the fit (a right-drag): in
        this dataset alone (a cosmic ray, a bad pixel), or in every dataset.

        Generated by RJC and Claude.
        """
        snip = self._snip_of_row(row_id)
        if snip is None or snip.pixels is None:
            return
        if linked:
            self.edit_regions(snip, [("remove", low, high)], "Exclude pixels of")
        else:
            self._do(SN.mask_step(self.session.project, snip, low, high))

    def _edge(self, strip, side, x, done):
        if not done or strip.snip is None:
            return
        snip = self._snip(strip.snip.specid)
        low, high = snip.extent
        low, high = (x, high) if side == "low" else (low, x)
        low, high = min(low, high), max(low, high)
        self._act("regions.edges", lambda: self.move_edges(strip.row_id, low, high))

    def move_edges(self, row_id, low, high):
        """
        Move a snip's edges (S6): outwards, more pixels are cut from the source.

        Generated by RJC and Claude.
        """
        snip = self._snip_of_row(row_id)
        if snip is None:
            return
        try:
            step = SN.edges_step(
                self.session.project, snip, low, high, self._spectra.get(row_id)
            )
        except SN.SnipError as error:
            self._warn("The snip's edges", str(error))
            return
        self._do(step)

    def _region_moved(self, strip, index, low, high):
        if strip.snip is None:
            return
        self._act("regions.region", lambda: self.move_region(strip, index, low, high))

    def move_region(self, strip, index, low, high):
        """
        A fit region's edges dragged: the pixels between each old edge and its new
        place are added or taken out, in every dataset (Q4.19); what was excluded
        inside the region stays excluded.

        Generated by RJC and Claude.
        """
        snip = self._snip(strip.snip.specid)
        regions = SN.regions_of(snip)
        if snip is None or not 0 <= index < len(regions):
            return
        old_low, old_high = regions[index]
        low, high = sorted((float(low), float(high)))
        tiny = 1.0e-9 * old_high
        edits = []
        if low < old_low:
            edits.append(("add", low, old_low))
        elif low > old_low:
            edits.append(("remove", old_low, low - tiny))
        if high > old_high:
            edits.append(("add", old_high, high))
        elif high < old_high:
            edits.append(("remove", high + tiny, old_high))
        if edits:
            self.edit_regions(snip, edits, "Move a fit region of", self._linked())

    def do_remove_region(self):
        """
        Delete: remove the fit region last clicked in the selected dataset's spectrum
        (as the right-click menu does).

        Generated by RJC and Claude.
        """
        if self._last_click is None or self._last_click[0] != self.selected:
            return
        snip = self.current_snip()
        if snip is None or snip.pixels is None:
            return
        x = self._last_click[1]
        for a, b in SN.regions_of(snip):
            if a <= x <= b:
                self.edit_regions(
                    snip, [("drop", a, b)], "Remove a fit region of", self._linked()
                )
                return

    def context_actions(self, strip, x):
        """
        What a right-click on a spectrum offers: ``[(text, handler), ...]``. With
        several datasets, a region is removed from every dataset or from this one
        alone; while tweaking, the pixel clicked can be left out of this dataset.

        Generated by RJC and Claude.
        """
        out = []
        if strip.snip is None or strip.snip.pixels is None:
            return out
        snip = self._snip(strip.snip.specid)
        regions = SN.regions_of(snip)
        several = len(self._rows) > 1
        what = "Remove a fit region of"

        def remove(a, b, linked):
            return lambda: self._act(
                "regions.region",
                lambda: self.edit_regions(snip, [("drop", a, b)], what, linked),
            )

        for a, b in regions:
            if not a <= x <= b:
                continue
            if several:
                out.append(
                    ("Remove this region from every dataset", remove(a, b, True))
                )
                out.append(
                    ("Remove this region from this dataset only", remove(a, b, False))
                )
            else:
                out.append(("Remove this region", remove(a, b, True)))
            if self._mode == "regions.tweak":
                out.append(
                    (
                        "Exclude this pixel",
                        lambda: self._act(
                            "regions.exclude",
                            lambda: self.exclude(strip.row_id, x, x, False),
                        ),
                    )
                )
        if regions and several:
            out.append(
                (
                    "Use these regions in every dataset",
                    lambda: self._act("regions.copy", lambda: self.copy_regions(False)),
                )
            )
        return out

    def _menu(self, strip, x, pos):
        self.select_row(strip.row_id)
        self._last_click = (strip.row_id, x)
        entries = self.context_actions(strip, x)
        if not entries:
            return
        menu = QtWidgets.QMenu(self)
        for text, handler in entries:
            menu.addAction(text, handler)
        point = pos.toPoint() if hasattr(pos, "toPoint") else QtGui.QCursor.pos()
        menu.exec(point)

    # -- the snip box ---------------------------------------------------------------------

    def copy_regions(self, only_empty=False):
        """
        Use the selected dataset's regions in every other dataset of the transition
        (D18), or only in those with none: an imported fit's datasets may have regions
        of their own; edits made here are the same in every dataset already (Q4.19).

        Generated by RJC and Claude.
        """
        snip = self.current_snip()
        if snip is None:
            return
        project = self.session.project
        targets = [
            project.snip(one.specid)
            for _, one in self._rows
            if one is not None and one.specid != snip.specid
        ]
        if not targets:
            self._warn(
                "Copy regions",
                "No other dataset has a snip of this transition: SNIP cuts one.",
            )
            return
        try:
            step = SN.copy_regions_step(project, snip, targets, only_empty=only_empty)
        except SN.SnipError as error:
            self._warn("Copy regions", str(error))
            return
        self._do(step)

    def _fix_others(self, snip, pair):
        if not self.fix_all.isHidden() and self.fix_all.isChecked():
            return SN.same_pairs(self.session.project, snip, pair, self._snip_map)
        return []

    def keep_shared(self):
        """
        Keep them in this snip only (D19): the other snip of each pair stops
        fitting the shared pixels.

        Generated by RJC and Claude.
        """
        snip = self.current_snip()
        if snip is None:
            return
        pairs = SN.shared_pixels(self.session.project, snip)
        if not pairs:
            return
        also = self._fix_others(snip, pairs[0])
        self._do(SN.keep_all_step(self.session.project, snip, also))

    def merge_shared(self):
        """
        Merge the snips… (D19, Q4.9): what changes is listed, and made once
        confirmed.

        Generated by RJC and Claude.
        """
        project = self.session.project
        snip = self.current_snip()
        if snip is None:
            return
        pairs = SN.shared_pixels(project, snip)
        if not pairs:
            return
        also = self._fix_others(snip, pairs[0])
        try:
            plan = SN.merge_all_plan(
                project,
                snip,
                pairs[0].other(snip),
                also,
                self._spectra,
                **self._options(),
            )
        except SN.SnipError as error:
            self._warn("Merge the snips", str(error))
            return
        dialog = D.PlanDialog("Merge the snips", plan.plan, BL.Gate(project), "Merge")
        if self.main.run_dialog(dialog):
            self._do(plan.step)


__all__ = ["RegionsTab", "Strip", "KeyHolder", "swatch", "KEY_ITEMS"]
