"""The five tabs, as frames of the agreed layout (D34–D42, Q3.4).

Dashboard Stage 3.5. Each tab holds the panes of its layout in the mockups
(``doc/dashboard/mockups/``), each pane titled and saying what it will hold, in the
same columns and proportions. Stages 4–6 replace the placeholders with the panels
(the ``gui-component`` skill). The Fit tab has its three sub-tabs, and the Plot tab
is built after v1.

Generated by RJC and Claude.
"""

from qtpy import QtWidgets

from alis.dashboard.qt import widgets as W
from alis.dashboard.qt.data import DataTab
from alis.dashboard.qt.regions import RegionsTab

# The base of every tab (kept here by name; it lives in widgets.py, which the tabs'
# own modules import)
Tab = W.Tab


class ComponentsTab(Tab):
    """
    The Components tab (D37): the ion navigator, equal panels of every transition of
    one ion on a velocity axis, and the component cards.

    Generated by RJC and Claude.
    """

    name = "Components"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ions = W.Pane("Ions", "each system and its ions.")
        self.panels = W.Pane(
            "Panels",
            "every transition of the chosen ion, on a velocity axis, in 1–4"
            " columns.",
        )
        self.cards = W.Pane(
            "Components",
            "one card per component: z, b, temperature, and each ion's column"
            " density, free, fixed or tied.",
        )
        self.layout_.addWidget(
            W.row(
                W.column(self.ions, width=186),
                W.column(self.panels, width=796),
                W.column(self.cards, width=396),
                stretch=[186, 796, 396],
            )
        )


class InspectTab(Tab):
    """
    The Fit tab's Inspect sub-tab (D38, D39).

    Generated by RJC and Claude.
    """

    name = "Inspect"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.run = W.Pane(
            "Run", "the settings you changed, the pre-flight check, Run and Cancel."
        )
        self.progress = W.Pane("Progress", "χ² against iteration, linear or log.")
        self.view = W.Pane(
            "View",
            "all snips, one ion or one snip, with the initial or final model and the"
            " residuals.",
        )
        self.snips = W.Pane(
            "All snips", "a chip per snip with its χ²ν and runs-test marks."
        )
        self.layout_.addWidget(
            W.row(
                W.column(self.run, self.progress, stretch=[3, 2], width=290),
                W.column(self.view, self.snips, stretch=[5, 1], width=1092),
                stretch=[290, 1092],
            )
        )


class ResultsTab(Tab):
    """
    The Fit tab's Results sub-tab (D40): the results, the run history, and the fit
    statistics above the correlations.

    Generated by RJC and Claude.
    """

    name = "Results"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.table = W.Pane(
            "Results", "each parameter's value and error, its tie state and flags."
        )
        self.correlations = W.Pane("Correlations", "the correlation matrix.")
        self.stats = W.Pane("Fit statistics", "χ², degrees of freedom, iterations.")
        self.history = W.Pane(
            "Run history", "the committed runs, each with your description."
        )
        # Run history beside the results, and the correlations below the
        # statistics (RJC's review swapped the two)
        self.layout_.addWidget(
            W.row(
                W.column(self.table, width=640),
                W.column(self.history, width=364),
                W.column(self.stats, self.correlations, stretch=[1, 2], width=370),
                stretch=[640, 364, 370],
            )
        )


class CompareTab(Tab):
    """
    The Fit tab's Compare sub-tab (D41).

    Generated by RJC and Claude.
    """

    name = "Compare"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.choose = W.Pane("Compare", "choose any two runs.")
        self.parameters = W.Pane(
            "Parameters",
            "the quantities both runs share, their difference and its size in σ.",
        )
        self.view = W.Pane(
            "View", "both models on the same data, with their difference in σ."
        )
        self.choose.setMaximumHeight(90)
        body = W.row(
            W.column(self.parameters, width=610),
            W.column(self.view, width=772),
            stretch=[610, 772],
        )
        body.layout().setContentsMargins(0, 0, 0, 0)
        holder = W.column(self.choose, body, stretch=[0, 1])
        holder.layout().setContentsMargins(8, 8, 8, 8)
        self.layout_.addWidget(holder)


class FitTab(Tab):
    """
    The Fit tab (D38–D41): its sub-tabs Inspect, Results and Compare.

    Generated by RJC and Claude.
    """

    name = "Fit"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.subtabs = QtWidgets.QTabWidget()
        self.subtabs.setObjectName("fitTabs")
        self.inspect = InspectTab()
        self.results = ResultsTab()
        self.compare = CompareTab()
        for tab in (self.inspect, self.results, self.compare):
            self.subtabs.addTab(tab, tab.name)
        self.layout_.setContentsMargins(4, 4, 4, 0)
        self.layout_.addWidget(self.subtabs)


class PlotTab(Tab):
    """
    The Plot tab (D42): built after v1, shown but disabled.

    Generated by RJC and Claude.
    """

    name = "Plot"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.layout_pane = W.Pane(
            "Layout", "the preset, the grid, the figure size and the style."
        )
        self.preview = W.Pane("Preview", "the figure, drawn by the plotting script.")
        self.panels = W.Pane("Panels", "the transitions, dragged onto the grid.")
        self.layout_.addWidget(
            W.row(
                W.column(self.layout_pane, width=400),
                W.column(self.preview, width=660),
                W.column(self.panels, width=322),
                stretch=[400, 660, 322],
            )
        )


TAB_CLASSES = (DataTab, RegionsTab, ComponentsTab, FitTab, PlotTab)

__all__ = [
    "Tab",
    "DataTab",
    "RegionsTab",
    "ComponentsTab",
    "FitTab",
    "InspectTab",
    "ResultsTab",
    "CompareTab",
    "PlotTab",
    "TAB_CLASSES",
]
